// SPDX-License-Identifier: AGPL-3.0-or-later
#include "dai.h"

u16 OVL_EXPORT(PrizeDrops)[] = {
    ITEMDROP_ANKH_OF_LIFE,   ITEMDROP_MORNINGSTAR,
    ITEMDROP_SILVER_RING,    ITEMDROP_AQUAMARINE,
    ITEMDROP_MYSTIC_PENDANT, ITEMDROP_MAGIC_MISSILE,
    ITEMDROP_SHURIKEN,       ITEMDROP_TNT,
    ITEMDROP_BOOMERANG,      ITEMDROP_GOGGLES,
    ITEMDROP_SILVER_PLATE,   ITEMDROP_STR_POTION,
    ITEMDROP_LIFE_VESSEL,    ITEMDROP_ZIRCON,
    ITEMDROP_CUTLASS,        ITEMDROP_POTION,
};
