// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_MariaSpritePackage7Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 g_MariaSpritePackage7Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, -3, 1, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage7Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 1, 1},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage7Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 0, 2},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage7Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 0, 3},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage7Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, -1, 4},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage7Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 1, 5},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage7Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 1, 6},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage7Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 1, 7},
    },
};

SaturnSpriteFrameHeader* g_MariaSpritePackage7Frames[9] = {
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage7Frame0,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage7Frame1,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage7Frame2,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage7Frame3,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage7Frame4,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage7Frame5,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage7Frame6,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage7Frame7,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage7Frame8,
};

struct {
    u16 countAndFlags;
    u16 colors[1][16];
    u16 padding[1];
} g_MariaSpritePackage7Palette = {
    0x0001,
    {
        {
            0x8140,
            0xFB74,
            0xF2F1,
            0xE66E,
            0xDA0B,
            0xCD88,
            0xC104,
            0xB881,
            0xFFFF,
            0xF37B,
            0xE6D6,
            0xD652,
            0xC9AD,
            0xBD29,
            0xAC84,
            0xA000,
        },
    },
    {0x0000},
};

SaturnSpriteImage g_MariaSpritePackage7Images[9] = {
    {12, 2, 0x0000}, {12, 4, 0x0008}, {12, 6, 0x0014},
    {12, 6, 0x0028}, {12, 9, 0x003C}, {8, 6, 0x0058},
    {8, 8, 0x0064},  {8, 8, 0x0074},  {0, 0, 0x0084},
};
