// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_MariaSpritePackage1Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 7, 1, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 12, 1, 1},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 8, 1, 2},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0000, 12, 0, 3},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0000, 12, 1, 4},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0000, 8, 1, 5},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0000, 12, 1, 6},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0000, 12, 1, 7},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0100, 2, 0, 8},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame10 = {
    {0x0100, 0x0000},
    {
        {0x0110, -1, 0, 8},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame11 = {
    {0x0100, 0x0000},
    {
        {0x0130, -1, 0, 8},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame12 = {
    {0x0100, 0x0000},
    {
        {0x0120, 2, 0, 8},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame13 = {
    {0x0100, 0x0000},
    {
        {0x0200, 2, 0, 9},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame14 = {
    {0x0100, 0x0000},
    {
        {0x0200, 1, 0, 10},
    },
};

SaturnSpriteFrame4 g_MariaSpritePackage1Frame15 = {
    {0x0400, 0x0000},
    {
        {0x0200, -6, -6, 11},
        {0x0210, 6, -6, 11},
        {0x0220, -6, 6, 11},
        {0x0230, 6, 6, 11},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame16 = {
    {0x0100, 0x0000},
    {
        {0x0300, 2, 0, 8},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame17 = {
    {0x0100, 0x0000},
    {
        {0x0400, 1, -7, 12},
    },
};

SaturnSpriteFrame2 g_MariaSpritePackage1Frame18 = {
    {0x0200, 0x0000},
    {
        {0x0300, 2, 0, 13},
        {0x0400, 20, -6, 14},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame19 = {
    {0x0100, 0x0000},
    {
        {0x0400, 15, 8, 15},
    },
};

SaturnSpriteFrame2 g_MariaSpritePackage1Frame20 = {
    {0x0200, 0x0000},
    {
        {0x0300, 2, 0, 13},
        {0x0400, 1, 9, 16},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame21 = {
    {0x0100, 0x0000},
    {
        {0x0500, -12, 5, 17},
    },
};

SaturnSpriteFrame2 g_MariaSpritePackage1Frame22 = {
    {0x0200, 0x0000},
    {
        {0x0300, 2, 0, 13},
        {0x0400, -14, -8, 18},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame23 = {
    {0x0100, 0x0000},
    {
        {0x0420, -7, 15, 12},
    },
};

SaturnSpriteFrame2 g_MariaSpritePackage1Frame24 = {
    {0x0200, 0x0000},
    {
        {0x0300, 2, 0, 13},
        {0x0420, 9, 14, 14},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame25 = {
    {0x0100, 0x0000},
    {
        {0x0420, 7, 0, 15},
    },
};

SaturnSpriteFrame2 g_MariaSpritePackage1Frame26 = {
    {0x0200, 0x0000},
    {
        {0x0300, 2, 0, 13},
        {0x0420, 11, -18, 16},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame27 = {
    {0x0100, 0x0000},
    {
        {0x0420, -6, -13, 17},
    },
};

SaturnSpriteFrame2 g_MariaSpritePackage1Frame28 = {
    {0x0200, 0x0000},
    {
        {0x0300, 2, 0, 13},
        {0x0420, -8, 0, 18},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame29 = {
    {0x0100, 0x0000},
    {
        {0x0600, 0, 0, 19},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame30 = {
    {0x0100, 0x0000},
    {
        {0x0100, 1, 0, 20},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame31 = {
    {0x0100, 0x0000},
    {
        {0x0110, -1, 0, 20},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame32 = {
    {0x0100, 0x0000},
    {
        {0x0130, -1, 0, 20},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame33 = {
    {0x0100, 0x0000},
    {
        {0x0120, 1, 0, 20},
    },
};

SaturnSpriteFrame2 g_MariaSpritePackage1Frame34 = {
    {0x0200, 0x0000},
    {
        {0x0300, 1, 0, 21},
        {0x0400, 15, -6, 14},
    },
};

SaturnSpriteFrame2 g_MariaSpritePackage1Frame35 = {
    {0x0200, 0x0000},
    {
        {0x0300, 1, 0, 21},
        {0x0400, 1, 9, 16},
    },
};

SaturnSpriteFrame2 g_MariaSpritePackage1Frame36 = {
    {0x0200, 0x0000},
    {
        {0x0300, 1, 0, 21},
        {0x0400, -13, -8, 18},
    },
};

SaturnSpriteFrame2 g_MariaSpritePackage1Frame37 = {
    {0x0200, 0x0000},
    {
        {0x0300, 1, 0, 21},
        {0x0420, 9, 14, 14},
    },
};

SaturnSpriteFrame2 g_MariaSpritePackage1Frame38 = {
    {0x0200, 0x0000},
    {
        {0x0300, 1, 0, 21},
        {0x0420, 10, -17, 16},
    },
};

SaturnSpriteFrame2 g_MariaSpritePackage1Frame39 = {
    {0x0200, 0x0000},
    {
        {0x0300, 1, 0, 21},
        {0x0420, -9, 0, 18},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame40 = {
    {0x0100, 0x0000},
    {
        {0x0700, 7, 1, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame41 = {
    {0x0100, 0x0000},
    {
        {0x0800, 7, 1, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame42 = {
    {0x0100, 0x0000},
    {
        {0x0900, 7, 1, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame43 = {
    {0x0100, 0x0000},
    {
        {0x0A00, 7, 1, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame44 = {
    {0x0100, 0x0000},
    {
        {0x0400, 7, 1, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame45 = {
    {0x0100, 0x0000},
    {
        {0x0B00, 7, 1, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame46 = {
    {0x0100, 0x0000},
    {
        {0x0C00, 7, 1, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame47 = {
    {0x0100, 0x0000},
    {
        {0x0D00, 7, 1, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame48 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 0, 1, 22},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame49 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 0, 1, 23},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame50 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 0, 1, 24},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame51 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 0, 1, 25},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame52 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 0, 1, 26},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame53 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 0, 1, 27},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage1Frame54 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 0, 1, 28},
    },
};

SaturnSpriteFrameHeader* g_MariaSpritePackage1Frames[55] = {
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame0,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame1,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame2,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame3,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame4,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame5,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame6,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame7,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame8,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame9,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame10,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame11,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame12,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame13,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame14,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame15,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame16,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame17,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame18,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame19,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame20,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame21,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame22,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame23,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame24,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame25,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame26,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame27,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame28,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame29,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame30,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame31,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame32,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame33,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame34,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame35,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame36,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame37,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame38,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame39,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame40,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame41,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame42,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame43,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame44,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame45,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame46,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame47,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame48,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame49,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame50,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame51,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame52,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame53,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage1Frame54,
};

struct {
    u16 countAndFlags;
    u16 colors[16][16];
    u16 padding[1];
} g_MariaSpritePackage1Palette = {
    0x0010,
    {
        {
            0xB88F,
            0xC104,
            0xCD88,
            0xDA0B,
            0xE66E,
            0xFB74,
            0xB881,
            0xC104,
            0xDA0B,
            0xE66E,
            0xFB74,
            0xB881,
            0xC104,
            0xCD88,
            0xE66E,
            0xFB74,
        },
        {
            0x8000,
            0xFFFF,
            0xFFE6,
            0xFEE0,
            0xFDC0,
            0xFCC0,
            0xFC00,
            0xFC00,
            0x8000,
            0xFF95,
            0xFF74,
            0xFF32,
            0xFECF,
            0xFE6D,
            0xFE09,
            0xFD43,
        },
        {
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
        },
        {
            0x838A,
            0x8B8A,
            0x938A,
            0x9B8A,
            0xA38A,
            0xAB8A,
            0xB38A,
            0xBB8A,
            0xC38A,
            0xCB8A,
            0xD38A,
            0xDB8A,
            0xE38A,
            0xEB8A,
            0xF38A,
            0xFB8A,
        },
        {
            0x8000,
            0x9400,
            0xAC20,
            0xC440,
            0xCC60,
            0x9800,
            0xA820,
            0x9400,
            0xA820,
            0xBC40,
            0xD460,
            0xE880,
            0xFCA0,
            0xFD60,
            0xFF20,
            0xFF98,
        },
        {
            0x8112,
            0x8912,
            0x9112,
            0x9912,
            0xA112,
            0xA912,
            0xB112,
            0xB912,
            0xC112,
            0xC912,
            0xD112,
            0xD912,
            0xE112,
            0xE912,
            0xF112,
            0xF912,
        },
        {
            0x8220,
            0x8421,
            0xC400,
            0xFC00,
            0xFD68,
            0xFE67,
            0xD800,
            0xFC00,
            0xA946,
            0x8957,
            0x82BB,
            0x9CE7,
            0xAD6B,
            0xC210,
            0xDAD6,
            0xF7BD,
        },
        {
            0x8000,
            0xADF7,
            0xAA3A,
            0xBA9C,
            0xCB5E,
            0x9A48,
            0x9B47,
            0xBF90,
            0xB29C,
            0xBB7F,
            0xC58B,
            0xBE2F,
            0xDA4F,
            0xE6D2,
            0xF379,
            0xFBDE,
        },
        {
            0x8200,
            0xF861,
            0xF948,
            0xFA4F,
            0xFB36,
            0xB000,
            0xBCA1,
            0xC543,
            0xA800,
            0xB841,
            0xFC01,
            0xFCC4,
            0xFD88,
            0xFE6B,
            0xFF2E,
            0xFFF2,
        },
        {
            0x99A0,
            0x801F,
            0x801B,
            0x8017,
            0x8013,
            0x8010,
            0x800C,
            0x8005,
            0x8000,
            0x80BF,
            0x815F,
            0x81FF,
            0x931F,
            0xAFFF,
            0xCFFF,
            0xFFFF,
        },
        {
            0x8420,
            0xFFAE,
            0xF7A6,
            0xF6A0,
            0xF5A0,
            0xF4C0,
            0xF400,
            0xB400,
            0xFFFF,
            0x845F,
            0x845B,
            0x8036,
            0x8032,
            0x800E,
            0x8009,
            0x8005,
        },
        {
            0x804C,
            0x884C,
            0x904C,
            0x984C,
            0xA04C,
            0xA84C,
            0xB04C,
            0xB84C,
            0xC04C,
            0xC84C,
            0xD04C,
            0xD84C,
            0xE04C,
            0xE84C,
            0xF04C,
            0xF84C,
        },
        {
            0x808C,
            0x888C,
            0x908C,
            0x988C,
            0xA08C,
            0xA88C,
            0xB08C,
            0xB88C,
            0xC08C,
            0xC88C,
            0xD08C,
            0xD88C,
            0xE08C,
            0xE88C,
            0xF08C,
            0xF88C,
        },
        {
            0x82CC,
            0x8ACC,
            0x92CC,
            0x9ACC,
            0xA2CC,
            0xAACC,
            0xB2CC,
            0xBACC,
            0xC2CC,
            0xCACC,
            0xD2CC,
            0xDACC,
            0xE2CC,
            0xEACC,
            0xF2CC,
            0xFACC,
        },
        {
            0x8220,
            0xFC21,
            0x8420,
            0xFC21,
            0xCE73,
            0xF39C,
            0x87FF,
            0x87E1,
            0x8220,
            0x8421,
            0xD421,
            0xFC21,
            0xFD42,
            0xFE48,
            0xF6D1,
            0xFFBD,
        },
        {
            0x8927,
            0x87FF,
            0x8421,
            0x87FF,
            0xA53F,
            0xBDFF,
            0x87E1,
            0x87E1,
            0x87E1,
            0x87E1,
            0x8601,
            0x86A1,
            0x8741,
            0x87E1,
            0xBBEE,
            0xEFFB,
        },
    },
    {0x0000},
};

SaturnSpriteImage g_MariaSpritePackage1Images[30] = {
    {16, 7, 0x0000},  {20, 7, 0x001C},  {16, 7, 0x0040}, {20, 7, 0x005C},
    {20, 7, 0x0080},  {16, 7, 0x00A4},  {20, 6, 0x00C0}, {20, 6, 0x00E0},
    {20, 15, 0x0100}, {8, 8, 0x014C},   {8, 6, 0x015C},  {12, 8, 0x0168},
    {12, 8, 0x0180},  {20, 15, 0x0198}, {8, 6, 0x01E4},  {4, 8, 0x01F0},
    {12, 6, 0x01F8},  {8, 5, 0x020C},   {8, 8, 0x0218},  {4, 3, 0x0228},
    {16, 15, 0x022C}, {16, 15, 0x0268}, {4, 4, 0x02A4},  {4, 4, 0x02A8},
    {4, 4, 0x02AC},   {8, 8, 0x02B0},   {8, 8, 0x02C0},  {8, 8, 0x02D0},
    {8, 8, 0x02E0},   {0, 0, 0x02F0},
};
