// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_MariaSpritePackage5Frame0 = {
    0x0000, 0x0000,
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 71, 12, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 70, 12, 1},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 70, 12, 2},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0000, 70, 12, 3},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0000, 70, 12, 4},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0100, 24, 48, 5},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 4, 6},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 4, 7},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 4, 8},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame10 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 4, 9},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame11 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 4, 10},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame12 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 4, 11},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame13 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 4, 12},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame14 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 4, 13},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame15 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 4, 14},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame16 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 4, 15},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame17 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 4, 16},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame18 = {
    {0x0100, 0x0000},
    {
        {0x0200, 4, 4, 17},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame19 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 4, 17},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame20 = {
    {0x0100, 0x0000},
    {
        {0x0300, 4, 4, 17},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame21 = {
    {0x0100, 0x0000},
    {
        {0x0400, 4, 4, 17},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame22 = {
    {0x0100, 0x0000},
    {
        {0x0500, 4, 4, 17},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame23 = {
    {0x0100, 0x0000},
    {
        {0x0600, 4, 4, 17},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame24 = {
    {0x0100, 0x0000},
    {
        {0x0700, 4, 4, 17},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame25 = {
    {0x0100, 0x0000},
    {
        {0x0800, 4, 4, 17},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame26 = {
    {0x0100, 0x0000},
    {
        {0x0900, 4, 4, 17},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame27 = {
    {0x0100, 0x0000},
    {
        {0x0A00, 4, 4, 17},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame28 = {
    {0x0100, 0x0000},
    {
        {0x0B00, 71, 12, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame29 = {
    {0x0100, 0x0000},
    {
        {0x0C00, 71, 12, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame30 = {
    {0x0100, 0x0000},
    {
        {0x0D00, 71, 12, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame31 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 71, 12, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame32 = {
    {0x0100, 0x0000},
    {
        {0x0F00, 71, 12, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame33 = {
    {0x0100, 0x0000},
    {
        {0x1000, 71, 12, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame34 = {
    {0x0100, 0x0000},
    {
        {0x1100, 71, 12, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame35 = {
    {0x0100, 0x0000},
    {
        {0x1200, 71, 12, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame36 = {
    {0x0100, 0x0000},
    {
        {0x1300, 71, 12, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage5Frame37 = {
    {0x0100, 0x0000},
    {
        {0x1400, 71, 12, 0},
    },
};

SaturnSpriteFrameHeader* g_MariaSpritePackage5Frames[38] = {
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame0,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame1,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame2,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame3,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame4,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame5,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame6,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame7,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame8,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame9,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame10,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame11,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame12,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame13,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame14,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame15,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame16,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame17,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame18,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame19,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame20,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame21,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame22,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame23,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame24,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame25,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame26,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame27,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame28,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame29,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame30,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame31,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame32,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame33,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame34,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame35,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame36,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage5Frame37,
};

struct {
    u16 countAndFlags;
    u16 colors[11][16];
    u16 padding[1];
} g_MariaSpritePackage5Palette = {
    0x400B,
    {
        {
            0x8009, 0xFE9F, 0xFCDA, 0xCCF8, 0x8013, 0x801F, 0xA99F, 0xDEDF,
            0x8000, 0xBC00, 0x88CA, 0x952D, 0xAA16, 0xCF7F, 0xEFFF, 0xFFFF,
        },
        {
            0xF400, 0x8C97, 0x8415, 0xFFFF, 0x98C6, 0x8CC2, 0x8000, 0xEFFF,
            0xCE73, 0xB38C, 0x8D43, 0x95C5, 0x9A28, 0x96A6, 0x9122, 0xB18C,
        },
        {
            0x8009, 0xFEA9, 0xFD86, 0xF000, 0x8000, 0x8020, 0x8020, 0x8020,
            0x8000, 0xBC00, 0x88CA, 0x952D, 0xA9F6, 0xCF7F, 0xEFFF, 0xFFFF,
        },
        {
            0x8009, 0xFE9F, 0xFCDA, 0xCCF8, 0x8013, 0x801F, 0xA99F, 0xDEDF,
            0x8000, 0xBC00, 0x88CA, 0x952D, 0xAA16, 0xCF7F, 0xEFFF, 0x801F,
        },
        {
            0x8009, 0xFE9F, 0xFCDA, 0xCCF8, 0x8013, 0x801F, 0xA99F, 0xDEDF,
            0x8000, 0xBC00, 0x88CA, 0x952D, 0xAA16, 0xCF7F, 0xEFFF, 0x83E0,
        },
        {
            0x8009, 0xFE9F, 0xFCDA, 0xCCF8, 0x8013, 0x801F, 0xA99F, 0xDEDF,
            0x8000, 0x83E0, 0x88CA, 0x952D, 0xAA16, 0xCF7F, 0xEFFF, 0xFC00,
        },
        {
            0x8009, 0xFE9F, 0xFCDA, 0xCCF8, 0x8013, 0x801F, 0xA99F, 0xDEDF,
            0x8000, 0xFFFF, 0x88CA, 0x952D, 0xAA16, 0xCF7F, 0xEFFF, 0x801F,
        },
        {
            0x90A5, 0x8421, 0xE800, 0xCC00, 0xDC00, 0xEC00, 0xFC00, 0xFD60,
            0xFE6B, 0x80B2, 0x815F, 0x827F, 0xBBBF, 0xBD4A, 0xCA52, 0xF7BD,
        },
        {
            0x90A5, 0x8421, 0xE800, 0xCC00, 0xDC00, 0xEC00, 0xFC00, 0xBCD3,
            0xB979, 0x88AE, 0x815F, 0x827F, 0xBBBF, 0xA529, 0xCA52, 0xF7BD,
        },
        {
            0x90A5, 0xE419, 0x823F, 0x8339, 0xCBE0, 0xE720, 0xE419, 0x823F,
            0x8339, 0xCBE0, 0xE720, 0xE419, 0x823F, 0x8339, 0xCBE0, 0xE720,
        },
        {
            0xB0A5, 0x843F, 0x8C7F, 0x94BF, 0x9CFF, 0xA53F, 0xAD7F, 0xB5BF,
            0xBDFF, 0xC63F, 0xCE7F, 0xD6BF, 0xDEFF, 0xE73F, 0xF7BF, 0xFD8C,
        },
    },
    {0x0000},
};

SaturnSpriteImage g_MariaSpritePackage5Images[19] = {
    {40, 12, 0x0000},
    {40, 8, 0x0078},
    {40, 4, 0x00C8},
    {40, 8, 0x00F0},
    {40, 12, 0x0140},
    {24, 48, 0x01B8},
    {4, 4, 0x02D8},
    {4, 4, 0x02DC},
    {4, 4, 0x02E0},
    {4, 4, 0x02E4},
    {4, 4, 0x02E8},
    {4, 4, 0x02EC},
    {4, 4, 0x02F0},
    {4, 4, 0x02F4},
    {4, 4, 0x02F8},
    {4, 4, 0x02FC},
    {4, 4, 0x0300},
    {4, 4, 0x0304},
    {0, 0, 0x0308},
};
