// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_MariaSpritePackage3Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame4 g_MariaSpritePackage3Frame1 = {
    {0x0400, 0x0000},
    {
        {0x0000, -33, -27, 0},
        {0x0010, 33, -27, 0},
        {0x0030, 33, 28, 0},
        {0x0020, -33, 28, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage3Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0100, -7, -24, 1},
    },
};

SaturnSpriteFrame4 g_MariaSpritePackage3Frame3 = {
    {0x0400, 0x0000},
    {
        {0x0000, -24, -24, 2},
        {0x0010, 26, -24, 2},
        {0x0030, 26, 23, 2},
        {0x0020, -24, 23, 2},
    },
};

SaturnSpriteFrameHeader* g_MariaSpritePackage3Frames[4] = {
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage3Frame0,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage3Frame1,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage3Frame2,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage3Frame3,
};

struct {
    u16 countAndFlags;
    u16 colors[2][16];
    u16 padding[1];
} g_MariaSpritePackage3Palette = {
    0x0002,
    {
        {
            0x8100,
            0x8400,
            0x8420,
            0x8421,
            0x8821,
            0x8841,
            0x8842,
            0x8C42,
            0x8C62,
            0x8C63,
            0x9063,
            0x9083,
            0x9084,
            0x9484,
            0xE318,
            0x94A5,
        },
        {
            0xC0A8,
            0x8421,
            0x84AB,
            0x8D2F,
            0x91D6,
            0x929B,
            0x994A,
            0xA5CE,
            0x8421,
            0x9CE7,
            0xFFE0,
            0x98A5,
            0xA94A,
            0xBE2E,
            0xC2F7,
            0xF39C,
        },
    },
    {0x0000},
};

SaturnSpriteImage g_MariaSpritePackage3Images[4] = {
    {48, 36, 0x0000},
    {28, 28, 0x01B0},
    {40, 40, 0x0274},
    {0, 0, 0x0404},
};
