// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_MariaSpritePackage2Frame0 = {
    0x0000, 0x0000,
};

SaturnSpriteFrame6 g_MariaSpritePackage2Frame1 = {
    {0x0600, 0x0000},
    {
        {0x0000, 0, -48, 0},
        {0x0000, 0, -32, 1},
        {0x0000, 0, -16, 2},
        {0x0000, 0, 0, 3},
        {0x0000, 0, 16, 4},
        {0x0000, 0, 32, 5},
    },
};

SaturnSpriteFrameHeader* g_MariaSpritePackage2Frames[2] = {
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage2Frame0,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage2Frame1,
};

struct {
    u16 countAndFlags;
    u16 colors[1][16];
    u16 padding[1];
} g_MariaSpritePackage2Palette = {
    0x0001,
    {
        {
            0x8000, 0x8000, 0x8000, 0x8000, 0x8000, 0x8000, 0x8000, 0x8000,
            0xCD2B, 0xD58C, 0xDE0E, 0xE670, 0xEEF1, 0xF753, 0xFFD5, 0xFFF9,
        },
    },
    {0x0000},
};

SaturnSpriteImage g_MariaSpritePackage2Images[7] = {
    {8, 8, 0x0000},
    {8, 8, 0x0010},
    {8, 8, 0x0020},
    {8, 8, 0x0030},
    {8, 8, 0x0040},
    {8, 8, 0x0050},
    {0, 0, 0x0060},
};
