// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_MariaSpritePackage11Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 g_MariaSpritePackage11Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 2, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage11Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 2, 1},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage11Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, -1, 2, 2},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage11Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, -6, 3},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage11Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 4, 4},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage11Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 5, 5},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage11Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 3, 6},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage11Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0000, 6, -10, 7},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage11Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0000, 6, -1, 8},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage11Frame10 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 4, 9},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage11Frame11 = {
    {0x0100, 0x0000},
    {
        {0x0000, 6, -3, 10},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage11Frame12 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 5, 11},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage11Frame13 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 3, 12},
    },
};

SaturnSpriteFrameHeader* g_MariaSpritePackage11Frames[14] = {
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage11Frame0,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage11Frame1,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage11Frame2,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage11Frame3,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage11Frame4,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage11Frame5,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage11Frame6,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage11Frame7,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage11Frame8,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage11Frame9,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage11Frame10,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage11Frame11,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage11Frame12,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage11Frame13,
};

struct {
    u16 countAndFlags;
    u16 colors[1][16];
    u16 padding[1];
} g_MariaSpritePackage11Palette = {
    0x0001,
    {
        {
            0x8000,
            0xE739,
            0xDEF7,
            0xB5AD,
            0xA94A,
            0x9CE7,
            0xA529,
            0x9084,
            0x8006,
            0x804C,
            0x8490,
            0x8914,
            0x921C,
            0x9A9C,
            0xE342,
            0xF39C,
        },
    },
    {0x0000},
};

SaturnSpriteImage g_MariaSpritePackage11Images[14] = {
    {8, 15, 0x0000},  {8, 14, 0x0020},  {8, 13, 0x003C},  {16, 20, 0x0058},
    {12, 9, 0x00A8},  {16, 11, 0x00C4}, {12, 12, 0x00F0}, {16, 16, 0x0114},
    {16, 6, 0x0154},  {16, 11, 0x016C}, {16, 9, 0x0198},  {12, 9, 0x01BC},
    {12, 12, 0x01D8}, {0, 0, 0x01FC},
};
