// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_MariaSpritePackage12Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 g_MariaSpritePackage12Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 9, -29, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage12Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 6, -29, 1},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage12Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 9, -27, 2},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage12Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0010, 9, -29, 1},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage12Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0020, 9, -30, 2},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage12Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0030, 9, -28, 1},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage12Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0030, 6, -30, 2},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage12Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0000, 18, -22, 1},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage12Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0100, -1, 32, 3},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage12Frame10 = {
    {0x0100, 0x0000},
    {
        {0x0100, 1, 26, 4},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage12Frame11 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 0, 0},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage12Frame12 = {
    {0x0100, 0x0000},
    {
        {0x0000, -1, 0, 1},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage12Frame13 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 2, 2},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage12Frame14 = {
    {0x0100, 0x0000},
    {
        {0x0010, 2, 0, 1},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage12Frame15 = {
    {0x0100, 0x0000},
    {
        {0x0020, 2, -1, 2},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage12Frame16 = {
    {0x0100, 0x0000},
    {
        {0x0030, 2, 1, 1},
    },
};

SaturnSpriteFrame1 g_MariaSpritePackage12Frame17 = {
    {0x0100, 0x0000},
    {
        {0x0030, -1, -1, 2},
    },
};

SaturnSpriteFrameHeader* g_MariaSpritePackage12Frames[19] = {
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame0,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame1,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame2,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame3,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame4,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame5,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame6,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame7,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame8,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame0,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame9,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame10,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame11,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame12,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame13,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame14,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame15,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame16,
    (SaturnSpriteFrameHeader*)&g_MariaSpritePackage12Frame17,
};

struct {
    u16 countAndFlags;
    u16 colors[2][16];
    u16 padding[1];
} g_MariaSpritePackage12Palette = {
    0x0002,
    {
        {
            0x8420,
            0xFFAE,
            0xF7A6,
            0xF6A0,
            0xF5A0,
            0xF4C0,
            0xF400,
            0xB400,
            0xFFFF,
            0x845F,
            0x845B,
            0x8036,
            0x8032,
            0x800E,
            0x8009,
            0x8005,
        },
        {
            0xB04B,
            0xB400,
            0xF400,
            0xF4C0,
            0xF5C0,
            0xF7A0,
            0xA820,
            0xF4C0,
            0xD140,
            0xBC01,
            0xE500,
            0xD440,
            0xDC40,
            0xF540,
            0x809F,
            0x825F,
        },
    },
    {0x0000},
};

SaturnSpriteImage g_MariaSpritePackage12Images[6] = {
    {8, 8, 0x0000},   {12, 15, 0x0010}, {16, 12, 0x0040},
    {28, 56, 0x0070}, {24, 20, 0x01F8}, {0, 0, 0x0270},
};
