// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[2][16];
    u16 padding[1];
} g_RStage15SpriteBank22Palette = {
    0x0002,
    {
        {
            0xB0C8,
            0x8476,
            0x9D3F,
            0x9218,
            0x931F,
            0x88A2,
            0x8140,
            0x8240,
            0xB76C,
            0x8421,
            0x8CA9,
            0x9130,
            0x9998,
            0xAA5E,
            0xCF3F,
            0xF7BC,
        },
        {
            0x81E0,
            0xFFE4,
            0xA94A,
            0xA94A,
            0xA94A,
            0xA94A,
            0xA94A,
            0xA94A,
            0xAD6B,
            0xAD6B,
            0xAD6B,
            0xAD6B,
            0xAD6B,
            0xAD6B,
            0xAD6B,
            0xAD6B,
        },
    },
    {0x0000},
};

SaturnSpriteFrameHeader g_RStage15SpriteBank22Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 6, 0},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, -2, 6, 1},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 4, 2},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0000, 6, 6, 3},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0000, 8, 6, 4},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 6, 5},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0000, 6, 6, 6},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0000, 5, 6, 7},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0010, -1, 6, 5},
    },
};

SaturnSpriteFrame3 g_RStage15SpriteBank22Frame10 = {
    {0x0300, 0x0000},
    {
        {0x0000, 6, -5, 8},
        {0x0000, 6, 13, 9},
        {0x0000, 8, -18, 10},
    },
};

SaturnSpriteFrame3 g_RStage15SpriteBank22Frame11 = {
    {0x0300, 0x0000},
    {
        {0x0000, 6, -6, 8},
        {0x0000, 6, 13, 9},
        {0x0000, 8, -20, 10},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame12 = {
    {0x0100, 0x0000},
    {
        {0x0000, 7, 3, 11},
    },
};

SaturnSpriteFrame3 g_RStage15SpriteBank22Frame13 = {
    {0x0300, 0x0000},
    {
        {0x0000, -6, -3, 12},
        {0x0000, 13, -3, 13},
        {0x0000, 1, 4, 14},
    },
};

SaturnSpriteFrame3 g_RStage15SpriteBank22Frame14 = {
    {0x0300, 0x0000},
    {
        {0x0000, -7, -2, 12},
        {0x0000, 14, -2, 13},
        {0x0000, 1, 4, 14},
    },
};

SaturnSpriteFrame3 g_RStage15SpriteBank22Frame15 = {
    {0x0300, 0x0000},
    {
        {0x0000, 1, 4, 14},
        {0x0000, 11, -3, 15},
        {0x0000, -6, -3, 16},
    },
};

SaturnSpriteFrame3 g_RStage15SpriteBank22Frame16 = {
    {0x0300, 0x0000},
    {
        {0x0000, 1, 4, 14},
        {0x0000, 9, -2, 15},
        {0x0000, -3, -2, 16},
    },
};

SaturnSpriteFrame3 g_RStage15SpriteBank22Frame17 = {
    {0x0300, 0x0000},
    {
        {0x0000, 1, 4, 14},
        {0x0000, 8, -5, 15},
        {0x0000, -4, -5, 16},
    },
};

SaturnSpriteFrame3 g_RStage15SpriteBank22Frame18 = {
    {0x0300, 0x0000},
    {
        {0x0000, 1, 4, 14},
        {0x0000, 8, -7, 15},
        {0x0000, -4, -7, 16},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame19 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 1, 17},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame20 = {
    {0x0100, 0x0000},
    {
        {0x0000, 5, 3, 18},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame21 = {
    {0x0100, 0x0000},
    {
        {0x0100, 6, 21, 19},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame22 = {
    {0x0100, 0x0000},
    {
        {0x0100, 5, 14, 20},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame23 = {
    {0x0100, 0x0000},
    {
        {0x0100, 10, -10, 21},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame24 = {
    {0x0100, 0x0000},
    {
        {0x0100, 5, -24, 22},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame25 = {
    {0x0100, 0x0000},
    {
        {0x0100, 4, -40, 23},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame26 = {
    {0x0100, 0x0000},
    {
        {0x0120, 3, -50, 20},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame27 = {
    {0x0100, 0x0000},
    {
        {0x0100, 3, -59, 24},
    },
};

SaturnSpriteFrame2 g_RStage15SpriteBank22Frame28 = {
    {0x0200, 0x0000},
    {
        {0x0110, -33, -61, 25},
        {0x0110, 31, -64, 25},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame29 = {
    {0x0100, 0x0000},
    {
        {0x0100, 3, 1, 26},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame30 = {
    {0x0100, 0x0000},
    {
        {0x0100, 3, 1, 27},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame31 = {
    {0x0100, 0x0000},
    {
        {0x0100, 2, 1, 28},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame32 = {
    {0x0100, 0x0000},
    {
        {0x0100, 3, 1, 29},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame33 = {
    {0x0100, 0x0000},
    {
        {0x0100, 4, 1, 30},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank22Frame34 = {
    {0x0100, 0x0000},
    {
        {0x0100, 3, 1, 31},
    },
};

SaturnSpriteFrameHeader* g_RStage15SpriteBank22Frames[35] = {
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame0,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame1,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame2,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame3,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame4,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame5,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame6,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame7,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame8,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame9,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame10,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame11,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame12,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame13,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame14,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame15,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame16,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame17,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame18,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame19,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame20,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame21,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame22,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame23,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame24,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame25,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame26,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame27,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame28,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame29,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame30,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame31,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame32,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame33,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank22Frame34,
};

SaturnSpriteImage g_RStage15SpriteBank22Images[33] = {
    {16, 19, 0x0000}, {20, 18, 0x004C}, {16, 15, 0x00A8}, {16, 19, 0x00E4},
    {16, 19, 0x0130}, {16, 20, 0x017C}, {20, 19, 0x01CC}, {16, 19, 0x022C},
    {8, 12, 0x0278},  {8, 12, 0x0290},  {8, 9, 0x02A8},   {20, 22, 0x02BC},
    {8, 6, 0x032C},   {4, 7, 0x0338},   {16, 22, 0x0340}, {12, 3, 0x0398},
    {8, 3, 0x03A4},   {16, 25, 0x03AC}, {20, 17, 0x0410}, {40, 5, 0x0468},
    {20, 11, 0x049C}, {12, 23, 0x04D4}, {8, 22, 0x051C},  {12, 15, 0x0548},
    {40, 8, 0x0578},  {8, 3, 0x05C8},   {40, 31, 0x05D0}, {40, 31, 0x0708},
    {40, 31, 0x0840}, {40, 31, 0x0978}, {40, 30, 0x0AB0}, {40, 31, 0x0BDC},
    {0, 0, 0x0D14},
};
