// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[5][16];
    u16 padding[1];
} g_RStage15SpriteBank24Palette = {
    0x0005,
    {
        {
            0x9480,
            0x83FF,
            0x835F,
            0x82BF,
            0x823F,
            0x819F,
            0x80FF,
            0x80B9,
            0x8093,
            0x804C,
            0x8026,
            0x8000,
            0xFFFF,
            0x81D9,
            0x80EF,
            0x8005,
        },
        {
            0xA8A6,
            0xBEFF,
            0xB61F,
            0x8D3F,
            0x807B,
            0x8017,
            0x8012,
            0x800D,
            0x8009,
            0x8004,
            0x8000,
            0x839A,
            0x81D1,
            0x80E8,
            0xC940,
            0xFFE0,
        },
        {
            0x80E0,
            0xD7FF,
            0xDFD5,
            0xE7AA,
            0xFFE0,
            0xFE84,
            0xF184,
            0xE902,
            0xE081,
            0xB840,
            0xAC20,
            0xA420,
            0x9C20,
            0x9000,
            0x8800,
            0x8000,
        },
        {
            0xA8A9,
            0x801F,
            0x801B,
            0x8016,
            0x8012,
            0x800F,
            0x800C,
            0x800A,
            0x8007,
            0x8005,
            0x8002,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0xFC00,
        },
        {
            0x9C8B,
            0x8004,
            0x8004,
            0x8004,
            0x8005,
            0x8004,
            0x8003,
            0x8003,
            0x8002,
            0x8001,
            0x8001,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
        },
    },
    {0x0000},
};

SaturnSpriteFrameHeader g_RStage15SpriteBank24Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 20, -16, 0},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 20, -16, 1},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 23, -17, 2},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0000, 22, -16, 3},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0000, 23, -28, 4},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0000, 22, -36, 5},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0000, 24, -42, 6},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -10, 7},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, -10, 8},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame10 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -10, 9},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame11 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -10, 10},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame12 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, -13, 11},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame13 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, -16, 12},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame14 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, -21, 13},
    },
};

SaturnSpriteFrame5 g_RStage15SpriteBank24Frame15 = {
    {0x0500, 0x0000},
    {
        {0x0100, 1, -18, 14},
        {0x0100, 2, 6, 15},
        {0x0000, 2, 23, 16},
        {0x0100, 2, 4, 17},
        {0x0000, 0, 10, 18},
    },
};

SaturnSpriteFrame5 g_RStage15SpriteBank24Frame16 = {
    {0x0500, 0x0000},
    {
        {0x0100, 0, -18, 14},
        {0x0100, 2, 6, 15},
        {0x0000, 2, 23, 16},
        {0x0100, 2, 2, 19},
        {0x0000, 2, 9, 20},
    },
};

SaturnSpriteFrame5 g_RStage15SpriteBank24Frame17 = {
    {0x0500, 0x0000},
    {
        {0x0100, 0, -18, 14},
        {0x0100, 2, 6, 15},
        {0x0000, 2, 23, 16},
        {0x0100, 3, 1, 19},
        {0x0000, 3, 7, 18},
    },
};

SaturnSpriteFrame5 g_RStage15SpriteBank24Frame18 = {
    {0x0500, 0x0000},
    {
        {0x0100, -13, -19, 21},
        {0x0100, -7, 6, 22},
        {0x0000, 1, 23, 23},
        {0x0100, -11, 2, 19},
        {0x0000, -8, 8, 24},
    },
};

SaturnSpriteFrame5 g_RStage15SpriteBank24Frame19 = {
    {0x0500, 0x0000},
    {
        {0x0100, -12, -19, 21},
        {0x0100, -6, 2, 25},
        {0x0000, 6, 23, 26},
        {0x0100, -10, 5, 17},
        {0x0000, -11, 11, 18},
    },
};

SaturnSpriteFrame5 g_RStage15SpriteBank24Frame20 = {
    {0x0500, 0x0000},
    {
        {0x0100, -2, -18, 14},
        {0x0100, 0, 6, 15},
        {0x0000, 2, 23, 27},
        {0x0100, 0, 4, 17},
        {0x0000, -1, 11, 20},
    },
};

SaturnSpriteFrame5 g_RStage15SpriteBank24Frame21 = {
    {0x0500, 0x0000},
    {
        {0x0100, 2, -17, 14},
        {0x0100, 0, 6, 28},
        {0x0000, -3, 23, 29},
        {0x0100, 4, 4, 17},
        {0x0000, 3, 10, 18},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank24Frame22 = {
    {0x0700, 0x0000},
    {
        {0x0100, -5, 3, 30},
        {0x0000, -7, 8, 18},
        {0x0100, 1, -17, 31},
        {0x0100, 2, 6, 15},
        {0x0000, 2, 23, 16},
        {0x0100, 3, 4, 17},
        {0x0000, 2, 9, 18},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank24Frame23 = {
    {0x0800, 0x0000},
    {
        {0x0100, -12, 3, 30},
        {0x0000, -13, 8, 18},
        {0x0100, 1, -17, 31},
        {0x0100, 5, 4, 32},
        {0x0100, 16, 3, 33},
        {0x0000, 4, 23, 34},
        {0x0000, 24, 9, 35},
        {0x0100, 23, 12, 36},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank24Frame24 = {
    {0x0800, 0x0000},
    {
        {0x0100, -14, 3, 30},
        {0x0000, -15, 8, 18},
        {0x0100, 1, -19, 37},
        {0x0100, 5, 4, 32},
        {0x0100, 18, 3, 33},
        {0x0000, 4, 23, 34},
        {0x0000, 26, 9, 35},
        {0x0100, 25, 12, 36},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank24Frame25 = {
    {0x0800, 0x0000},
    {
        {0x0100, 1, -19, 37},
        {0x0100, -13, 5, 38},
        {0x0110, 14, 5, 38},
        {0x0000, 3, 23, 39},
        {0x0000, 31, 10, 35},
        {0x0100, 30, 13, 36},
        {0x0010, -30, 10, 35},
        {0x0110, -29, 13, 36},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank24Frame26 = {
    {0x0800, 0x0000},
    {
        {0x0110, -1, -17, 31},
        {0x0100, -13, 5, 38},
        {0x0110, 14, 5, 38},
        {0x0010, -2, 23, 39},
        {0x0000, 31, 10, 35},
        {0x0100, 30, 13, 36},
        {0x0010, -30, 10, 35},
        {0x0110, -29, 13, 36},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank24Frame27 = {
    {0x0800, 0x0000},
    {
        {0x0110, 15, 4, 30},
        {0x0110, -1, -17, 31},
        {0x0110, -5, 4, 32},
        {0x0110, -18, 4, 33},
        {0x0010, -4, 23, 34},
        {0x0010, -26, 10, 35},
        {0x0110, -25, 13, 36},
        {0x0010, 16, 9, 18},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank24Frame28 = {
    {0x0800, 0x0000},
    {
        {0x0110, 14, 4, 30},
        {0x0110, -1, -18, 14},
        {0x0110, -5, 4, 32},
        {0x0110, -16, 4, 33},
        {0x0010, -4, 23, 34},
        {0x0010, 15, 9, 18},
        {0x0010, -24, 10, 35},
        {0x0110, -23, 13, 36},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank24Frame29 = {
    {0x0700, 0x0000},
    {
        {0x0110, 5, 3, 30},
        {0x0010, 6, 10, 18},
        {0x0110, -1, -18, 14},
        {0x0110, -2, 6, 15},
        {0x0010, -2, 23, 16},
        {0x0110, -4, 4, 17},
        {0x0010, -3, 10, 18},
    },
};

SaturnSpriteFrame5 g_RStage15SpriteBank24Frame30 = {
    {0x0500, 0x0000},
    {
        {0x0110, -1, -18, 14},
        {0x0110, -2, 6, 15},
        {0x0010, -2, 23, 16},
        {0x0110, -2, 4, 17},
        {0x0010, -1, 10, 18},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank24Frame31 = {
    {0x0700, 0x0000},
    {
        {0x0100, 0, -7, 40},
        {0x0010, -9, -11, 24},
        {0x0100, 1, -18, 14},
        {0x0100, 2, 6, 15},
        {0x0000, 2, 23, 16},
        {0x0100, 0, 4, 17},
        {0x0000, -1, 11, 20},
    },
};

SaturnSpriteFrame6 g_RStage15SpriteBank24Frame32 = {
    {0x0600, 0x0000},
    {
        {0x0100, 4, -18, 40},
        {0x0100, 1, -18, 14},
        {0x0100, 2, 5, 41},
        {0x0000, 2, 23, 16},
        {0x0100, -11, 1, 42},
        {0x0000, -14, 9, 43},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank24Frame33 = {
    {0x0800, 0x0000},
    {
        {0x0100, 16, -19, 44},
        {0x0100, 1, -18, 14},
        {0x0100, 2, 5, 41},
        {0x0000, 2, 23, 16},
        {0x0100, -11, 1, 42},
        {0x0200, 20, -40, 45},
        {0x0010, -19, 10, 20},
        {0x0010, 12, -24, 46},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank24Frame34 = {
    {0x0800, 0x0000},
    {
        {0x0100, 18, -20, 44},
        {0x0100, 1, -18, 14},
        {0x0100, 2, 5, 47},
        {0x0000, 2, 23, 16},
        {0x0100, -14, -6, 48},
        {0x0200, 19, -46, 7},
        {0x0010, -26, -4, 24},
        {0x0000, 19, -23, 49},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank24Frame35 = {
    {0x0800, 0x0000},
    {
        {0x0100, 17, -19, 44},
        {0x0100, 1, -18, 14},
        {0x0100, 2, 5, 47},
        {0x0000, 2, 23, 16},
        {0x0100, -14, -5, 48},
        {0x0200, 20, -46, 8},
        {0x0010, -23, -2, 18},
        {0x0000, 18, -24, 46},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank24Frame36 = {
    {0x0800, 0x0000},
    {
        {0x0100, 18, -18, 44},
        {0x0100, 1, -18, 14},
        {0x0100, 2, 5, 47},
        {0x0000, 2, 23, 16},
        {0x0100, -14, -5, 48},
        {0x0200, 19, -46, 9},
        {0x0010, -23, -2, 18},
        {0x0010, 14, -22, 46},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank24Frame37 = {
    {0x0800, 0x0000},
    {
        {0x0100, 19, -19, 44},
        {0x0100, 1, -18, 14},
        {0x0100, 2, 5, 47},
        {0x0000, 2, 23, 16},
        {0x0100, -14, -6, 48},
        {0x0200, 19, -46, 10},
        {0x0010, -23, -3, 18},
        {0x0000, 20, -21, 49},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank24Frame38 = {
    {0x0800, 0x0000},
    {
        {0x0100, 16, -19, 44},
        {0x0100, 1, -18, 14},
        {0x0100, 2, 5, 41},
        {0x0000, 2, 23, 16},
        {0x0100, -11, 1, 42},
        {0x0200, 16, -43, 7},
        {0x0010, 14, -23, 46},
        {0x0010, -19, 10, 20},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank24Frame39 = {
    {0x0800, 0x0000},
    {
        {0x0100, 8, -20, 44},
        {0x0000, 10, -24, 46},
        {0x0100, 1, -18, 14},
        {0x0100, 2, 6, 15},
        {0x0000, 2, 23, 16},
        {0x0100, -5, 1, 42},
        {0x0200, 9, -45, 8},
        {0x0010, -14, 10, 20},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank24Frame40 = {
    {0x0700, 0x0000},
    {
        {0x0100, -2, -19, 40},
        {0x0010, -8, -22, 46},
        {0x0100, -7, -1, 50},
        {0x0000, 2, 23, 16},
        {0x0200, -19, -39, 9},
        {0x0100, 0, 6, 51},
        {0x0000, -1, 12, 20},
    },
};

SaturnSpriteFrame6 g_RStage15SpriteBank24Frame41 = {
    {0x0600, 0x0000},
    {
        {0x0100, -12, -11, 40},
        {0x0200, -31, -33, 10},
        {0x0100, -7, -1, 50},
        {0x0000, 2, 23, 16},
        {0x0100, 1, 4, 51},
        {0x0000, 0, 10, 20},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank24Frame42 = {
    {0x0800, 0x0000},
    {
        {0x0100, -30, -4, 52},
        {0x0100, -8, -1, 53},
        {0x0000, 2, 23, 16},
        {0x0100, -50, -6, 54},
        {0x0200, -60, -6, 55},
        {0x0100, 11, -2, 51},
        {0x0000, 10, 4, 20},
        {0x0000, -45, 1, 20},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank24Frame43 = {
    {0x0800, 0x0000},
    {
        {0x0100, -31, -4, 52},
        {0x0100, -9, -1, 53},
        {0x0000, 3, 23, 16},
        {0x0100, -51, -6, 54},
        {0x0200, -61, -6, 56},
        {0x0100, 10, -2, 51},
        {0x0000, -47, 0, 43},
        {0x0000, 12, 2, 24},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank24Frame44 = {
    {0x0800, 0x0000},
    {
        {0x0200, -32, -4, 52},
        {0x0200, -9, -1, 53},
        {0x0000, 3, 23, 16},
        {0x0200, -52, -6, 54},
        {0x0200, -60, -5, 57},
        {0x0200, 11, -2, 51},
        {0x0010, -52, 1, 20},
        {0x0000, 10, 4, 20},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank24Frame45 = {
    {0x0800, 0x0000},
    {
        {0x0100, -31, -4, 52},
        {0x0100, -8, -1, 53},
        {0x0000, 2, 23, 16},
        {0x0100, -51, -6, 54},
        {0x0200, -60, -5, 58},
        {0x0100, 10, -2, 51},
        {0x0010, -51, 1, 20},
        {0x0000, 12, 2, 24},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank24Frame46 = {
    {0x0700, 0x0000},
    {
        {0x0100, -30, -4, 52},
        {0x0100, -8, -1, 53},
        {0x0000, 2, 23, 16},
        {0x0100, -50, -6, 54},
        {0x0100, 11, -2, 51},
        {0x0000, 10, 4, 20},
        {0x0000, -45, 0, 43},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank24Frame47 = {
    {0x0700, 0x0000},
    {
        {0x0100, -41, -1, 54},
        {0x0100, -21, 1, 52},
        {0x0100, -8, -1, 53},
        {0x0000, 2, 23, 16},
        {0x0100, 8, 1, 51},
        {0x0010, -40, 5, 59},
        {0x0000, 10, 5, 24},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank24Frame48 = {
    {0x0700, 0x0000},
    {
        {0x0100, -18, 9, 60},
        {0x0010, -24, 9, 20},
        {0x0100, -10, -17, 21},
        {0x0100, -4, 4, 25},
        {0x0000, 1, 23, 16},
        {0x0100, -8, 6, 17},
        {0x0000, -6, 11, 24},
    },
};

SaturnSpriteFrame5 g_RStage15SpriteBank24Frame49 = {
    {0x0500, 0x0000},
    {
        {0x0100, -1, -17, 14},
        {0x0100, 1, 7, 15},
        {0x0000, 1, 23, 16},
        {0x0100, -1, 5, 17},
        {0x0000, -2, 12, 20},
    },
};

SaturnSpriteFrame5 g_RStage15SpriteBank24Frame50 = {
    {0x0500, 0x0000},
    {
        {0x0100, 3, 6, 15},
        {0x0000, 2, 23, 16},
        {0x0100, 5, -21, 61},
        {0x0100, 4, 5, 17},
        {0x0000, 3, 11, 43},
    },
};

SaturnSpriteFrame5 g_RStage15SpriteBank24Frame51 = {
    {0x0500, 0x0000},
    {
        {0x0100, 6, -23, 61},
        {0x0100, 1, 5, 62},
        {0x0000, 2, 23, 16},
        {0x0100, 10, 5, 63},
        {0x0010, 8, 9, 49},
    },
};

SaturnSpriteFrame5 g_RStage15SpriteBank24Frame52 = {
    {0x0500, 0x0000},
    {
        {0x0100, 2, 6, 15},
        {0x0000, 2, 23, 16},
        {0x0100, 5, -22, 61},
        {0x0100, 8, 5, 63},
        {0x0000, 11, 8, 46},
    },
};

SaturnSpriteFrame5 g_RStage15SpriteBank24Frame53 = {
    {0x0500, 0x0000},
    {
        {0x0100, -2, -20, 64},
        {0x0100, 1, 6, 15},
        {0x0000, 2, 23, 16},
        {0x0100, 3, 4, 17},
        {0x0010, 0, 8, 49},
    },
};

SaturnSpriteFrame4 g_RStage15SpriteBank24Frame54 = {
    {0x0400, 0x0000},
    {
        {0x0100, -6, 3, 50},
        {0x0000, 2, 23, 16},
        {0x0100, -9, 11, 17},
        {0x0010, -13, 15, 49},
    },
};

SaturnSpriteFrame4 g_RStage15SpriteBank24Frame55 = {
    {0x0400, 0x0000},
    {
        {0x0100, -24, 4, 65},
        {0x0000, -1, 23, 26},
        {0x0100, -34, 10, 42},
        {0x0000, -37, 18, 18},
    },
};

SaturnSpriteFrame4 g_RStage15SpriteBank24Frame56 = {
    {0x0400, 0x0000},
    {
        {0x0100, -24, 4, 65},
        {0x0000, -1, 23, 26},
        {0x0100, -34, 10, 42},
        {0x0000, -37, 19, 20},
    },
};

SaturnSpriteFrame4 g_RStage15SpriteBank24Frame57 = {
    {0x0400, 0x0000},
    {
        {0x0100, -24, 4, 65},
        {0x0000, -1, 23, 26},
        {0x0100, -34, 10, 42},
        {0x0000, -37, 19, 43},
    },
};

SaturnSpriteFrame4 g_RStage15SpriteBank24Frame58 = {
    {0x0400, 0x0000},
    {
        {0x0100, -24, 4, 65},
        {0x0000, -1, 23, 26},
        {0x0100, -34, 10, 42},
        {0x0010, -42, 19, 20},
    },
};

SaturnSpriteFrame4 g_RStage15SpriteBank24Frame59 = {
    {0x0400, 0x0000},
    {
        {0x0100, -24, 4, 65},
        {0x0000, -1, 23, 26},
        {0x0100, -34, 10, 42},
        {0x0000, -37, 19, 43},
    },
};

SaturnSpriteFrame4 g_RStage15SpriteBank24Frame60 = {
    {0x0400, 0x0000},
    {
        {0x0100, -24, 4, 65},
        {0x0000, -1, 23, 26},
        {0x0100, -34, 10, 42},
        {0x0000, -37, 19, 43},
    },
};

SaturnSpriteFrame4 g_RStage15SpriteBank24Frame61 = {
    {0x0400, 0x0000},
    {
        {0x0100, -24, 4, 65},
        {0x0000, -1, 23, 26},
        {0x0100, -34, 10, 42},
        {0x0000, -37, 19, 20},
    },
};

SaturnSpriteFrame4 g_RStage15SpriteBank24Frame62 = {
    {0x0400, 0x0000},
    {
        {0x0100, -24, 4, 65},
        {0x0000, -1, 23, 26},
        {0x0100, -34, 10, 42},
        {0x0000, -37, 19, 43},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame63 = {
    {0x0100, 0x0000},
    {
        {0x0200, 6, 1, 66},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame64 = {
    {0x0100, 0x0000},
    {
        {0x0200, 7, 1, 67},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame65 = {
    {0x0100, 0x0000},
    {
        {0x0200, 7, 1, 68},
    },
};

SaturnSpriteFrame5 g_RStage15SpriteBank24Frame66 = {
    {0x0500, 0x0000},
    {
        {0x0100, 3, 6, 62},
        {0x0000, 2, 23, 16},
        {0x0100, 12, 6, 63},
        {0x0100, 7, -23, 69},
        {0x0000, 15, 12, 24},
    },
};

SaturnSpriteFrame5 g_RStage15SpriteBank24Frame67 = {
    {0x0500, 0x0000},
    {
        {0x0300, 2, 5, 62},
        {0x0300, 2, 23, 16},
        {0x0300, 11, 5, 63},
        {0x0300, 6, -24, 69},
        {0x0300, 15, 10, 24},
    },
};

SaturnSpriteFrame5 g_RStage15SpriteBank24Frame68 = {
    {0x0500, 0x0000},
    {
        {0x0400, 2, 5, 62},
        {0x0400, 2, 23, 16},
        {0x0400, 11, 5, 63},
        {0x0400, 6, -24, 69},
        {0x0400, 15, 11, 24},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame69 = {
    {0x0100, 0x0000},
    {
        {0x0200, 3, -28, 70},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank24Frame70 = {
    {0x0100, 0x0000},
    {
        {0x0400, 6, 2, 71},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank24Frame71 = {
    {0x0700, 0x0000},
    {
        {0x0100, 16, -19, 44},
        {0x0100, 1, -18, 14},
        {0x0100, 2, 5, 41},
        {0x0000, 2, 23, 16},
        {0x0100, -11, 1, 42},
        {0x0010, -19, 10, 20},
        {0x0010, 12, -24, 46},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank24Frame72 = {
    {0x0700, 0x0000},
    {
        {0x0100, 18, -20, 44},
        {0x0100, 1, -18, 14},
        {0x0100, 2, 5, 47},
        {0x0000, 2, 23, 16},
        {0x0100, -14, -6, 48},
        {0x0010, -26, -4, 24},
        {0x0010, 14, -24, 46},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank24Frame73 = {
    {0x0700, 0x0000},
    {
        {0x0100, 18, -19, 44},
        {0x0100, 1, -18, 14},
        {0x0100, 2, 5, 47},
        {0x0000, 2, 23, 16},
        {0x0100, -14, -7, 48},
        {0x0000, -21, -6, 49},
        {0x0000, 19, -22, 49},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank24Frame74 = {
    {0x0700, 0x0000},
    {
        {0x0100, 8, -20, 44},
        {0x0100, 1, -18, 14},
        {0x0100, 2, 6, 15},
        {0x0000, 2, 23, 16},
        {0x0100, -5, 1, 42},
        {0x0000, 10, -24, 46},
        {0x0010, -14, 10, 20},
    },
};

SaturnSpriteFrame5 g_RStage15SpriteBank24Frame75 = {
    {0x0500, 0x0000},
    {
        {0x0100, -12, -11, 40},
        {0x0100, -7, -1, 50},
        {0x0000, 2, 23, 16},
        {0x0100, 1, 4, 51},
        {0x0000, 0, 10, 20},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank24Frame76 = {
    {0x0700, 0x0000},
    {
        {0x0100, -30, -4, 52},
        {0x0100, -8, -1, 53},
        {0x0000, 2, 23, 16},
        {0x0100, 11, -2, 51},
        {0x0100, -44, 1, 60},
        {0x0000, 10, 4, 20},
        {0x0000, -45, 1, 20},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank24Frame77 = {
    {0x0700, 0x0000},
    {
        {0x0100, -32, -4, 52},
        {0x0100, -8, -1, 53},
        {0x0000, 2, 23, 16},
        {0x0100, 11, -2, 51},
        {0x0100, -46, 1, 60},
        {0x0000, 11, 3, 18},
        {0x0000, -47, 1, 43},
    },
};

SaturnSpriteFrame6 g_RStage15SpriteBank24Frame78 = {
    {0x0600, 0x0000},
    {
        {0x0100, -26, 8, 72},
        {0x0100, -8, -1, 53},
        {0x0000, 2, 23, 16},
        {0x0100, 11, -2, 51},
        {0x0000, 10, 4, 20},
        {0x0010, -31, 14, 46},
    },
};

SaturnSpriteFrame6 g_RStage15SpriteBank24Frame79 = {
    {0x0600, 0x0000},
    {
        {0x0100, -24, 8, 72},
        {0x0100, -8, -1, 53},
        {0x0000, 2, 23, 16},
        {0x0100, 11, -2, 51},
        {0x0000, -25, 16, 49},
        {0x0000, 11, 3, 18},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank24Frame80 = {
    {0x0700, 0x0000},
    {
        {0x0100, -21, 1, 52},
        {0x0100, -8, -1, 53},
        {0x0000, 2, 23, 16},
        {0x0100, 8, 1, 51},
        {0x0100, -35, 6, 60},
        {0x0010, 5, 4, 49},
        {0x0010, -39, 5, 59},
    },
};

SaturnSpriteFrame10 g_RStage15SpriteBank24Frame81 = {
    {0x0A00, 0x0000},
    {
        {0x0000, 2, -31, 7},
        {0x0000, 20, -16, 0},
        {0x0100, 18, -20, 44},
        {0x0100, 1, -18, 14},
        {0x0100, 2, 5, 47},
        {0x0000, 2, 23, 16},
        {0x0100, -14, -6, 48},
        {0x0200, 19, -46, 7},
        {0x0010, -26, -4, 24},
        {0x0000, 19, -23, 49},
    },
};

SaturnSpriteFrameHeader* g_RStage15SpriteBank24Frames[82] = {
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame0,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame1,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame2,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame3,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame4,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame5,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame6,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame7,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame8,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame9,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame10,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame11,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame12,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame13,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame14,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame15,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame16,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame17,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame18,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame19,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame20,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame21,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame22,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame23,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame24,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame25,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame26,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame27,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame28,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame29,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame30,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame31,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame32,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame33,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame34,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame35,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame36,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame37,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame38,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame39,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame40,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame41,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame42,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame43,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame44,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame45,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame46,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame47,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame48,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame49,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame50,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame51,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame52,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame53,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame54,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame55,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame56,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame57,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame58,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame59,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame60,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame61,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame62,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame63,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame64,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame65,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame66,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame67,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame68,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame69,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame70,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame71,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame72,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame73,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame74,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame75,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame76,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame77,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame78,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame79,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame80,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank24Frame81,
};

SaturnSpriteImage g_RStage15SpriteBank24Images[74] = {
    {20, 31, 0x0000}, {20, 32, 0x009C}, {20, 32, 0x013C}, {20, 31, 0x01DC},
    {20, 20, 0x0278}, {16, 12, 0x02DC}, {16, 7, 0x030C},  {8, 11, 0x0328},
    {8, 10, 0x0340},  {8, 11, 0x0354},  {8, 11, 0x036C},  {8, 7, 0x0384},
    {8, 5, 0x0394},   {8, 2, 0x03A0},   {12, 12, 0x03A4}, {12, 19, 0x03C8},
    {12, 14, 0x0404}, {16, 18, 0x0430}, {4, 6, 0x0478},   {16, 16, 0x0480},
    {4, 7, 0x04C0},   {12, 10, 0x04C8}, {12, 19, 0x04E8}, {12, 14, 0x0524},
    {8, 5, 0x0550},   {12, 15, 0x055C}, {16, 14, 0x058C}, {16, 14, 0x05C4},
    {12, 18, 0x05FC}, {16, 14, 0x0634}, {16, 18, 0x066C}, {12, 14, 0x06B4},
    {16, 21, 0x06E0}, {12, 17, 0x0734}, {16, 14, 0x0768}, {8, 6, 0x07A0},
    {8, 8, 0x07AC},   {8, 12, 0x07BC},  {20, 20, 0x07D4}, {16, 14, 0x0838},
    {16, 18, 0x0870}, {12, 19, 0x08B8}, {20, 14, 0x08F4}, {4, 7, 0x093C},
    {12, 18, 0x0944}, {8, 6, 0x097C},   {8, 2, 0x0988},   {12, 20, 0x098C},
    {20, 14, 0x09C8}, {8, 4, 0x0A10},   {20, 27, 0x0A18}, {16, 17, 0x0AA0},
    {16, 8, 0x0AE4},  {20, 27, 0x0B04}, {12, 9, 0x0B8C},  {4, 10, 0x0BA8},
    {4, 14, 0x0BB4},  {8, 33, 0x0BC4},  {8, 33, 0x0C08},  {4, 7, 0x0C4C},
    {16, 7, 0x0C54},  {8, 10, 0x0C70},  {12, 19, 0x0C84}, {12, 19, 0x0CC0},
    {12, 10, 0x0CFC}, {24, 19, 0x0D1C}, {12, 17, 0x0D90}, {12, 16, 0x0DC4},
    {12, 17, 0x0DF4}, {8, 10, 0x0E28},  {20, 28, 0x0E3C}, {16, 36, 0x0EC8},
    {12, 20, 0x0F58}, {0, 0, 0x0F94},
};
