// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[5][16];
    u16 padding[1];
} g_RStage15SpriteBank26Palette = {
    0x0005,
    {
        {
            0x8842,
            0xC3B8,
            0xA2D0,
            0xA60B,
            0xA945,
            0xC40C,
            0x8401,
            0x806D,
            0x80D8,
            0xD4B0,
            0xDCD6,
            0xF99E,
            0x80D1,
            0x815F,
            0xA4A5,
            0xEF9C,
        },
        {
            0xB103,
            0xB779,
            0x9AB1,
            0xA5EC,
            0xA146,
            0xB84C,
            0x8401,
            0x808D,
            0x8518,
            0xC4D0,
            0xCD16,
            0xE5BC,
            0x8111,
            0x899D,
            0x98A6,
            0xEF9C,
        },
        {
            0x9164,
            0xAF3A,
            0x9692,
            0xA5EE,
            0x9948,
            0xAC8C,
            0x8401,
            0x80CD,
            0x8D78,
            0xB4F0,
            0xBD56,
            0xD5FB,
            0x8152,
            0x95FC,
            0x90A7,
            0xEF9C,
        },
        {
            0xC464,
            0xA6FB,
            0x9273,
            0xA5EF,
            0x914A,
            0xA0CC,
            0x8401,
            0x80ED,
            0x95D8,
            0xA510,
            0xAD96,
            0xC63A,
            0x8193,
            0x9E5A,
            0x88A8,
            0xEF9C,
        },
        {
            0x9C4D,
            0xAEDC,
            0x8E54,
            0xA5F1,
            0x8D4C,
            0x950C,
            0x8401,
            0x812D,
            0x9E38,
            0x9930,
            0xA1D6,
            0xB679,
            0x81D4,
            0xAAB8,
            0x80AA,
            0xEF9C,
        },
    },
    {0x0000},
};

SaturnSpriteFrameHeader g_RStage15SpriteBank26Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -10, 0},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 5, -9, 1},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 5, -8, 2},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0000, -3, 0, 3},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0000, -2, 2, 4},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0000, -4, 2, 5},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0000, -3, 1, 4},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0000, -3, -1, 3},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, -8, 2},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame10 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, -8, 1},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame11 = {
    {0x0100, 0x0000},
    {
        {0x0000, -4, -2, 6},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame12 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, -8, 7},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame13 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, -9, 8},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame14 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -10, 9},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame15 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -10, 10},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame16 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -10, 11},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame17 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -10, 12},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame18 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -10, 11},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame19 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -10, 9},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame20 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -11, 11},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame21 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -12, 12},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame22 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -12, 9},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame23 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, -9, 8},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame24 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, -8, 7},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame25 = {
    {0x0100, 0x0000},
    {
        {0x0000, -4, -1, 6},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame26 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, -10, 13},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame27 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, -9, 14},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame28 = {
    {0x0100, 0x0000},
    {
        {0x0100, 3, -7, 15},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame29 = {
    {0x0100, 0x0000},
    {
        {0x0200, 2, -5, 16},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame30 = {
    {0x0100, 0x0000},
    {
        {0x0300, 5, -5, 17},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame31 = {
    {0x0100, 0x0000},
    {
        {0x0400, 5, -4, 17},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame32 = {
    {0x0100, 0x0000},
    {
        {0x0400, 5, -4, 18},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank26Frame33 = {
    {0x0100, 0x0000},
    {
        {0x0400, 1, -3, 19},
    },
};

SaturnSpriteFrameHeader* g_RStage15SpriteBank26Frames[34] = {
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame0,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame1,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame2,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame3,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame4,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame5,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame6,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame7,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame8,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame9,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame10,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame11,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame12,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame13,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame14,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame15,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame16,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame17,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame18,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame19,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame20,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame21,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame22,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame23,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame24,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame25,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame26,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame27,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame28,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame29,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame30,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame31,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame32,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank26Frame33,
};

SaturnSpriteImage g_RStage15SpriteBank26Images[21] = {
    {20, 14, 0x0000}, {24, 14, 0x0048}, {24, 14, 0x009C}, {16, 12, 0x00F0},
    {16, 11, 0x0120}, {16, 11, 0x014C}, {16, 12, 0x0178}, {24, 14, 0x01A8},
    {24, 14, 0x01FC}, {20, 14, 0x0250}, {20, 15, 0x0298}, {20, 15, 0x02E4},
    {20, 15, 0x0330}, {24, 14, 0x037C}, {20, 12, 0x03D0}, {16, 10, 0x040C},
    {12, 9, 0x0434},  {12, 8, 0x0450},  {12, 8, 0x0468},  {8, 8, 0x0480},
    {0, 0, 0x0490},
};
