// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[4][16];
    u16 padding[1];
} g_RStage15SpriteBank27Palette = {
    0x0004,
    {
        {
            0x80E0,
            0x84CB,
            0x8D53,
            0xA21A,
            0xB6DB,
            0xD79B,
            0x8000,
            0x8157,
            0x82FF,
            0x83BF,
            0x801F,
            0x9084,
            0xB148,
            0xCA2E,
            0xE2F6,
            0xEF7B,
        },
        {
            0x80A0,
            0x940B,
            0x940E,
            0x9411,
            0x9414,
            0x9416,
            0x800B,
            0x800E,
            0x8011,
            0x8014,
            0x8016,
            0x8019,
            0x801C,
            0x801F,
            0x9574,
            0x8E5F,
        },
        {
            0x8160,
            0x8C63,
            0xA108,
            0xA975,
            0xCD9E,
            0xDB1F,
            0x9925,
            0x9DCB,
            0xAE90,
            0xBF72,
            0xCE73,
            0xEB5A,
            0x800B,
            0x9076,
            0x957E,
            0x9F3E,
        },
        {
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0xE4DF,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
        },
    },
    {0x0000},
};

SaturnSpriteFrameHeader g_RStage15SpriteBank27Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 g_RStage15SpriteBank27Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 3, 0},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank27Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 5, 4, 1},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank27Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0100, 4, 7, 2},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank27Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0100, 4, 7, 3},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank27Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0100, 1, 7, 4},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank27Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0100, 1, 7, 5},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank27Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0200, 2, -1, 6},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank27Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0300, 2, 3, 0},
    },
};

SaturnSpriteFrameHeader* g_RStage15SpriteBank27Frames[9] = {
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank27Frame0,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank27Frame1,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank27Frame2,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank27Frame3,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank27Frame4,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank27Frame5,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank27Frame6,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank27Frame7,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank27Frame8,
};

SaturnSpriteImage g_RStage15SpriteBank27Images[8] = {
    {20, 27, 0x0000}, {20, 23, 0x0088}, {20, 21, 0x00FC}, {20, 21, 0x0168},
    {16, 21, 0x01D4}, {16, 21, 0x0228}, {8, 25, 0x027C},  {0, 0, 0x02B0},
};
