// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[2][16];
    u16 padding[1];
} g_RStage15SpriteBank28Palette = {
    0x0002,
    {
        {
            0x8922,
            0x8485,
            0x8CEA,
            0x954E,
            0x94E6,
            0xA969,
            0xD231,
            0xF338,
            0x800F,
            0x8014,
            0x8039,
            0x845E,
            0x8318,
            0x8256,
            0x8131,
            0x8441,
        },
        {
            0x84C0,
            0x8000,
            0x94A5,
            0xA529,
            0xBDEF,
            0xDEF7,
            0x9840,
            0xACE3,
            0xC586,
            0xACE3,
            0x829B,
            0xA067,
            0xBCEC,
            0xD572,
            0x9004,
            0x85BB,
        },
    },
    {0x0000},
};

SaturnSpriteFrameHeader g_RStage15SpriteBank28Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame6 g_RStage15SpriteBank28Frame1 = {
    {0x0600, 0x0000},
    {
        {0x0000, 12, -44, 0},
        {0x0100, 2, -24, 1},
        {0x0000, 13, -21, 2},
        {0x0000, -22, -13, 3},
        {0x0000, -6, -25, 0},
        {0x0100, -9, -22, 4},
    },
};

SaturnSpriteFrame6 g_RStage15SpriteBank28Frame2 = {
    {0x0600, 0x0000},
    {
        {0x0000, 9, -39, 5},
        {0x0100, 1, -23, 6},
        {0x0000, 11, -22, 2},
        {0x0000, -27, -13, 7},
        {0x0000, -11, -22, 5},
        {0x0100, -10, -21, 4},
    },
};

SaturnSpriteFrame6 g_RStage15SpriteBank28Frame3 = {
    {0x0600, 0x0000},
    {
        {0x0000, 11, -28, 8},
        {0x0100, 3, -23, 9},
        {0x0000, 10, -22, 2},
        {0x0000, -13, -20, 8},
        {0x0000, -29, -14, 10},
        {0x0100, -10, -20, 4},
    },
};

SaturnSpriteFrame4 g_RStage15SpriteBank28Frame4 = {
    {0x0400, 0x0000},
    {
        {0x0000, 6, -60, 11},
        {0x0000, 20, -37, 12},
        {0x0100, 1, -22, 13},
        {0x0010, -5, -19, 2},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank28Frame5 = {
    {0x0700, 0x0000},
    {
        {0x0000, -28, -62, 14},
        {0x0000, -15, -74, 15},
        {0x0020, -12, -46, 0},
        {0x0020, 12, -32, 0},
        {0x0100, -3, -38, 16},
        {0x0100, 0, -21, 17},
        {0x0000, 4, -19, 18},
    },
};

SaturnSpriteFrame6 g_RStage15SpriteBank28Frame6 = {
    {0x0600, 0x0000},
    {
        {0x0000, -37, -43, 19},
        {0x0000, -22, -33, 20},
        {0x0000, -8, -31, 20},
        {0x0100, -6, -33, 21},
        {0x0100, 0, -21, 17},
        {0x0000, 8, -20, 18},
    },
};

SaturnSpriteFrame6 g_RStage15SpriteBank28Frame7 = {
    {0x0600, 0x0000},
    {
        {0x0000, -37, -6, 10},
        {0x0000, -21, -12, 8},
        {0x0000, -7, -18, 8},
        {0x0000, 6, -24, 8},
        {0x0100, 0, -19, 22},
        {0x0000, 18, -20, 2},
    },
};

SaturnSpriteFrame6 g_RStage15SpriteBank28Frame8 = {
    {0x0600, 0x0000},
    {
        {0x0000, 10, -54, 23},
        {0x0000, 11, -24, 24},
        {0x0000, 11, -20, 24},
        {0x0100, 13, -29, 25},
        {0x0100, 1, -21, 26},
        {0x0000, 7, -19, 2},
    },
};

SaturnSpriteFrame6 g_RStage15SpriteBank28Frame9 = {
    {0x0600, 0x0000},
    {
        {0x0000, 10, -54, 23},
        {0x0000, 11, -24, 24},
        {0x0000, 11, -20, 24},
        {0x0100, 13, -29, 25},
        {0x0100, 1, -21, 26},
        {0x0000, 2, -19, 18},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank28Frame10 = {
    {0x0700, 0x0000},
    {
        {0x0000, 10, -54, 23},
        {0x0000, 11, -24, 24},
        {0x0000, 11, -20, 24},
        {0x0100, 13, -29, 25},
        {0x0100, 1, -21, 26},
        {0x0110, 2, -30, 27},
        {0x0010, -8, -18, 2},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank28Frame11 = {
    {0x0700, 0x0000},
    {
        {0x0000, -17, -48, 14},
        {0x0010, -7, -31, 0},
        {0x0010, 16, -12, 0},
        {0x0100, 14, -28, 25},
        {0x0100, 1, -21, 26},
        {0x0110, 2, -30, 27},
        {0x0010, -8, -18, 2},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank28Frame12 = {
    {0x0700, 0x0000},
    {
        {0x0000, -25, -25, 28},
        {0x0000, -8, -26, 29},
        {0x0000, 20, -26, 30},
        {0x0100, 14, -27, 25},
        {0x0100, 1, -21, 26},
        {0x0110, 2, -30, 27},
        {0x0010, -8, -18, 2},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank28Frame13 = {
    {0x0700, 0x0000},
    {
        {0x0000, -25, -27, 28},
        {0x0000, -8, -26, 29},
        {0x0000, 20, -26, 30},
        {0x0100, 14, -27, 25},
        {0x0100, 1, -21, 26},
        {0x0110, 2, -30, 27},
        {0x0010, -8, -18, 2},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank28Frame14 = {
    {0x0700, 0x0000},
    {
        {0x0000, -25, -26, 28},
        {0x0000, -8, -26, 29},
        {0x0000, 20, -26, 30},
        {0x0100, 14, -27, 25},
        {0x0100, 1, -21, 26},
        {0x0110, 2, -30, 27},
        {0x0010, -8, -18, 2},
    },
};

SaturnSpriteFrame7 g_RStage15SpriteBank28Frame15 = {
    {0x0700, 0x0000},
    {
        {0x0000, -15, -42, 31},
        {0x0000, -33, -26, 28},
        {0x0000, -16, -26, 29},
        {0x0000, 12, -26, 30},
        {0x0100, 5, -29, 25},
        {0x0100, 5, -20, 32},
        {0x0000, -15, -23, 33},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank28Frame16 = {
    {0x0800, 0x0000},
    {
        {0x0000, -13, -47, 31},
        {0x0000, -34, -28, 28},
        {0x0000, -17, -28, 29},
        {0x0000, -4, -28, 29},
        {0x0000, 11, -28, 30},
        {0x0100, 6, -33, 25},
        {0x0100, 5, -22, 34},
        {0x0000, -13, -28, 33},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank28Frame17 = {
    {0x0800, 0x0000},
    {
        {0x0000, -16, -45, 31},
        {0x0000, -33, -28, 28},
        {0x0000, -16, -28, 29},
        {0x0000, -5, -28, 29},
        {0x0000, 12, -28, 30},
        {0x0100, 6, -32, 25},
        {0x0100, 5, -22, 35},
        {0x0000, -16, -26, 33},
    },
};

SaturnSpriteFrame8 g_RStage15SpriteBank28Frame18 = {
    {0x0800, 0x0000},
    {
        {0x0000, -25, -27, 28},
        {0x0000, -8, -27, 29},
        {0x0000, 20, -25, 30},
        {0x0100, 18, -27, 25},
        {0x0100, 11, -33, 36},
        {0x0100, 1, -12, 37},
        {0x0110, 2, -30, 27},
        {0x0010, -9, -19, 2},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank28Frame19 = {
    {0x0100, 0x0000},
    {
        {0x0100, 0, -1, 38},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank28Frame20 = {
    {0x0100, 0x0000},
    {
        {0x0100, 4, 1, 39},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank28Frame21 = {
    {0x0100, 0x0000},
    {
        {0x0100, 0, 3, 40},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank28Frame22 = {
    {0x0100, 0x0000},
    {
        {0x0100, 0, 1, 41},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank28Frame23 = {
    {0x0100, 0x0000},
    {
        {0x0100, 0, 1, 42},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank28Frame24 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 0, 3},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank28Frame25 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 0, 8},
    },
};

SaturnSpriteFrame1 g_RStage15SpriteBank28Frame26 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 0, 2},
    },
};

SaturnSpriteFrameHeader* g_RStage15SpriteBank28Frames[27] = {
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame0,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame1,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame2,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame3,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame4,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame5,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame6,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame7,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame8,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame9,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame10,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame11,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame12,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame13,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame14,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame15,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame16,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame17,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame18,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame19,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame20,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame21,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame22,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame23,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame24,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame25,
    (SaturnSpriteFrameHeader*)&g_RStage15SpriteBank28Frame26,
};

SaturnSpriteImage g_RStage15SpriteBank28Images[44] = {
    {8, 6, 0x0000},   {16, 24, 0x000C}, {8, 19, 0x006C},  {8, 8, 0x0094},
    {4, 1, 0x00A4},   {8, 6, 0x00A8},   {16, 24, 0x00B4}, {8, 6, 0x0114},
    {8, 5, 0x0120},   {20, 23, 0x012C}, {8, 5, 0x01A0},   {8, 12, 0x01AC},
    {8, 11, 0x01C4},  {20, 22, 0x01DC}, {8, 12, 0x024C},  {4, 1, 0x0264},
    {12, 7, 0x0268},  {20, 21, 0x0280}, {8, 19, 0x02EC},  {12, 15, 0x0314},
    {8, 2, 0x0344},   {12, 6, 0x0348},  {20, 19, 0x035C}, {8, 11, 0x03BC},
    {4, 20, 0x03D4},  {4, 5, 0x03E8},   {20, 21, 0x03F0}, {4, 6, 0x045C},
    {16, 6, 0x0464},  {8, 1, 0x047C},   {12, 1, 0x0480},  {4, 4, 0x0484},
    {20, 22, 0x0488}, {4, 19, 0x04F8},  {20, 24, 0x050C}, {20, 23, 0x0584},
    {12, 9, 0x05F8},  {20, 12, 0x0614}, {4, 6, 0x0650},   {12, 7, 0x0658},
    {4, 6, 0x0670},   {8, 11, 0x0678},  {8, 8, 0x0690},   {0, 0, 0x06A0},
};
