// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader AlucardPkg6Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 AlucardPkg6Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 0, 0},
    },
};

SaturnSpriteFrame1 AlucardPkg6Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 0, 1},
    },
};

SaturnSpriteFrame1 AlucardPkg6Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 0, 2},
    },
};

SaturnSpriteFrame1 AlucardPkg6Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, -1, 3},
    },
};

SaturnSpriteFrameHeader* AlucardPkg6Frames[5] = {
    (SaturnSpriteFrameHeader*)&AlucardPkg6Frame0,
    (SaturnSpriteFrameHeader*)&AlucardPkg6Frame1,
    (SaturnSpriteFrameHeader*)&AlucardPkg6Frame2,
    (SaturnSpriteFrameHeader*)&AlucardPkg6Frame3,
    (SaturnSpriteFrameHeader*)&AlucardPkg6Frame4,
};
