// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader AlucardPkg3Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 AlucardPkg3Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 7, 1, 0},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 12, 1, 1},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 8, 1, 2},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0000, 12, 0, 3},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0000, 12, 1, 4},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0000, 8, 1, 5},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0000, 12, 1, 6},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0000, 12, 1, 7},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 0, 8},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame10 = {
    {0x0100, 0x0000},
    {
        {0x0010, -1, 0, 8},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame11 = {
    {0x0100, 0x0000},
    {
        {0x0030, -1, 0, 8},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame12 = {
    {0x0100, 0x0000},
    {
        {0x0020, 2, 0, 8},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame13 = {
    {0x0100, 0x0000},
    {
        {0x0100, 2, 0, 9},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame14 = {
    {0x0100, 0x0000},
    {
        {0x0100, 1, 0, 10},
    },
};

SaturnSpriteFrame4 AlucardPkg3Frame15 = {
    {0x0400, 0x0000},
    {
        {0x0100, -6, -6, 11},
        {0x0110, 6, -6, 11},
        {0x0120, -6, 6, 11},
        {0x0130, 6, 6, 11},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame16 = {
    {0x0100, 0x0000},
    {
        {0x0100, 1, 0, 21},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame17 = {
    {0x0100, 0x0000},
    {
        {0x0200, 1, -7, 12},
    },
};

SaturnSpriteFrame2 AlucardPkg3Frame18 = {
    {0x0200, 0x0000},
    {
        {0x0100, 2, 0, 13},
        {0x0200, 20, -6, 14},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame19 = {
    {0x0100, 0x0000},
    {
        {0x0200, 15, 8, 15},
    },
};

SaturnSpriteFrame2 AlucardPkg3Frame20 = {
    {0x0200, 0x0000},
    {
        {0x0100, 2, 0, 13},
        {0x0200, 1, 9, 16},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame21 = {
    {0x0100, 0x0000},
    {
        {0x0200, -12, 5, 17},
    },
};

SaturnSpriteFrame2 AlucardPkg3Frame22 = {
    {0x0200, 0x0000},
    {
        {0x0100, 2, 0, 13},
        {0x0200, -14, -8, 18},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame23 = {
    {0x0100, 0x0000},
    {
        {0x0220, -7, 15, 12},
    },
};

SaturnSpriteFrame2 AlucardPkg3Frame24 = {
    {0x0200, 0x0000},
    {
        {0x0100, 2, 0, 13},
        {0x0220, 9, 14, 14},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame25 = {
    {0x0100, 0x0000},
    {
        {0x0220, 7, 0, 15},
    },
};

SaturnSpriteFrame2 AlucardPkg3Frame26 = {
    {0x0200, 0x0000},
    {
        {0x0100, 2, 0, 13},
        {0x0220, 11, -18, 16},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame27 = {
    {0x0100, 0x0000},
    {
        {0x0220, -6, -13, 17},
    },
};

SaturnSpriteFrame2 AlucardPkg3Frame28 = {
    {0x0200, 0x0000},
    {
        {0x0100, 2, 0, 13},
        {0x0220, -8, 0, 18},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame29 = {
    {0x0100, 0x0000},
    {
        {0x0300, 0, 0, 19},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame30 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 0, 20},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame31 = {
    {0x0100, 0x0000},
    {
        {0x0010, -1, 0, 20},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame32 = {
    {0x0100, 0x0000},
    {
        {0x0030, -1, 0, 20},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame33 = {
    {0x0100, 0x0000},
    {
        {0x0020, 1, 0, 20},
    },
};

SaturnSpriteFrame2 AlucardPkg3Frame34 = {
    {0x0200, 0x0000},
    {
        {0x0100, 1, 0, 21},
        {0x0200, 15, -6, 14},
    },
};

SaturnSpriteFrame2 AlucardPkg3Frame35 = {
    {0x0200, 0x0000},
    {
        {0x0100, 1, 0, 21},
        {0x0200, 1, 9, 16},
    },
};

SaturnSpriteFrame2 AlucardPkg3Frame36 = {
    {0x0200, 0x0000},
    {
        {0x0100, 1, 0, 21},
        {0x0200, -13, -8, 18},
    },
};

SaturnSpriteFrame2 AlucardPkg3Frame37 = {
    {0x0200, 0x0000},
    {
        {0x0100, 1, 0, 21},
        {0x0220, 9, 14, 14},
    },
};

SaturnSpriteFrame2 AlucardPkg3Frame38 = {
    {0x0200, 0x0000},
    {
        {0x0100, 1, 0, 21},
        {0x0220, 10, -17, 16},
    },
};

SaturnSpriteFrame2 AlucardPkg3Frame39 = {
    {0x0200, 0x0000},
    {
        {0x0100, 1, 0, 21},
        {0x0220, -9, 0, 18},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame40 = {
    {0x0100, 0x0000},
    {
        {0x0400, 7, 1, 0},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame41 = {
    {0x0100, 0x0000},
    {
        {0x0500, 7, 1, 0},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame42 = {
    {0x0100, 0x0000},
    {
        {0x0600, 7, 1, 0},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame43 = {
    {0x0100, 0x0000},
    {
        {0x0700, 7, 1, 0},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame44 = {
    {0x0100, 0x0000},
    {
        {0x0800, 7, 1, 0},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame45 = {
    {0x0100, 0x0000},
    {
        {0x0900, 7, 1, 0},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame46 = {
    {0x0100, 0x0000},
    {
        {0x0A00, 7, 1, 0},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame47 = {
    {0x0100, 0x0000},
    {
        {0x0B00, 7, 1, 0},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame48 = {
    {0x0100, 0x0000},
    {
        {0x0C00, 0, 1, 22},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame49 = {
    {0x0100, 0x0000},
    {
        {0x0C00, 0, 1, 23},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame50 = {
    {0x0100, 0x0000},
    {
        {0x0C00, 0, 1, 24},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame51 = {
    {0x0100, 0x0000},
    {
        {0x0C00, 0, 1, 25},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame52 = {
    {0x0100, 0x0000},
    {
        {0x0C00, 0, 1, 26},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame53 = {
    {0x0100, 0x0000},
    {
        {0x0C00, 0, 1, 27},
    },
};

SaturnSpriteFrame1 AlucardPkg3Frame54 = {
    {0x0100, 0x0000},
    {
        {0x0C00, 0, 1, 28},
    },
};

SaturnSpriteFrameHeader* AlucardPkg3Frames[55] = {
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame0,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame1,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame2,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame3,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame4,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame5,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame6,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame7,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame8,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame9,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame10,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame11,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame12,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame13,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame14,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame15,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame16,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame17,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame18,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame19,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame20,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame21,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame22,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame23,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame24,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame25,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame26,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame27,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame28,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame29,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame30,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame31,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame32,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame33,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame34,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame35,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame36,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame37,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame38,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame39,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame40,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame41,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame42,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame43,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame44,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame45,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame46,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame47,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame48,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame49,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame50,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame51,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame52,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame53,
    (SaturnSpriteFrameHeader*)&AlucardPkg3Frame54,
};
