// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader AlucardPkg4Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 AlucardPkg4Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 0, 0},
    },
};

SaturnSpriteFrame1 AlucardPkg4Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 0, 1},
    },
};

SaturnSpriteFrame6 AlucardPkg4Frame3 = {
    {0x0600, 0x0000},
    {
        {0x0000, 0, -48, 2},
        {0x0000, 0, -32, 3},
        {0x0000, 0, -16, 4},
        {0x0000, 0, 0, 5},
        {0x0000, 0, 16, 6},
        {0x0000, 0, 32, 7},
    },
};

SaturnSpriteFrame6 AlucardPkg4Frame4 = {
    {0x0600, 0x0000},
    {
        {0x0000, 0, -48, 8},
        {0x0000, 0, -32, 9},
        {0x0000, 0, -16, 10},
        {0x0000, 0, 0, 11},
        {0x0000, 0, 16, 12},
        {0x0000, 0, 32, 13},
    },
};

SaturnSpriteFrame2 AlucardPkg4Frame5 = {
    {0x0200, 0x0000},
    {
        {0x0100, -41, -4, 14},
        {0x0100, 43, -4, 15},
    },
};

SaturnSpriteFrame2 AlucardPkg4Frame6 = {
    {0x0200, 0x0000},
    {
        {0x0100, -40, -2, 16},
        {0x0100, 40, -2, 17},
    },
};

SaturnSpriteFrameHeader* AlucardPkg4Frames[7] = {
    (SaturnSpriteFrameHeader*)&AlucardPkg4Frame0,
    (SaturnSpriteFrameHeader*)&AlucardPkg4Frame1,
    (SaturnSpriteFrameHeader*)&AlucardPkg4Frame2,
    (SaturnSpriteFrameHeader*)&AlucardPkg4Frame3,
    (SaturnSpriteFrameHeader*)&AlucardPkg4Frame4,
    (SaturnSpriteFrameHeader*)&AlucardPkg4Frame5,
    (SaturnSpriteFrameHeader*)&AlucardPkg4Frame6,
};
