// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader AlucardFrame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 AlucardFrame1 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 1, 0},
    },
};

SaturnSpriteFrame1 AlucardFrame2 = {
    {0x0100, 0x0001},
    {
        {0x0000, -9, 2, 1},
    },
};

SaturnSpriteFrame1 AlucardFrame3 = {
    {0x0100, 0x0001},
    {
        {0x0000, -5, 5, 2},
    },
};

SaturnSpriteFrame1 AlucardFrame4 = {
    {0x0100, 0x0001},
    {
        {0x0000, -8, 5, 3},
    },
};

SaturnSpriteFrame1 AlucardFrame5 = {
    {0x0100, 0x0001},
    {
        {0x0000, -6, 5, 4},
    },
};

SaturnSpriteFrame1 AlucardFrame6 = {
    {0x0100, 0x0001},
    {
        {0x0000, -8, 6, 5},
    },
};

SaturnSpriteFrame1 AlucardFrame7 = {
    {0x0100, 0x0001},
    {
        {0x0000, -8, 7, 6},
    },
};

SaturnSpriteFrame1 AlucardFrame8 = {
    {0x0100, 0x0001},
    {
        {0x0000, -8, 8, 7},
    },
};

SaturnSpriteFrame1 AlucardFrame9 = {
    {0x0100, 0x0001},
    {
        {0x0000, -7, 9, 8},
    },
};

SaturnSpriteFrame1 AlucardFrame10 = {
    {0x0100, 0x0001},
    {
        {0x0000, -5, 10, 9},
    },
};

SaturnSpriteFrame1 AlucardFrame11 = {
    {0x0100, 0x0001},
    {
        {0x0000, -4, 11, 10},
    },
};

SaturnSpriteFrame1 AlucardFrame12 = {
    {0x0100, 0x0001},
    {
        {0x0000, -3, 12, 11},
    },
};

SaturnSpriteFrame1 AlucardFrame13 = {
    {0x0100, 0x0001},
    {
        {0x0000, -2, 12, 12},
    },
};

SaturnSpriteFrame1 AlucardFrame14 = {
    {0x0100, 0x0001},
    {
        {0x0000, -3, 12, 13},
    },
};

SaturnSpriteFrame1 AlucardFrame15 = {
    {0x0100, 0x0001},
    {
        {0x0000, 2, 12, 14},
    },
};

SaturnSpriteFrame1 AlucardFrame16 = {
    {0x0100, 0x0001},
    {
        {0x0000, 4, 9, 15},
    },
};

SaturnSpriteFrame1 AlucardFrame17 = {
    {0x0100, 0x0001},
    {
        {0x0000, 5, 3, 16},
    },
};

SaturnSpriteFrame1 AlucardFrame18 = {
    {0x0100, 0x0001},
    {
        {0x0000, 4, 2, 17},
    },
};

SaturnSpriteFrame1 AlucardFrame19 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 1, 18},
    },
};

SaturnSpriteFrame1 AlucardFrame20 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 2, 19},
    },
};

SaturnSpriteFrame1 AlucardFrame21 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 2, 20},
    },
};

SaturnSpriteFrame1 AlucardFrame22 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 2, 21},
    },
};

SaturnSpriteFrame1 AlucardFrame23 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 1, 22},
    },
};

SaturnSpriteFrame1 AlucardFrame24 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 1, 23},
    },
};

SaturnSpriteFrame1 AlucardFrame25 = {
    {0x0100, 0x0001},
    {
        {0x0000, 5, 2, 24},
    },
};

SaturnSpriteFrame1 AlucardFrame26 = {
    {0x0100, 0x0001},
    {
        {0x0000, 5, 2, 25},
    },
};

SaturnSpriteFrame1 AlucardFrame27 = {
    {0x0100, 0x0001},
    {
        {0x0000, 5, 2, 26},
    },
};

SaturnSpriteFrame1 AlucardFrame28 = {
    {0x0100, 0x0001},
    {
        {0x0000, 7, 3, 27},
    },
};

SaturnSpriteFrame1 AlucardFrame29 = {
    {0x0100, 0x0001},
    {
        {0x0000, 1, 4, 28},
    },
};

SaturnSpriteFrame1 AlucardFrame30 = {
    {0x0100, 0x0001},
    {
        {0x0000, -3, 3, 29},
    },
};

SaturnSpriteFrame1 AlucardFrame31 = {
    {0x0100, 0x0001},
    {
        {0x0000, -4, 3, 30},
    },
};

SaturnSpriteFrame1 AlucardFrame32 = {
    {0x0100, 0x0001},
    {
        {0x0000, -1, 2, 31},
    },
};

SaturnSpriteFrame1 AlucardFrame33 = {
    {0x0100, 0x0001},
    {
        {0x0000, -3, 2, 32},
    },
};

SaturnSpriteFrame1 AlucardFrame34 = {
    {0x0100, 0x0001},
    {
        {0x0000, 0, 1, 33},
    },
};

SaturnSpriteFrame1 AlucardFrame35 = {
    {0x0100, 0x0001},
    {
        {0x0000, -2, 1, 34},
    },
};

SaturnSpriteFrame1 AlucardFrame36 = {
    {0x0100, 0x0001},
    {
        {0x0000, -4, 1, 35},
    },
};

SaturnSpriteFrame1 AlucardFrame37 = {
    {0x0100, 0x0001},
    {
        {0x0000, -3, 0, 36},
    },
};

SaturnSpriteFrame1 AlucardFrame38 = {
    {0x0100, 0x0001},
    {
        {0x0000, -2, -1, 37},
    },
};

SaturnSpriteFrame1 AlucardFrame39 = {
    {0x0100, 0x0001},
    {
        {0x0000, -1, 0, 38},
    },
};

SaturnSpriteFrame1 AlucardFrame40 = {
    {0x0100, 0x0001},
    {
        {0x0000, -3, 1, 39},
    },
};

SaturnSpriteFrame1 AlucardFrame41 = {
    {0x0100, 0x0001},
    {
        {0x0000, -2, 2, 40},
    },
};

SaturnSpriteFrame1 AlucardFrame42 = {
    {0x0100, 0x0001},
    {
        {0x0000, -3, 2, 41},
    },
};

SaturnSpriteFrame1 AlucardFrame43 = {
    {0x0100, 0x0001},
    {
        {0x0000, -2, 1, 42},
    },
};

SaturnSpriteFrame1 AlucardFrame44 = {
    {0x0100, 0x0001},
    {
        {0x0000, -1, 2, 43},
    },
};

SaturnSpriteFrame1 AlucardFrame45 = {
    {0x0100, 0x0001},
    {
        {0x0000, 1, 2, 44},
    },
};

SaturnSpriteFrame1 AlucardFrame46 = {
    {0x0100, 0x0001},
    {
        {0x0000, 2, 2, 45},
    },
};

SaturnSpriteFrame1 AlucardFrame47 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 2, 46},
    },
};

SaturnSpriteFrame1 AlucardFrame48 = {
    {0x0100, 0x0001},
    {
        {0x0000, 2, 2, 47},
    },
};

SaturnSpriteFrame1 AlucardFrame49 = {
    {0x0100, 0x0001},
    {
        {0x0000, 0, 2, 48},
    },
};

SaturnSpriteFrame1 AlucardFrame50 = {
    {0x0100, 0x0001},
    {
        {0x0000, -4, 2, 49},
    },
};

SaturnSpriteFrame1 AlucardFrame51 = {
    {0x0100, 0x0001},
    {
        {0x0000, -6, 2, 50},
    },
};

SaturnSpriteFrame1 AlucardFrame52 = {
    {0x0100, 0x0001},
    {
        {0x0000, -8, 2, 51},
    },
};

SaturnSpriteFrame1 AlucardFrame53 = {
    {0x0100, 0x0001},
    {
        {0x0000, -6, 2, 52},
    },
};

SaturnSpriteFrame1 AlucardFrame54 = {
    {0x0100, 0x0001},
    {
        {0x0000, -8, 2, 53},
    },
};

SaturnSpriteFrame1 AlucardFrame55 = {
    {0x0100, 0x0001},
    {
        {0x0000, -3, 2, 54},
    },
};

SaturnSpriteFrame1 AlucardFrame56 = {
    {0x0100, 0x0001},
    {
        {0x0000, -5, 2, 55},
    },
};

SaturnSpriteFrame1 AlucardFrame57 = {
    {0x0100, 0x0001},
    {
        {0x0000, 0, 2, 56},
    },
};

SaturnSpriteFrame1 AlucardFrame58 = {
    {0x0100, 0x0001},
    {
        {0x0000, 6, 2, 57},
    },
};

SaturnSpriteFrame1 AlucardFrame59 = {
    {0x0100, 0x0001},
    {
        {0x0000, 2, 2, 58},
    },
};

SaturnSpriteFrame1 AlucardFrame60 = {
    {0x0100, 0x0001},
    {
        {0x0000, 0, 2, 59},
    },
};

SaturnSpriteFrame1 AlucardFrame61 = {
    {0x0100, 0x0001},
    {
        {0x0000, -4, 3, 60},
    },
};

SaturnSpriteFrame1 AlucardFrame62 = {
    {0x0100, 0x0001},
    {
        {0x0000, -1, 3, 61},
    },
};

SaturnSpriteFrame1 AlucardFrame63 = {
    {0x0100, 0x0001},
    {
        {0x0000, -1, 2, 62},
    },
};

SaturnSpriteFrame1 AlucardFrame64 = {
    {0x0100, 0x0001},
    {
        {0x0000, 0, 1, 63},
    },
};

SaturnSpriteFrame1 AlucardFrame65 = {
    {0x0100, 0x0001},
    {
        {0x0000, 5, 1, 64},
    },
};

SaturnSpriteFrame1 AlucardFrame66 = {
    {0x0100, 0x0001},
    {
        {0x0000, 0, 3, 65},
    },
};

SaturnSpriteFrame1 AlucardFrame67 = {
    {0x0100, 0x0001},
    {
        {0x0000, -6, 1, 66},
    },
};

SaturnSpriteFrame1 AlucardFrame68 = {
    {0x0100, 0x0001},
    {
        {0x0000, -3, 0, 67},
    },
};

SaturnSpriteFrame1 AlucardFrame69 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 3, 68},
    },
};

SaturnSpriteFrame1 AlucardFrame70 = {
    {0x0100, 0x0001},
    {
        {0x0000, 7, 5, 69},
    },
};

SaturnSpriteFrame1 AlucardFrame71 = {
    {0x0100, 0x0001},
    {
        {0x0000, 10, 5, 70},
    },
};

SaturnSpriteFrame1 AlucardFrame72 = {
    {0x0100, 0x0001},
    {
        {0x0000, 10, 4, 71},
    },
};

SaturnSpriteFrame1 AlucardFrame73 = {
    {0x0100, 0x0001},
    {
        {0x0000, 9, 4, 72},
    },
};

SaturnSpriteFrame1 AlucardFrame74 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 2, 73},
    },
};

SaturnSpriteFrame1 AlucardFrame75 = {
    {0x0100, 0x0001},
    {
        {0x0000, 1, 2, 74},
    },
};

SaturnSpriteFrame1 AlucardFrame76 = {
    {0x0100, 0x0001},
    {
        {0x0000, -2, 1, 75},
    },
};

SaturnSpriteFrame1 AlucardFrame77 = {
    {0x0100, 0x0001},
    {
        {0x0000, -1, 1, 76},
    },
};

SaturnSpriteFrame1 AlucardFrame78 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 1, 77},
    },
};

SaturnSpriteFrame1 AlucardFrame79 = {
    {0x0100, 0x0001},
    {
        {0x0000, 1, 1, 78},
    },
};

SaturnSpriteFrame1 AlucardFrame80 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 2, 79},
    },
};

SaturnSpriteFrame1 AlucardFrame81 = {
    {0x0100, 0x0001},
    {
        {0x0000, 1, 2, 80},
    },
};

SaturnSpriteFrame1 AlucardFrame82 = {
    {0x0100, 0x0001},
    {
        {0x0000, -2, 1, 81},
    },
};

SaturnSpriteFrame1 AlucardFrame83 = {
    {0x0100, 0x0001},
    {
        {0x0000, -2, 2, 82},
    },
};

SaturnSpriteFrame1 AlucardFrame84 = {
    {0x0100, 0x0001},
    {
        {0x0000, 2, 2, 83},
    },
};

SaturnSpriteFrame1 AlucardFrame85 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 2, 84},
    },
};

SaturnSpriteFrame1 AlucardFrame86 = {
    {0x0100, 0x0001},
    {
        {0x0000, -4, 3, 85},
    },
};

SaturnSpriteFrame1 AlucardFrame87 = {
    {0x0100, 0x0001},
    {
        {0x0000, 2, 3, 86},
    },
};

SaturnSpriteFrame1 AlucardFrame88 = {
    {0x0100, 0x0001},
    {
        {0x0000, -2, 2, 87},
    },
};

SaturnSpriteFrame1 AlucardFrame89 = {
    {0x0100, 0x0001},
    {
        {0x0000, 0, 2, 88},
    },
};

SaturnSpriteFrame1 AlucardFrame90 = {
    {0x0100, 0x0001},
    {
        {0x0000, 4, 1, 89},
    },
};

SaturnSpriteFrame1 AlucardFrame91 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 1, 90},
    },
};

SaturnSpriteFrame1 AlucardFrame92 = {
    {0x0100, 0x0001},
    {
        {0x0000, 4, 1, 91},
    },
};

SaturnSpriteFrame1 AlucardFrame93 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 1, 92},
    },
};

SaturnSpriteFrame1 AlucardFrame94 = {
    {0x0100, 0x0001},
    {
        {0x0000, 5, 1, 93},
    },
};

SaturnSpriteFrame1 AlucardFrame95 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 1, 94},
    },
};

SaturnSpriteFrame1 AlucardFrame96 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 1, 95},
    },
};

SaturnSpriteFrame1 AlucardFrame97 = {
    {0x0100, 0x0001},
    {
        {0x0000, 4, 1, 96},
    },
};

SaturnSpriteFrame1 AlucardFrame98 = {
    {0x0100, 0x0001},
    {
        {0x0000, 7, 1, 97},
    },
};

SaturnSpriteFrame1 AlucardFrame99 = {
    {0x0100, 0x0001},
    {
        {0x0000, 4, 2, 98},
    },
};

SaturnSpriteFrame1 AlucardFrame100 = {
    {0x0100, 0x0001},
    {
        {0x0000, -1, 3, 99},
    },
};

SaturnSpriteFrame1 AlucardFrame101 = {
    {0x0100, 0x0001},
    {
        {0x0000, 1, 3, 100},
    },
};

SaturnSpriteFrame1 AlucardFrame102 = {
    {0x0100, 0x0001},
    {
        {0x0000, 0, 3, 101},
    },
};

SaturnSpriteFrame1 AlucardFrame103 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 1, 102},
    },
};

SaturnSpriteFrame1 AlucardFrame104 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 1, 103},
    },
};

SaturnSpriteFrame1 AlucardFrame105 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 1, 104},
    },
};

SaturnSpriteFrame1 AlucardFrame106 = {
    {0x0100, 0x0001},
    {
        {0x0000, -11, 1, 105},
    },
};

SaturnSpriteFrame1 AlucardFrame107 = {
    {0x0100, 0x0001},
    {
        {0x0000, -7, 0, 106},
    },
};

SaturnSpriteFrame1 AlucardFrame108 = {
    {0x0100, 0x0001},
    {
        {0x0000, -8, -1, 107},
    },
};

SaturnSpriteFrame1 AlucardFrame109 = {
    {0x0100, 0x0001},
    {
        {0x0000, -8, -1, 108},
    },
};

SaturnSpriteFrame1 AlucardFrame110 = {
    {0x0100, 0x0001},
    {
        {0x0000, -5, -2, 109},
    },
};

SaturnSpriteFrame1 AlucardFrame111 = {
    {0x0100, 0x0001},
    {
        {0x0000, -5, -4, 110},
    },
};

SaturnSpriteFrame1 AlucardFrame112 = {
    {0x0100, 0x0001},
    {
        {0x0000, -8, -4, 111},
    },
};

SaturnSpriteFrame1 AlucardFrame113 = {
    {0x0100, 0x0001},
    {
        {0x0000, -12, -5, 112},
    },
};

SaturnSpriteFrame1 AlucardFrame114 = {
    {0x0100, 0x0001},
    {
        {0x0000, -12, -6, 113},
    },
};

SaturnSpriteFrame1 AlucardFrame115 = {
    {0x0100, 0x0001},
    {
        {0x0000, -9, -5, 114},
    },
};

SaturnSpriteFrame1 AlucardFrame116 = {
    {0x0100, 0x0001},
    {
        {0x0000, -5, 1, 115},
    },
};

SaturnSpriteFrame1 AlucardFrame117 = {
    {0x0100, 0x0001},
    {
        {0x0000, -10, 2, 116},
    },
};

SaturnSpriteFrame1 AlucardFrame118 = {
    {0x0100, 0x0001},
    {
        {0x0000, -9, 2, 117},
    },
};

SaturnSpriteFrame1 AlucardFrame119 = {
    {0x0100, 0x0001},
    {
        {0x0000, -9, 3, 118},
    },
};

SaturnSpriteFrame1 AlucardFrame120 = {
    {0x0100, 0x0001},
    {
        {0x0000, -3, 2, 119},
    },
};

SaturnSpriteFrame1 AlucardFrame121 = {
    {0x0100, 0x0001},
    {
        {0x0000, 4, 1, 120},
    },
};

SaturnSpriteFrame1 AlucardFrame122 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 2, 121},
    },
};

SaturnSpriteFrame1 AlucardFrame123 = {
    {0x0100, 0x0001},
    {
        {0x0000, 4, 2, 122},
    },
};

SaturnSpriteFrame1 AlucardFrame124 = {
    {0x0100, 0x0001},
    {
        {0x0000, 6, 2, 123},
    },
};

SaturnSpriteFrame1 AlucardFrame125 = {
    {0x0100, 0x0001},
    {
        {0x0000, 10, 2, 124},
    },
};

SaturnSpriteFrame1 AlucardFrame126 = {
    {0x0100, 0x0001},
    {
        {0x0000, 14, 2, 125},
    },
};

SaturnSpriteFrame1 AlucardFrame127 = {
    {0x0100, 0x0001},
    {
        {0x0000, 18, 2, 126},
    },
};

SaturnSpriteFrame1 AlucardFrame128 = {
    {0x0100, 0x0001},
    {
        {0x0000, 5, 2, 127},
    },
};

SaturnSpriteFrame1 AlucardFrame129 = {
    {0x0100, 0x0001},
    {
        {0x0000, 1, 11, 128},
    },
};

SaturnSpriteFrame1 AlucardFrame130 = {
    {0x0100, 0x0001},
    {
        {0x0000, 2, 11, 129},
    },
};

SaturnSpriteFrame1 AlucardFrame131 = {
    {0x0100, 0x0001},
    {
        {0x0000, 7, 11, 130},
    },
};

SaturnSpriteFrame1 AlucardFrame132 = {
    {0x0100, 0x0001},
    {
        {0x0000, 11, 11, 131},
    },
};

SaturnSpriteFrame1 AlucardFrame133 = {
    {0x0100, 0x0001},
    {
        {0x0000, 1, 3, 132},
    },
};

SaturnSpriteFrame1 AlucardFrame134 = {
    {0x0100, 0x0001},
    {
        {0x0000, 0, 4, 133},
    },
};

SaturnSpriteFrame1 AlucardFrame135 = {
    {0x0100, 0x0001},
    {
        {0x0000, 8, 2, 134},
    },
};

SaturnSpriteFrame1 AlucardFrame136 = {
    {0x0100, 0x0001},
    {
        {0x0000, -8, -5, 135},
    },
};

SaturnSpriteFrame1 AlucardFrame137 = {
    {0x0100, 0x0001},
    {
        {0x0000, 5, -9, 136},
    },
};

SaturnSpriteFrame1 AlucardFrame138 = {
    {0x0100, 0x0001},
    {
        {0x0000, 7, -9, 137},
    },
};

SaturnSpriteFrame1 AlucardFrame139 = {
    {0x0100, 0x0001},
    {
        {0x0000, -3, -6, 138},
    },
};

SaturnSpriteFrame1 AlucardFrame140 = {
    {0x0100, 0x0001},
    {
        {0x0000, 14, -6, 139},
    },
};

SaturnSpriteFrame1 AlucardFrame141 = {
    {0x0100, 0x0001},
    {
        {0x0000, 15, -6, 140},
    },
};

SaturnSpriteFrame1 AlucardFrame142 = {
    {0x0100, 0x0001},
    {
        {0x0000, 7, 1, 141},
    },
};

SaturnSpriteFrame1 AlucardFrame143 = {
    {0x0100, 0x0001},
    {
        {0x0000, 7, 1, 142},
    },
};

SaturnSpriteFrame1 AlucardFrame144 = {
    {0x0100, 0x0001},
    {
        {0x0000, 7, 1, 143},
    },
};

SaturnSpriteFrame1 AlucardFrame145 = {
    {0x0100, 0x0001},
    {
        {0x0000, 7, 1, 144},
    },
};

SaturnSpriteFrame1 AlucardFrame146 = {
    {0x0100, 0x0001},
    {
        {0x0000, 6, 1, 145},
    },
};

SaturnSpriteFrame1 AlucardFrame147 = {
    {0x0100, 0x0001},
    {
        {0x0000, 2, 1, 146},
    },
};

SaturnSpriteFrame1 AlucardFrame148 = {
    {0x0100, 0x0001},
    {
        {0x0000, 1, 1, 147},
    },
};

SaturnSpriteFrame1 AlucardFrame149 = {
    {0x0100, 0x0001},
    {
        {0x0000, 1, 1, 148},
    },
};

SaturnSpriteFrame1 AlucardFrame150 = {
    {0x0100, 0x0001},
    {
        {0x0000, 1, 1, 149},
    },
};

SaturnSpriteFrame1 AlucardFrame151 = {
    {0x0100, 0x0001},
    {
        {0x0000, -4, 1, 150},
    },
};

SaturnSpriteFrame1 AlucardFrame152 = {
    {0x0100, 0x0001},
    {
        {0x0000, 8, -22, 151},
    },
};

SaturnSpriteFrame1 AlucardFrame153 = {
    {0x0100, 0x0001},
    {
        {0x0000, 4, -2, 152},
    },
};

SaturnSpriteFrame1 AlucardFrame154 = {
    {0x0100, 0x0001},
    {
        {0x0000, 1, 1, 153},
    },
};

SaturnSpriteFrame1 AlucardFrame155 = {
    {0x0100, 0x0001},
    {
        {0x0000, 1, 1, 154},
    },
};

SaturnSpriteFrame1 AlucardFrame156 = {
    {0x0100, 0x0001},
    {
        {0x0000, 4, -2, 155},
    },
};

SaturnSpriteFrame1 AlucardFrame157 = {
    {0x0100, 0x0001},
    {
        {0x0000, 5, 1, 156},
    },
};

SaturnSpriteFrame1 AlucardFrame158 = {
    {0x0100, 0x0001},
    {
        {0x0000, -2, -2, 157},
    },
};

SaturnSpriteFrame1 AlucardFrame159 = {
    {0x0100, 0x0001},
    {
        {0x0000, 7, 2, 158},
    },
};

SaturnSpriteFrame1 AlucardFrame160 = {
    {0x0100, 0x0001},
    {
        {0x0000, 7, 1, 158},
    },
};

SaturnSpriteFrame1 AlucardFrame161 = {
    {0x0100, 0x0001},
    {
        {0x0000, 9, 3, 159},
    },
};

SaturnSpriteFrame1 AlucardFrame162 = {
    {0x0100, 0x0001},
    {
        {0x0000, 10, 2, 160},
    },
};

SaturnSpriteFrame1 AlucardFrame163 = {
    {0x0100, 0x0001},
    {
        {0x0000, 9, 1, 161},
    },
};

SaturnSpriteFrame1 AlucardFrame164 = {
    {0x0100, 0x0001},
    {
        {0x0000, 9, 0, 161},
    },
};

SaturnSpriteFrame1 AlucardFrame165 = {
    {0x0100, 0x0001},
    {
        {0x0000, 11, 2, 162},
    },
};

SaturnSpriteFrame1 AlucardFrame166 = {
    {0x0100, 0x0001},
    {
        {0x0000, 10, 2, 162},
    },
};

SaturnSpriteFrame1 AlucardFrame167 = {
    {0x0100, 0x0001},
    {
        {0x0000, 10, 1, 163},
    },
};

SaturnSpriteFrame1 AlucardFrame168 = {
    {0x0100, 0x0001},
    {
        {0x0000, 9, 1, 163},
    },
};

SaturnSpriteFrame1 AlucardFrame169 = {
    {0x0100, 0x0001},
    {
        {0x0000, 7, 4, 164},
    },
};

SaturnSpriteFrame1 AlucardFrame170 = {
    {0x0100, 0x0001},
    {
        {0x0000, 8, 4, 165},
    },
};

SaturnSpriteFrame1 AlucardFrame171 = {
    {0x0100, 0x0001},
    {
        {0x0000, -5, 2, 166},
    },
};

SaturnSpriteFrame1 AlucardFrame172 = {
    {0x0100, 0x0001},
    {
        {0x0000, -4, 2, 167},
    },
};

SaturnSpriteFrame1 AlucardFrame173 = {
    {0x0100, 0x0001},
    {
        {0x0100, 9, 3, 168},
    },
};

SaturnSpriteFrame1 AlucardFrame174 = {
    {0x0100, 0x0001},
    {
        {0x0100, 6, 2, 169},
    },
};

SaturnSpriteFrame2 AlucardFrame175 = {
    {0x0200, 0x0001},
    {
        {0x0100, -41, -8, 170},
        {0x0100, 28, -9, 171},
    },
};

SaturnSpriteFrame1 AlucardFrame176 = {
    {0x0100, 0x0001},
    {
        {0x0000, -4, -3, 172},
    },
};

SaturnSpriteFrame1 AlucardFrame177 = {
    {0x0100, 0x0001},
    {
        {0x0000, -6, -4, 173},
    },
};

SaturnSpriteFrame1 AlucardFrame178 = {
    {0x0100, 0x0001},
    {
        {0x0000, -8, -6, 174},
    },
};

SaturnSpriteFrame1 AlucardFrame179 = {
    {0x0100, 0x0001},
    {
        {0x0000, -11, -5, 175},
    },
};

SaturnSpriteFrame1 AlucardFrame180 = {
    {0x0100, 0x0001},
    {
        {0x0000, 13, 2, 176},
    },
};

SaturnSpriteFrame1 AlucardFrame181 = {
    {0x0100, 0x0001},
    {
        {0x0000, 13, 2, 177},
    },
};

SaturnSpriteFrame1 AlucardFrame182 = {
    {0x0100, 0x0001},
    {
        {0x0000, 8, 0, 178},
    },
};

SaturnSpriteFrame1 AlucardFrame183 = {
    {0x0100, 0x0001},
    {
        {0x0000, 12, 2, 179},
    },
};

SaturnSpriteFrame1 AlucardFrame184 = {
    {0x0100, 0x0001},
    {
        {0x0000, 11, 1, 180},
    },
};

SaturnSpriteFrame1 AlucardFrame185 = {
    {0x0100, 0x0001},
    {
        {0x0000, -1, 2, 181},
    },
};

SaturnSpriteFrame1 AlucardFrame186 = {
    {0x0100, 0x0001},
    {
        {0x0000, 2, 2, 182},
    },
};

SaturnSpriteFrame1 AlucardFrame187 = {
    {0x0100, 0x0001},
    {
        {0x0000, 0, 1, 183},
    },
};

SaturnSpriteFrame1 AlucardFrame188 = {
    {0x0100, 0x0001},
    {
        {0x0000, 4, 0, 184},
    },
};

SaturnSpriteFrame1 AlucardFrame189 = {
    {0x0100, 0x0001},
    {
        {0x0000, 6, 1, 185},
    },
};

SaturnSpriteFrame1 AlucardFrame190 = {
    {0x0100, 0x0001},
    {
        {0x0000, 7, 3, 186},
    },
};

SaturnSpriteFrame1 AlucardFrame191 = {
    {0x0100, 0x0001},
    {
        {0x0000, 8, 3, 187},
    },
};

SaturnSpriteFrame1 AlucardFrame192 = {
    {0x0100, 0x0001},
    {
        {0x0000, 8, 3, 188},
    },
};

SaturnSpriteFrame1 AlucardFrame193 = {
    {0x0100, 0x0001},
    {
        {0x0000, 7, 2, 189},
    },
};

SaturnSpriteFrame1 AlucardFrame194 = {
    {0x0100, 0x0001},
    {
        {0x0000, 7, 2, 190},
    },
};

SaturnSpriteFrame1 AlucardFrame195 = {
    {0x0100, 0x0001},
    {
        {0x0000, 4, 1, 191},
    },
};

SaturnSpriteFrame1 AlucardFrame196 = {
    {0x0100, 0x0001},
    {
        {0x0000, -1, 10, 192},
    },
};

SaturnSpriteFrame1 AlucardFrame197 = {
    {0x0100, 0x0001},
    {
        {0x0000, -1, 11, 193},
    },
};

SaturnSpriteFrame1 AlucardFrame198 = {
    {0x0100, 0x0001},
    {
        {0x0000, -5, 11, 194},
    },
};

SaturnSpriteFrame1 AlucardFrame199 = {
    {0x0100, 0x0001},
    {
        {0x0000, -6, 10, 195},
    },
};

SaturnSpriteFrame1 AlucardFrame200 = {
    {0x0100, 0x0001},
    {
        {0x0000, -3, 8, 196},
    },
};

SaturnSpriteFrame1 AlucardFrame201 = {
    {0x0100, 0x0001},
    {
        {0x0000, -5, 9, 197},
    },
};

SaturnSpriteFrame1 AlucardFrame202 = {
    {0x0100, 0x0001},
    {
        {0x0000, 0, 11, 198},
    },
};

SaturnSpriteFrame1 AlucardFrame203 = {
    {0x0100, 0x0001},
    {
        {0x0000, -2, 11, 199},
    },
};

SaturnSpriteFrame1 AlucardFrame204 = {
    {0x0100, 0x0001},
    {
        {0x0000, -2, 11, 200},
    },
};

SaturnSpriteFrame1 AlucardFrame205 = {
    {0x0100, 0x0001},
    {
        {0x0000, -2, 11, 201},
    },
};

SaturnSpriteFrame1 AlucardFrame206 = {
    {0x0100, 0x0001},
    {
        {0x0000, -2, 11, 202},
    },
};

SaturnSpriteFrame1 AlucardFrame207 = {
    {0x0100, 0x0001},
    {
        {0x0000, -3, 11, 203},
    },
};

SaturnSpriteFrame1 AlucardFrame208 = {
    {0x0100, 0x0001},
    {
        {0x0000, 2, 0, 204},
    },
};

SaturnSpriteFrame1 AlucardFrame209 = {
    {0x0100, 0x0001},
    {
        {0x0000, 0, 0, 205},
    },
};

SaturnSpriteFrame1 AlucardFrame210 = {
    {0x0100, 0x0001},
    {
        {0x0000, -4, 2, 206},
    },
};

SaturnSpriteFrame1 AlucardFrame211 = {
    {0x0100, 0x0001},
    {
        {0x0000, -4, 2, 207},
    },
};

SaturnSpriteFrame1 AlucardFrame212 = {
    {0x0100, 0x0001},
    {
        {0x0000, -12, -5, 208},
    },
};

SaturnSpriteFrame1 AlucardFrame213 = {
    {0x0100, 0x0001},
    {
        {0x0000, 2, -7, 209},
    },
};

SaturnSpriteFrame1 AlucardFrame214 = {
    {0x0100, 0x0001},
    {
        {0x0000, 2, -7, 210},
    },
};

SaturnSpriteFrame1 AlucardFrame215 = {
    {0x0100, 0x0001},
    {
        {0x0000, -4, -8, 211},
    },
};

SaturnSpriteFrame1 AlucardFrame216 = {
    {0x0100, 0x0001},
    {
        {0x0000, -2, -8, 212},
    },
};

SaturnSpriteFrame1 AlucardFrame217 = {
    {0x0100, 0x0001},
    {
        {0x0000, 1, 6, 213},
    },
};

SaturnSpriteFrame1 AlucardFrame218 = {
    {0x0100, 0x0001},
    {
        {0x0000, -2, 3, 214},
    },
};

SaturnSpriteFrame1 AlucardFrame219 = {
    {0x0100, 0x0001},
    {
        {0x0000, -1, 3, 215},
    },
};

SaturnSpriteFrame1 AlucardFrame220 = {
    {0x0100, 0x0001},
    {
        {0x0000, 4, 4, 216},
    },
};

SaturnSpriteFrame1 AlucardFrame221 = {
    {0x0100, 0x0001},
    {
        {0x0000, -1, 5, 217},
    },
};

SaturnSpriteFrame1 AlucardFrame222 = {
    {0x0100, 0x0001},
    {
        {0x0000, 2, 5, 218},
    },
};

SaturnSpriteFrame1 AlucardFrame223 = {
    {0x0100, 0x0001},
    {
        {0x0000, 4, 5, 219},
    },
};

SaturnSpriteFrame1 AlucardFrame224 = {
    {0x0100, 0x0001},
    {
        {0x0000, 3, 2, 220},
    },
};

SaturnSpriteFrameHeader* AlucardFrames[225] = {
    (SaturnSpriteFrameHeader*)&AlucardFrame0,
    (SaturnSpriteFrameHeader*)&AlucardFrame1,
    (SaturnSpriteFrameHeader*)&AlucardFrame2,
    (SaturnSpriteFrameHeader*)&AlucardFrame3,
    (SaturnSpriteFrameHeader*)&AlucardFrame4,
    (SaturnSpriteFrameHeader*)&AlucardFrame5,
    (SaturnSpriteFrameHeader*)&AlucardFrame6,
    (SaturnSpriteFrameHeader*)&AlucardFrame7,
    (SaturnSpriteFrameHeader*)&AlucardFrame8,
    (SaturnSpriteFrameHeader*)&AlucardFrame9,
    (SaturnSpriteFrameHeader*)&AlucardFrame10,
    (SaturnSpriteFrameHeader*)&AlucardFrame11,
    (SaturnSpriteFrameHeader*)&AlucardFrame12,
    (SaturnSpriteFrameHeader*)&AlucardFrame13,
    (SaturnSpriteFrameHeader*)&AlucardFrame14,
    (SaturnSpriteFrameHeader*)&AlucardFrame15,
    (SaturnSpriteFrameHeader*)&AlucardFrame16,
    (SaturnSpriteFrameHeader*)&AlucardFrame17,
    (SaturnSpriteFrameHeader*)&AlucardFrame18,
    (SaturnSpriteFrameHeader*)&AlucardFrame19,
    (SaturnSpriteFrameHeader*)&AlucardFrame20,
    (SaturnSpriteFrameHeader*)&AlucardFrame21,
    (SaturnSpriteFrameHeader*)&AlucardFrame22,
    (SaturnSpriteFrameHeader*)&AlucardFrame23,
    (SaturnSpriteFrameHeader*)&AlucardFrame24,
    (SaturnSpriteFrameHeader*)&AlucardFrame25,
    (SaturnSpriteFrameHeader*)&AlucardFrame26,
    (SaturnSpriteFrameHeader*)&AlucardFrame27,
    (SaturnSpriteFrameHeader*)&AlucardFrame28,
    (SaturnSpriteFrameHeader*)&AlucardFrame29,
    (SaturnSpriteFrameHeader*)&AlucardFrame30,
    (SaturnSpriteFrameHeader*)&AlucardFrame31,
    (SaturnSpriteFrameHeader*)&AlucardFrame32,
    (SaturnSpriteFrameHeader*)&AlucardFrame33,
    (SaturnSpriteFrameHeader*)&AlucardFrame34,
    (SaturnSpriteFrameHeader*)&AlucardFrame35,
    (SaturnSpriteFrameHeader*)&AlucardFrame36,
    (SaturnSpriteFrameHeader*)&AlucardFrame37,
    (SaturnSpriteFrameHeader*)&AlucardFrame38,
    (SaturnSpriteFrameHeader*)&AlucardFrame39,
    (SaturnSpriteFrameHeader*)&AlucardFrame40,
    (SaturnSpriteFrameHeader*)&AlucardFrame41,
    (SaturnSpriteFrameHeader*)&AlucardFrame42,
    (SaturnSpriteFrameHeader*)&AlucardFrame43,
    (SaturnSpriteFrameHeader*)&AlucardFrame44,
    (SaturnSpriteFrameHeader*)&AlucardFrame45,
    (SaturnSpriteFrameHeader*)&AlucardFrame46,
    (SaturnSpriteFrameHeader*)&AlucardFrame47,
    (SaturnSpriteFrameHeader*)&AlucardFrame48,
    (SaturnSpriteFrameHeader*)&AlucardFrame49,
    (SaturnSpriteFrameHeader*)&AlucardFrame50,
    (SaturnSpriteFrameHeader*)&AlucardFrame51,
    (SaturnSpriteFrameHeader*)&AlucardFrame52,
    (SaturnSpriteFrameHeader*)&AlucardFrame53,
    (SaturnSpriteFrameHeader*)&AlucardFrame54,
    (SaturnSpriteFrameHeader*)&AlucardFrame55,
    (SaturnSpriteFrameHeader*)&AlucardFrame56,
    (SaturnSpriteFrameHeader*)&AlucardFrame57,
    (SaturnSpriteFrameHeader*)&AlucardFrame58,
    (SaturnSpriteFrameHeader*)&AlucardFrame59,
    (SaturnSpriteFrameHeader*)&AlucardFrame60,
    (SaturnSpriteFrameHeader*)&AlucardFrame61,
    (SaturnSpriteFrameHeader*)&AlucardFrame62,
    (SaturnSpriteFrameHeader*)&AlucardFrame63,
    (SaturnSpriteFrameHeader*)&AlucardFrame64,
    (SaturnSpriteFrameHeader*)&AlucardFrame65,
    (SaturnSpriteFrameHeader*)&AlucardFrame66,
    (SaturnSpriteFrameHeader*)&AlucardFrame67,
    (SaturnSpriteFrameHeader*)&AlucardFrame68,
    (SaturnSpriteFrameHeader*)&AlucardFrame69,
    (SaturnSpriteFrameHeader*)&AlucardFrame70,
    (SaturnSpriteFrameHeader*)&AlucardFrame71,
    (SaturnSpriteFrameHeader*)&AlucardFrame72,
    (SaturnSpriteFrameHeader*)&AlucardFrame73,
    (SaturnSpriteFrameHeader*)&AlucardFrame74,
    (SaturnSpriteFrameHeader*)&AlucardFrame75,
    (SaturnSpriteFrameHeader*)&AlucardFrame76,
    (SaturnSpriteFrameHeader*)&AlucardFrame77,
    (SaturnSpriteFrameHeader*)&AlucardFrame78,
    (SaturnSpriteFrameHeader*)&AlucardFrame79,
    (SaturnSpriteFrameHeader*)&AlucardFrame80,
    (SaturnSpriteFrameHeader*)&AlucardFrame81,
    (SaturnSpriteFrameHeader*)&AlucardFrame82,
    (SaturnSpriteFrameHeader*)&AlucardFrame83,
    (SaturnSpriteFrameHeader*)&AlucardFrame84,
    (SaturnSpriteFrameHeader*)&AlucardFrame85,
    (SaturnSpriteFrameHeader*)&AlucardFrame86,
    (SaturnSpriteFrameHeader*)&AlucardFrame87,
    (SaturnSpriteFrameHeader*)&AlucardFrame88,
    (SaturnSpriteFrameHeader*)&AlucardFrame89,
    (SaturnSpriteFrameHeader*)&AlucardFrame90,
    (SaturnSpriteFrameHeader*)&AlucardFrame91,
    (SaturnSpriteFrameHeader*)&AlucardFrame92,
    (SaturnSpriteFrameHeader*)&AlucardFrame93,
    (SaturnSpriteFrameHeader*)&AlucardFrame94,
    (SaturnSpriteFrameHeader*)&AlucardFrame95,
    (SaturnSpriteFrameHeader*)&AlucardFrame96,
    (SaturnSpriteFrameHeader*)&AlucardFrame97,
    (SaturnSpriteFrameHeader*)&AlucardFrame98,
    (SaturnSpriteFrameHeader*)&AlucardFrame99,
    (SaturnSpriteFrameHeader*)&AlucardFrame100,
    (SaturnSpriteFrameHeader*)&AlucardFrame101,
    (SaturnSpriteFrameHeader*)&AlucardFrame102,
    (SaturnSpriteFrameHeader*)&AlucardFrame103,
    (SaturnSpriteFrameHeader*)&AlucardFrame104,
    (SaturnSpriteFrameHeader*)&AlucardFrame105,
    (SaturnSpriteFrameHeader*)&AlucardFrame106,
    (SaturnSpriteFrameHeader*)&AlucardFrame107,
    (SaturnSpriteFrameHeader*)&AlucardFrame108,
    (SaturnSpriteFrameHeader*)&AlucardFrame109,
    (SaturnSpriteFrameHeader*)&AlucardFrame110,
    (SaturnSpriteFrameHeader*)&AlucardFrame111,
    (SaturnSpriteFrameHeader*)&AlucardFrame112,
    (SaturnSpriteFrameHeader*)&AlucardFrame113,
    (SaturnSpriteFrameHeader*)&AlucardFrame114,
    (SaturnSpriteFrameHeader*)&AlucardFrame115,
    (SaturnSpriteFrameHeader*)&AlucardFrame116,
    (SaturnSpriteFrameHeader*)&AlucardFrame117,
    (SaturnSpriteFrameHeader*)&AlucardFrame118,
    (SaturnSpriteFrameHeader*)&AlucardFrame119,
    (SaturnSpriteFrameHeader*)&AlucardFrame120,
    (SaturnSpriteFrameHeader*)&AlucardFrame121,
    (SaturnSpriteFrameHeader*)&AlucardFrame122,
    (SaturnSpriteFrameHeader*)&AlucardFrame123,
    (SaturnSpriteFrameHeader*)&AlucardFrame124,
    (SaturnSpriteFrameHeader*)&AlucardFrame125,
    (SaturnSpriteFrameHeader*)&AlucardFrame126,
    (SaturnSpriteFrameHeader*)&AlucardFrame127,
    (SaturnSpriteFrameHeader*)&AlucardFrame128,
    (SaturnSpriteFrameHeader*)&AlucardFrame129,
    (SaturnSpriteFrameHeader*)&AlucardFrame130,
    (SaturnSpriteFrameHeader*)&AlucardFrame131,
    (SaturnSpriteFrameHeader*)&AlucardFrame132,
    (SaturnSpriteFrameHeader*)&AlucardFrame133,
    (SaturnSpriteFrameHeader*)&AlucardFrame134,
    (SaturnSpriteFrameHeader*)&AlucardFrame135,
    (SaturnSpriteFrameHeader*)&AlucardFrame136,
    (SaturnSpriteFrameHeader*)&AlucardFrame137,
    (SaturnSpriteFrameHeader*)&AlucardFrame138,
    (SaturnSpriteFrameHeader*)&AlucardFrame139,
    (SaturnSpriteFrameHeader*)&AlucardFrame140,
    (SaturnSpriteFrameHeader*)&AlucardFrame141,
    (SaturnSpriteFrameHeader*)&AlucardFrame142,
    (SaturnSpriteFrameHeader*)&AlucardFrame143,
    (SaturnSpriteFrameHeader*)&AlucardFrame144,
    (SaturnSpriteFrameHeader*)&AlucardFrame145,
    (SaturnSpriteFrameHeader*)&AlucardFrame146,
    (SaturnSpriteFrameHeader*)&AlucardFrame147,
    (SaturnSpriteFrameHeader*)&AlucardFrame148,
    (SaturnSpriteFrameHeader*)&AlucardFrame149,
    (SaturnSpriteFrameHeader*)&AlucardFrame150,
    (SaturnSpriteFrameHeader*)&AlucardFrame151,
    (SaturnSpriteFrameHeader*)&AlucardFrame152,
    (SaturnSpriteFrameHeader*)&AlucardFrame153,
    (SaturnSpriteFrameHeader*)&AlucardFrame154,
    (SaturnSpriteFrameHeader*)&AlucardFrame155,
    (SaturnSpriteFrameHeader*)&AlucardFrame156,
    (SaturnSpriteFrameHeader*)&AlucardFrame157,
    (SaturnSpriteFrameHeader*)&AlucardFrame158,
    (SaturnSpriteFrameHeader*)&AlucardFrame159,
    (SaturnSpriteFrameHeader*)&AlucardFrame160,
    (SaturnSpriteFrameHeader*)&AlucardFrame161,
    (SaturnSpriteFrameHeader*)&AlucardFrame162,
    (SaturnSpriteFrameHeader*)&AlucardFrame163,
    (SaturnSpriteFrameHeader*)&AlucardFrame164,
    (SaturnSpriteFrameHeader*)&AlucardFrame165,
    (SaturnSpriteFrameHeader*)&AlucardFrame166,
    (SaturnSpriteFrameHeader*)&AlucardFrame167,
    (SaturnSpriteFrameHeader*)&AlucardFrame168,
    (SaturnSpriteFrameHeader*)&AlucardFrame169,
    (SaturnSpriteFrameHeader*)&AlucardFrame170,
    (SaturnSpriteFrameHeader*)&AlucardFrame171,
    (SaturnSpriteFrameHeader*)&AlucardFrame172,
    (SaturnSpriteFrameHeader*)&AlucardFrame173,
    (SaturnSpriteFrameHeader*)&AlucardFrame174,
    (SaturnSpriteFrameHeader*)&AlucardFrame175,
    (SaturnSpriteFrameHeader*)&AlucardFrame176,
    (SaturnSpriteFrameHeader*)&AlucardFrame177,
    (SaturnSpriteFrameHeader*)&AlucardFrame178,
    (SaturnSpriteFrameHeader*)&AlucardFrame179,
    (SaturnSpriteFrameHeader*)&AlucardFrame180,
    (SaturnSpriteFrameHeader*)&AlucardFrame181,
    (SaturnSpriteFrameHeader*)&AlucardFrame182,
    (SaturnSpriteFrameHeader*)&AlucardFrame183,
    (SaturnSpriteFrameHeader*)&AlucardFrame184,
    (SaturnSpriteFrameHeader*)&AlucardFrame185,
    (SaturnSpriteFrameHeader*)&AlucardFrame186,
    (SaturnSpriteFrameHeader*)&AlucardFrame187,
    (SaturnSpriteFrameHeader*)&AlucardFrame188,
    (SaturnSpriteFrameHeader*)&AlucardFrame189,
    (SaturnSpriteFrameHeader*)&AlucardFrame190,
    (SaturnSpriteFrameHeader*)&AlucardFrame191,
    (SaturnSpriteFrameHeader*)&AlucardFrame192,
    (SaturnSpriteFrameHeader*)&AlucardFrame193,
    (SaturnSpriteFrameHeader*)&AlucardFrame194,
    (SaturnSpriteFrameHeader*)&AlucardFrame195,
    (SaturnSpriteFrameHeader*)&AlucardFrame196,
    (SaturnSpriteFrameHeader*)&AlucardFrame197,
    (SaturnSpriteFrameHeader*)&AlucardFrame198,
    (SaturnSpriteFrameHeader*)&AlucardFrame199,
    (SaturnSpriteFrameHeader*)&AlucardFrame200,
    (SaturnSpriteFrameHeader*)&AlucardFrame201,
    (SaturnSpriteFrameHeader*)&AlucardFrame202,
    (SaturnSpriteFrameHeader*)&AlucardFrame203,
    (SaturnSpriteFrameHeader*)&AlucardFrame204,
    (SaturnSpriteFrameHeader*)&AlucardFrame205,
    (SaturnSpriteFrameHeader*)&AlucardFrame206,
    (SaturnSpriteFrameHeader*)&AlucardFrame207,
    (SaturnSpriteFrameHeader*)&AlucardFrame208,
    (SaturnSpriteFrameHeader*)&AlucardFrame209,
    (SaturnSpriteFrameHeader*)&AlucardFrame210,
    (SaturnSpriteFrameHeader*)&AlucardFrame211,
    (SaturnSpriteFrameHeader*)&AlucardFrame212,
    (SaturnSpriteFrameHeader*)&AlucardFrame213,
    (SaturnSpriteFrameHeader*)&AlucardFrame214,
    (SaturnSpriteFrameHeader*)&AlucardFrame215,
    (SaturnSpriteFrameHeader*)&AlucardFrame216,
    (SaturnSpriteFrameHeader*)&AlucardFrame217,
    (SaturnSpriteFrameHeader*)&AlucardFrame218,
    (SaturnSpriteFrameHeader*)&AlucardFrame219,
    (SaturnSpriteFrameHeader*)&AlucardFrame220,
    (SaturnSpriteFrameHeader*)&AlucardFrame221,
    (SaturnSpriteFrameHeader*)&AlucardFrame222,
    (SaturnSpriteFrameHeader*)&AlucardFrame223,
    (SaturnSpriteFrameHeader*)&AlucardFrame224,
};
