// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader AlucardPkg8Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 AlucardPkg8Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 24, 32, 0},
    },
};

SaturnSpriteFrameHeader* AlucardPkg8Frames[2] = {
    (SaturnSpriteFrameHeader*)&AlucardPkg8Frame0,
    (SaturnSpriteFrameHeader*)&AlucardPkg8Frame1,
};
