// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[1][15];
} AlucardFxPalette = {
    0x0001,
    {
        {
            0xC0A8,
            0x8421,
            0x84AB,
            0x8D2F,
            0x91D6,
            0x929B,
            0x994A,
            0xA5CE,
            0x8421,
            0x9CE7,
            0xFFE0,
            0x98A5,
            0xA94A,
            0xBE2E,
            0xC2F7,
        },
    },
};
