// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[1][16];
    u16 padding[1];
} AlucardPkg7Palette = {
    0x0001,
    {
        {
            0x9121,
            0x90C7,
            0x94E8,
            0x9909,
            0x9D4B,
            0xA16C,
            0xA5AE,
            0xA9CF,
            0xB211,
            0xB632,
            0xBA53,
            0xBE95,
            0xC2B6,
            0xC6F8,
            0xCB19,
            0xD35B,
        },
    },
    {0x0000},
};

SaturnSpriteImage AlucardPkg7Images[3] = {
    {20, 47, 0x0000},
    {20, 15, 0x00EC},
    {0, 0, 0x0138},
};
