// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[3][16];
} AlucardSubPalette = {
    0x0003,
    {
        {
            0x8000,
            0x8421,
            0xA465,
            0xBC88,
            0xC8EC,
            0xE5CF,
            0x9DB5,
            0xBEBD,
            0xFF9A,
            0x8888,
            0x98F0,
            0x800D,
            0xFF35,
            0x8019,
            0xA17F,
            0x801F,
        },
        {
            0x8000,
            0x8000,
            0x9802,
            0x9423,
            0xA866,
            0xB908,
            0x90EC,
            0xA990,
            0xA9F6,
            0x8023,
            0x8049,
            0x81E1,
            0xD1A9,
            0x81C0,
            0x8360,
            0x801F,
        },
        {
            0x8000,
            0x8001,
            0x8008,
            0x800E,
            0x8015,
            0x801A,
            0x801F,
            0x8D3F,
            0x95DF,
            0x9E5F,
            0xA6BF,
            0xAF1F,
            0xAB7F,
            0xB7DF,
            0xD7FF,
            0xFFFF,
        },
    },
};

SaturnSpriteFrameHeader AlucardSubFrame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 AlucardSubFrame1 = {
    {0x0100, 0x0002},
    {
        {0x0000, 1, 8, 0},
    },
};

SaturnSpriteFrame2 AlucardSubFrame2 = {
    {0x0200, 0x0002},
    {
        {0x0100, 2, 17, 1},
        {0x0004, -5, 17, 2},
    },
};

SaturnSpriteFrame2 AlucardSubFrame3 = {
    {0x0200, 0x0002},
    {
        {0x0100, 1, 17, 3},
        {0x0004, -3, 16, 4},
    },
};

SaturnSpriteFrame2 AlucardSubFrame4 = {
    {0x0200, 0x0002},
    {
        {0x0100, -5, 17, 2},
        {0x0004, 2, 16, 5},
    },
};

SaturnSpriteFrame2 AlucardSubFrame5 = {
    {0x0200, 0x0002},
    {
        {0x0100, -3, 16, 4},
        {0x0004, 3, 15, 6},
    },
};

SaturnSpriteFrame2 AlucardSubFrame6 = {
    {0x0200, 0x0002},
    {
        {0x0100, 2, 16, 5},
        {0x0004, 5, 17, 7},
    },
};

SaturnSpriteFrame2 AlucardSubFrame7 = {
    {0x0200, 0x0002},
    {
        {0x0100, 3, 15, 6},
        {0x0004, 5, 17, 8},
    },
};

SaturnSpriteFrame2 AlucardSubFrame8 = {
    {0x0200, 0x0002},
    {
        {0x0100, 5, 17, 7},
        {0x0004, 2, 17, 1},
    },
};

SaturnSpriteFrame2 AlucardSubFrame9 = {
    {0x0200, 0x0002},
    {
        {0x0100, 5, 17, 8},
        {0x0004, 1, 17, 3},
    },
};

SaturnSpriteFrame2 AlucardSubFrame10 = {
    {0x0200, 0x0002},
    {
        {0x0100, 2, 17, 1},
        {0x0004, 2, 16, 5},
    },
};

SaturnSpriteFrame2 AlucardSubFrame11 = {
    {0x0200, 0x0002},
    {
        {0x0100, 1, 17, 3},
        {0x0004, 3, 15, 6},
    },
};

SaturnSpriteFrame2 AlucardSubFrame12 = {
    {0x0200, 0x0002},
    {
        {0x0100, -5, 17, 2},
        {0x0004, 5, 17, 7},
    },
};

SaturnSpriteFrame2 AlucardSubFrame13 = {
    {0x0200, 0x0002},
    {
        {0x0100, -3, 16, 4},
        {0x0004, 5, 17, 8},
    },
};

SaturnSpriteFrame2 AlucardSubFrame14 = {
    {0x0200, 0x0002},
    {
        {0x0100, 2, 16, 5},
        {0x0004, 2, 17, 1},
    },
};

SaturnSpriteFrame2 AlucardSubFrame15 = {
    {0x0200, 0x0002},
    {
        {0x0100, 3, 15, 6},
        {0x0004, 1, 17, 3},
    },
};

SaturnSpriteFrame2 AlucardSubFrame16 = {
    {0x0200, 0x0002},
    {
        {0x0100, 5, 17, 7},
        {0x0004, -5, 17, 2},
    },
};

SaturnSpriteFrame2 AlucardSubFrame17 = {
    {0x0200, 0x0002},
    {
        {0x0100, 5, 17, 8},
        {0x0004, -3, 16, 4},
    },
};

SaturnSpriteFrame1 AlucardSubFrame18 = {
    {0x0100, 0x0002},
    {
        {0x0000, 2, 19, 9},
    },
};

SaturnSpriteFrame1 AlucardSubFrame19 = {
    {0x0100, 0x0002},
    {
        {0x0000, 0, 21, 10},
    },
};

SaturnSpriteFrame1 AlucardSubFrame20 = {
    {0x0100, 0x0002},
    {
        {0x0000, 1, 21, 11},
    },
};

SaturnSpriteFrame2 AlucardSubFrame21 = {
    {0x0200, 0x0002},
    {
        {0x0100, -10, 15, 4},
        {0x0004, -2, 16, 12},
    },
};

SaturnSpriteFrame2 AlucardSubFrame22 = {
    {0x0200, 0x0002},
    {
        {0x0100, -3, 16, 13},
        {0x0004, 4, 16, 14},
    },
};

SaturnSpriteFrame2 AlucardSubFrame23 = {
    {0x0200, 0x0002},
    {
        {0x0100, 2, 17, 15},
        {0x0004, 5, 17, 16},
    },
};

SaturnSpriteFrame2 AlucardSubFrame24 = {
    {0x0200, 0x0002},
    {
        {0x0100, 14, 12, 17},
        {0x0004, 10, 14, 17},
    },
};

SaturnSpriteFrame2 AlucardSubFrame25 = {
    {0x0200, 0x0002},
    {
        {0x0100, 1, 18, 4},
        {0x0004, 0, 18, 18},
    },
};

SaturnSpriteFrame2 AlucardSubFrame26 = {
    {0x0200, 0x0002},
    {
        {0x0100, 5, 17, 15},
        {0x0004, 1, 18, 13},
    },
};

SaturnSpriteFrame2 AlucardSubFrame27 = {
    {0x0200, 0x0002},
    {
        {0x0100, 7, 15, 6},
        {0x0004, 1, 16, 15},
    },
};

SaturnSpriteFrame2 AlucardSubFrame28 = {
    {0x0200, 0x0002},
    {
        {0x0100, 0, 16, 19},
        {0x0004, 3, 15, 6},
    },
};

SaturnSpriteFrame2 AlucardSubFrame29 = {
    {0x0200, 0x0002},
    {
        {0x0100, 1, 19, 13},
        {0x0004, 3, 16, 15},
    },
};

SaturnSpriteFrame2 AlucardSubFrame30 = {
    {0x0200, 0x0002},
    {
        {0x0100, 1, 20, 18},
        {0x0004, 1, 15, 19},
    },
};

SaturnSpriteFrame1 AlucardSubFrame31 = {
    {0x0100, 0x0002},
    {
        {0x0002, 2, 8, 20},
    },
};

SaturnSpriteFrame1 AlucardSubFrame32 = {
    {0x0100, 0x0002},
    {
        {0x0000, 4, 8, 21},
    },
};

SaturnSpriteFrame2 AlucardSubFrame33 = {
    {0x0200, 0x0002},
    {
        {0x0000, -3, 17, 22},
        {0x0104, 7, 17, 22},
    },
};

SaturnSpriteFrame2 AlucardSubFrame34 = {
    {0x0200, 0x0002},
    {
        {0x0000, -5, 17, 23},
        {0x0004, 9, 17, 23},
    },
};

SaturnSpriteFrame1 AlucardSubFrame35 = {
    {0x0100, 0x0002},
    {
        {0x0000, 5, 9, 24},
    },
};

SaturnSpriteFrame2 AlucardSubFrame36 = {
    {0x0200, 0x0002},
    {
        {0x0100, 1, 15, 25},
        {0x0004, 8, 16, 26},
    },
};

SaturnSpriteFrame2 AlucardSubFrame37 = {
    {0x0200, 0x0002},
    {
        {0x0100, 5, 16, 27},
        {0x0004, 4, 17, 28},
    },
};

SaturnSpriteFrame2 AlucardSubFrame38 = {
    {0x0200, 0x0002},
    {
        {0x0100, 10, 16, 26},
        {0x0004, 2, 17, 29},
    },
};

SaturnSpriteFrame2 AlucardSubFrame39 = {
    {0x0200, 0x0002},
    {
        {0x0100, 6, 17, 28},
        {0x0004, 2, 17, 30},
    },
};

SaturnSpriteFrame2 AlucardSubFrame40 = {
    {0x0200, 0x0002},
    {
        {0x0100, 2, 17, 29},
        {0x0004, -3, 17, 31},
    },
};

SaturnSpriteFrame2 AlucardSubFrame41 = {
    {0x0200, 0x0002},
    {
        {0x0100, 2, 17, 30},
        {0x0004, -3, 16, 32},
    },
};

SaturnSpriteFrame2 AlucardSubFrame42 = {
    {0x0200, 0x0002},
    {
        {0x0100, -3, 17, 31},
        {0x0004, 3, 15, 33},
    },
};

SaturnSpriteFrame2 AlucardSubFrame43 = {
    {0x0200, 0x0002},
    {
        {0x0100, -3, 16, 32},
        {0x0004, 6, 15, 27},
    },
};

SaturnSpriteFrame2 AlucardSubFrame44 = {
    {0x0200, 0x0002},
    {
        {0x0100, 3, 15, 33},
        {0x0004, 2, 17, 29},
    },
};

SaturnSpriteFrame2 AlucardSubFrame45 = {
    {0x0200, 0x0002},
    {
        {0x0100, 6, 15, 27},
        {0x0004, 2, 17, 30},
    },
};

SaturnSpriteFrame2 AlucardSubFrame46 = {
    {0x0200, 0x0002},
    {
        {0x0100, 10, 16, 26},
        {0x0004, -3, 17, 31},
    },
};

SaturnSpriteFrame2 AlucardSubFrame47 = {
    {0x0200, 0x0002},
    {
        {0x0100, 6, 17, 28},
        {0x0004, -3, 16, 32},
    },
};

SaturnSpriteFrame2 AlucardSubFrame48 = {
    {0x0200, 0x0002},
    {
        {0x0100, 2, 17, 29},
        {0x0004, 3, 15, 33},
    },
};

SaturnSpriteFrame2 AlucardSubFrame49 = {
    {0x0200, 0x0002},
    {
        {0x0100, 2, 17, 30},
        {0x0004, 6, 15, 27},
    },
};

SaturnSpriteFrame2 AlucardSubFrame50 = {
    {0x0200, 0x0002},
    {
        {0x0100, -3, 17, 31},
        {0x0004, 10, 16, 26},
    },
};

SaturnSpriteFrame2 AlucardSubFrame51 = {
    {0x0200, 0x0002},
    {
        {0x0100, -3, 16, 32},
        {0x0004, 6, 17, 28},
    },
};

SaturnSpriteFrame1 AlucardSubFrame52 = {
    {0x0100, 0x0002},
    {
        {0x0000, 5, 19, 34},
    },
};

SaturnSpriteFrame1 AlucardSubFrame53 = {
    {0x0100, 0x0002},
    {
        {0x0000, 3, 21, 35},
    },
};

SaturnSpriteFrame1 AlucardSubFrame54 = {
    {0x0100, 0x0002},
    {
        {0x0000, 5, 20, 36},
    },
};

SaturnSpriteFrame2 AlucardSubFrame55 = {
    {0x0200, 0x0002},
    {
        {0x0100, 2, 17, 32},
        {0x0004, -3, 16, 37},
    },
};

SaturnSpriteFrame2 AlucardSubFrame56 = {
    {0x0200, 0x0002},
    {
        {0x0100, -2, 17, 32},
        {0x0004, -3, 16, 38},
    },
};

SaturnSpriteFrame2 AlucardSubFrame57 = {
    {0x0200, 0x0002},
    {
        {0x0100, 0, 15, 39},
        {0x0004, -4, 15, 39},
    },
};

SaturnSpriteFrame2 AlucardSubFrame58 = {
    {0x0200, 0x0002},
    {
        {0x0100, -6, 12, 40},
        {0x0004, -5, 14, 40},
    },
};

SaturnSpriteFrame2 AlucardSubFrame59 = {
    {0x0200, 0x0002},
    {
        {0x0100, 1, 18, 41},
        {0x0004, 3, 19, 41},
    },
};

SaturnSpriteFrame2 AlucardSubFrame60 = {
    {0x0200, 0x0002},
    {
        {0x0100, 2, 18, 33},
        {0x0004, 3, 19, 42},
    },
};

SaturnSpriteFrame2 AlucardSubFrame61 = {
    {0x0200, 0x0002},
    {
        {0x0100, 8, 17, 33},
        {0x0004, 5, 16, 33},
    },
};

SaturnSpriteFrame2 AlucardSubFrame62 = {
    {0x0200, 0x0002},
    {
        {0x0100, 12, 16, 27},
        {0x0004, 8, 16, 27},
    },
};

SaturnSpriteFrame2 AlucardSubFrame63 = {
    {0x0200, 0x0002},
    {
        {0x0100, 7, 17, 33},
        {0x0004, 4, 19, 42},
    },
};

SaturnSpriteFrame2 AlucardSubFrame64 = {
    {0x0200, 0x0002},
    {
        {0x0100, 8, 19, 33},
        {0x0004, 3, 19, 41},
    },
};

SaturnSpriteFrame1 AlucardSubFrame65 = {
    {0x0100, 0x0002},
    {
        {0x0000, 3, 9, 43},
    },
};

SaturnSpriteFrame1 AlucardSubFrame66 = {
    {0x0100, 0x0002},
    {
        {0x0000, 3, 9, 44},
    },
};

SaturnSpriteFrame2 AlucardSubFrame67 = {
    {0x0200, 0x0002},
    {
        {0x0100, 5, 17, 45},
        {0x0004, -2, 17, 45},
    },
};

SaturnSpriteFrame2 AlucardSubFrame68 = {
    {0x0200, 0x0002},
    {
        {0x0000, -4, 17, 46},
        {0x0004, 10, 17, 46},
    },
};

SaturnSpriteFrame2 AlucardSubFrame69 = {
    {0x0200, 0x0002},
    {
        {0x0100, 1, 17, 30},
        {0x0004, 5, 17, 28},
    },
};

SaturnSpriteFrame2 AlucardSubFrame70 = {
    {0x0200, 0x0002},
    {
        {0x0100, 2, 17, 8},
        {0x0004, 4, 17, 1},
    },
};

SaturnSpriteFrame2 AlucardSubFrame71 = {
    {0x0200, 0x0002},
    {
        {0x0100, 5, 17, 30},
        {0x0004, -1, 17, 29},
    },
};

SaturnSpriteFrame1 AlucardSubFrame72 = {
    {0x0100, 0x0002},
    {
        {0x0000, 4, 0, 47},
    },
};

SaturnSpriteFrame1 AlucardSubFrame73 = {
    {0x0100, 0x0002},
    {
        {0x0000, 4, 0, 48},
    },
};

SaturnSpriteFrame1 AlucardSubFrame74 = {
    {0x0100, 0x0002},
    {
        {0x0000, 3, 0, 49},
    },
};

SaturnSpriteFrame1 AlucardSubFrame75 = {
    {0x0100, 0x0002},
    {
        {0x0000, 4, 0, 50},
    },
};

SaturnSpriteFrame1 AlucardSubFrame76 = {
    {0x0100, 0x0002},
    {
        {0x0000, 1, 1, 51},
    },
};

SaturnSpriteFrame1 AlucardSubFrame77 = {
    {0x0100, 0x0002},
    {
        {0x0000, 1, 1, 52},
    },
};

SaturnSpriteFrame1 AlucardSubFrame78 = {
    {0x0100, 0x0002},
    {
        {0x0000, 1, 0, 53},
    },
};

SaturnSpriteFrame1 AlucardSubFrame79 = {
    {0x0100, 0x0002},
    {
        {0x0000, -1, 1, 54},
    },
};

SaturnSpriteFrame1 AlucardSubFrame80 = {
    {0x0100, 0x0002},
    {
        {0x0000, 0, 1, 55},
    },
};

SaturnSpriteFrame1 AlucardSubFrame81 = {
    {0x0100, 0x0002},
    {
        {0x0000, 1, 1, 56},
    },
};

SaturnSpriteFrame1 AlucardSubFrame82 = {
    {0x0100, 0x0002},
    {
        {0x0000, 2, 1, 57},
    },
};

SaturnSpriteFrame2 AlucardSubFrame83 = {
    {0x0200, 0x0002},
    {
        {0x0200, -61, 34, 58},
        {0x0200, 7, 34, 59},
    },
};

SaturnSpriteFrame1 AlucardSubFrame84 = {
    {0x0100, 0x0002},
    {
        {0x0200, -13, 34, 60},
    },
};

SaturnSpriteFrame1 AlucardSubFrame85 = {
    {0x0100, 0x0002},
    {
        {0x0000, 3, 35, 61},
    },
};

SaturnSpriteFrame1 AlucardSubFrame86 = {
    {0x0100, 0x0002},
    {
        {0x0200, 0, 34, 62},
    },
};

SaturnSpriteFrame1 AlucardSubFrame87 = {
    {0x0100, 0x0002},
    {
        {0x0000, 2, 12, 0},
    },
};

SaturnSpriteFrame1 AlucardSubFrame88 = {
    {0x0100, 0x0002},
    {
        {0x0000, 2, 16, 0},
    },
};

SaturnSpriteFrame1 AlucardSubFrame89 = {
    {0x0100, 0x0002},
    {
        {0x0000, 5, 13, 24},
    },
};

SaturnSpriteFrame1 AlucardSubFrame90 = {
    {0x0100, 0x0002},
    {
        {0x0000, 5, 17, 24},
    },
};

SaturnSpriteFrame1 AlucardSubFrame91 = {
    {0x0100, 0x0002},
    {
        {0x0000, 3, 0, 63},
    },
};

SaturnSpriteFrame1 AlucardSubFrame92 = {
    {0x0100, 0x0002},
    {
        {0x0000, 2, 0, 64},
    },
};

SaturnSpriteFrame1 AlucardSubFrame93 = {
    {0x0100, 0x0002},
    {
        {0x0000, 2, 0, 65},
    },
};

SaturnSpriteFrame1 AlucardSubFrame94 = {
    {0x0100, 0x0002},
    {
        {0x0000, 1, 0, 66},
    },
};

u16 AlucardSubFramePadding = 0;

SaturnSpriteFrameHeader* AlucardSubFrames[95] = {
    (SaturnSpriteFrameHeader*)&AlucardSubFrame0,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame1,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame2,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame3,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame4,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame5,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame6,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame7,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame8,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame9,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame10,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame11,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame12,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame13,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame14,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame15,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame16,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame17,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame18,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame19,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame20,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame21,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame22,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame23,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame24,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame25,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame26,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame27,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame28,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame29,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame30,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame31,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame32,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame33,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame34,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame35,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame36,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame37,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame38,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame39,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame40,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame41,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame42,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame43,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame44,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame45,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame46,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame47,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame48,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame49,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame50,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame51,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame52,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame53,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame54,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame55,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame56,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame57,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame58,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame59,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame60,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame61,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame62,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame63,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame64,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame65,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame66,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame67,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame68,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame69,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame70,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame71,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame72,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame73,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame74,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame75,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame76,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame77,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame78,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame79,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame80,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame81,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame82,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame83,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame84,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame85,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame86,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame87,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame88,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame89,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame90,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame91,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame92,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame93,
    (SaturnSpriteFrameHeader*)&AlucardSubFrame94,
};
