// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[2][16];
} AlucardPkg4Palette = {
    0x0002,
    {
        {
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0xCD2B,
            0xD58C,
            0xDE0E,
            0xE670,
            0xEEF1,
            0xF753,
            0xFFD5,
            0xFFF9,
        },
        {
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0xE900,
            0xED40,
            0xF180,
            0xF604,
            0xFA85,
            0xFF4B,
            0xFFD5,
            0xFFFF,
        },
    },
};

SaturnSpriteImage AlucardPkg4Images[19] = {
    {64, 8, 0x0000}, {64, 8, 0x0080}, {8, 8, 0x0100},  {8, 8, 0x0110},
    {8, 8, 0x0120},  {8, 8, 0x0130},  {8, 8, 0x0140},  {8, 8, 0x0150},
    {8, 8, 0x0160},  {8, 8, 0x0170},  {8, 8, 0x0180},  {8, 8, 0x0190},
    {8, 8, 0x01A0},  {8, 8, 0x01B0},  {44, 4, 0x01C0}, {40, 4, 0x01EC},
    {40, 4, 0x0214}, {40, 4, 0x023C}, {0, 0, 0x0264},
};
