// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[1][16];
    u16 padding[1];
} AlucardPkg8Palette = {
    0x0001,
    {
        {
            0xC0A8,
            0x8000,
            0x8045,
            0x84A9,
            0x8D50,
            0x8E15,
            0x8884,
            0x9508,
            0x8000,
            0x8421,
            0x801B,
            0x8000,
            0x9084,
            0xA969,
            0xB231,
            0xDAD6,
        },
    },
    {0x0000},
};

SaturnSpriteImage AlucardPkg8Images[2] = {
    {32, 32, 0x0000},
    {0, 0, 0x0100},
};
