// SPDX-License-Identifier: AGPL-3.0-or-later
#include "rno0.h"

u16 PrizeDrops[] = {
    ITEMDROP_LIBRARY_CARD, ITEMDROP_POTION,         ITEMDROP_ANTIVENOM,
    ITEMDROP_LIFE_VESSEL,  ITEMDROP_HEART_VESSEL,   ITEMDROP_RESIST_DARK,
    ITEMDROP_RESIST_HOLY,  ITEMDROP_RESIST_THUNDER, ITEMDROP_RESIST_FIRE,
    ITEMDROP_MEAL_TICKET,  ITEMDROP_IRON_BALL,      ITEMDROP_HEART_REFRESH,
    ITEMDROP_LIFE_VESSEL,  ITEMDROP_LIFE_VESSEL,    ITEMDROP_LIFE_VESSEL,
    ITEMDROP_LIFE_VESSEL,
};
