// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
WAIT_FOR_FLAG(0),
PLAY_SOUND(0x10),
SCRIPT_UNKNOWN_11(),
SET_POS(60,28),
LOAD_PORTRAIT(0x80182cc0,0),
SET_PORTRAIT(1,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3ba),
WAIT_FOR_SOUND(),
SET_SPEED(3),
'A','l','u','c','a','r','d','?',
SET_WAIT(56),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x80181f40,1),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3bb),
WAIT_FOR_SOUND(),
SET_SPEED(3),
'T','h','a','t',' ','v','o','i','c','e','?',' ',
SET_WAIT(16),
'M','a','r','i','a','?',
SET_WAIT(56),
NEXT_DIALOG(),
SET_PORTRAIT(1,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3bc),
WAIT_FOR_SOUND(),
SET_SPEED(3),
'I','\'','m',' ','s','o','r','r','y','.',' ',
SET_WAIT(16),
SET_SPEED(2),
'Y','o','u',' ','w','e','r','e',
LINE_BREAK(),
SET_WAIT(4),
'r','i','g','h','t','.',' ',
SET_WAIT(32),
'H','e',' ','h','a','s',' ','j','o','i','n','e','d',
LINE_BREAK(),
SET_WAIT(4),
'f','o','r','c','e','s',' ','w','i','t','h',' ','t','h','e',
LINE_BREAK(),
SET_WAIT(4),
'e','n','e','m','y','.','.','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3bd),
WAIT_FOR_SOUND(),
SET_SPEED(2),
'S','o',' ','i','t',' ','w','a','s',' ','a',' ','B','e','l','m','o','n','t',
LINE_BREAK(),
SET_WAIT(4),
'a','f','t','e','r',' ','a','l','l','.','.','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(1,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3be),
WAIT_FOR_SOUND(),
SET_SPEED(3),
'B','u','t',' ','s','o','m','e','o','n','e',' ','m','u','s','t',' ','b','e',
LINE_BREAK(),
SET_WAIT(4),
'c','o','n','t','r','o','l','l','i','n','g',' ','h','i','m','.','.','.',
LINE_BREAK(),
SET_WAIT(32),
SET_SPEED(2),
'W','h','a','t','e','v','e','r',' ','w','e',' ','d','o',',',' ',
SET_WAIT(16),
SET_SPEED(3),
'w','e',
LINE_BREAK(),
SET_WAIT(4),
'c','a','n','\'','t',' ','h','a','r','m',' ','R','i','c','h','t','e','r','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3bf),
WAIT_FOR_SOUND(),
SET_SPEED(2),
'B','u','t',' ','h','e',' ','m','u','s','t',
LINE_BREAK(),
SET_WAIT(4),
'b','e',' ','s','t','o','p','p','e','d','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(1,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3c0),
WAIT_FOR_SOUND(),
SET_SPEED(3),
'I',' ','k','n','o','w','.',
LINE_BREAK(),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3cc),
WAIT_FOR_SOUND(),
'W','e','l','l','.','.','.',
SET_WAIT(16),
'h','e','r','e','.',
LINE_BREAK(),
SET_WAIT(40),
SET_SPEED(2),
'T','a','k','e',' ','t','h','e','s','e',' ','w','i','t','h',' ','y','o','u','.',
SET_FLAG(3),
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3cd),
WAIT_FOR_SOUND(),
SET_SPEED(2),
'W','h','a','t',' ','a','r','e',' ','t','h','e','s','e','?',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(1,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3ce),
WAIT_FOR_SOUND(),
SET_SPEED(2),
'I','f',' ','y','o','u',' ','w','e','a','r',' ','t','h','e','s','e',',',
LINE_BREAK(),
SET_WAIT(24),
'y','o','u',' ','c','a','n',' ','s','e','e',' ','b','e','y','o','n','d',
LINE_BREAK(),
SET_WAIT(4),
'e','v','i','l',' ','i','l','l','u','s','i','o','n','s','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3cf),
WAIT_FOR_SOUND(),
SET_SPEED(2),
'T','h','a','n','k',' ','y','o','u','.',
LINE_BREAK(),
SET_WAIT(20),
SET_SPEED(1),
'\'','T','i','s',' ','b','e','s','t',' ','t','h','e','n',' ',
SET_SPEED(2),
'i','f',
LINE_BREAK(),
SET_WAIT(4),
'y','o','u',' ','p','r','a','y',' ','f','o','r',' ','t','h','e',
LINE_BREAK(),
SET_WAIT(4),
's','o','u','l',' ','o','f',' ','y','o','u','r',' ','f','r','i','e','n','d','.',
SET_WAIT(48),
NEXT_DIALOG(),
CLOSE_DIALOG(),
SCRIPT_UNKNOWN_11(),
SET_FLAG(1),
SCRIPT_UNKNOWN_20(0x11),
END_CUTSCENE(),
0xff,
0xff,
