// SPDX-License-Identifier: AGPL-3.0-or-later
#include "np3.h"

u16 OVL_EXPORT(PrizeDrops)[] = {
    ITEMDROP_HEART_VESSEL, ITEMDROP_LIFE_VESSEL,   ITEMDROP_LIFE_APPLE,
    ITEMDROP_HEART_VESSEL, ITEMDROP_SHIELD_POTION, ITEMDROP_HOLY_MAIL,
    ITEMDROP_LIFE_VESSEL,  ITEMDROP_HEART_VESSEL,  ITEMDROP_LIFE_VESSEL,
    ITEMDROP_JEWEL_SWORD,
};
