REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
#include "sfx.h"

#define GAIBON self[8]
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        if ((self->hitFlags & 3) && (self->step != SLOGRA_KNOCKBACK)) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
                self->hitboxState = 0;
                PlaySfxPositional(NA_SE_EN_SLOGRA_HURT_2);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            self->hitboxState = 0;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        if (g_CastleFlags[KilledInAlchLab] ||
            g_CastleFlags[RetreatedInEntrance]) {
REDACTED
REDACTED
REDACTED
REDACTED
        self->facingLeft = (GetSideToPlayer() & 1) ^ 1;
REDACTED
REDACTED
REDACTED
        if (UnkCollisionFunc3(&D_801812D0) & 1) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        if (GetDistanceToPlayerX() < 96) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            self->facingLeft = (GetSideToPlayer() & 1) ^ 1;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        self->facingLeft = (GetSideToPlayer() & 1) ^ 1;
        if (self->facingLeft != self->ext.GS_Props.flag) {
            self->velocityX = FIX(0.75);
REDACTED
            self->velocityX = FIX(-0.75);
REDACTED
        UnkCollisionFunc2(&D_801812E0);
REDACTED
            if (GetDistanceToPlayerX() < 72) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            if (GetDistanceToPlayerX() > 112) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            PlaySfxPositional(NA_SE_EN_SLOGRA_HISSING);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        if (self->animFrameIdx == 4 && self->animFrameDuration == 0) {
            PlaySfxPositional(NA_SE_EN_SLOGRA_SPEAR_SLASH);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            self->facingLeft = (GetSideToPlayer() & 1) ^ 1;
REDACTED
REDACTED
REDACTED
REDACTED
                PlaySfxPositional(NA_SE_EN_SLOGRA_SPEAR_PROJECTILE);
                newEntity = AllocEntity(g_Entities + 160, g_Entities + 192);
REDACTED
                    CreateEntityFromEntity(
                        E_SLOGRA_SPEAR_PROJECTILE, self, newEntity);
                    if (self->facingLeft != 0) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
                    newEntity->facingLeft = self->facingLeft;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            PlaySfxPositional(NA_SE_EN_SLOGRA_HURT);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            self->facingLeft = (GetSideToPlayer() & 1) ^ 1;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        self->facingLeft = (GetSideToPlayer() & 1) ^ 1;
        if (self->facingLeft != self->ext.GS_Props.flag) {
            self->velocityX = FIX(0.75);
REDACTED
            self->velocityX = FIX(-0.75);
REDACTED
REDACTED
        UnkCollisionFunc2(&D_801812E0);
REDACTED
            if (GetDistanceToPlayerX() < 72) {
REDACTED
REDACTED
REDACTED
                if (GetDistanceToPlayerX() > 112) {
REDACTED
REDACTED
REDACTED
REDACTED
            if (GetDistanceToPlayerX() >= 0x71) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        if (self->animFrameIdx == 7 && self->animFrameDuration == 0) {
            PlaySfxPositional(NA_SE_EN_SLOGRA_BEAK_ATTACK);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
                self->velocityX = 0;
                self->velocityY = 0;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            if (UnkCollisionFunc3(&D_801812D0) & 1) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            self->hitboxState = 0;
REDACTED
REDACTED
REDACTED
REDACTED
            PlaySfxPositional(NA_SE_EN_SLOGRA_DEATH_EXPLOSION);
            g_CastleFlags[RetreatedInEntrance] |= 1;
REDACTED
REDACTED
REDACTED
            UnkCollisionFunc3(&D_801812D0);
REDACTED
            if (!(g_Timer % 4)) {
                newEntity = AllocEntity(&g_Entities[224], &g_Entities[256]);
REDACTED
                    CreateEntityFromEntity(E_EXPLOSION, self, newEntity);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
                CreateEntityFromEntity(E_EXPLOSION, self, newEntity);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        if (g_pads[1].pressed & PAD_CIRCLE) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
    self->hitboxOffX = *hitbox++;
    self->hitboxOffY = *hitbox++;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        self->facingLeft = self[-1].facingLeft;
REDACTED
REDACTED
REDACTED
REDACTED
        self->hitboxOffX = *hitbox++;
        self->hitboxOffY = *hitbox++;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            self->drawFlags = FLAG_DRAW_ROTZ;
            self->hitboxState = 0;
            if (self->facingLeft != 0) {
                self->velocityX = FIX(-2.25);
REDACTED
                self->velocityX = FIX(2.25);
REDACTED
            self->velocityY = FIX(-4);
REDACTED
            self->flags |= FLAG_DESTROY_IF_OUT_OF_CAMERA;
REDACTED
REDACTED
REDACTED
REDACTED
            self->velocityY += FIX(0.15625);
            self->rotZ += 0x80;
            if (!(self->rotZ & 0xFFF)) {
                PlaySfxPositional(SFX_ARROW_SHOT_A);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
    if (self->flags & FLAG_DEAD) {
REDACTED
REDACTED
            CreateEntityFromEntity(E_EXPLOSION, self, entity);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        InitializeEntity(D_80180B5C);
        if (self->facingLeft == 0) {
            self->velocityX = FIX(-4);
REDACTED
            self->velocityX = FIX(4);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
