// SPDX-License-Identifier: AGPL-3.0-or-later
#include "rno3.h"

u16 OVL_EXPORT(PrizeDrops)[] = {
    ITEMDROP_HAMMER, ITEMDROP_ANTIVENOM, ITEMDROP_HIGH_POTION, ITEMDROP_HEART_VESSEL,  ITEMDROP_ZIRCON, ITEMDROP_OPAL, ITEMDROP_BERYL_CIRCLET, ITEMDROP_FIRE_BOOMERANG, ITEMDROP_LIFE_VESSEL, ITEMDROP_TALISMAN,
    ITEMDROP_FLAME_STAR,  ITEMDROP_DIM_SUM_SET,  ITEMDROP_DIM_SUM_SET,  ITEMDROP_DIM_SUM_SET, ITEMDROP_DIM_SUM_SET,  ITEMDROP_DIM_SUM_SET,  ITEMDROP_DIM_SUM_SET,  ITEMDROP_DIM_SUM_SET,  ITEMDROP_DIM_SUM_SET, 0};
