// SPDX-License-Identifier: AGPL-3.0-or-later
#include "nz1.h"

u16 OVL_EXPORT(PrizeDrops)[] = {ITEMDROP_MAGIC_MISSILE, ITEMDROP_PENTAGRAM, ITEMDROP_STONE_SWORD, ITEMDROP_STAR_FLAIL, ITEMDROP_GOLD_PLATE, ITEMDROP_STEEL_HELM,
                                ITEMDROP_HEALING_MAIL, ITEMDROP_BEKATOWA, ITEMDROP_SHAMAN_SHIELD, ITEMDROP_ICE_MAIL, ITEMDROP_LIFE_VESSEL, ITEMDROP_HEART_VESSEL};
