// SPDX-License-Identifier: AGPL-3.0-or-later
#include <stage.h>

#include "gen/nz1_tilemap_0.h"
#include "gen/nz1_tilemap_1.h"
#include "gen/nz1_tilemap_2.h"
#include "gen/nz1_tilemap_3.h"
#include "gen/nz1_tilemap_4.h"
#include "gen/nz1_tilemap_5.h"
#include "gen/nz1_tilemap_6.h"
#include "gen/nz1_tilemap_7.h"
#include "gen/nz1_tilemap_8.h"
#include "gen/nz1_tilemap_9.h"
#include "gen/nz1_tilemap_10.h"
#include "gen/nz1_tilemap_11.h"
#include "gen/nz1_tilemap_12.h"
#include "gen/nz1_tilemap_13.h"
#include "gen/nz1_tilemap_14.h"
#include "gen/nz1_tilemap_15.h"
#include "gen/nz1_tilemap_16.h"
#include "gen/nz1_tilemap_17.h"
#include "gen/nz1_tilemap_18.h"
#include "gen/nz1_tilemap_19.h"
#include "gen/nz1_tilemap_20.h"
#include "gen/nz1_tilemap_21.h"
#include "gen/nz1_tiledef_0.h"
#include "gen/nz1_tiledef_1.h"
