// SPDX-License-Identifier: AGPL-3.0-or-later
#include "no2.h"

u16 OVL_EXPORT(PrizeDrops)[] = {
    ITEMDROP_LIFE_VESSEL,    ITEMDROP_HEART_VESSEL, ITEMDROP_PENTAGRAM,
    ITEMDROP_GODDESS_SHIELD, ITEMDROP_BROADSWORD,   ITEMDROP_ONYX,
    ITEMDROP_CHEESE,         ITEMDROP_MANNA_PRISM,  ITEMDROP_RESIST_FIRE,
    ITEMDROP_LUCK_POTION,    ITEMDROP_ESTOC,        ITEMDROP_IRON_BALL,
};

static u32 D_us_80181004 = 0x0000016C; // dirty
