// SPDX-License-Identifier: AGPL-3.0-or-later
#include "rno2.h"

u16 PrizeDrops[] = {
    ITEMDROP_OPAL,          ITEMDROP_SWORD_OF_HADOR, ITEMDROP_HIGH_POTION,
    ITEMDROP_SHIELD_POTION, ITEMDROP_LUCK_POTION,    ITEMDROP_MANNA_PRISM,
    ITEMDROP_AQUAMARINE,    ITEMDROP_ALUCARD_MAIL,   ITEMDROP_LIFE_VESSEL,
    ITEMDROP_HEART_REFRESH, ITEMDROP_SHURIKEN,       ITEMDROP_HEART_VESSEL,
};
