// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[1][16];
    u16 padding[1];
} g_Stage16SpriteBank21Palette = {
    0x0001,
    {
        {
            0xA800,
            0xF860,
            0xA400,
            0xF4DD,
            0xD415,
            0xA82A,
            0x9826,
            0x8421,
            0x80DA,
            0x82BD,
            0xB7BD,
            0x94A5,
            0xA94A,
            0xC5AD,
            0xD6B5,
            0xF7BD,
        },
    },
    {0x0000},
};

SaturnSpriteFrameHeader g_Stage16SpriteBank21Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame6 g_Stage16SpriteBank21Frame1 = {
    {0x0600, 0x0000},
    {
        {0x0000, -4, 16, 0},
        {0x0000, -4, 0, 0},
        {0x0000, -4, -16, 0},
        {0x0000, -5, -32, 1},
        {0x0000, 3, 8, 2},
        {0x0000, 3, -14, 3},
    },
};

SaturnSpriteFrame6 g_Stage16SpriteBank21Frame2 = {
    {0x0600, 0x0000},
    {
        {0x0000, -4, 15, 0},
        {0x0000, -4, -1, 0},
        {0x0000, -4, -17, 0},
        {0x0000, -5, -33, 1},
        {0x0000, 3, -7, 4},
        {0x0000, -1, 16, 5},
    },
};

SaturnSpriteFrame6 g_Stage16SpriteBank21Frame3 = {
    {0x0600, 0x0000},
    {
        {0x0000, -3, 16, 0},
        {0x0000, -3, 0, 0},
        {0x0000, -3, -16, 0},
        {0x0000, -4, -32, 1},
        {0x0000, 4, -7, 4},
        {0x0000, 2, 16, 6},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame4 = {
    {0x0700, 0x0000},
    {
        {0x0000, 4, 16, 7},
        {0x0000, -1, 1, 8},
        {0x0000, 2, -13, 9},
        {0x0000, 22, -5, 10},
        {0x0000, 2, 2, 10},
        {0x0000, -18, 9, 10},
        {0x0000, -35, 15, 11},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame5 = {
    {0x0700, 0x0000},
    {
        {0x0000, 6, 16, 12},
        {0x0000, -1, 0, 8},
        {0x0000, 2, -14, 9},
        {0x0000, 22, -6, 10},
        {0x0000, 2, 1, 10},
        {0x0000, -18, 8, 10},
        {0x0000, -35, 14, 11},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame6 = {
    {0x0700, 0x0000},
    {
        {0x0000, 3, 16, 7},
        {0x0000, -1, 0, 13},
        {0x0000, 1, -13, 9},
        {0x0000, 23, 0, 14},
        {0x0000, -1, 0, 14},
        {0x0000, -21, 0, 14},
        {0x0000, -41, 0, 15},
    },
};

SaturnSpriteFrame8 g_Stage16SpriteBank21Frame7 = {
    {0x0800, 0x0000},
    {
        {0x0000, 1, 18, 16},
        {0x0000, -7, 3, 13},
        {0x0000, -5, -10, 9},
        {0x0000, 10, 3, 14},
        {0x0000, -8, 3, 14},
        {0x0000, -28, 3, 14},
        {0x0000, -37, 3, 14},
        {0x0000, -55, 3, 15},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame8 = {
    {0x0700, 0x0000},
    {
        {0x0000, 6, 16, 12},
        {0x0000, 0, 0, 13},
        {0x0000, 2, -13, 9},
        {0x0000, 18, 0, 14},
        {0x0000, 0, 0, 14},
        {0x0000, -20, 0, 14},
        {0x0000, -40, 0, 15},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame9 = {
    {0x0700, 0x0000},
    {
        {0x0000, 3, -6, 17},
        {0x0000, -2, 16, 5},
        {0x0000, -10, -9, 18},
        {0x0000, 9, 4, 19},
        {0x0000, 5, 1, 19},
        {0x0000, -14, -14, 19},
        {0x0000, -30, -28, 20},
    },
};

SaturnSpriteFrame6 g_Stage16SpriteBank21Frame10 = {
    {0x0600, 0x0000},
    {
        {0x0000, 5, -24, 0},
        {0x0000, 5, -36, 0},
        {0x0000, 4, -52, 1},
        {0x0000, 1, 16, 21},
        {0x0000, 2, -8, 22},
        {0x0000, 4, -25, 23},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame11 = {
    {0x0700, 0x0000},
    {
        {0x0000, 5, 16, 24},
        {0x0000, 0, -8, 25},
        {0x0000, 12, -9, 26},
        {0x0010, -10, -24, 10},
        {0x0010, 10, -16, 10},
        {0x0010, 26, -11, 10},
        {0x0010, 41, -6, 11},
    },
};

SaturnSpriteFrame11 g_Stage16SpriteBank21Frame12 = {
    {0x0B00, 0x0000},
    {
        {0x0000, 9, 17, 27},
        {0x0000, 2, 1, 28},
        {0x0000, 2, -13, 29},
        {0x0000, -12, -8, 18},
        {0x0020, 10, 3, 10},
        {0x0020, -5, -3, 10},
        {0x0020, -24, -10, 10},
        {0x0020, -43, -17, 11},
        {0x0000, -45, -8, 30},
        {0x0000, -37, -40, 31},
        {0x0000, -40, -32, 32},
    },
};

SaturnSpriteFrame11 g_Stage16SpriteBank21Frame13 = {
    {0x0B00, 0x0000},
    {
        {0x0000, 8, 18, 16},
        {0x0000, -1, 3, 8},
        {0x0000, 2, -11, 9},
        {0x0000, 12, 1, 10},
        {0x0000, -8, 8, 10},
        {0x0000, -24, 13, 10},
        {0x0000, -42, 19, 11},
        {0x0000, -59, 7, 30},
        {0x0000, -54, -17, 32},
        {0x0000, -47, -32, 33},
        {0x0000, -34, -40, 31},
    },
};

SaturnSpriteFrame8 g_Stage16SpriteBank21Frame14 = {
    {0x0800, 0x0000},
    {
        {0x0000, 8, 18, 16},
        {0x0000, 2, -2, 34},
        {0x0000, 14, -7, 35},
        {0x0020, 8, -24, 0},
        {0x0020, 8, -16, 0},
        {0x0020, 8, 0, 0},
        {0x0020, 8, 16, 0},
        {0x0020, 7, 32, 1},
    },
};

SaturnSpriteFrame8 g_Stage16SpriteBank21Frame15 = {
    {0x0800, 0x0000},
    {
        {0x0000, 4, 16, 7},
        {0x0000, 2, -5, 34},
        {0x0000, 14, -10, 35},
        {0x0020, 8, -27, 0},
        {0x0020, 8, -19, 0},
        {0x0020, 8, -3, 0},
        {0x0020, 8, 13, 0},
        {0x0020, 7, 29, 1},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame16 = {
    {0x0700, 0x0000},
    {
        {0x0000, 4, 16, 7},
        {0x0000, 0, 0, 13},
        {0x0000, 2, -13, 9},
        {0x0000, -38, 8, 11},
        {0x0000, -21, 2, 10},
        {0x0000, -1, -5, 10},
        {0x0000, 19, -12, 10},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame17 = {
    {0x0700, 0x0000},
    {
        {0x0000, 4, 16, 7},
        {0x0000, 0, 0, 13},
        {0x0000, 2, -13, 9},
        {0x0000, -45, 0, 15},
        {0x0000, -24, 0, 14},
        {0x0000, 0, 0, 14},
        {0x0000, 16, 0, 14},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame18 = {
    {0x0700, 0x0000},
    {
        {0x0000, 4, 16, 7},
        {0x0000, 0, 0, 13},
        {0x0000, 2, -13, 9},
        {0x0020, 11, 10, 10},
        {0x0020, -4, 4, 10},
        {0x0020, -23, -3, 10},
        {0x0020, -42, -10, 11},
    },
};

SaturnSpriteFrame8 g_Stage16SpriteBank21Frame19 = {
    {0x0800, 0x0000},
    {
        {0x0000, 4, 16, 7},
        {0x0000, 0, 0, 13},
        {0x0000, 2, -13, 9},
        {0x0020, 4, -26, 36},
        {0x0020, 0, -19, 36},
        {0x0020, -8, -7, 36},
        {0x0020, -16, 5, 36},
        {0x0020, -25, 20, 37},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame20 = {
    {0x0700, 0x0000},
    {
        {0x0000, 4, 16, 7},
        {0x0000, 0, 0, 13},
        {0x0000, 2, -13, 9},
        {0x0020, 8, -20, 19},
        {0x0020, -1, -13, 19},
        {0x0020, -19, 1, 19},
        {0x0020, -35, 15, 20},
    },
};

SaturnSpriteFrame6 g_Stage16SpriteBank21Frame21 = {
    {0x0600, 0x0000},
    {
        {0x0000, 4, 16, 7},
        {0x0000, 0, 0, 13},
        {0x0000, 2, -13, 9},
        {0x0010, -2, 15, 38},
        {0x0000, -35, -14, 39},
        {0x0000, -36, 15, 38},
    },
};

SaturnSpriteFrame6 g_Stage16SpriteBank21Frame22 = {
    {0x0600, 0x0000},
    {
        {0x0000, 4, 16, 7},
        {0x0000, 0, 0, 13},
        {0x0000, 2, -13, 9},
        {0x0020, -34, -15, 38},
        {0x0030, 0, -15, 38},
        {0x0030, -1, 14, 39},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame23 = {
    {0x0700, 0x0000},
    {
        {0x0000, 0, 0, 13},
        {0x0000, 2, -13, 9},
        {0x0000, 6, 16, 12},
        {0x0000, -45, 0, 15},
        {0x0000, -24, 0, 14},
        {0x0000, 0, 0, 14},
        {0x0000, 16, 0, 14},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame24 = {
    {0x0700, 0x0000},
    {
        {0x0000, 4, -6, 17},
        {0x0000, -2, 16, 5},
        {0x0000, -10, -9, 18},
        {0x0000, 9, 4, 19},
        {0x0000, 5, 1, 19},
        {0x0000, -14, -14, 19},
        {0x0000, -30, -28, 20},
    },
};

SaturnSpriteFrame6 g_Stage16SpriteBank21Frame25 = {
    {0x0600, 0x0000},
    {
        {0x0000, 5, -24, 0},
        {0x0000, 5, -36, 0},
        {0x0000, 4, -52, 1},
        {0x0000, 1, 16, 21},
        {0x0000, 2, -8, 22},
        {0x0000, 4, -25, 23},
    },
};

SaturnSpriteFrame6 g_Stage16SpriteBank21Frame26 = {
    {0x0600, 0x0000},
    {
        {0x0000, 17, -6, 36},
        {0x0000, -1, -35, 36},
        {0x0000, -9, -49, 37},
        {0x0000, 1, 16, 21},
        {0x0000, 2, -8, 22},
        {0x0000, 4, -25, 23},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame27 = {
    {0x0700, 0x0000},
    {
        {0x0000, 38, 0, 19},
        {0x0000, 27, -9, 19},
        {0x0000, 12, -21, 19},
        {0x0000, 1, -31, 20},
        {0x0000, 5, 16, 24},
        {0x0000, 0, -8, 25},
        {0x0000, 15, -9, 26},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame28 = {
    {0x0700, 0x0000},
    {
        {0x0020, 30, -17, 10},
        {0x0020, 13, -23, 10},
        {0x0020, -6, -29, 10},
        {0x0020, -26, -36, 11},
        {0x0000, 1, 16, 21},
        {0x0000, 2, -8, 22},
        {0x0000, 4, -25, 23},
    },
};

SaturnSpriteFrame8 g_Stage16SpriteBank21Frame29 = {
    {0x0800, 0x0000},
    {
        {0x0000, 12, -16, 14},
        {0x0000, -8, -16, 14},
        {0x0000, -24, -16, 14},
        {0x0000, -42, -16, 15},
        {0x0000, 9, 17, 27},
        {0x0000, 2, 1, 28},
        {0x0000, 2, -13, 29},
        {0x0000, -12, -8, 18},
    },
};

SaturnSpriteFrame3 g_Stage16SpriteBank21Frame30 = {
    {0x0300, 0x0000},
    {
        {0x0000, 8, 18, 16},
        {0x0000, -1, 3, 8},
        {0x0000, 2, -11, 9},
    },
};

SaturnSpriteFrame3 g_Stage16SpriteBank21Frame31 = {
    {0x0300, 0x0000},
    {
        {0x0000, 3, 16, 7},
        {0x0000, -1, 1, 13},
        {0x0000, 1, -12, 9},
    },
};

SaturnSpriteFrame3 g_Stage16SpriteBank21Frame32 = {
    {0x0300, 0x0000},
    {
        {0x0000, -1, 0, 13},
        {0x0000, 1, -13, 9},
        {0x0000, 5, 16, 12},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame33 = {
    {0x0700, 0x0000},
    {
        {0x0000, 4, 16, 7},
        {0x0000, 2, -5, 34},
        {0x0000, 14, -10, 35},
        {0x0020, 25, -14, 19},
        {0x0020, 16, -7, 19},
        {0x0020, -2, 7, 19},
        {0x0020, -18, 21, 20},
    },
};

SaturnSpriteFrame8 g_Stage16SpriteBank21Frame34 = {
    {0x0800, 0x0000},
    {
        {0x0000, 4, 16, 7},
        {0x0000, 2, -5, 34},
        {0x0000, 14, -10, 35},
        {0x0020, 8, -28, 0},
        {0x0020, 8, -20, 0},
        {0x0020, 8, -4, 0},
        {0x0020, 8, 12, 0},
        {0x0020, 7, 28, 1},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame35 = {
    {0x0700, 0x0000},
    {
        {0x0000, 4, 16, 7},
        {0x0000, 2, -3, 40},
        {0x0020, 6, 4, 0},
        {0x0020, 6, 12, 0},
        {0x0020, 6, 28, 0},
        {0x0020, 6, 41, 0},
        {0x0020, 5, 52, 1},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame36 = {
    {0x0700, 0x0000},
    {
        {0x0000, 4, 16, 7},
        {0x0000, 2, -3, 40},
        {0x0020, 6, 4, 0},
        {0x0020, 6, 20, 0},
        {0x0020, 6, 36, 0},
        {0x0000, 6, 52, 0},
        {0x0020, 5, 68, 1},
    },
};

SaturnSpriteFrame8 g_Stage16SpriteBank21Frame37 = {
    {0x0800, 0x0000},
    {
        {0x0000, 4, 16, 7},
        {0x0000, 2, -3, 40},
        {0x0020, 6, 4, 0},
        {0x0020, 6, 20, 0},
        {0x0020, 6, 36, 0},
        {0x0000, 6, 52, 0},
        {0x0000, 6, 68, 0},
        {0x0020, 5, 84, 1},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank21Frame38 = {
    {0x0900, 0x0000},
    {
        {0x0000, 4, 16, 7},
        {0x0000, 2, -3, 40},
        {0x0020, 6, 4, 0},
        {0x0020, 6, 20, 0},
        {0x0020, 6, 36, 0},
        {0x0000, 6, 52, 0},
        {0x0000, 6, 68, 0},
        {0x0000, 6, 84, 0},
        {0x0020, 5, 100, 1},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame39 = {
    {0x0700, 0x0000},
    {
        {0x0000, 6, 16, 12},
        {0x0000, 0, 0, 13},
        {0x0000, 2, -13, 9},
        {0x0000, 18, 0, 14},
        {0x0000, 0, 0, 14},
        {0x0000, -20, 0, 14},
        {0x0000, -40, 0, 15},
    },
};

SaturnSpriteFrame6 g_Stage16SpriteBank21Frame40 = {
    {0x0600, 0x0000},
    {
        {0x0000, 1, -6, 17},
        {0x0000, -2, 16, 5},
        {0x0000, -10, -9, 18},
        {0x0000, -3, -1, 19},
        {0x0000, -22, -17, 19},
        {0x0000, -38, -31, 20},
    },
};

SaturnSpriteFrame5 g_Stage16SpriteBank21Frame41 = {
    {0x0500, 0x0000},
    {
        {0x0000, 5, 16, 0},
        {0x0000, 5, -16, 0},
        {0x0000, 4, -32, 1},
        {0x0000, 1, 16, 21},
        {0x0000, 2, -6, 41},
    },
};

SaturnSpriteFrame7 g_Stage16SpriteBank21Frame42 = {
    {0x0700, 0x0000},
    {
        {0x0000, 5, -24, 0},
        {0x0000, 5, -48, 0},
        {0x0000, 5, -38, 0},
        {0x0000, 4, -64, 1},
        {0x0000, 1, 16, 21},
        {0x0000, 2, -8, 22},
        {0x0000, 4, -25, 23},
    },
};

SaturnSpriteFrame8 g_Stage16SpriteBank21Frame43 = {
    {0x0800, 0x0000},
    {
        {0x0000, 5, -17, 0},
        {0x0000, 5, -33, 0},
        {0x0000, 5, -49, 0},
        {0x0000, 5, -65, 0},
        {0x0000, 4, -80, 1},
        {0x0000, 1, 16, 21},
        {0x0000, 2, -8, 22},
        {0x0000, 4, -25, 23},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank21Frame44 = {
    {0x0900, 0x0000},
    {
        {0x0000, 5, -22, 0},
        {0x0000, 5, -32, 0},
        {0x0000, 5, -48, 0},
        {0x0000, 5, -64, 0},
        {0x0000, 5, -80, 0},
        {0x0000, 4, -96, 1},
        {0x0000, 1, 16, 21},
        {0x0000, 2, -8, 22},
        {0x0000, 4, -25, 23},
    },
};

SaturnSpriteFrame10 g_Stage16SpriteBank21Frame45 = {
    {0x0A00, 0x0000},
    {
        {0x0000, 5, -22, 0},
        {0x0000, 5, -32, 0},
        {0x0000, 5, -48, 0},
        {0x0000, 5, -64, 0},
        {0x0000, 5, -80, 0},
        {0x0000, 5, -96, 0},
        {0x0000, 4, -112, 1},
        {0x0000, 1, 16, 21},
        {0x0000, 2, -8, 22},
        {0x0000, 4, -25, 23},
    },
};

SaturnSpriteFrame4 g_Stage16SpriteBank21Frame46 = {
    {0x0400, 0x0000},
    {
        {0x0010, -22, 24, 14},
        {0x0010, -40, 24, 14},
        {0x0010, -58, 24, 14},
        {0x0010, 0, 24, 15},
    },
};

SaturnSpriteFrame4 g_Stage16SpriteBank21Frame47 = {
    {0x0400, 0x0000},
    {
        {0x0010, -48, 6, 10},
        {0x0010, -33, 11, 10},
        {0x0010, -19, 16, 10},
        {0x0010, 0, 23, 11},
    },
};

SaturnSpriteFrame4 g_Stage16SpriteBank21Frame48 = {
    {0x0400, 0x0000},
    {
        {0x0030, -39, -6, 19},
        {0x0030, -33, -1, 19},
        {0x0030, -18, 11, 19},
        {0x0030, -5, 23, 20},
    },
};

SaturnSpriteFrame5 g_Stage16SpriteBank21Frame49 = {
    {0x0500, 0x0000},
    {
        {0x0030, -2, 24, 37},
        {0x0030, -9, 13, 36},
        {0x0030, -15, 3, 36},
        {0x0030, -22, -8, 36},
        {0x0030, -29, -19, 36},
    },
};

SaturnSpriteFrame5 g_Stage16SpriteBank21Frame50 = {
    {0x0500, 0x0000},
    {
        {0x0020, 2, 26, 1},
        {0x0020, 3, 10, 0},
        {0x0020, 3, -6, 0},
        {0x0020, 3, -22, 0},
        {0x0020, 3, -26, 0},
    },
};

SaturnSpriteFrame5 g_Stage16SpriteBank21Frame51 = {
    {0x0500, 0x0000},
    {
        {0x0020, 0, 24, 37},
        {0x0020, 7, 13, 36},
        {0x0020, 13, 3, 36},
        {0x0020, 20, -8, 36},
        {0x0020, 27, -19, 36},
    },
};

SaturnSpriteFrame4 g_Stage16SpriteBank21Frame52 = {
    {0x0400, 0x0000},
    {
        {0x0020, 38, -5, 19},
        {0x0020, 32, 0, 19},
        {0x0020, 17, 12, 19},
        {0x0020, 3, 24, 20},
    },
};

SaturnSpriteFrame4 g_Stage16SpriteBank21Frame53 = {
    {0x0400, 0x0000},
    {
        {0x0000, 49, 5, 10},
        {0x0000, 20, 15, 10},
        {0x0000, 35, 10, 10},
        {0x0000, 1, 23, 11},
    },
};

SaturnSpriteFrame4 g_Stage16SpriteBank21Frame54 = {
    {0x0400, 0x0000},
    {
        {0x0000, 56, 0, 14},
        {0x0000, 38, 0, 14},
        {0x0000, 20, 0, 14},
        {0x0000, 0, 0, 15},
    },
};

SaturnSpriteFrame4 g_Stage16SpriteBank21Frame55 = {
    {0x0400, 0x0000},
    {
        {0x0020, 53, 44, 10},
        {0x0020, 40, 39, 10},
        {0x0020, 21, 32, 10},
        {0x0020, 2, 25, 11},
    },
};

SaturnSpriteFrame4 g_Stage16SpriteBank21Frame56 = {
    {0x0400, 0x0000},
    {
        {0x0000, 41, 56, 19},
        {0x0000, 30, 47, 19},
        {0x0000, 15, 35, 19},
        {0x0000, 4, 25, 20},
    },
};

SaturnSpriteFrame4 g_Stage16SpriteBank21Frame57 = {
    {0x0400, 0x0000},
    {
        {0x0000, 26, 68, 36},
        {0x0000, 8, 38, 36},
        {0x0000, 17, 53, 36},
        {0x0000, 0, 24, 37},
    },
};

SaturnSpriteFrame5 g_Stage16SpriteBank21Frame58 = {
    {0x0500, 0x0000},
    {
        {0x0000, 3, 22, 1},
        {0x0000, 4, 38, 0},
        {0x0000, 4, 54, 0},
        {0x0000, 4, 65, 0},
        {0x0000, 4, 78, 0},
    },
};

SaturnSpriteFrame4 g_Stage16SpriteBank21Frame59 = {
    {0x0400, 0x0000},
    {
        {0x0010, -26, 68, 36},
        {0x0010, -8, 38, 36},
        {0x0010, -17, 53, 36},
        {0x0010, 0, 24, 37},
    },
};

SaturnSpriteFrame4 g_Stage16SpriteBank21Frame60 = {
    {0x0400, 0x0000},
    {
        {0x0010, -39, 56, 19},
        {0x0010, -28, 47, 19},
        {0x0010, -13, 35, 19},
        {0x0010, -2, 25, 20},
    },
};

SaturnSpriteFrame4 g_Stage16SpriteBank21Frame61 = {
    {0x0400, 0x0000},
    {
        {0x0030, -51, 43, 10},
        {0x0030, -37, 38, 10},
        {0x0030, -19, 32, 10},
        {0x0030, 0, 25, 11},
    },
};

SaturnSpriteFrame3 g_Stage16SpriteBank21Frame62 = {
    {0x0300, 0x0000},
    {
        {0x0000, 3, 16, 7},
        {0x0000, -1, 1, 13},
        {0x0000, 1, -12, 9},
    },
};

SaturnSpriteFrame4 g_Stage16SpriteBank21Frame63 = {
    {0x0400, 0x0000},
    {
        {0x0000, 2, -5, 22},
        {0x0000, 5, -22, 23},
        {0x0000, -12, -1, 18},
        {0x0000, 3, 16, 24},
    },
};

SaturnSpriteFrame4 g_Stage16SpriteBank21Frame64 = {
    {0x0400, 0x0000},
    {
        {0x0000, 2, -4, 22},
        {0x0000, 5, -21, 23},
        {0x0000, -12, 0, 18},
        {0x0000, 3, 16, 24},
    },
};

SaturnSpriteFrameHeader* g_Stage16SpriteBank21Frames[65] = {
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame0,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame1,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame2,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame3,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame4,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame5,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame6,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame7,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame8,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame9,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame10,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame11,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame12,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame13,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame14,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame15,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame16,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame17,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame18,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame19,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame20,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame21,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame22,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame23,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame24,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame25,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame26,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame27,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame28,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame29,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame30,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame31,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame32,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame33,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame34,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame35,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame36,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame37,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame38,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame39,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame40,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame41,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame42,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame43,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame44,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame45,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame46,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame47,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame48,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame49,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame50,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame51,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame52,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame53,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame54,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame55,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame56,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame57,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame58,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame59,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame60,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame61,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame62,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame63,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank21Frame64,
};

SaturnSpriteImage g_Stage16SpriteBank21Images[43] = {
    {4, 8, 0x0000},   {4, 8, 0x0008},   {12, 16, 0x0010}, {8, 7, 0x0040},
    {12, 15, 0x0050}, {12, 8, 0x0080},  {12, 8, 0x0098},  {20, 8, 0x00B0},
    {16, 8, 0x00D8},  {8, 6, 0x00F8},   {12, 4, 0x0104},  {12, 5, 0x0110},
    {16, 8, 0x0120},  {20, 8, 0x0140},  {12, 1, 0x0168},  {12, 2, 0x016C},
    {20, 7, 0x0174},  {12, 15, 0x0198}, {8, 4, 0x01C8},   {12, 8, 0x01D0},
    {12, 7, 0x01E8},  {16, 8, 0x0200},  {12, 16, 0x0220}, {4, 2, 0x0250},
    {20, 8, 0x0254},  {12, 16, 0x027C}, {8, 7, 0x02AC},   {16, 8, 0x02BC},
    {12, 8, 0x02DC},  {12, 7, 0x02F4},  {12, 16, 0x030C}, {8, 7, 0x033C},
    {16, 8, 0x034C},  {12, 7, 0x036C},  {12, 14, 0x0384}, {4, 4, 0x03B0},
    {8, 8, 0x03B4},   {8, 8, 0x03C4},   {20, 15, 0x03D4}, {20, 14, 0x0420},
    {12, 15, 0x0468}, {12, 14, 0x0498}, {0, 0, 0x04C4},
};
