// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[27][16];
    u16 padding[1];
} g_Stage16SpriteBank24Palette = {
    0x001B,
    {
        {
            0x8920,
            0xFFFF,
            0xE739,
            0xDEF7,
            0xD6B5,
            0xD294,
            0xCA52,
            0xC210,
            0xBDEF,
            0xB5AD,
            0xB18C,
            0xA94A,
            0xA108,
            0x9CE7,
            0x94A5,
            0x9084,
        },
        {
            0x88E0,
            0xE739,
            0xDAD6,
            0xCE73,
            0xC631,
            0xB9CE,
            0xB18C,
            0xA529,
            0x9CE7,
            0xC631,
            0xAD6B,
            0x98C6,
            0xE739,
            0xB9CE,
            0x9084,
            0xA108,
        },
        {
            0x88E0,
            0xEF7B,
            0xE318,
            0xD6B5,
            0xCA52,
            0xC1EF,
            0xB58C,
            0xA929,
            0xA0E6,
            0xB99B,
            0xA914,
            0x988D,
            0xEF66,
            0xD205,
            0xB8A4,
            0x9084,
        },
        {
            0x88E0,
            0xF739,
            0xE6D5,
            0xDA72,
            0xCE0F,
            0xC1AC,
            0xB549,
            0xA8E6,
            0x9C83,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
        },
        {
            0x88E0,
            0xFFFF,
            0xE739,
            0xD6B5,
            0xCA52,
            0xBDEE,
            0xB16B,
            0xA507,
            0x98A4,
            0xA91F,
            0x9897,
            0x880F,
            0xFFE4,
            0xFE03,
            0xFC22,
            0x8000,
        },
        {
            0x88E0,
            0xD231,
            0xC9EF,
            0xC5AD,
            0xBD6B,
            0xB94A,
            0xB108,
            0xACC6,
            0xA8A5,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
        },
        {
            0x80C0,
            0xFD9F,
            0xED5F,
            0xDD1F,
            0xCCDF,
            0xB89F,
            0xA85F,
            0x981F,
            0x881F,
            0x841B,
            0x8416,
            0x8412,
            0x800D,
            0x8009,
            0x8004,
            0x8000,
        },
        {
            0x8940,
            0xF7BD,
            0xDA52,
            0xD210,
            0xCDCE,
            0xC58C,
            0xC14A,
            0xBD29,
            0xB4E7,
            0xACC6,
            0xA4A5,
            0x9C84,
            0x9463,
            0x8C42,
            0x8421,
            0x8000,
        },
        {
            0x80C0,
            0x9E1F,
            0x897F,
            0x855F,
            0x853F,
            0x811D,
            0x80FA,
            0x80D7,
            0x80B4,
            0x8091,
            0x806E,
            0x804B,
            0x8048,
            0x8025,
            0x8002,
            0x8000,
        },
        {
            0x8940,
            0xF7BD,
            0xDA52,
            0xD210,
            0xCDCE,
            0xC58C,
            0xC14A,
            0xBD29,
            0xB4E7,
            0xACC6,
            0xA4A5,
            0x9C84,
            0x9463,
            0x8C42,
            0x8421,
            0x8000,
        },
        {
            0x88E0,
            0xDA52,
            0xCDEF,
            0xC58C,
            0xBD29,
            0xB4E7,
            0xA4A5,
            0x9463,
            0x8821,
            0xCDCE,
            0xAD6B,
            0xB4E7,
            0xC58C,
            0xB4E7,
            0x9C84,
            0xACC6,
        },
        {
            0x88E0,
            0xEAF7,
            0xDA73,
            0xCDEF,
            0xC16B,
            0xB4E7,
            0xA4A5,
            0x9863,
            0x8C42,
            0xA25A,
            0x9975,
            0x90B0,
            0xFEFF,
            0xCDDF,
            0x9CDF,
            0x8000,
        },
        {
            0x88E0,
            0xF6D6,
            0xE652,
            0xD5CE,
            0xC56B,
            0xB4E7,
            0xA884,
            0x9C63,
            0x9442,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
        },
        {
            0x88E0,
            0xFFFF,
            0xE294,
            0xD1EF,
            0xC16B,
            0xB4E7,
            0xA8A5,
            0x9C84,
            0x9463,
            0x83BF,
            0x81F7,
            0x804F,
            0xFE1F,
            0xC05F,
            0x801F,
            0x8000,
        },
        {
            0x88E0,
            0xD16C,
            0xC52A,
            0xBD09,
            0xB4E7,
            0xACA6,
            0xA484,
            0x9C63,
            0x9442,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
        },
        {
            0x88A0,
            0x83FF,
            0x837F,
            0x82FF,
            0x827F,
            0x821F,
            0x819F,
            0x811F,
            0x809F,
            0x801F,
            0x801A,
            0x8015,
            0x8010,
            0x800A,
            0x8005,
            0x8000,
        },
        {
            0x8920,
            0xFFFF,
            0xE739,
            0xDEF7,
            0xD6B5,
            0xD294,
            0xCA52,
            0xC210,
            0xBDEF,
            0xB5AD,
            0xB18C,
            0xA94A,
            0xA108,
            0x9CE7,
            0x94A5,
            0x9084,
        },
        {
            0x80C0,
            0x9E1F,
            0x897F,
            0x855F,
            0x853F,
            0x811D,
            0x80FA,
            0x80D7,
            0x80B4,
            0x8091,
            0x806E,
            0x804B,
            0x8048,
            0x8025,
            0x8002,
            0x8000,
        },
        {
            0x80C0,
            0x9E1F,
            0x897F,
            0x855F,
            0x853F,
            0x811D,
            0x80FA,
            0x80D7,
            0x80B4,
            0x8091,
            0x806E,
            0x804B,
            0x8048,
            0x8025,
            0x8002,
            0x8000,
        },
        {
            0x88E0,
            0x8D7F,
            0x893C,
            0x8918,
            0x84F4,
            0x84B0,
            0x808C,
            0x8068,
            0x8045,
            0x91BF,
            0x88F5,
            0x804A,
            0x897F,
            0x84D2,
            0x8045,
            0x8027,
        },
        {
            0x88E0,
            0x8D7F,
            0x893C,
            0x8918,
            0x84F4,
            0x84B0,
            0x808C,
            0x8068,
            0x8045,
            0xF7AF,
            0xF629,
            0xF4C4,
            0xB36A,
            0xA247,
            0x9544,
            0x8000,
        },
        {
            0x88E0,
            0x9DDA,
            0x895C,
            0x8918,
            0x88F4,
            0x88D0,
            0x888C,
            0x8868,
            0x8845,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
        },
        {
            0x88E0,
            0x9E1F,
            0x897F,
            0x853C,
            0x84F8,
            0x80D5,
            0x808F,
            0x804A,
            0x8025,
            0xFFE0,
            0xFE00,
            0xFC00,
            0x83E0,
            0x86A0,
            0x8940,
            0x8000,
        },
        {
            0x88E0,
            0x90F1,
            0x8CD0,
            0x88AF,
            0x848F,
            0x846C,
            0x846A,
            0x8447,
            0x8445,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
        },
        {
            0x80E0,
            0xFFE0,
            0xFF60,
            0xFEC0,
            0xFE40,
            0xFDA0,
            0xFD20,
            0xFC80,
            0xFC00,
            0xEC00,
            0xD800,
            0xC800,
            0xB400,
            0xA400,
            0x9000,
            0x8000,
        },
        {
            0x8940,
            0xF7BD,
            0xDA52,
            0xD210,
            0xCDCE,
            0xC58C,
            0xC14A,
            0xBD29,
            0xB4E7,
            0xACC6,
            0xA4A5,
            0x9C84,
            0x9463,
            0x8C42,
            0x8421,
            0x8000,
        },
        {
            0x8920,
            0xFFFF,
            0xE739,
            0xDEF7,
            0xD6B5,
            0xD294,
            0xCA52,
            0xC210,
            0xBDEF,
            0xB5AD,
            0xB18C,
            0xA94A,
            0xA108,
            0x9CE7,
            0x94A5,
            0x9084,
        },
    },
    {0x0000},
};

SaturnSpriteFrameHeader g_Stage16SpriteBank24Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 3, 0},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame2 = {
    {0x0900, 0x0000},
    {
        {0x0100, 6, -1, 1},
        {0x0100, 8, -1, 2},
        {0x0100, -3, 8, 3},
        {0x0100, -1, 11, 4},
        {0x0100, 13, 5, 5},
        {0x0100, -1, 0, 6},
        {0x0100, 5, 12, 7},
        {0x0100, -4, 9, 8},
        {0x0100, -5, 3, 9},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame3 = {
    {0x0900, 0x0000},
    {
        {0x0200, 6, -1, 1},
        {0x0200, 8, -1, 2},
        {0x0200, -3, 8, 3},
        {0x0200, -1, 11, 4},
        {0x0200, 13, 5, 5},
        {0x0200, -1, 0, 6},
        {0x0200, 5, 12, 7},
        {0x0200, -4, 9, 8},
        {0x0200, -5, 3, 9},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame4 = {
    {0x0900, 0x0000},
    {
        {0x0300, 6, -1, 1},
        {0x0400, 8, -1, 2},
        {0x0300, -3, 8, 3},
        {0x0500, -1, 11, 4},
        {0x0400, 13, 5, 5},
        {0x0400, -1, 0, 6},
        {0x0400, 5, 12, 7},
        {0x0400, -4, 9, 8},
        {0x0400, -5, 3, 9},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame5 = {
    {0x0900, 0x0000},
    {
        {0x0300, 6, -1, 1},
        {0x0400, 13, 11, 10},
        {0x0400, 8, -1, 2},
        {0x0300, -3, 8, 3},
        {0x0500, -1, 11, 4},
        {0x0400, -1, 0, 6},
        {0x0400, 5, 12, 7},
        {0x0400, -4, 9, 8},
        {0x0400, -5, 3, 9},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame6 = {
    {0x0900, 0x0000},
    {
        {0x0300, 6, -1, 1},
        {0x0400, 17, 13, 11},
        {0x0400, 8, -1, 2},
        {0x0300, -3, 8, 3},
        {0x0500, -1, 11, 4},
        {0x0400, -1, 0, 6},
        {0x0400, 5, 12, 7},
        {0x0400, -4, 9, 8},
        {0x0400, -5, 3, 9},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame7 = {
    {0x0900, 0x0000},
    {
        {0x0300, 6, -1, 1},
        {0x0400, 17, 10, 12},
        {0x0400, 8, -1, 2},
        {0x0300, -3, 8, 3},
        {0x0500, -1, 11, 4},
        {0x0400, -1, 0, 6},
        {0x0400, 5, 12, 7},
        {0x0400, -4, 9, 8},
        {0x0400, -5, 3, 9},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame8 = {
    {0x0900, 0x0000},
    {
        {0x0300, 6, -1, 1},
        {0x0400, 16, 3, 13},
        {0x0400, 8, -1, 2},
        {0x0300, -3, 8, 3},
        {0x0500, -1, 11, 4},
        {0x0400, -1, 0, 6},
        {0x0400, 5, 12, 7},
        {0x0400, -4, 9, 8},
        {0x0400, -5, 3, 9},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame9 = {
    {0x0900, 0x0000},
    {
        {0x0300, 10, -4, 14},
        {0x0400, 13, 5, 5},
        {0x0400, 12, -4, 15},
        {0x0300, -3, 8, 3},
        {0x0500, -1, 11, 4},
        {0x0400, -1, 0, 6},
        {0x0400, 5, 12, 7},
        {0x0400, -4, 9, 8},
        {0x0400, -5, 3, 9},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame10 = {
    {0x0900, 0x0000},
    {
        {0x0300, 3, -12, 16},
        {0x0400, 13, 5, 5},
        {0x0400, 6, -12, 17},
        {0x0300, -3, 8, 3},
        {0x0500, -1, 11, 4},
        {0x0400, -1, 0, 6},
        {0x0400, 5, 12, 7},
        {0x0400, -4, 9, 8},
        {0x0400, -5, 3, 9},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame11 = {
    {0x0900, 0x0000},
    {
        {0x0300, 3, 4, 18},
        {0x0400, 13, 10, 10},
        {0x0300, -3, 7, 3},
        {0x0500, -1, 10, 4},
        {0x0400, -1, -1, 6},
        {0x0400, 5, 11, 7},
        {0x0400, -4, 8, 8},
        {0x0400, 6, 4, 19},
        {0x0400, -4, 2, 20},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame12 = {
    {0x0900, 0x0000},
    {
        {0x0300, 3, 9, 21},
        {0x0400, 16, 9, 11},
        {0x0500, 2, 10, 22},
        {0x0300, -4, 5, 3},
        {0x0400, -2, -4, 6},
        {0x0400, -6, 4, 23},
        {0x0400, 3, 9, 24},
        {0x0400, 6, 10, 25},
        {0x0400, -5, -1, 26},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame13 = {
    {0x0900, 0x0000},
    {
        {0x0400, 1, 3, 21},
        {0x0400, 19, 5, 27},
        {0x0400, -5, -1, 3},
        {0x0400, 1, 6, 28},
        {0x0400, -3, -11, 6},
        {0x0400, -6, -2, 23},
        {0x0400, 3, 4, 29},
        {0x0400, 5, 4, 25},
        {0x0400, -6, -8, 30},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame14 = {
    {0x0900, 0x0000},
    {
        {0x0300, 0, -8, 21},
        {0x0400, 14, -9, 11},
        {0x0300, -5, -11, 3},
        {0x0300, 0, -7, 29},
        {0x0400, -4, -22, 6},
        {0x0400, -7, -14, 23},
        {0x0400, 2, -5, 28},
        {0x0400, 4, -7, 25},
        {0x0400, -7, -19, 26},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame15 = {
    {0x0900, 0x0000},
    {
        {0x0300, 3, -22, 1},
        {0x0400, 9, -18, 5},
        {0x0400, 5, -22, 2},
        {0x0300, -6, -12, 3},
        {0x0500, 2, -7, 29},
        {0x0400, -4, -21, 6},
        {0x0400, -8, -13, 23},
        {0x0400, 0, -8, 22},
        {0x0400, -8, -18, 9},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame16 = {
    {0x0900, 0x0000},
    {
        {0x0300, 3, -8, 1},
        {0x0400, 9, -4, 5},
        {0x0400, 5, -8, 2},
        {0x0300, -6, 2, 3},
        {0x0500, 2, 7, 29},
        {0x0400, -4, -7, 6},
        {0x0400, -8, 1, 23},
        {0x0400, 0, 6, 22},
        {0x0400, -8, -4, 9},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame17 = {
    {0x0900, 0x0000},
    {
        {0x0300, 7, -10, 14},
        {0x0400, 10, 4, 10},
        {0x0400, 9, -10, 15},
        {0x0300, -5, 2, 3},
        {0x0500, -1, 7, 22},
        {0x0400, -4, -6, 6},
        {0x0400, 0, 7, 24},
        {0x0400, -8, 1, 23},
        {0x0400, -8, -3, 31},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame18 = {
    {0x0900, 0x0000},
    {
        {0x0300, 1, -19, 16},
        {0x0400, 14, 5, 11},
        {0x0400, 4, -19, 17},
        {0x0500, -2, 7, 24},
        {0x0300, -6, 2, 3},
        {0x0400, -4, -6, 6},
        {0x0400, 0, 7, 22},
        {0x0400, -7, 3, 32},
        {0x0400, -9, -3, 33},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame19 = {
    {0x0900, 0x0000},
    {
        {0x0300, 2, -2, 18},
        {0x0400, 15, 1, 12},
        {0x0300, -7, 1, 3},
        {0x0500, 0, 6, 22},
        {0x0400, -4, -7, 6},
        {0x0400, 2, 7, 29},
        {0x0400, -6, 2, 32},
        {0x0400, 5, -2, 19},
        {0x0400, -7, -4, 26},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame20 = {
    {0x0900, 0x0000},
    {
        {0x0300, 0, 5, 21},
        {0x0300, -6, 1, 3},
        {0x0500, 1, 6, 22},
        {0x0400, -4, -8, 6},
        {0x0400, 1, 7, 29},
        {0x0400, -7, 1, 32},
        {0x0400, 14, -5, 13},
        {0x0400, 3, 6, 25},
        {0x0400, -7, -5, 30},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame21 = {
    {0x0900, 0x0000},
    {
        {0x0300, 4, -14, 34},
        {0x0300, 3, -8, 1},
        {0x0400, 8, -4, 5},
        {0x0400, 5, -8, 2},
        {0x0500, 3, 7, 29},
        {0x0400, -4, -7, 6},
        {0x0400, -7, -4, 26},
        {0x0400, -11, -4, 35},
        {0x0400, 0, 6, 24},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame22 = {
    {0x0900, 0x0000},
    {
        {0x0300, 2, -16, 34},
        {0x0300, 7, -11, 14},
        {0x0400, 9, 2, 10},
        {0x0400, 9, -11, 15},
        {0x0500, 3, 7, 29},
        {0x0400, -4, -7, 6},
        {0x0400, -8, -4, 31},
        {0x0400, -11, -5, 35},
        {0x0400, 0, 6, 24},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame23 = {
    {0x0900, 0x0000},
    {
        {0x0300, 4, -10, 14},
        {0x0400, 6, -10, 15},
        {0x0300, -13, -12, 36},
        {0x0400, -7, -6, 6},
        {0x0500, -1, 6, 29},
        {0x0400, -2, 6, 22},
        {0x0400, -7, 4, 37},
        {0x0400, 7, 3, 10},
        {0x0400, -12, -3, 33},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame24 = {
    {0x0900, 0x0000},
    {
        {0x0300, -9, -18, 16},
        {0x0400, -5, -18, 17},
        {0x0400, 7, 2, 11},
        {0x0500, -7, 5, 22},
        {0x0400, -24, -8, 38},
        {0x0400, -11, -5, 39},
        {0x0400, -4, 6, 29},
        {0x0400, -11, 6, 37},
        {0x0400, -20, 0, 40},
    },
};

SaturnSpriteFrame10 g_Stage16SpriteBank24Frame25 = {
    {0x0A00, 0x0000},
    {
        {0x0300, -12, -17, 16},
        {0x0400, -7, -18, 17},
        {0x0400, 4, 1, 11},
        {0x0500, -10, 4, 24},
        {0x0400, -22, 4, 41},
        {0x0400, -13, -5, 39},
        {0x0300, -5, 7, 28},
        {0x0400, -8, 4, 42},
        {0x0400, -21, 0, 9},
        {0x0600, -32, -2, 43},
    },
};

SaturnSpriteFrame11 g_Stage16SpriteBank24Frame26 = {
    {0x0B00, 0x0000},
    {
        {0x0300, -14, -14, 16},
        {0x0400, -8, -17, 17},
        {0x0400, 2, -4, 12},
        {0x0500, -5, 0, 44},
        {0x0400, -12, 8, 45},
        {0x0400, -13, -3, 46},
        {0x0400, 0, -3, 47},
        {0x0300, -8, 5, 42},
        {0x0400, -8, 13, 48},
        {0x0400, -20, 3, 20},
        {0x0600, -32, -2, 43},
    },
};

SaturnSpriteFrame10 g_Stage16SpriteBank24Frame27 = {
    {0x0A00, 0x0000},
    {
        {0x0300, -11, 0, 18},
        {0x0400, 4, -4, 12},
        {0x0500, 0, 0, 49},
        {0x0400, -5, 6, 50},
        {0x0400, -11, -3, 46},
        {0x0400, -2, -1, 44},
        {0x0300, -6, 5, 42},
        {0x0400, -5, 9, 51},
        {0x0400, -5, 2, 19},
        {0x0400, -18, 3, 26},
    },
};

SaturnSpriteFrame10 g_Stage16SpriteBank24Frame28 = {
    {0x0A00, 0x0000},
    {
        {0x0300, -8, 8, 21},
        {0x0400, 8, -3, 12},
        {0x0500, -1, 2, 52},
        {0x0400, -9, 7, 45},
        {0x0400, -7, -3, 46},
        {0x0400, -2, 2, 22},
        {0x0400, -4, 6, 42},
        {0x0400, -7, 12, 51},
        {0x0400, -2, 10, 25},
        {0x0400, -14, 3, 30},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame29 = {
    {0x0900, 0x0000},
    {
        {0x0400, 15, -7, 13},
        {0x0300, -3, 6, 21},
        {0x0500, -1, 4, 24},
        {0x0400, -13, 4, 41},
        {0x0400, -4, -5, 39},
        {0x0300, 4, 7, 28},
        {0x0400, 1, 5, 42},
        {0x0400, 2, 9, 25},
        {0x0400, -11, 0, 26},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame30 = {
    {0x0900, 0x0000},
    {
        {0x0300, 1, 6, 21},
        {0x0400, 14, -5, 13},
        {0x0500, 0, 6, 24},
        {0x0300, -9, 0, 3},
        {0x0400, -4, -7, 6},
        {0x0400, 1, 7, 29},
        {0x0400, -6, 3, 32},
        {0x0400, 3, 7, 25},
        {0x0400, -8, -4, 31},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame31 = {
    {0x0900, 0x0000},
    {
        {0x0300, -6, 0, 3},
        {0x0300, 3, -8, 1},
        {0x0400, 9, -4, 5},
        {0x0400, 5, -8, 2},
        {0x0500, 2, 7, 29},
        {0x0400, -4, -7, 6},
        {0x0400, 0, 6, 22},
        {0x0400, -9, 1, 23},
        {0x0400, -7, -4, 20},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame32 = {
    {0x0900, 0x0000},
    {
        {0x0300, 7, -11, 14},
        {0x0500, 1, 5, 29},
        {0x0400, 10, 3, 10},
        {0x0400, 9, -11, 15},
        {0x0300, -6, 1, 3},
        {0x0400, -4, -6, 53},
        {0x0400, 0, 5, 22},
        {0x0400, -8, 1, 23},
        {0x0400, -7, -3, 26},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame33 = {
    {0x0900, 0x0000},
    {
        {0x0300, 1, -20, 16},
        {0x0500, 2, 7, 29},
        {0x0400, 14, 4, 11},
        {0x0400, 4, -20, 17},
        {0x0300, -6, 2, 3},
        {0x0400, -4, -7, 6},
        {0x0400, -7, 2, 32},
        {0x0400, 0, 6, 22},
        {0x0400, -7, -4, 30},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame34 = {
    {0x0900, 0x0000},
    {
        {0x0300, 2, -2, 18},
        {0x0500, 1, 5, 29},
        {0x0400, 15, 1, 12},
        {0x0300, -7, 2, 3},
        {0x0400, -4, -6, 53},
        {0x0400, 0, 5, 22},
        {0x0400, -7, 2, 32},
        {0x0400, 5, -2, 19},
        {0x0400, -7, -3, 26},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame35 = {
    {0x0900, 0x0000},
    {
        {0x0400, 14, -4, 13},
        {0x0300, 0, 6, 21},
        {0x0300, -6, 1, 3},
        {0x0500, 2, 7, 29},
        {0x0400, -4, -7, 6},
        {0x0400, -8, 1, 32},
        {0x0400, 0, 6, 22},
        {0x0400, 3, 7, 25},
        {0x0400, -8, -4, 31},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame36 = {
    {0x0900, 0x0000},
    {
        {0x0300, 3, -8, 1},
        {0x0500, 1, 5, 29},
        {0x0400, 9, -4, 5},
        {0x0400, 5, -8, 2},
        {0x0300, -6, 0, 3},
        {0x0400, -4, -6, 53},
        {0x0400, 0, 5, 22},
        {0x0400, -9, 1, 23},
        {0x0400, -9, -3, 33},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame37 = {
    {0x0900, 0x0000},
    {
        {0x0300, 7, -11, 14},
        {0x0500, 2, 7, 29},
        {0x0400, 10, 3, 10},
        {0x0400, 9, -11, 15},
        {0x0300, -6, 1, 3},
        {0x0400, -4, -7, 6},
        {0x0400, 0, 6, 22},
        {0x0400, -8, 1, 23},
        {0x0400, -9, -4, 40},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame38 = {
    {0x0900, 0x0000},
    {
        {0x0300, 1, -20, 16},
        {0x0500, 1, 5, 29},
        {0x0400, 14, 4, 11},
        {0x0400, 4, -20, 17},
        {0x0300, -6, 2, 3},
        {0x0400, -4, -6, 53},
        {0x0400, 0, 5, 22},
        {0x0400, -7, 2, 32},
        {0x0400, -9, -3, 33},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame39 = {
    {0x0900, 0x0000},
    {
        {0x0300, 2, -2, 18},
        {0x0500, 2, 7, 29},
        {0x0400, 15, 1, 12},
        {0x0300, -7, 2, 3},
        {0x0400, -4, -7, 6},
        {0x0400, 0, 6, 22},
        {0x0400, -7, 2, 32},
        {0x0400, 5, -2, 19},
        {0x0400, -8, -4, 31},
    },
};

SaturnSpriteFrame9 g_Stage16SpriteBank24Frame40 = {
    {0x0900, 0x0000},
    {
        {0x0300, 0, 6, 21},
        {0x0400, 14, -4, 13},
        {0x0300, -6, 1, 3},
        {0x0500, 1, 5, 29},
        {0x0400, -4, -6, 53},
        {0x0400, 0, 5, 22},
        {0x0400, -8, 1, 32},
        {0x0400, 3, 7, 25},
        {0x0400, -8, -3, 9},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame41 = {
    {0x0100, 0x0000},
    {
        {0x0100, 3, 0, 54},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame42 = {
    {0x0100, 0x0000},
    {
        {0x0100, 3, 0, 55},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame43 = {
    {0x0100, 0x0000},
    {
        {0x0100, 3, 1, 56},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame44 = {
    {0x0100, 0x0000},
    {
        {0x0100, 3, 1, 57},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame45 = {
    {0x0100, 0x0000},
    {
        {0x0100, 4, 1, 58},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame46 = {
    {0x0100, 0x0000},
    {
        {0x0100, 1, 0, 59},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame47 = {
    {0x0100, 0x0000},
    {
        {0x0100, 3, 1, 60},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame48 = {
    {0x0100, 0x0000},
    {
        {0x0100, 2, 2, 61},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame49 = {
    {0x0100, 0x0000},
    {
        {0x0100, 0, 1, 62},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame50 = {
    {0x0100, 0x0000},
    {
        {0x0100, 2, 0, 63},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame51 = {
    {0x0100, 0x0000},
    {
        {0x0100, 2, -1, 64},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame52 = {
    {0x0100, 0x0000},
    {
        {0x0100, 5, 0, 65},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame53 = {
    {0x0100, 0x0000},
    {
        {0x0100, 2, -2, 66},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame54 = {
    {0x0100, 0x0000},
    {
        {0x0100, 1, 1, 67},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame55 = {
    {0x0100, 0x0000},
    {
        {0x0100, 2, 5, 68},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame56 = {
    {0x0100, 0x0000},
    {
        {0x0100, 3, 1, 9},
    },
};

SaturnSpriteFrame16 g_Stage16SpriteBank24Frame57 = {
    {0x1000, 0x0000},
    {
        {0x0100, 10, -13, 67},
        {0x0100, 16, -9, 68},
        {0x0100, 1, 7, 65},
        {0x0100, 12, 1, 64},
        {0x0100, -4, 2, 63},
        {0x0100, 4, -24, 66},
        {0x0100, 24, 4, 61},
        {0x0100, 2, -11, 59},
        {0x0100, 5, -3, 55},
        {0x0100, 4, 3, 60},
        {0x0100, 4, 11, 58},
        {0x0100, -1, -9, 54},
        {0x0100, -1, -3, 62},
        {0x0100, -3, 5, 56},
        {0x0100, -3, 4, 57},
        {0x0100, -4, -2, 9},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame58 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 3, 69},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank24Frame59 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 3, 70},
    },
};

SaturnSpriteFrameHeader* g_Stage16SpriteBank24Frames[60] = {
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame0,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame1,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame2,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame3,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame4,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame5,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame6,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame7,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame8,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame9,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame10,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame11,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame12,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame13,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame14,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame15,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame16,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame17,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame18,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame19,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame20,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame21,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame22,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame23,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame24,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame25,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame26,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame27,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame28,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame29,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame30,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame31,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame32,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame33,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame34,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame35,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame36,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame37,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame38,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame39,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame40,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame41,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame42,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame43,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame44,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame45,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame46,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame47,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame48,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame49,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame50,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame51,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame52,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame53,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame54,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame55,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame56,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame57,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame58,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank24Frame59,
};

SaturnSpriteImage g_Stage16SpriteBank24Images[72] = {
    {16, 14, 0x0000}, {8, 12, 0x0038},  {8, 12, 0x0050},  {8, 8, 0x0068},
    {8, 5, 0x0078},   {8, 7, 0x0084},   {8, 9, 0x0094},   {8, 5, 0x00A8},
    {8, 8, 0x00B4},   {4, 3, 0x00C4},   {8, 7, 0x00C8},   {12, 5, 0x00D8},
    {12, 7, 0x00E8},  {12, 8, 0x0100},  {12, 8, 0x0118},  {12, 8, 0x0130},
    {8, 15, 0x0148},  {8, 15, 0x0168},  {8, 7, 0x0188},   {8, 7, 0x0198},
    {4, 3, 0x01A8},   {8, 14, 0x01AC},  {8, 8, 0x01C8},   {8, 7, 0x01D8},
    {8, 8, 0x01E8},   {8, 14, 0x01F8},  {4, 3, 0x0214},   {16, 8, 0x0218},
    {8, 10, 0x0238},  {8, 9, 0x024C},   {4, 3, 0x0260},   {4, 3, 0x0264},
    {8, 8, 0x0268},   {4, 3, 0x0278},   {8, 7, 0x027C},   {12, 6, 0x028C},
    {8, 10, 0x02A0},  {8, 10, 0x02B4},  {12, 8, 0x02C8},  {12, 7, 0x02E0},
    {4, 3, 0x02F8},   {12, 8, 0x02FC},  {8, 8, 0x0314},   {8, 14, 0x0324},
    {8, 6, 0x0340},   {8, 10, 0x034C},  {12, 6, 0x0360},  {12, 5, 0x0374},
    {4, 5, 0x0384},   {12, 5, 0x038C},  {12, 8, 0x039C},  {8, 5, 0x03B4},
    {8, 5, 0x03C0},   {8, 9, 0x03CC},   {8, 6, 0x03E0},   {8, 5, 0x03EC},
    {8, 6, 0x03F8},   {8, 5, 0x0404},   {8, 5, 0x0410},   {4, 7, 0x041C},
    {8, 5, 0x0424},   {8, 7, 0x0430},   {4, 4, 0x0440},   {4, 7, 0x0444},
    {8, 3, 0x044C},   {8, 9, 0x0454},   {8, 10, 0x0468},  {8, 8, 0x047C},
    {8, 12, 0x048C},  {20, 14, 0x04A4}, {20, 14, 0x04EC}, {0, 0, 0x0534},
};
