// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[5][16];
    u16 padding[1];
} g_Stage16SpriteBank26Palette = {
    0x4005,
    {
        {
            0x98C8,
            0xFFFF,
            0xFBDA,
            0xF795,
            0xF770,
            0xF34A,
            0xEF05,
            0xEAE0,
            0xEE60,
            0xE9E1,
            0xE961,
            0xE4E2,
            0xE463,
            0xC042,
            0xA021,
            0x8000,
        },
        {
            0xA980,
            0xFFFF,
            0xFFF5,
            0xFFEA,
            0xFFE0,
            0xFF42,
            0xFEA4,
            0xFE06,
            0xFD48,
            0xFCAA,
            0xFC0D,
            0xE40A,
            0xCC07,
            0xB005,
            0x9802,
            0x8000,
        },
        {
            0x98C8,
            0xB5AD,
            0xB58B,
            0xB989,
            0xBD87,
            0xBD65,
            0xC163,
            0xC561,
            0xB120,
            0xB4C0,
            0xB880,
            0xBC40,
            0xC000,
            0xA800,
            0x9400,
            0x8000,
        },
        {
            0x98C8,
            0xA108,
            0xA0E6,
            0xA0E5,
            0xA4E4,
            0xA4C3,
            0xA8C2,
            0xA8C1,
            0xACC0,
            0xA880,
            0xA860,
            0xA420,
            0xA400,
            0x9800,
            0x8C00,
            0x8000,
        },
        {
            0x98C8,
            0x98C6,
            0x98A5,
            0x98A4,
            0x9883,
            0x9882,
            0x9861,
            0x9860,
            0x9860,
            0x9440,
            0x9420,
            0x9400,
            0x9400,
            0x8C00,
            0x8400,
            0x8000,
        },
    },
    {0x0000},
};

SaturnSpriteFrameHeader g_Stage16SpriteBank26Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, -9, 0},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -9, 1},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -10, 2},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -9, 3},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, -8, 4},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -9, 5},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0000, 7, -8, 6},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0000, 10, -8, 7},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0000, 22, -8, 8},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame10 = {
    {0x0100, 0x0000},
    {
        {0x0000, 22, -8, 9},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame11 = {
    {0x0100, 0x0000},
    {
        {0x0000, 18, -8, 10},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame12 = {
    {0x0100, 0x0000},
    {
        {0x0000, 18, -7, 11},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame13 = {
    {0x0100, 0x0000},
    {
        {0x0000, 18, -8, 12},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame14 = {
    {0x0100, 0x0000},
    {
        {0x0000, 18, -7, 13},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame15 = {
    {0x0100, 0x0000},
    {
        {0x0000, 18, -8, 14},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame16 = {
    {0x0100, 0x0000},
    {
        {0x0000, 18, -8, 15},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame17 = {
    {0x0100, 0x0000},
    {
        {0x0100, -15, 21, 16},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame18 = {
    {0x0100, 0x0000},
    {
        {0x0100, -12, 17, 17},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame19 = {
    {0x0100, 0x0000},
    {
        {0x0100, -20, 28, 18},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame20 = {
    {0x0100, 0x0000},
    {
        {0x0100, -19, 22, 19},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame21 = {
    {0x0100, 0x0000},
    {
        {0x0100, -16, 22, 20},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame22 = {
    {0x0100, 0x0000},
    {
        {0x0100, -14, 22, 21},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame23 = {
    {0x0100, 0x0000},
    {
        {0x0100, -17, 23, 22},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame24 = {
    {0x0100, 0x0000},
    {
        {0x0010, -18, -8, 10},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame25 = {
    {0x0100, 0x0000},
    {
        {0x0000, -11, -8, 23},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame26 = {
    {0x0100, 0x0000},
    {
        {0x0000, -6, -6, 24},
    },
};

SaturnSpriteFrame2 g_Stage16SpriteBank26Frame27 = {
    {0x0200, 0x0000},
    {
        {0x0000, -6, -6, 24},
        {0x0100, 0, 0, 25},
    },
};

SaturnSpriteFrame2 g_Stage16SpriteBank26Frame28 = {
    {0x0200, 0x0000},
    {
        {0x0000, -2, -4, 26},
        {0x0100, 1, 0, 27},
    },
};

SaturnSpriteFrame4 g_Stage16SpriteBank26Frame29 = {
    {0x0400, 0x0000},
    {
        {0x0100, -9, -10, 28},
        {0x0110, 9, -10, 28},
        {0x0120, -9, 10, 28},
        {0x0130, 9, 10, 28},
    },
};

SaturnSpriteFrame5 g_Stage16SpriteBank26Frame30 = {
    {0x0500, 0x0000},
    {
        {0x0100, -10, -11, 29},
        {0x0110, 10, -11, 29},
        {0x0130, 10, 11, 29},
        {0x0120, -10, 11, 29},
        {0x0100, 0, 0, 25},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame31 = {
    {0x0100, 0x0000},
    {
        {0x0100, 1, 0, 27},
    },
};

SaturnSpriteFrame4 g_Stage16SpriteBank26Frame32 = {
    {0x0400, 0x0000},
    {
        {0x0100, -9, -10, 28},
        {0x0110, 9, -10, 28},
        {0x0120, -9, 10, 28},
        {0x0130, 9, 10, 28},
    },
};

SaturnSpriteFrame4 g_Stage16SpriteBank26Frame33 = {
    {0x0400, 0x0000},
    {
        {0x0100, -10, -11, 29},
        {0x0110, 10, -11, 29},
        {0x0120, -10, 11, 29},
        {0x0130, 10, 11, 29},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame34 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 0, 30},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame35 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, -3, 31},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame36 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -7, 32},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame37 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, -8, 33},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame38 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, -9, 34},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame39 = {
    {0x0100, 0x0000},
    {
        {0x0200, 18, -8, 10},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame40 = {
    {0x0100, 0x0000},
    {
        {0x0300, 18, -8, 10},
    },
};

SaturnSpriteFrame1 g_Stage16SpriteBank26Frame41 = {
    {0x0100, 0x0000},
    {
        {0x0400, 18, -8, 10},
    },
};

SaturnSpriteFrameHeader* g_Stage16SpriteBank26Frames[42] = {
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame0,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame1,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame2,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame3,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame4,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame5,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame6,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame7,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame8,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame9,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame10,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame11,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame12,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame13,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame14,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame15,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame16,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame17,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame18,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame19,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame20,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame21,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame22,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame23,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame24,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame25,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame26,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame27,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame28,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame29,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame30,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame31,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame32,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame33,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame34,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame35,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame36,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame37,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame38,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame39,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame40,
    (SaturnSpriteFrameHeader*)&g_Stage16SpriteBank26Frame41,
};

SaturnSpriteImage g_Stage16SpriteBank26Images[36] = {
    {8, 14, 0x0000},  {8, 14, 0x001C},  {8, 15, 0x0038},  {8, 14, 0x0058},
    {8, 14, 0x0074},  {8, 14, 0x0090},  {12, 14, 0x00AC}, {16, 15, 0x00D8},
    {28, 14, 0x0114}, {28, 15, 0x0178}, {24, 15, 0x01E4}, {24, 14, 0x0240},
    {24, 15, 0x0294}, {24, 14, 0x02F0}, {24, 15, 0x0344}, {24, 15, 0x03A0},
    {24, 26, 0x03FC}, {20, 20, 0x0498}, {20, 19, 0x04FC}, {28, 26, 0x055C},
    {28, 25, 0x0614}, {32, 27, 0x06C4}, {28, 26, 0x079C}, {20, 15, 0x0854},
    {16, 10, 0x08A0}, {8, 8, 0x08C8},   {12, 8, 0x08D8},  {12, 11, 0x08F0},
    {12, 11, 0x0914}, {12, 11, 0x0938}, {4, 2, 0x095C},   {8, 5, 0x0960},
    {12, 9, 0x096C},  {12, 12, 0x0988}, {12, 15, 0x09AC}, {0, 0, 0x09DC},
};
