REDACTED
#include "sfx.h"
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
    s32 velX;
REDACTED
REDACTED
REDACTED
REDACTED
        self->flags |= FLAG_DEAD;
REDACTED
REDACTED
    if (self->flags & FLAG_DEAD) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            self->flags |= FLAG_DEAD;
            g_api.PlaySfxVolPan(0x6D9, 0x54, 0);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        velX =
            self->ext.generic.unkA0 - (self->posX.i.hi + g_Tilemap.scrollX.i.hi)
            << 0x10;
        if (velX < 0) {
            velX += 0x3F;
REDACTED
        self->velocityX = velX >> 6;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        self->facingLeft = newEntity->facingLeft;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        self->facingLeft = newEntity->facingLeft;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        if (self->animFrameIdx == 4 && self->animFrameDuration == 0) {
            PlaySfxPositional(0x6E2);
REDACTED
                newEntity = AllocEntity(g_Entities + 160, g_Entities + 192);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        if (self->animFrameIdx == 5 && self->animFrameDuration == 0) {
            PlaySfxPositional(0x872);
            PlaySfxPositional(0x87C);
            PlaySfxPositional(SFX_FIRE_SHOT);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
    self->hitboxOffX = *hitbox++;
    self->hitboxOffY = *hitbox++;
REDACTED
REDACTED
}
