// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
SET_END(0x80181d06),
WAIT_FOR_FLAG(0),
SET_POS(60,28),
LOAD_PORTRAIT(0x8018800c,1),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_11(),
SET_SPEED(1),
'!','!',
LINE_BREAK(),
PLAY_SOUND(0x37a),
WAIT_FOR_SOUND(),
'M','o','t','h','e','r','!','!','!',
SET_WAIT(48),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x80188d8c,0),
SET_PORTRAIT(1,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x37b),
WAIT_FOR_SOUND(),
SET_SPEED(4),
'T','h','a','t',' ','v','o','i','c','e','!',' ',
SET_WAIT(16),
SET_SPEED(3),
'A','l','u','c','a','r','d',',',
LINE_BREAK(),
SET_WAIT(16),
SET_FLAG(2),
'i','t','\'','s',' ','y','o','u','!',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x37c),
WAIT_FOR_SOUND(),
SET_SPEED(2),
'I','\'','m',' ','c','o','m','i','n','g',' ','M','o','t','h','e','r','!',
LINE_BREAK(),
SET_WAIT(20),
'I','\'','l','l',' ','s','a','v','e',' ','y','o','u','!','!',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(1,0),
SET_FLAG(1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x37d),
WAIT_FOR_SOUND(),
SET_FLAG(10),
SET_SPEED(4),
'N','o',' ','A','l','u','c','a','r','d','!',
LINE_BREAK(),
SET_WAIT(16),
SET_FLAG(11),
'D','o','n','\'','t',' ','c','o','m','e',' ','h','e','r','e','!',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x37e),
WAIT_FOR_SOUND(),
SET_SPEED(2),
'B','u','t',' ','M','o','t','h','e','r','!',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(1,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x37f),
WAIT_FOR_SOUND(),
SET_SPEED(3),
'I','t','\'','s',' ','a','l','l',' ','r','i','g','h','t','!',
LINE_BREAK(),
SET_WAIT(8),
'I','f',' ','m','y',' ','d','e','a','t','h',' ','c','a','n',' ','s','a','v','e',
LINE_BREAK(),
SET_WAIT(4),
'o','t','h','e','r','s',',',' ',
SET_WAIT(8),
SET_SPEED(4),
'I',' ','g','l','a','d','l','y',
LINE_BREAK(),
SET_WAIT(4),
's','u','r','r','e','n','d','e','r',' ','m','y',' ','l','i','f','e','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x380),
WAIT_FOR_SOUND(),
SET_SPEED(3),
'M','o','t','h','e','r','!',' ','N','o','!','.','.','.',
LINE_BREAK(),
SET_WAIT(16),
'P','l','e','a','s','e','!',' ','N','o','!','.','.','.',
SET_WAIT(56),
NEXT_DIALOG(),
SET_PORTRAIT(1,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x381),
WAIT_FOR_SOUND(),
SET_FLAG(12),
SET_SPEED(3),
'Y','e','s',' ','A','l','u','c','a','r','d','!',' ',
SET_WAIT(32),
SET_SPEED(4),
'W','a','t','c','h',
LINE_BREAK(),
SET_WAIT(4),
'm','e',' ','d','i','e',' ',
SET_WAIT(24),
SET_SPEED(3),
'a','n','d',' ','r','e','m','e','m','b','e','r',
LINE_BREAK(),
SET_WAIT(4),
'a','l','w','a','y','s',' ','m','y',' ','l','a','s','t',' ','w','o','r','d','s',
LINE_BREAK(),
SET_WAIT(4),
't','o',' ','y','o','u','.','.','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x382),
WAIT_FOR_SOUND(),
SET_SPEED(3),
'Y','e','s',' ','M','o','t','h','e','r','.','.','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(1,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x383),
WAIT_FOR_SOUND(),
SET_SPEED(4),
'Y','o','u',' ','m','u','s','t',' ','d','e','s','p','i','s','e',
LINE_BREAK(),
SET_WAIT(4),
'h','u','m','a','n','s','.',' ',
SET_FLAG(13),
SET_WAIT(36),
SET_SPEED(3),
'T','h','e','y',' ','a','r','e',' ','t','o',
LINE_BREAK(),
SET_WAIT(4),
'b','e',' ','y','o','u','r',' ','p','r','e','y','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x384),
WAIT_FOR_SOUND(),
SET_SPEED(2),
'W','h','a','t','?','!','.','.','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(1,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x385),
WAIT_FOR_SOUND(),
SET_SPEED(2),
'B','e','t','t','e','r',' ','f','o','r',' ','t','h','e','m',' ','t','o',
LINE_BREAK(),
SET_WAIT(4),
'd','i','e',' ','t','h','a','n',' ','t','o',' ','l','e','t',' ','t','h','e','m',
LINE_BREAK(),
SET_WAIT(4),
'c','o','m','p','o','u','n','d',' ','t','h','e','i','r',' ','s','i','n','s','.',
LINE_BREAK(),
SET_WAIT(48),
SET_SPEED(3),
'B','e','g','i','n',' ','b','y',' ','s','l','a','y','i','n','g',
LINE_BREAK(),
SET_WAIT(4),
't','h','a','t',' ','o','n','e',' ','o','v','e','r',' ','t','h','e','r','e','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x386),
WAIT_FOR_SOUND(),
SET_SPEED(3),
'N','o','.','.','.','i','t',' ','w','a','s','n','\'','t',
LINE_BREAK(),
SET_WAIT(8),
'l','i','k','e',' ','t','h','i','s','.','.','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(1,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x387),
WAIT_FOR_SOUND(),
SET_SPEED(3),
'W','h','a','t','\'','s',' ','w','r','o','n','g','?',
LINE_BREAK(),
SET_WAIT(24),
'A','l','u','c','a','r','d','?',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x388),
WAIT_FOR_SOUND(),
SET_SPEED(3),
'M','y',' ','m','o','t','h','e','r',' ','n','e','v','e','r',' ','s','a','i','d',
LINE_BREAK(),
SET_WAIT(4),
's','u','c','h',' ','a',' ','t','h','i','n','g','.','.','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(1,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x389),
WAIT_FOR_SOUND(),
SET_SPEED(2),
'W','h','a','t',' ','d','o',' ','y','o','u',' ','m','e','a','n','!','?',
LINE_BREAK(),
SET_WAIT(40),
'K','i','l','l',' ','t','h','e','m',' ',
SET_WAIT(16),
'a','n','d',' ','b','r','i','n','g',
LINE_BREAK(),
SET_WAIT(4),
't','h','e','m',' ','h','a','p','p','i','n','e','s','s','!',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x38a),
WAIT_FOR_SOUND(),
SET_SPEED(2),
'N','o','!',' ',
SET_WAIT(16),
'Y','o','u','\'','r','e',' ','n','o','t',
SET_FLAG(3),
' ','m','y',
LINE_BREAK(),
SET_WAIT(4),
'm','o','t','h','e','r','!',' ',
SET_WAIT(24),
'W','h','a','t',' ','k','i','n','d',' ','o','f',
LINE_BREAK(),
SET_WAIT(4),
'd','e','m','o','n',' ','a','r','e',' ','y','o','u','!','?',
SET_WAIT(48),
NEXT_DIALOG(),
CLOSE_DIALOG(),
LOAD_PORTRAIT(0x80189b0c,0),
SCRIPT_UNKNOWN_11(),
SET_FLAG(4),
SET_WAIT(56),
PLAY_SOUND(0x38b),
WAIT_FOR_SOUND(),
SET_WAIT(8),
SET_POS(60,28),
SET_PORTRAIT(2,0),
SET_FLAG(6),
SET_SPEED(2),
'Y','o','u',' ','b','r','o','k','e',' ','f','r','e','e',' ','o','f',' ','m','y',
LINE_BREAK(),
SET_WAIT(4),
's','p','e','l','l','.',' ',
SET_WAIT(32),
SET_SPEED(3),
'I',' ','l','i','k','e',' ','t','h','a','t','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x38d),
WAIT_FOR_SOUND(),
SET_SPEED(3),
'D','e','m','o','n',',',' ',
SET_WAIT(16),
'd','e','a','t','h',' ','i','s',' ','t','o','o',
LINE_BREAK(),
SET_WAIT(4),
'g','o','o','d',' ','f','o','r',' ','y','o','u','!',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(2,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x38e),
WAIT_FOR_SOUND(),
SET_FLAG(7),
SET_SPEED(3),
'C','o','m','e',' ','h','e','r','e',' ','l','i','t','t','l','e',' ','b','o','y',
LINE_BREAK(),
SET_WAIT(4),
'a','n','d',' ','s','h','o','w',' ','m','e',' ','w','h','a','t',
LINE_BREAK(),
SET_WAIT(4),
SET_FLAG(8),
'y','o','u','\'','v','e',' ','g','o','t','.',
SET_WAIT(48),
NEXT_DIALOG(),
CLOSE_DIALOG(),
SCRIPT_UNKNOWN_11(),
SET_FLAG(9),
END_CUTSCENE(),
SCRIPT_UNKNOWN_20(0x91),
SET_WAIT(32),
SCRIPT_UNKNOWN_11(),
SET_END(0x80181d1a),
WAIT_FOR_FLAG(0),
SET_POS(60,28),
LOAD_PORTRAIT(0x80189b0c,0),
SCRIPT_UNKNOWN_14(0x801816c4,0x80181b88,0x80181b90),
SET_PORTRAIT(2,0),
SCRIPT_UNKNOWN_15(0x80181b93),
SET_PORTRAIT(2,128),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x38f),
WAIT_FOR_SOUND(),
SET_SPEED(2),
'D','a','r','k','l','i','n','g','!',' ','I',' ','s','m','e','l','l',
LINE_BREAK(),
SET_WAIT(4),
'y','o','u','\'','r','e',' ','b','l','o','o','d','.',
LINE_BREAK(),
SET_WAIT(20),
SET_SPEED(4),
'Y','o','u','\'','r','e',' ','a',' ','v','a','m','p','i','r','e','.','.','.',
LINE_BREAK(),
SET_WAIT(32),
SET_SPEED(3),
'C','o','u','l','d',' ','i','t',' ','b','e','.','.','.',
SET_WAIT(48),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x8018800c,1),
SCRIPT_UNKNOWN_14(0x801816c4,0x80181bfc,0x80181c04),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_15(0x80181c07),
SET_PORTRAIT(0,129),
SET_SPEED(4),
'.','.','.','.','.','.','.','.','.',
SET_WAIT(48),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x80189b0c,0),
SCRIPT_UNKNOWN_14(0x801816c4,0x80181c28,0x80181c30),
SET_PORTRAIT(2,0),
SCRIPT_UNKNOWN_15(0x80181c33),
SET_PORTRAIT(2,128),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x390),
WAIT_FOR_SOUND(),
SET_SPEED(3),
'T','h','a','t',' ','s','t','r','e','n','g','t','h',',',' ',
SET_WAIT(16),
't','h','a','t',
LINE_BREAK(),
SET_WAIT(4),
'b','e','a','u','t','y','.','.','.',
SET_WAIT(16),
'Y','o','u','\'','r','e',' ','t','h','e',
LINE_BREAK(),
SET_WAIT(4),
's','o','n',' ','o','f',' ',
SET_SPEED(4),
'L','o','r','d',' ','D','r','a','c','u','l','a','.',
SET_WAIT(48),
NEXT_DIALOG(),
SCRIPT_UNKNOWN_14(0x801816c4,0x80181c90,0x80181c98),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_15(0x80181c9b),
SET_PORTRAIT(0,129),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x391),
WAIT_FOR_SOUND(),
SET_SPEED(2),
'D','e','a','t','h',' ','i','n',' ','t','h','e',' ','d','r','e','a','m',
LINE_BREAK(),
SET_WAIT(4),
'w','o','r','l','d',' ','w','i','l','l',' ','s','e','t',' ','y','o','u','r',
LINE_BREAK(),
SET_WAIT(4),
's','o','u','l',' ',
SET_SPEED(3),
'w','a','n','d','e','r','i','n','g',' ','f','o','r',
LINE_BREAK(),
SET_WAIT(4),
'e','t','e','r','n','i','t','y',',',' ','D','e','m','o','n','.',
SET_WAIT(48),
NEXT_DIALOG(),
CLOSE_DIALOG(),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x392),
WAIT_FOR_SOUND(),
SET_FLAG(4),
SCRIPT_UNKNOWN_11(),
WAIT_FOR_FLAG(6),
SET_FLAG(5),
END_CUTSCENE(),
