// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
PLAY_SOUND(0xa),
SET_END(0x80184110),
SCRIPT_UNKNOWN_14(0x80183f60,0x80183f7d,0x801840e9),
SET_POS(60,36),
LOAD_PORTRAIT(0x8018a488,0),
WAIT_FOR_FLAG(0),
SET_PORTRAIT(0,128),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3a3),
WAIT_FOR_SOUND(),
SET_SPEED(2),
'I','t','\'','s',' ','b','e','e','n',' ','a',' ','l','o','n','g',
LINE_BREAK(),
SET_WAIT(4),
't','i','m','e',',',' ',
SET_FLAG(1),
'o','l','d',' ','o','n','e','.','.','.',
SET_WAIT(48),
SET_FLAG(2),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x8018b208,1),
SET_PORTRAIT(1,1),
SET_FLAG(6),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3a4),
WAIT_FOR_SOUND(),
SET_SPEED(5),
'O','h',' ','i','t','\'','s',' ','y','o','u',',',
LINE_BREAK(),
SET_WAIT(4),
'M','a','s','t','e','r',' ','A','l','u','c','a','r','d','.',
LINE_BREAK(),
SET_WAIT(8),
SET_SPEED(3),
'W','h','a','t',' ','d','o',' ','y','o','u',' ','n','e','e','d','?',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,128),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3a5),
WAIT_FOR_SOUND(),
SET_SPEED(3),
'I',' ','n','e','e','d',' ','y','o','u','r',' ','h','e','l','p','.',
SET_WAIT(48),
SET_FLAG(3),
NEXT_DIALOG(),
SET_PORTRAIT(1,1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3a6),
WAIT_FOR_SOUND(),
SET_SPEED(4),
'Y','o','u','n','g',' ','m','a','s','t','e','r',',',
LINE_BREAK(),
SET_WAIT(4),
SET_SPEED(3),
'I',' ','c','a','n','n','o','t',' ','a','i','d',' ','o','n','e',' ','w','h','o',
LINE_BREAK(),
SET_WAIT(4),
SET_FLAG(4),
'o','p','p','o','s','e','s',' ','t','h','e',' ','M','a','s','t','e','r','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,128),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3a7),
WAIT_FOR_SOUND(),
SET_SPEED(3),
'Y','o','u',' ','w','o','n','\'','t',' ','g','o',
LINE_BREAK(),
SET_WAIT(4),
'u','n','r','e','w','a','r','d','e','d','.','.','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(1,1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3a8),
WAIT_FOR_SOUND(),
SET_FLAG(5),
SET_SPEED(3),
'R','e','a','l','l','y','?',' ',
SET_WAIT(16),
'I','n',' ','t','h','a','t',' ','c','a','s','e',
LINE_BREAK(),
SET_WAIT(4),
'j','u','s','t',' ','t','e','l','l',' ','m','e',' ',
SET_SPEED(2),
'w','h','a','t',
LINE_BREAK(),
SET_WAIT(4),
'y','o','u',' ','n','e','e','d','.',
SET_WAIT(48),
SET_FLAG(9),
NEXT_DIALOG(),
CLOSE_DIALOG(),
SCRIPT_UNKNOWN_11(),
SCRIPT_UNKNOWN_15(0x80184105),
WAIT_FOR_FLAG(0),
PLAY_SOUND(0xa),
SCRIPT_UNKNOWN_11(),
SCRIPT_UNKNOWN_14(0x80183f64,0x801840fc,0x80184100),
PLAY_SOUND(0x3b9),
WAIT_FOR_SOUND(),
SET_FLAG(7),
SET_FLAG(9),
SCRIPT_UNKNOWN_11(),
WAIT_FOR_FLAG_RESET(8),
SCRIPT_UNKNOWN_23(),
WAIT_FOR_FLAG(13),
SCRIPT_UNKNOWN_21(),
SCRIPT_UNKNOWN_15(0x801840e9),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
0x82,
