// SPDX-License-Identifier: AGPL-3.0-or-later
#include "rare.h"

u16 OVL_EXPORT(PrizeDrops)[] = {
    ITEMDROP_FURY_PLATE,
    ITEMDROP_ZIRCON,
    ITEMDROP_BUFFALO_STAR,
    ITEMDROP_GRAM,
    ITEMDROP_AQUAMARINE,
    ITEMDROP_HEART_VESSEL,
    ITEMDROP_LIFE_VESSEL,
    ITEMDROP_HEART_VESSEL,
    // Appears in ARE, not RARE - unclear why this is here, and repeated
    ITEMDROP_BLOOD_CLOAK,
    ITEMDROP_BLOOD_CLOAK,
    ITEMDROP_BLOOD_CLOAK,
    ITEMDROP_BLOOD_CLOAK,
    ITEMDROP_BLOOD_CLOAK,
    ITEMDROP_BLOOD_CLOAK,
    ITEMDROP_BLOOD_CLOAK,
    ITEMDROP_BLOOD_CLOAK,
};
