// SPDX-License-Identifier: AGPL-3.0-or-later
#include "../rare/rare.h"

#include "../pfn_entity_update.h"

extern LayoutEntity* D_8D2E0FC;
extern LayoutEntity* D_8D2E1D0;

extern Overlay OVL_EXPORT(Overlay);

s32 E_ID(BACKGROUND_BLOCK);
s32 E_ID(LOCK_CAMERA);
s32 E_ID(UNK_ID13);
s32 E_ID(EXPLOSION_VARIANTS);
s32 E_ID(GREY_PUFF);
s32 E_ID(MINOTAUR);
s32 E_ID(MINOTAUR_ATTACK_HITBOX);
s32 E_ID(MINOTAUR_FIREBALL);
s32 E_ID(MINOTAUR_SPIT_LIQUID);
s32 E_ID(WEREWOLF);
s32 E_ID(WEREWOLF_ATTACK_HITBOX);
s32 E_ID(WEREWOLF_ENERGY_WAVE);
s32 E_ID(WEREWOLF_AFTERIMAGE);
s32 E_ID(WEREWOLF_DEATH_FLAMES);
s32 E_ID(MINOTAUR_DEATH_PUFF);
s32 E_ID(UNK_20);
s32 E_ID(UNK_21);
s32 E_ID(BREAKABLE_FLOOR_SECRET);
s32 E_ID(BREAKABLE_DEBRIS);
s32 E_ID(BACKGROUND_DOOR_RUBBLE);
s32 E_ID(FOUNTAIN_WATER);
s32 E_ID(BOSS_TORCH);
s32 E_ID(BOSS_DOORS);
s32 E_ID(WHITE_DRAGON);
s32 E_ID(WHITE_DRAGON_FLAME_BREATH);
s32 E_ID(STONE_SKULL);

void InitEntityIds(void) {
    E_ID(BACKGROUND_BLOCK) = E_BACKGROUND_BLOCK;
    E_ID(LOCK_CAMERA) = E_LOCK_CAMERA;
    E_ID(UNK_ID13) = E_UNK_ID13;
    E_ID(EXPLOSION_VARIANTS) = E_EXPLOSION_VARIANTS;
    E_ID(GREY_PUFF) = E_GREY_PUFF;
    E_ID(MINOTAUR) = E_MINOTAUR;
    E_ID(MINOTAUR_ATTACK_HITBOX) = E_MINOTAUR_ATTACK_HITBOX;
    E_ID(MINOTAUR_FIREBALL) = E_MINOTAUR_FIREBALL;
    E_ID(MINOTAUR_SPIT_LIQUID) = E_MINOTAUR_SPIT_LIQUID;
    E_ID(WEREWOLF) = E_WEREWOLF;
    E_ID(WEREWOLF_ATTACK_HITBOX) = E_WEREWOLF_ATTACK_HITBOX;
    E_ID(WEREWOLF_ENERGY_WAVE) = E_WEREWOLF_ENERGY_WAVE;
    E_ID(WEREWOLF_AFTERIMAGE) = E_WEREWOLF_AFTERIMAGE;
    E_ID(WEREWOLF_DEATH_FLAMES) = E_WEREWOLF_DEATH_FLAMES;
    E_ID(MINOTAUR_DEATH_PUFF) = E_MINOTAUR_DEATH_PUFF;
    E_ID(UNK_20) = E_UNK_20;
    E_ID(UNK_21) = E_UNK_21;
    E_ID(BREAKABLE_FLOOR_SECRET) = E_BREAKABLE_FLOOR_SECRET;
    E_ID(BREAKABLE_DEBRIS) = E_BREAKABLE_DEBRIS;
    E_ID(BACKGROUND_DOOR_RUBBLE) = E_BACKGROUND_DOOR_RUBBLE;
    E_ID(FOUNTAIN_WATER) = E_FOUNTAIN_WATER;
    E_ID(BOSS_TORCH) = E_BOSS_TORCH;
    E_ID(BOSS_DOORS) = E_BOSS_DOORS;
    E_ID(WHITE_DRAGON) = E_WHITE_DRAGON;
    E_ID(WHITE_DRAGON_FLAME_BREATH) = E_WHITE_DRAGON_FLAME_BREATH;
    E_ID(STONE_SKULL) = E_STONE_SKULL;
}

void OVL_EXPORT(Load)(void) {
    InitEntityIds();
    PfnEntityUpdates = OVL_EXPORT(EntityUpdates);
    g_pStObjLayoutHorizontal = &D_8D2E0FC;
    g_pStObjLayoutVertical = &D_8D2E1D0;
    func_892A018();
    memcpy(&g_api.o, &OVL_EXPORT(Overlay), sizeof(Overlay));
}
