// SPDX-License-Identifier: AGPL-3.0-or-later
#include "../rare/rare.h"

#include "../pfn_entity_update.h"

extern LayoutEntity* D_8D2E0FC;
extern LayoutEntity* D_8D2E1D0;

extern Overlay OVL_EXPORT(Overlay);

s32 E_ID(BACKGROUND_BLOCK);
s32 E_ID(LOCK_CAMERA);
s32 E_ID(UNK_ID13);
s32 E_ID(EXPLOSION_VARIANTS);
s32 E_ID(GREY_PUFF);
s32 E_ID(UNK_16);
s32 E_ID(UNK_17);
s32 E_ID(UNK_18);
s32 E_ID(UNK_19);
s32 E_ID(UNK_1A);
s32 E_ID(CORNER_GUARD_ATTACK);
s32 E_ID(UNK_1C);
s32 E_ID(UNK_1D);
s32 E_ID(UNK_1E);
s32 E_ID(UNK_1F);
s32 E_ID(UNK_20);
s32 E_ID(UNK_21);
s32 E_ID(BREAKABLE_FLOOR_SECRET);
s32 E_ID(BREAKABLE_DEBRIS);
s32 E_ID(BACKGROUND_DOOR_RUBBLE);
s32 E_ID(FOUNTAIN_WATER);
s32 E_ID(BOSS_TORCH);
s32 E_ID(BOSS_DOORS);
s32 E_ID(WHITE_DRAGON);
s32 E_ID(WHITE_DRAGON_FLAME_BREATH);
s32 E_ID(STONE_SKULL);

void InitEntityIds(void) {
    E_ID(BACKGROUND_BLOCK) = E_BACKGROUND_BLOCK;
    E_ID(LOCK_CAMERA) = E_LOCK_CAMERA;
    E_ID(UNK_ID13) = E_UNK_ID13;
    E_ID(EXPLOSION_VARIANTS) = E_EXPLOSION_VARIANTS;
    E_ID(GREY_PUFF) = E_GREY_PUFF;
    E_ID(UNK_16) = E_UNK_16;
    E_ID(UNK_17) = E_UNK_17;
    E_ID(UNK_18) = E_UNK_18;
    E_ID(UNK_19) = E_UNK_19;
    E_ID(UNK_1A) = E_UNK_1A;
    E_ID(CORNER_GUARD_ATTACK) = E_CORNER_GUARD_ATTACK;
    E_ID(UNK_1C) = E_UNK_1C;
    E_ID(UNK_1D) = E_UNK_1D;
    E_ID(UNK_1E) = E_UNK_1E;
    E_ID(UNK_1F) = E_UNK_1F;
    E_ID(UNK_20) = E_UNK_20;
    E_ID(UNK_21) = E_UNK_21;
    E_ID(BREAKABLE_FLOOR_SECRET) = E_BREAKABLE_FLOOR_SECRET;
    E_ID(BREAKABLE_DEBRIS) = E_BREAKABLE_DEBRIS;
    E_ID(BACKGROUND_DOOR_RUBBLE) = E_BACKGROUND_DOOR_RUBBLE;
    E_ID(FOUNTAIN_WATER) = E_FOUNTAIN_WATER;
    E_ID(BOSS_TORCH) = E_BOSS_TORCH;
    E_ID(BOSS_DOORS) = E_BOSS_DOORS;
    E_ID(WHITE_DRAGON) = E_WHITE_DRAGON;
    E_ID(WHITE_DRAGON_FLAME_BREATH) = E_WHITE_DRAGON_FLAME_BREATH;
    E_ID(STONE_SKULL) = E_STONE_SKULL;
}

void OVL_EXPORT(Load)(void) {
    InitEntityIds();
    PfnEntityUpdates = OVL_EXPORT(EntityUpdates);
    g_pStObjLayoutHorizontal = &D_8D2E0FC;
    g_pStObjLayoutVertical = &D_8D2E1D0;
    func_892A018();
    memcpy(&g_api.o, &OVL_EXPORT(Overlay), sizeof(Overlay));
}
