// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
PLAY_SOUND(0xa),
SET_END(0x801001ae),
SCRIPT_UNKNOWN_14(0x80100000,0x8010001d,0x80100187),
SET_POS(60,36),
LOAD_PORTRAIT(0x80100000,0),
WAIT_FOR_FLAG(0),
SET_PORTRAIT(0,128),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3a1),
WAIT_FOR_SOUND(),
SET_SPEED(6),
'\xB2','C','u','\xCC','n','t','o',' ','t','i','e','m','p','o','!',
LINE_BREAK(),
SET_FLAG(1),
SET_WAIT(24),
'\xB3','Q','u','\xD1',' ','t','a','l','?',
SET_WAIT(60),
SET_FLAG(2),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x80100005,1),
SET_PORTRAIT(1,1),
SET_FLAG(6),
PLAY_SOUND(0x3a2),
WAIT_FOR_SOUND(),
SET_SPEED(7),
'\xB3','E','h','?',' ','\xB2','P','e','r','o',' ','s','i',' ','e','s',' ','e','l',
LINE_BREAK(),
'M','a','e','s','t','r','o',' ','A','l','u','c','a','r','d','!',
LINE_BREAK(),
'.','.','.',' ','\xB3','V','i','e','n','e','s',' ','d','e',' ','v','i','s','i','t','a','?',
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,128),
PLAY_SOUND(0x3a3),
WAIT_FOR_SOUND(),
SET_SPEED(7),
'N','e','c','e','s','i','t','o',' ','t','u',' ','a','y','u','d','a','.',
SET_WAIT(56),
SET_FLAG(3),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,1),
PLAY_SOUND(0x3a4),
WAIT_FOR_SOUND(),
SET_SPEED(7),
'V','a','y','a',',',' ','p','e','r','o',' ','y','o',' ','n','u','n','c','a',
LINE_BREAK(),
SET_WAIT(8),
SET_FLAG(4),
'p','o','d','r','\xD5','a',' ','t','r','a','i','c','i','o','n','a','r',' ','a','l',' ','s','e','\xD8','o','r',
LINE_BREAK(),
'c','o','n','d','e',',',' ','j','o','v','e','n',' ','m','a','e','s','t','r','o','.',
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,128),
PLAY_SOUND(0x3a5),
WAIT_FOR_SOUND(),
SET_SPEED(6),
'T','e','n','d','r','\xCC','s',' ','t','u',' ','r','e','c','o','m','p','e','n','s','a','.','.','.',
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,1),
PLAY_SOUND(0x3a6),
WAIT_FOR_SOUND(),
SET_FLAG(5),
SET_SPEED(8),
'\xB3','D','e',' ','v','e','r','d','a','d','?',
LINE_BREAK(),
'E','n',' ','e','s','e',' ','c','a','s','o',',',
LINE_BREAK(),
'\xB2','d','\xD5','g','a','m','e',' ','q','u','\xD1',' ','e','s',' ','l','o',
LINE_BREAK(),
'q','u','e',' ','n','e','c','e','s','i','t','a','!',
SCRIPT_UNKNOWN_11(),
SET_FLAG(9),
NEXT_DIALOG(),
CLOSE_DIALOG(),
SCRIPT_UNKNOWN_15(0x801001a3),
WAIT_FOR_FLAG(0),
PLAY_SOUND(0xa),
SCRIPT_UNKNOWN_11(),
SCRIPT_UNKNOWN_14(0x80100004,0x8010019a,0x8010019e),
PLAY_SOUND(0x3b5),
WAIT_FOR_SOUND(),
SET_FLAG(7),
SET_FLAG(9),
SCRIPT_UNKNOWN_11(),
WAIT_FOR_FLAG_RESET(8),
SCRIPT_UNKNOWN_23(),
WAIT_FOR_FLAG(13),
SCRIPT_UNKNOWN_21(),
SCRIPT_UNKNOWN_15(0x80100187),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
0x82,
'#',
CLOSE_DIALOG(),
0x80,
CLOSE_DIALOG(),
0x80,
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
0x83,
'&',
CLOSE_DIALOG(),
0x80,
CLOSE_DIALOG(),
0x80,
0xff,
0xff,
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
