// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
PLAY_SOUND(0xa),
SET_END(0x801001d6),
SCRIPT_UNKNOWN_14(0x80100000,0x8010001d,0x801001af),
SET_POS(60,36),
LOAD_PORTRAIT(0x80100000,0),
WAIT_FOR_FLAG(0),
SET_PORTRAIT(0,128),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3a1),
WAIT_FOR_SOUND(),
SET_SPEED(6),
'N','e',' ','\xD0',' ','p','a','s','s','a','t','o',' ','d','i',' ','t','e','m','p','o',',',
LINE_BREAK(),
SET_FLAG(1),
SET_WAIT(24),
'v','e','c','c','h','i','o','.',
SET_WAIT(60),
SET_FLAG(2),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x80100005,1),
SET_PORTRAIT(1,1),
SET_FLAG(6),
PLAY_SOUND(0x3a2),
WAIT_FOR_SOUND(),
SET_SPEED(7),
'E','h','?',' ','N','o','n',' ','c','r','e','d','o',' ','a','i',' ','m','i','e','i',
LINE_BREAK(),
'o','c','c','h','i','!',' ','P','a','d','r','o','n',' ','A','l','u','c','a','r','d','!',
LINE_BREAK(),
'A',' ','c','o','s','a',' ','d','e','v','o',' ','i','l',' ','p','i','a','c','e','r','e','?',
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,128),
PLAY_SOUND(0x3a3),
WAIT_FOR_SOUND(),
SET_SPEED(7),
'M','i',' ','o','c','c','o','r','r','e',' ','i','l',' ','t','u','o',' ','a','i','u','t','o','.',
SET_WAIT(56),
SET_FLAG(3),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,1),
PLAY_SOUND(0x3a4),
WAIT_FOR_SOUND(),
SET_SPEED(7),
'O','h',',',' ','p','a','d','r','o','n','c','i','n','o',',',' ',
SET_WAIT(8),
SET_FLAG(4),
'm','a',' ','i','o',
LINE_BREAK(),
'n','o','n',' ','p','o','t','r','e','i',' ','m','a','i',' ','t','r','a','d','i','r','e',
LINE_BREAK(),
'i','l',' ','b','u','o','n',' ','C','o','n','t','e','.',
SET_WAIT(96),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,128),
PLAY_SOUND(0x3a5),
WAIT_FOR_SOUND(),
SET_SPEED(6),
'S','a','r','a','i',' ','d','e','b','i','t','a','m','e','n','t','e',
LINE_BREAK(),
'r','i','c','o','m','p','e','n','s','a','t','o','.',
SET_WAIT(88),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,1),
PLAY_SOUND(0x3a6),
WAIT_FOR_SOUND(),
SET_FLAG(5),
SET_SPEED(8),
'D','a','v','v','e','r','o','?',
LINE_BREAK(),
SET_WAIT(32),
'I','n',' ','q','u','e','s','t','o',' ','c','a','s','o',',',' ','s','o','n','o',
LINE_BREAK(),
't','u','t','t','\'','o','r','e','c','c','h','i','e','.',
LINE_BREAK(),
'M','i',' ','d','i','c','a',' ','c','o','s','a',' ','l','e',' ','s','e','r','v','e','!',
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
SET_FLAG(9),
NEXT_DIALOG(),
CLOSE_DIALOG(),
SCRIPT_UNKNOWN_15(0x801001cb),
WAIT_FOR_FLAG(0),
PLAY_SOUND(0xa),
SCRIPT_UNKNOWN_11(),
SCRIPT_UNKNOWN_14(0x80100004,0x801001c2,0x801001c6),
PLAY_SOUND(0x3b5),
WAIT_FOR_SOUND(),
SET_FLAG(7),
SET_FLAG(9),
SCRIPT_UNKNOWN_11(),
WAIT_FOR_FLAG_RESET(8),
SCRIPT_UNKNOWN_23(),
WAIT_FOR_FLAG(13),
SCRIPT_UNKNOWN_21(),
SCRIPT_UNKNOWN_15(0x801001af),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
0x82,
'#',
CLOSE_DIALOG(),
0x80,
CLOSE_DIALOG(),
0x80,
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
0x83,
'&',
CLOSE_DIALOG(),
0x80,
CLOSE_DIALOG(),
0x80,
0xff,
0xff,
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
