// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
PLAY_SOUND(0xa),
SET_END(0x801001e2),
SCRIPT_UNKNOWN_14(0x80100000,0x8010001d,0x801001bb),
SET_POS(60,36),
LOAD_PORTRAIT(0x80100000,0),
WAIT_FOR_FLAG(0),
SET_PORTRAIT(0,128),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3a1),
WAIT_FOR_SOUND(),
SET_SPEED(6),
'\xB8','a',' ','f','a','i','s','a','i','t',' ','l','o','n','g','t','e','m','p','s',',',
LINE_BREAK(),
SET_FLAG(1),
SET_WAIT(24),
'm','o','n',' ','a','m','i','.','.','.',
SET_WAIT(60),
SET_FLAG(2),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x80100005,1),
SET_PORTRAIT(1,1),
SET_FLAG(6),
PLAY_SOUND(0x3a2),
WAIT_FOR_SOUND(),
SET_SPEED(7),
'H','e','i','n',' ','?',' ','O','h',',',' ','c','\'','e','s','t',' ','M','a','\xD6','t','r','e',
LINE_BREAK(),
'A','l','u','c','a','r','d',' ','!',' ','.','.','.','V','o','u','s',' ','\xD2','t','e','s',
LINE_BREAK(),
'v','e','n','u',' ','n','o','u','s',' ','r','e','n','d','r','e',' ','v','i','s','i','t','e',' ','?',
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,128),
PLAY_SOUND(0x3a3),
WAIT_FOR_SOUND(),
SET_SPEED(7),
'J','\'','a','i',' ','b','e','s','o','i','n',' ','d','e',' ','t','o','n',' ','a','i','d','e','.',
SET_WAIT(56),
SET_FLAG(3),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,1),
PLAY_SOUND(0x3a4),
WAIT_FOR_SOUND(),
SET_SPEED(7),
'O','h',',',' ','m','a','i','s',' ','j','e','u','n','e',' ','M','a','\xD6','t','r','e',',',
LINE_BREAK(),
SET_WAIT(8),
SET_FLAG(4),
'j','e',' ','n','e',' ','p','o','u','r','r','a','i','s',' ','j','a','m','a','i','s',
LINE_BREAK(),
't','r','a','h','i','r',' ','n','o','t','r','e',' ','b','o','n',' ','C','o','m','t','e','.','.','.',
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,128),
PLAY_SOUND(0x3a5),
WAIT_FOR_SOUND(),
SET_SPEED(6),
'T','o','n',' ','a','i','d','e',' ','s','e','r','a',' ','\xD1','v','i','d','e','m','m','e','n','t',
LINE_BREAK(),
'r','\xD1','c','o','m','p','e','n','s','\xD1','e','.','.','.',
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,1),
PLAY_SOUND(0x3a6),
WAIT_FOR_SOUND(),
SET_FLAG(5),
SET_SPEED(8),
'V','r','a','i','m','e','n','t',' ','?',
LINE_BREAK(),
'B','o','n',',',' ','d','a','n','s',' ','c','e',' ','c','a','s',',',
LINE_BREAK(),
'd','i','t','e','s','-','m','o','i',' ','d','e',' ','q','u','o','i',
LINE_BREAK(),
'v','o','u','s',' ','a','v','e','z',' ','b','e','s','o','i','n',' ','!',
SCRIPT_UNKNOWN_11(),
SET_FLAG(9),
NEXT_DIALOG(),
CLOSE_DIALOG(),
SCRIPT_UNKNOWN_15(0x801001d7),
WAIT_FOR_FLAG(0),
PLAY_SOUND(0xa),
SCRIPT_UNKNOWN_11(),
SCRIPT_UNKNOWN_14(0x80100004,0x801001ce,0x801001d2),
PLAY_SOUND(0x3b5),
WAIT_FOR_SOUND(),
SET_FLAG(7),
SET_FLAG(9),
SCRIPT_UNKNOWN_11(),
WAIT_FOR_FLAG_RESET(8),
SCRIPT_UNKNOWN_23(),
WAIT_FOR_FLAG(13),
SCRIPT_UNKNOWN_21(),
SCRIPT_UNKNOWN_15(0x801001bb),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
0x82,
'#',
CLOSE_DIALOG(),
0x80,
CLOSE_DIALOG(),
0x80,
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
0x83,
'&',
CLOSE_DIALOG(),
0x80,
CLOSE_DIALOG(),
0x80,
0xff,
0xff,
END_CUTSCENE(),
END_CUTSCENE(),
