// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
PLAY_SOUND(0xa),
SET_END(0x801001a5),
SCRIPT_UNKNOWN_14(0x80100000,0x8010001d,0x8010017e),
SET_POS(60,36),
LOAD_PORTRAIT(0x80100000,0),
WAIT_FOR_FLAG(0),
SET_PORTRAIT(0,128),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3a1),
WAIT_FOR_SOUND(),
SET_SPEED(6),
'I','t','\'','s',' ','b','e','e','n',' ','a',' ','l','o','n','g',' ','t','i','m','e',',',
LINE_BREAK(),
SET_FLAG(1),
SET_WAIT(24),
'o','l','d',' ','o','n','e','.','.','.',
SET_WAIT(60),
SET_FLAG(2),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x80100005,1),
SET_PORTRAIT(1,1),
SET_FLAG(6),
PLAY_SOUND(0x3a2),
WAIT_FOR_SOUND(),
SET_SPEED(7),
'E','h','?',' ','W','h','y',',',
LINE_BREAK(),
'i','t','\'','s',' ','M','a','s','t','e','r',' ','A','l','u','c','a','r','d','!',
LINE_BREAK(),
'.','.','.','C','o','m','e',' ','t','o',' ','v','i','s','i','t',',',' ','h','a','v','e',' ','w','e','?',
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,128),
PLAY_SOUND(0x3a3),
WAIT_FOR_SOUND(),
SET_SPEED(7),
'I',' ','n','e','e','d',' ','y','o','u','r',' ','h','e','l','p','.',
SET_WAIT(56),
SET_FLAG(3),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,1),
PLAY_SOUND(0x3a4),
WAIT_FOR_SOUND(),
SET_SPEED(7),
'O','h',',',' ','b','u','t',' ','Y','o','u','n','g',' ','M','a','s','t','e','r',',',
LINE_BREAK(),
SET_WAIT(8),
SET_FLAG(4),
'I',' ','c','o','u','l','d',' ','n','e','v','e','r',' ','b','e','t','r','a','y',
LINE_BREAK(),
't','h','e',' ','g','o','o','d',' ','C','o','u','n','t','.','.','.',
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,128),
PLAY_SOUND(0x3a5),
WAIT_FOR_SOUND(),
SET_SPEED(6),
'Y','o','u',' ','w','o','n','\'','t',' ','g','o',' ','u','n','r','e','w','a','r','d','e','d','.','.','.',
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,1),
PLAY_SOUND(0x3a6),
WAIT_FOR_SOUND(),
SET_FLAG(5),
SET_SPEED(8),
'R','e','a','l','l','y','?',
LINE_BREAK(),
'I','n',' ','t','h','a','t',' ','c','a','s','e',',',
LINE_BREAK(),
'j','u','s','t',' ','t','e','l','l',' ','m','e',
LINE_BREAK(),
'w','h','a','t',' ','y','o','u',' ','n','e','e','d','!',
SCRIPT_UNKNOWN_11(),
SET_FLAG(9),
NEXT_DIALOG(),
CLOSE_DIALOG(),
SCRIPT_UNKNOWN_15(0x8010019a),
WAIT_FOR_FLAG(0),
PLAY_SOUND(0xa),
SCRIPT_UNKNOWN_11(),
SCRIPT_UNKNOWN_14(0x80100004,0x80100191,0x80100195),
PLAY_SOUND(0x3b5),
WAIT_FOR_SOUND(),
SET_FLAG(7),
SET_FLAG(9),
SCRIPT_UNKNOWN_11(),
WAIT_FOR_FLAG_RESET(8),
SCRIPT_UNKNOWN_23(),
WAIT_FOR_FLAG(13),
SCRIPT_UNKNOWN_21(),
SCRIPT_UNKNOWN_15(0x8010017e),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
0x82,
'#',
CLOSE_DIALOG(),
0x80,
CLOSE_DIALOG(),
0x80,
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
0x83,
'&',
CLOSE_DIALOG(),
0x80,
CLOSE_DIALOG(),
0x80,
0xff,
0xff,
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
