// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
PLAY_SOUND(0xa),
SET_END(0x801001d0),
SCRIPT_UNKNOWN_14(0x80100000,0x8010001d,0x801001a9),
SET_POS(60,36),
LOAD_PORTRAIT(0x80100000,0),
WAIT_FOR_FLAG(0),
SET_PORTRAIT(0,128),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x3a1),
WAIT_FOR_SOUND(),
SET_SPEED(6),
'E','s',' ','i','s','t',' ','l','a','n','g','e',' ','h','e','r',',',
LINE_BREAK(),
SET_FLAG(1),
SET_WAIT(24),
'a','l','t','e','r',' ','F','r','e','u','n','d',' ','.','.','.',
SET_WAIT(60),
SET_FLAG(2),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x80100005,1),
SET_PORTRAIT(1,1),
SET_FLAG(6),
PLAY_SOUND(0x3a2),
WAIT_FOR_SOUND(),
SET_SPEED(7),
'W','i','e','?',' ','O','h',',',' ','M','e','i','s','t','e','r',' ','A','l','u','c','a','r','d','!',
LINE_BREAK(),
'.','.','.',' ','A','u','c','h',' ','m','a','l',' ','w','i','e','d','e','r',' ','d','a','?',
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,128),
PLAY_SOUND(0x3a3),
WAIT_FOR_SOUND(),
SET_SPEED(7),
'I','c','h',' ','b','r','a','u','c','h','e',' ','E','u','r','e',' ','H','i','l','f','e','.',
SET_WAIT(56),
SET_FLAG(3),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,1),
PLAY_SOUND(0x3a4),
WAIT_FOR_SOUND(),
SET_SPEED(7),
'O','h',',',' ','a','b','e','r',' ','j','u','n','g','e','r',' ','M','e','i','s','t','e','r',',',
LINE_BREAK(),
SET_WAIT(8),
SET_FLAG(4),
'i','c','h',' ','k','\xDC','n','n','t','e',' ','d','e','n',' ','G','r','a','f','e','n',
LINE_BREAK(),
'n','i','e','m','a','l','s',' ','h','i','n','t','e','r','g','e','h','e','n',' ','.','.','.',
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,128),
PLAY_SOUND(0x3a5),
WAIT_FOR_SOUND(),
SET_SPEED(6),
'I','h','r',' ','w','e','r','d','e','t',' ','r','e','i','c','h',' ','b','e','l','o','h','n','t',
LINE_BREAK(),
'w','e','r','d','e','n',' ','.','.','.',
SET_WAIT(88),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,1),
PLAY_SOUND(0x3a6),
WAIT_FOR_SOUND(),
SET_FLAG(5),
SET_SPEED(8),
'W','i','r','k','l','i','c','h','?',
LINE_BREAK(),
SET_WAIT(32),
'N','u','n',',',' ','i','n',' ','d','i','e','s','e','m',' ','F','a','l','l',',',
LINE_BREAK(),
's','a','g','t',' ','m','i','r',' ','e','i','n','f','a','c','h',',',' ','w','a','s',
LINE_BREAK(),
'I','h','r',' ','b','r','a','u','c','h','t','!',
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
SET_FLAG(9),
NEXT_DIALOG(),
CLOSE_DIALOG(),
SCRIPT_UNKNOWN_15(0x801001c5),
WAIT_FOR_FLAG(0),
PLAY_SOUND(0xa),
SCRIPT_UNKNOWN_11(),
SCRIPT_UNKNOWN_14(0x80100004,0x801001bc,0x801001c0),
PLAY_SOUND(0x3b5),
WAIT_FOR_SOUND(),
SET_FLAG(7),
SET_FLAG(9),
SCRIPT_UNKNOWN_11(),
WAIT_FOR_FLAG_RESET(8),
SCRIPT_UNKNOWN_23(),
WAIT_FOR_FLAG(13),
SCRIPT_UNKNOWN_21(),
SCRIPT_UNKNOWN_15(0x801001a9),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
0x82,
'#',
CLOSE_DIALOG(),
0x80,
CLOSE_DIALOG(),
0x80,
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
0x83,
'&',
CLOSE_DIALOG(),
0x80,
CLOSE_DIALOG(),
0x80,
0xff,
0xff,
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
