// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
SET_END(0x801002db),
WAIT_FOR_FLAG(0),
PLAY_SOUND(0x81),
SET_POS(60,36),
LOAD_PORTRAIT(0x80100002,0),
SET_PORTRAIT(0,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x356),
WAIT_FOR_SOUND(),
'D','r','a','c','u','l','a','!',' ','S','t','e','r','b','t',' ','u','n','d',
LINE_BREAK(),
'v','e','r','l','a','s','s','t',' ','d','i','e','s','e',' ','W','e','l','t','!',
LINE_BREAK(),
'I','h','r',' ','g','e','h','\xDC','r','t',' ','n','i','c','h','t',' ','h','i','e','r','h','e','r','!',
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x80100003,1),
SET_PORTRAIT(1,129),
PLAY_SOUND(0x357),
WAIT_FOR_SOUND(),
'O','h',',',' ','a','b','e','r',' ','d','i','e','s','e',' ','W','e','l','t',',',
LINE_BREAK(),
'E','u','r','e','s','g','l','e','i','c','h','e','n',',',' ','h','a','b','e','n',
LINE_BREAK(),
'm','i','c','h',' ','d','u','r','c','h',' ','A','n','r','u','f','u','n','g',
LINE_BREAK(),
'u','n','d',' ','O','p','f','e','r','g','a','b','e','n',
LINE_BREAK(),
'h','e','r','a','u','f','b','e','s','c','h','w','o','r','e','n','.',
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,0),
PLAY_SOUND(0x358),
WAIT_FOR_SOUND(),
SET_FLAG(10),
'O','p','f','e','r','g','a','b','e','n','?',' ','I','h','r',' ','s','e','i','d',
LINE_BREAK(),
'e','i','n',' ','D','i','e','b','!',' ',
SET_FLAG(11),
'I','h','r',' ','b','e','r','a','u','b','t',' ','d','i','e',
LINE_BREAK(),
'M','e','n','s','c','h','e','n',' ','i','h','r','e','r',' ','S','e','e','l','e','n',',',
LINE_BREAK(),
SET_FLAG(12),
'i','h','r','e','r',' ','F','r','e','i','h','e','i','t',' ','.','.','.',
SET_FLAG(13),
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,129),
PLAY_SOUND(0x359),
WAIT_FOR_SOUND(),
'D','i','e',' ','F','r','e','i','h','e','i','t',' ','f','\xCE','l','l','t',' ','i','m','m','e','r',
LINE_BREAK(),
'd','e','m',' ','G','l','a','u','b','e','n',' ','z','u','m',' ','O','p','f','e','r',',',
LINE_BREAK(),
'w','e','r','t','e','r',' ','J','\xCE','g','e','r','.',' ','O','d','e','r',' ','s','e','i','d',
LINE_BREAK(),
'I','h','r',' ','e','t','w','a',' ','a','u','s',' ','f','r','e','i','e','n',
LINE_BREAK(),
'S','t','\xA8','c','k','e','n',' ','h','i','e','r','?',
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,0),
PLAY_SOUND(0x35a),
WAIT_FOR_SOUND(),
SET_FLAG(14),
'I','c','h',' ','b','i','n',' ','a','l','l','e','i','n',' ','w','e','g','e','n',
LINE_BREAK(),
'E','u','c','h',' ','h','i','e','r','!',' ',
SET_FLAG(15),
'Z','u','r',' ','H','\xDC','l','l','e',' ','m','i','t',
LINE_BREAK(),
'E','u','r','e','r',' ','K','e','t','z','e','r','e','i','!',' ',
SET_FLAG(16),
'I','h','r',' ','s','e','i','d',
LINE_BREAK(),
'n','u','r',' ','d','i','e',' ',
SET_FLAG(4),
SET_FLAG(17),
'G','e','i','\xCA','e','l',' ','d','e','r',
LINE_BREAK(),
'M','e','n','s','c','h','h','e','i','t','.',
SET_FLAG(18),
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,129),
PLAY_SOUND(0x35b),
WAIT_FOR_SOUND(),
'P','a','h','!',' ','D','i','e',' ','M','e','n','s','c','h','h','e','i','t','!',' ',
SET_FLAG(5),
SET_WAIT(80),
'E','i','n',
LINE_BREAK(),
'M','o','l','o','c','h',' ','d','e','s',' ','H','a','s','s','e','s',' ','u','n','d',
LINE_BREAK(),
'd','e','r',' ','L','\xA8','g','e',' ','.','.','.',' ','i','s','t',' ','e','s',' ','d','a','s',',',
LINE_BREAK(),
'w','o','f','\xA8','r',' ','I','h','r',' ','k','\xCE','m','p','f','t','?',' ','G','u','t',',',
LINE_BREAK(),
'd','a','n','n',' ','k','\xCE','m','p','f','t',' ','j','e','t','z','t',' ','u','n','d',
LINE_BREAK(),
's','t','e','r','b','t',' ','f','\xA8','r',' ','d','i','e',' ','S','\xA8','n','d','e','n',' ','d','e','r',
LINE_BREAK(),
'M','e','n','s','c','h','e','n','!',
WAIT_FOR_FLAG(8),
SET_FLAG(6),
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SCRIPT_UNKNOWN_20(0x31f),
SET_FLAG(2),
CLOSE_DIALOG(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
0x81,
SCRIPT_UNKNOWN_23(),
CLOSE_DIALOG(),
0x80,
CLOSE_DIALOG(),
0x80,
0xff,
0xff,
END_CUTSCENE(),
END_CUTSCENE(),
