// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
SET_END(0x801002ca),
WAIT_FOR_FLAG(0),
PLAY_SOUND(0x81),
SET_POS(60,36),
LOAD_PORTRAIT(0x80100002,0),
SET_PORTRAIT(0,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x356),
WAIT_FOR_SOUND(),
'D','r','a','c','u','l','a','.',' ','\xB2','M','u','e','r','e',' ','y',' ','a','b','a','n','d','o','n','a',
LINE_BREAK(),
'e','s','t','e',' ','m','u','n','d','o','!',' ','\xB2','N','u','n','c','a',
LINE_BREAK(),
'p','e','r','t','e','n','e','c','e','r','\xCC','s',' ','a',' ','\xD1','l','!',
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x80100003,1),
SET_PORTRAIT(1,129),
PLAY_SOUND(0x357),
WAIT_FOR_SOUND(),
'O','h',',',' ','p','e','r','o',' ','f','u','e',' ','e','s','t','e',' ','m','u','n','d','o',' ','e','l',
LINE_BREAK(),
'q','u','e',' ','m','e',' ','i','n','v','i','t','\xDA','.',' ','L','o','s',' ','m','i','s','m','o','s',
LINE_BREAK(),
'h','u','m','a','n','o','s',' ','a',' ','l','o','s',' ','q','u','e',' ','p','r','o','t','e','g','e','s',
LINE_BREAK(),
'r','e','c','l','a','m','a','r','o','n',' ','m','i',' ','p','r','e','s','e','n','c','i','a',
LINE_BREAK(),
'c','o','n',' ','e','l','o','g','i','o','s',' ','y',' ','t','r','i','b','u','t','o','s','.',
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,0),
PLAY_SOUND(0x358),
WAIT_FOR_SOUND(),
SET_FLAG(10),
'\xB3','T','r','i','b','u','t','o','s','?',' ','E','r','e','s',' ','u','n',' ','l','a','d','r','\xDA','n','.',
LINE_BREAK(),
SET_FLAG(11),
'R','o','b','a','s',' ','l','a','s',' ','a','l','m','a','s',' ','d','e',' ','l','o','s',
LINE_BREAK(),
SET_FLAG(12),
'h','o','m','b','r','e','s',',',' ','s','u',' ','l','i','b','e','r','t','a','d','.','.','.',
SET_FLAG(13),
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,129),
PLAY_SOUND(0x359),
WAIT_FOR_SOUND(),
'L','a',' ','l','i','b','e','r','t','a','d',' ','s','e',' ','s','a','c','r','i','f','i','c','a',
LINE_BREAK(),
's','i','e','m','p','r','e',' ','e','n',' ','f','a','v','o','r',' ','d','e',
LINE_BREAK(),
'l','a',' ','f','e',',',' ','b','u','e','n',' ','c','a','z','a','d','o','r','.',' ','\xB3','O',
LINE_BREAK(),
'e','s',' ','q','u','e',' ','e','s','t','\xCC','s',' ','a','q','u','\xD5',' ','p','o','r',
LINE_BREAK(),
'c','a','s','u','a','l','i','d','a','d','?',
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,0),
PLAY_SOUND(0x35a),
WAIT_FOR_SOUND(),
SET_FLAG(14),
'Y','o',' ','s','\xDA','l','o',' ','e','s','t','o','y',' ','a','q','u','\xD5',' ','p','o','r',' ','t','i','.',
LINE_BREAK(),
SET_FLAG(15),
'\xB2','A','l',' ','d','i','a','b','l','o',' ','c','o','n',' ','t','u','s',' ','h','e','r','e','j','\xD5','a','s','!',
LINE_BREAK(),
SET_FLAG(16),
'N','o',' ','e','r','e','s',' ','m','\xCC','s',' ','q','u','e',' ','u','n','a',
LINE_BREAK(),
SET_FLAG(4),
SET_FLAG(17),
'p','e','s','t','e',' ','p','a','r','a',' ','l','a',' ','h','u','m','a','n','i','d','a','d','.',
SET_FLAG(18),
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,129),
PLAY_SOUND(0x35b),
WAIT_FOR_SOUND(),
'\xB2','J','a','!',' ','L','a',' ','h','u','m','a','n','i','d','a','d',' ','e','s',' ','u','n',
LINE_BREAK(),
SET_FLAG(5),
'p','o','z','o',' ','d','e',' ','o','d','i','o',' ','y',' ','m','e','n','t','i','r','a','s','.',
LINE_BREAK(),
'\xB3','E','s',' ','e','s','o',' ','p','o','r',' ','l','o',' ','q','u','e',' ','l','u','c','h','a','s','?',
LINE_BREAK(),
'\xB2','P','u','e','s',' ','v','e','n','g','a',',',' ','l','u','c','h','a',' ','a','h','o','r','a',
LINE_BREAK(),
'y',' ','m','u','e','r','e',' ','p','o','r',' ','s','u','s',' ','p','e','c','a','d','o','s','!',
WAIT_FOR_FLAG(8),
SET_FLAG(6),
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SCRIPT_UNKNOWN_20(0x31f),
SET_FLAG(2),
CLOSE_DIALOG(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
0x81,
SCRIPT_UNKNOWN_23(),
CLOSE_DIALOG(),
0x80,
CLOSE_DIALOG(),
0x80,
0xff,
0xff,
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
