// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
SET_END(0x80100302),
WAIT_FOR_FLAG(0),
PLAY_SOUND(0x81),
SET_POS(60,36),
LOAD_PORTRAIT(0x80100002,0),
SET_PORTRAIT(0,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x356),
WAIT_FOR_SOUND(),
'D','r','a','c','u','l','a','.',' ','M','u','o','r','i','!',
LINE_BREAK(),
'A','b','b','a','n','d','o','n','a',' ','q','u','e','s','t','o',' ','m','o','n','d','o','!',
LINE_BREAK(),
'N','o','n',' ','c','i',' ','s','a','r','\xCB',
LINE_BREAK(),
'm','a','i',' ','p','o','s','t','o',' ','p','e','r',' ','t','e',',',' ','q','u','i','!',
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x80100003,1),
SET_PORTRAIT(1,129),
PLAY_SOUND(0x357),
WAIT_FOR_SOUND(),
'E','p','p','u','r','e',' ','\xD0',' ','s','t','a','t','o',' ','q','u','e','s','t','o',
LINE_BREAK(),
'm','o','n','d','o',' ','a',' ','i','n','v','i','t','a','r','m','i','.',
LINE_BREAK(),
'S','o','n','o',' ','g','l','i',' ','s','t','e','s','s','i',' ','u','m','a','n','i',
LINE_BREAK(),
'c','h','e',' ','t','u',' ','p','r','o','t','e','g','g','i',' ','c','h','e',
LINE_BREAK(),
'm','i',' ','h','a','n','n','o',' ','r','i','c','h','i','a','m','a','t','o',
LINE_BREAK(),
'q','u','i',' ','c','o','n',' ','l','o','d','i',' ','e',' ','o','m','a','g','g','i','.',
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,0),
PLAY_SOUND(0x358),
WAIT_FOR_SOUND(),
SET_FLAG(10),
'O','m','a','g','g','i','?',' ','T','u',' ','s','e','i',' ','u','n',' ','l','a','d','r','o','.',
LINE_BREAK(),
SET_FLAG(11),
'R','u','b','i',' ','l','\'','a','n','i','m','a',' ','a','g','l','i',' ','u','o','m','i','n','i',',',
LINE_BREAK(),
SET_FLAG(12),
'r','u','b','i',' ','l','o','r','o',' ','l','a',' ','l','i','b','e','r','t','\xCB','.','.','.',
SET_FLAG(13),
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,129),
PLAY_SOUND(0x359),
WAIT_FOR_SOUND(),
'L','a',' ','l','i','b','e','r','t','\xCB',' ','v','i','e','n','e',' ','s','e','m','p','r','e',' ',
LINE_BREAK(),
's','a','c','r','i','f','i','c','a','t','a',' ','s','u','l','l','\'','a','l','t','a','r','e',
LINE_BREAK(),
'd','e','l','l','a',' ','f','e','d','e',',',' ','m','i','o',' ','b','u','o','n',
LINE_BREAK(),
'c','a','c','c','i','a','t','o','r','e','.',
LINE_BREAK(),
'O',' ','s','e','i',' ','d','a','v','v','e','r','o',' ','q','u','i',' ','p','e','r',
LINE_BREAK(),
't','u','a',' ','l','i','b','e','r','a',' ','s','c','e','l','t','a','?',
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,0),
PLAY_SOUND(0x35a),
WAIT_FOR_SOUND(),
SET_FLAG(14),
'S','o','n','o',' ','q','u','i',' ','s','o','l','o',' ','p','e','r',' ','t','e','.',
LINE_BREAK(),
SET_FLAG(15),
'A','l',' ','d','i','a','v','o','l','o',' ','l','e',' ','t','u','e',
LINE_BREAK(),
'e','r','e','s','i','e','!',
LINE_BREAK(),
SET_FLAG(16),
'N','o','n',' ','s','e','i',' ','a','l','t','r','o',' ','c','h','e',' ','u','n','a',
LINE_BREAK(),
'p','i','a','g','a',' ','c','h','e',' ','a','f','f','l','i','g','g','e',
LINE_BREAK(),
SET_FLAG(4),
SET_FLAG(17),
'l','\'','u','m','a','n','i','t','\xCB','.',
SET_FLAG(18),
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,129),
PLAY_SOUND(0x35b),
WAIT_FOR_SOUND(),
'A','h','!',' ','L','\'','u','m','a','n','i','t','\xCB','.',
LINE_BREAK(),
SET_FLAG(5),
'U','n',' ','i','m','m','o','n','d','o',' ','r','i','c','e','t','t','a','c','o','l','o',
LINE_BREAK(),
'd','i',' ','o','d','i','o',' ','e',' ','d','i',' ','b','u','g','i','e','.',
LINE_BREAK(),
'\xB9',' ','q','u','e','s','t','a',' ','l','a',' ','c','a','u','s','a',' ','p','e','r',
LINE_BREAK(),
'c','u','i',' ','c','o','m','b','a','t','t','i','?',
LINE_BREAK(),
'C','o','m','b','a','t','t','i',',',' ','a','l','l','o','r','a',',',' ','e',
LINE_BREAK(),
'o','f','f','r','i',' ','l','a',' ','t','u','a',' ','v','i','t','a',
LINE_BREAK(),
'p','e','r',' ','i',' ','l','o','r','o',' ','p','e','c','c','a','t','i','!',
WAIT_FOR_FLAG(8),
SET_FLAG(6),
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SCRIPT_UNKNOWN_20(0x31f),
SET_FLAG(2),
CLOSE_DIALOG(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
0x81,
SCRIPT_UNKNOWN_23(),
CLOSE_DIALOG(),
0x80,
CLOSE_DIALOG(),
0x80,
0xff,
0xff,
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
