// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
SET_END(0x80100259),
WAIT_FOR_FLAG(0),
PLAY_SOUND(0x81),
SET_POS(60,36),
LOAD_PORTRAIT(0x80100002,0),
SET_PORTRAIT(0,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x356),
WAIT_FOR_SOUND(),
'D','r','a','c','u','l','a','.',' ','D','i','e',' ','n','o','w',',',' ','a','n','d',
LINE_BREAK(),
'l','e','a','v','e',' ','t','h','i','s',' ','w','o','r','l','d','!',
LINE_BREAK(),
'Y','o','u','\'','l','l',' ','n','e','v','e','r',' ','b','e','l','o','n','g',' ','h','e','r','e','!',
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x80100003,1),
SET_PORTRAIT(1,129),
PLAY_SOUND(0x357),
WAIT_FOR_SOUND(),
'O','h',',',' ','b','u','t',' ','t','h','i','s',' ','w','o','r','l','d',
LINE_BREAK(),
'i','n','v','i','t','e','d',' ','m','e','.',' ','Y','o','u','r',' ','o','w','n',
LINE_BREAK(),
'k','i','n','d',' ','c','a','l','l','e','d',' ','m','e',' ','f','o','r','t','h',
LINE_BREAK(),
'w','i','t','h',' ','p','r','a','i','s','e',' ','a','n','d',' ','t','r','i','b','u','t','e','.',
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,0),
PLAY_SOUND(0x358),
WAIT_FOR_SOUND(),
SET_FLAG(10),
'T','r','i','b','u','t','e','?',' ','Y','o','u','\'','r','e',' ','a',' ','t','h','i','e','f','.',
LINE_BREAK(),
SET_FLAG(11),
'Y','o','u',' ','s','t','e','a','l',' ','m','e','n','\'','s',' ','s','o','u','l','s',',',
LINE_BREAK(),
SET_FLAG(12),
't','h','e','i','r',' ','f','r','e','e','d','o','m','.','.','.',
SET_FLAG(13),
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,129),
PLAY_SOUND(0x359),
WAIT_FOR_SOUND(),
'F','r','e','e','d','o','m',' ','i','s',' ','a','l','w','a','y','s',' ',
LINE_BREAK(),
's','a','c','r','i','f','i','c','e','d',' ','t','o',' ','f','a','i','t','h',',',' ',
LINE_BREAK(),
'g','o','o','d',' ','h','u','n','t','e','r','.',' ','O','r',' ','a','r','e',' ','y','o','u',
LINE_BREAK(),
't','r','u','l','y',' ','h','e','r','e',' ','b','y',' ','c','h','o','i','c','e','?',
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,0),
PLAY_SOUND(0x35a),
WAIT_FOR_SOUND(),
SET_FLAG(14),
'A','l','l',' ','I','\'','m',' ','h','e','r','e',' ','f','o','r',' ','i','s',' ','y','o','u','.',
LINE_BREAK(),
SET_FLAG(15),
'T','o',' ','h','e','l','l',' ','w','i','t','h',' ','y','o','u','r',' ','h','e','r','e','s','y','!',
LINE_BREAK(),
SET_FLAG(16),
'Y','o','u','\'','r','e',' ','n','o','t','h','i','n','g',' ','b','u','t',' ','a',
LINE_BREAK(),
SET_FLAG(4),
SET_FLAG(17),
'b','l','i','g','h','t',' ','o','n',' ','m','a','n','k','i','n','d','.',
SET_FLAG(18),
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,129),
PLAY_SOUND(0x35b),
WAIT_FOR_SOUND(),
'H','a','!',' ','M','a','n','k','i','n','d','.',' ','A',' ','c','e','s','s','p','i','t',' ','o','f',
LINE_BREAK(),
SET_FLAG(5),
'h','a','t','r','e','d',' ','a','n','d',' ','l','i','e','s','.',
LINE_BREAK(),
'F','i','g','h','t',' ','f','o','r',' ','t','h','e','m',',',' ','t','h','e','n',',',
LINE_BREAK(),
'a','n','d',' ','d','i','e',' ','f','o','r',' ','t','h','e','i','r',' ','s','i','n','s','!',
WAIT_FOR_FLAG(8),
SET_FLAG(6),
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SCRIPT_UNKNOWN_20(0x31f),
SET_FLAG(2),
CLOSE_DIALOG(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
0x81,
SCRIPT_UNKNOWN_23(),
CLOSE_DIALOG(),
0x80,
CLOSE_DIALOG(),
0x80,
0xff,
0xff,
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
