// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
SET_END(0x801002bb),
WAIT_FOR_FLAG(0),
PLAY_SOUND(0x81),
SET_POS(60,36),
LOAD_PORTRAIT(0x80100002,0),
SET_PORTRAIT(0,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x356),
WAIT_FOR_SOUND(),
'D','r','a','c','u','l','a','.',' ','T','u',' ','v','a','s',' ','m','o','u','r','i','r',' ','e','t',
LINE_BREAK(),
'q','u','i','t','t','e','r',' ','c','e',' ','m','o','n','d','e',' ','!',' ','T','u',' ','n','\'','a','s',
LINE_BREAK(),
'r','i','e','n',' ','\xCB',' ','y',' ','f','a','i','r','e',' ','!',
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x80100003,1),
SET_PORTRAIT(1,129),
PLAY_SOUND(0x357),
WAIT_FOR_SOUND(),
'O','h',',',' ','m','a','i','s',' ','c','\'','e','s','t',' ','c','e',' ','m','o','n','d','e',
LINE_BREAK(),
'q','u','i',' ','m','\'','a',' ','i','n','v','i','t','\xD1','.',' ','T','a',' ','p','r','o','p','r','e',
LINE_BREAK(),
'r','a','c','e',' ','m','\'','a',' ','a','p','p','e','l','\xD1',' ','a','v','e','c',
LINE_BREAK(),
'r','e','s','p','e','c','t',' ','e','t',' ','s','o','u','m','i','s','s','i','o','n','.',
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,0),
PLAY_SOUND(0x358),
WAIT_FOR_SOUND(),
SET_FLAG(10),
'R','e','s','p','e','c','t',' ','?',' ','T','u',' ','n','\'','e','s',' ','q','u','\'','u','n',
LINE_BREAK(),
'v','o','l','e','u','r','.',
LINE_BREAK(),
SET_FLAG(11),
'T','u',' ','t','\'','e','m','p','a','r','e','s',' ','d','e',
LINE_BREAK(),
'l','\'','\xCD','m','e',' ','d','e','s',' ','g','e','n','s',',',
LINE_BREAK(),
SET_FLAG(12),
'd','e',' ','l','e','u','r',' ','l','i','b','e','r','t','\xD1','.','.','.',' ',
SET_FLAG(13),
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,129),
PLAY_SOUND(0x359),
WAIT_FOR_SOUND(),
'L','a',' ','l','i','b','e','r','t','\xD1',' ','e','s','t',' ','t','o','u','j','o','u','r','s',
LINE_BREAK(),
's','a','c','r','i','f','i','\xD1','e',' ','s','u','r',' ','l','\'','a','u','t','e','l',
LINE_BREAK(),
'd','e',' ','l','a',' ','f','o','i',',',' ','t','r','\xD0','s',' ','c','h','e','r',
LINE_BREAK(),
'c','h','a','s','s','e','u','r','.',' ','P','o','u','r','q','u','o','i',
LINE_BREAK(),
'c','r','o','i','s','-','t','u',' ','\xD2','t','r','e',' ','i','c','i',' ','?',
LINE_BREAK(),
'P','a','r',' ','c','h','o','i','x',' ','?',
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(0,0),
PLAY_SOUND(0x35a),
WAIT_FOR_SOUND(),
SET_FLAG(14),
'J','e',' ','s','u','i','s',' ','v','e','n','u',' ','i','c','i',
LINE_BREAK(),
'u','n','i','q','u','e','m','e','n','t',' ','p','o','u','r',' ','t','o','i','.',
LINE_BREAK(),
SET_FLAG(15),
'P','o','u','r',' ','e','n',' ','f','i','n','i','r',' ','a','v','e','c',' ','t','o','n',
LINE_BREAK(),
'h','\xD1','r','\xD1','s','i','e',' ','!',
LINE_BREAK(),
SET_FLAG(16),
'T','u',' ','n','\'','e','s',' ','q','u','\'','u','n',
LINE_BREAK(),
SET_FLAG(4),
SET_FLAG(17),
'f','l','\xD1','a','u',' ','p','o','u','r',' ','l','\'','h','u','m','a','n','i','t','\xD1','.',
SET_FLAG(18),
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SET_PORTRAIT(1,129),
PLAY_SOUND(0x35b),
WAIT_FOR_SOUND(),
'A','h',' ','!',' ','L','\'','h','u','m','a','n','i','t','\xD1','.',' ','U','n',
LINE_BREAK(),
SET_FLAG(5),
'c','l','o','a','q','u','e',' ','d','e',' ','h','a','i','n','e',' ','e','t',' ','d','e',
LINE_BREAK(),
'm','e','n','s','o','n','g','e','s','.',' ','B','a','t','s','-','t','o','i',' ','p','o','u','r',
LINE_BREAK(),
'e','l','l','e',',',' ','a','l','o','r','s',',',' ','e','t',' ','m','e','u','r','s',' ','p','o','u','r',
LINE_BREAK(),
's','e','s',' ','p','\xD1','c','h','\xD1','s',' ','!',
WAIT_FOR_FLAG(8),
SET_FLAG(6),
SET_WAIT(64),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SCRIPT_UNKNOWN_20(0x31f),
SET_FLAG(2),
CLOSE_DIALOG(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
0x81,
SCRIPT_UNKNOWN_23(),
CLOSE_DIALOG(),
0x80,
CLOSE_DIALOG(),
0x80,
0xff,
0xff,
END_CUTSCENE(),
END_CUTSCENE(),
