// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[1][16];
} g_Stage15SpriteBank23Palette = {
    0x0001,
    {
        {
            0x848F,
            0x9084,
            0x9909,
            0xA9AE,
            0xBE54,
            0xCAB7,
            0xDB3C,
            0xB94B,
            0x8D02,
            0x95AA,
            0xA6D2,
            0x81B4,
            0x921A,
            0x9F1C,
            0x801B,
            0x8421,
        },
    },
};

SaturnSpriteFrameHeader g_Stage15SpriteBank23Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame5 g_Stage15SpriteBank23Frame1 = {
    {0x0500, 0x0000},
    {
        {0x0000, 5, 8, 0},
        {0x0000, -8, -3, 1},
        {0x0000, -3, -11, 2},
        {0x0000, 0, -6, 3},
        {0x0000, -1, -1, 4},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank23Frame2 = {
    {0x0500, 0x0000},
    {
        {0x0000, 5, 7, 5},
        {0x0000, -9, -4, 1},
        {0x0000, -3, -12, 2},
        {0x0000, 1, -7, 3},
        {0x0000, 0, -2, 4},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank23Frame3 = {
    {0x0500, 0x0000},
    {
        {0x0000, -11, -5, 1},
        {0x0000, 3, 7, 6},
        {0x0000, -3, -13, 2},
        {0x0000, 1, -8, 3},
        {0x0000, 0, -3, 4},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank23Frame4 = {
    {0x0500, 0x0000},
    {
        {0x0000, -12, -3, 1},
        {0x0000, 4, 8, 7},
        {0x0000, -3, -11, 2},
        {0x0000, 2, -6, 3},
        {0x0000, 1, -1, 4},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank23Frame5 = {
    {0x0500, 0x0000},
    {
        {0x0000, -11, -4, 1},
        {0x0000, -1, 8, 8},
        {0x0000, -3, -12, 2},
        {0x0000, 1, -7, 3},
        {0x0000, 0, -2, 4},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank23Frame6 = {
    {0x0500, 0x0000},
    {
        {0x0000, -10, -5, 1},
        {0x0000, 1, 8, 9},
        {0x0000, -3, -13, 2},
        {0x0000, 1, -8, 3},
        {0x0000, 0, -3, 4},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank23Frame7 = {
    {0x0400, 0x0000},
    {
        {0x0000, 5, 6, 6},
        {0x0000, -3, -13, 2},
        {0x0000, -3, -8, 3},
        {0x0000, -3, -4, 4},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank23Frame8 = {
    {0x0400, 0x0000},
    {
        {0x0000, 4, 8, 7},
        {0x0000, -3, -11, 2},
        {0x0000, -8, -6, 3},
        {0x0000, -8, -2, 4},
    },
};

SaturnSpriteFrame2 g_Stage15SpriteBank23Frame9 = {
    {0x0200, 0x0000},
    {
        {0x0000, -2, -1, 10},
        {0x0000, -14, -8, 4},
    },
};

SaturnSpriteFrame2 g_Stage15SpriteBank23Frame10 = {
    {0x0200, 0x0000},
    {
        {0x0000, -2, -2, 11},
        {0x0000, -10, -3, 12},
    },
};

SaturnSpriteFrame2 g_Stage15SpriteBank23Frame11 = {
    {0x0200, 0x0000},
    {
        {0x0000, -4, -3, 13},
        {0x0010, -6, -3, 4},
    },
};

SaturnSpriteFrame2 g_Stage15SpriteBank23Frame12 = {
    {0x0200, 0x0000},
    {
        {0x0000, -1, -1, 14},
        {0x0010, 8, -7, 4},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank23Frame13 = {
    {0x0500, 0x0000},
    {
        {0x0000, 4, 9, 15},
        {0x0000, -14, -3, 1},
        {0x0000, -6, -9, 2},
        {0x0000, -3, -4, 3},
        {0x0000, -4, 1, 4},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank23Frame14 = {
    {0x0500, 0x0000},
    {
        {0x0000, 4, 10, 16},
        {0x0000, -16, -7, 1},
        {0x0000, -5, -7, 2},
        {0x0000, -3, -5, 3},
        {0x0000, -4, -1, 4},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank23Frame15 = {
    {0x0100, 0x0000},
    {
        {0x0000, 5, -1, 17},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank23Frame16 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 1, 18},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank23Frame17 = {
    {0x0100, 0x0000},
    {
        {0x0000, -1, 2, 3},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank23Frame18 = {
    {0x0100, 0x0000},
    {
        {0x0010, 4, 1, 3},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank23Frame19 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 1, 19},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank23Frame20 = {
    {0x0100, 0x0000},
    {
        {0x0010, 0, 1, 19},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank23Frame21 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, -2, 4},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank23Frame22 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 0, 20},
    },
};

u16 g_Stage15SpriteBank23FramePadding = 0;

SaturnSpriteFrameHeader* g_Stage15SpriteBank23Frames[23] = {
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame0,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame1,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame2,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame3,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame4,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame5,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame6,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame7,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame8,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame9,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame10,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame11,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame12,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame13,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame14,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame15,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame16,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame17,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame18,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame19,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame20,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame21,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank23Frame22,
};

SaturnSpriteImage g_Stage15SpriteBank23Images[22] = {
    {12, 13, 0x0000}, {8, 2, 0x0028},   {8, 9, 0x002C},   {8, 6, 0x0040},
    {8, 8, 0x004C},   {12, 13, 0x005C}, {8, 13, 0x0084},  {8, 13, 0x00A0},
    {8, 13, 0x00BC},  {12, 13, 0x00D8}, {16, 21, 0x0100}, {20, 23, 0x0154},
    {12, 8, 0x01C8},  {16, 23, 0x01E0}, {20, 20, 0x023C}, {12, 12, 0x02A0},
    {12, 11, 0x02C4}, {8, 5, 0x02E8},   {8, 6, 0x02F4},   {4, 11, 0x0300},
    {4, 7, 0x030C},   {0, 0, 0x0314},
};
