// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[4][16];
    u16 padding[1];
} g_Stage15SpriteBank27Palette = {
    0x0004,
    {
        {
            0x8100,
            0xFFFF,
            0xFBDA,
            0xF377,
            0xEF14,
            0xE6B2,
            0xE24F,
            0xDDED,
            0xB9DA,
            0xAD56,
            0xA0D2,
            0x986F,
            0x8858,
            0x842F,
            0x8006,
            0x8000,
        },
        {
            0x8100,
            0xE2D4,
            0xE2D2,
            0xDA70,
            0xD20D,
            0xC9AB,
            0xC148,
            0xB8E6,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
        },
        {
            0x8100,
            0xFF54,
            0xFAD3,
            0xFA91,
            0xFE4F,
            0xFE0D,
            0xFDCB,
            0xFD69,
            0xD516,
            0xCCF1,
            0xC4AD,
            0xC089,
            0xE413,
            0xD009,
            0xBC00,
            0x8000,
        },
        {
            0x8100,
            0xFB54,
            0xFE0D,
            0xFEAE,
            0xFF4F,
            0xFFF1,
            0xFE09,
            0xFD04,
            0xDD49,
            0xE9AA,
            0xFE8A,
            0xFDAA,
            0xFE08,
            0xFD25,
            0xFD29,
            0xFC00,
        },
    },
    {0x0000},
};

SaturnSpriteFrameHeader g_Stage15SpriteBank27Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame3 g_Stage15SpriteBank27Frame1 = {
    {0x0300, 0x0000},
    {
        {0x0000, -3, 4, 0},
        {0x0000, 32, 2, 1},
        {0x0000, 11, -9, 2},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank27Frame2 = {
    {0x0300, 0x0000},
    {
        {0x0000, -3, 4, 0},
        {0x0000, 3, -15, 3},
        {0x0000, 31, 3, 4},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank27Frame3 = {
    {0x0300, 0x0000},
    {
        {0x0000, 28, -3, 5},
        {0x0000, -3, 4, 0},
        {0x0000, 3, -15, 3},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank27Frame4 = {
    {0x0300, 0x0000},
    {
        {0x0000, 31, 2, 6},
        {0x0000, -3, 4, 0},
        {0x0000, 3, 7, 7},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank27Frame5 = {
    {0x0300, 0x0000},
    {
        {0x0000, -3, 4, 0},
        {0x0000, 28, 6, 8},
        {0x0000, 3, 7, 7},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank27Frame6 = {
    {0x0400, 0x0000},
    {
        {0x0100, 12, -9, 2},
        {0x0000, -3, 4, 0},
        {0x0000, 24, -2, 9},
        {0x0000, 10, -9, 2},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank27Frame7 = {
    {0x0400, 0x0000},
    {
        {0x0100, 9, -9, 2},
        {0x0000, -3, 4, 0},
        {0x0000, 24, 4, 10},
        {0x0000, 12, -9, 2},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank27Frame8 = {
    {0x0300, 0x0000},
    {
        {0x0000, -12, -10, 11},
        {0x0000, 12, 4, 12},
        {0x0000, 23, -9, 13},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank27Frame9 = {
    {0x0300, 0x0000},
    {
        {0x0000, 2, 4, 14},
        {0x0000, 30, -10, 15},
        {0x0010, -31, -10, 15},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank27Frame10 = {
    {0x0300, 0x0000},
    {
        {0x0000, 1, 4, 16},
        {0x0010, 12, -12, 11},
        {0x0010, -24, -9, 13},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank27Frame11 = {
    {0x0300, 0x0000},
    {
        {0x0010, 3, 4, 0},
        {0x0010, -32, 2, 1},
        {0x0010, -11, -9, 2},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank27Frame12 = {
    {0x0500, 0x0000},
    {
        {0x0000, 31, 3, 4},
        {0x0000, -9, 0, 17},
        {0x0000, 0, 4, 18},
        {0x0000, -6, 2, 19},
        {0x0000, 3, -15, 3},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank27Frame13 = {
    {0x0500, 0x0000},
    {
        {0x0000, 0, 4, 18},
        {0x0000, -13, 1, 17},
        {0x0000, -6, 2, 19},
        {0x0000, 28, -3, 5},
        {0x0000, 3, -15, 3},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank27Frame14 = {
    {0x0500, 0x0000},
    {
        {0x0000, 0, 4, 18},
        {0x0000, -18, 0, 17},
        {0x0000, -3, 2, 20},
        {0x0000, 32, 2, 1},
        {0x0000, 13, -8, 2},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank27Frame15 = {
    {0x0500, 0x0000},
    {
        {0x0000, 31, 2, 6},
        {0x0000, 0, 4, 18},
        {0x0000, -16, 1, 21},
        {0x0000, -3, 2, 20},
        {0x0000, 5, 8, 7},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank27Frame16 = {
    {0x0500, 0x0000},
    {
        {0x0000, 0, 4, 18},
        {0x0000, -16, 0, 22},
        {0x0000, -3, 2, 20},
        {0x0000, 28, 6, 8},
        {0x0000, 5, 8, 7},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank27Frame17 = {
    {0x0500, 0x0000},
    {
        {0x0000, 31, 2, 6},
        {0x0000, 0, 4, 18},
        {0x0000, -3, 2, 20},
        {0x0000, -16, 0, 22},
        {0x0000, 5, 8, 7},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank27Frame18 = {
    {0x0500, 0x0000},
    {
        {0x0000, 28, 6, 8},
        {0x0000, 0, 4, 18},
        {0x0000, -3, 2, 20},
        {0x0000, -16, 0, 22},
        {0x0000, 5, 8, 7},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank27Frame19 = {
    {0x0500, 0x0000},
    {
        {0x0000, 31, 3, 4},
        {0x0000, 0, 4, 18},
        {0x0000, -16, 1, 21},
        {0x0000, -3, 2, 20},
        {0x0000, 5, -14, 3},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank27Frame20 = {
    {0x0500, 0x0000},
    {
        {0x0000, 0, 4, 18},
        {0x0000, -16, 1, 21},
        {0x0000, -3, 2, 20},
        {0x0000, 5, -14, 3},
        {0x0000, 28, -3, 5},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank27Frame21 = {
    {0x0500, 0x0000},
    {
        {0x0000, -18, 1, 21},
        {0x0000, 0, 4, 18},
        {0x0000, -6, 2, 19},
        {0x0000, 31, 2, 6},
        {0x0000, 11, -9, 2},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank27Frame22 = {
    {0x0500, 0x0000},
    {
        {0x0000, -20, 1, 17},
        {0x0000, 0, 4, 18},
        {0x0000, -6, 2, 19},
        {0x0000, 28, 6, 8},
        {0x0000, 11, -10, 2},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank27Frame23 = {
    {0x0300, 0x0000},
    {
        {0x0000, -16, 2, 22},
        {0x0000, 6, 9, 23},
        {0x0000, 3, -15, 3},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank27Frame24 = {
    {0x0100, 0x0000},
    {
        {0x0200, 4, 0, 24},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank27Frame25 = {
    {0x0100, 0x0000},
    {
        {0x0300, 4, 0, 24},
    },
};

SaturnSpriteFrameHeader* g_Stage15SpriteBank27Frames[26] = {
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame0,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame1,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame2,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame3,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame4,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame5,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame6,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame7,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame8,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame9,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame10,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame11,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame12,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame13,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame14,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame15,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame16,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame17,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame18,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame19,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame20,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame21,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame22,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame23,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame24,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank27Frame25,
};

SaturnSpriteImage g_Stage15SpriteBank27Images[26] = {
    {16, 12, 0x0000}, {20, 7, 0x0030},  {20, 7, 0x0054},  {12, 12, 0x0078},
    {24, 11, 0x009C}, {20, 16, 0x00E0}, {24, 13, 0x0130}, {12, 12, 0x0180},
    {20, 12, 0x01A4}, {12, 10, 0x01E0}, {12, 9, 0x0200},  {12, 6, 0x021C},
    {28, 12, 0x0230}, {24, 7, 0x0284},  {16, 12, 0x02B0}, {20, 7, 0x02E0},
    {16, 12, 0x0304}, {8, 2, 0x0334},   {12, 12, 0x0338}, {12, 11, 0x035C},
    {12, 12, 0x0380}, {8, 3, 0x03A4},   {8, 3, 0x03AC},   {24, 18, 0x03B4},
    {28, 27, 0x0420}, {0, 0, 0x04E0},
};
