// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[6][16];
    u16 padding[1];
} g_Stage15SpriteBank29Palette = {
    0x0006,
    {
        {
            0x88AA,
            0x8DE9,
            0x9563,
            0x9122,
            0x8CE1,
            0x88C1,
            0x8480,
            0x8460,
            0x8460,
            0x8197,
            0x8132,
            0x80CD,
            0x8069,
            0xAF39,
            0x9633,
            0x812E,
        },
        {
            0x88A8,
            0xCFF9,
            0xA68A,
            0xA1E0,
            0x99A0,
            0x9560,
            0x9120,
            0x8CE0,
            0x88A0,
            0x867F,
            0x81B8,
            0x8110,
            0x8069,
            0xB3DE,
            0x9EB8,
            0x8171,
        },
        {
            0x88AA,
            0x9A4C,
            0x9DA4,
            0x9963,
            0x9522,
            0x90E1,
            0x8CA0,
            0x8880,
            0x8460,
            0x81B8,
            0x8153,
            0x80EE,
            0x848A,
            0xAF39,
            0x9633,
            0x812E,
        },
        {
            0x88AA,
            0x9D89,
            0x9947,
            0x9526,
            0x9505,
            0x90C4,
            0x8CA3,
            0x8C82,
            0x8041,
            0x8975,
            0x8911,
            0x88CD,
            0x8889,
            0xA672,
            0x95AF,
            0x890C,
        },
        {
            0x88AA,
            0x9985,
            0x9544,
            0x9123,
            0x90E3,
            0x8CC2,
            0x8881,
            0x8861,
            0x8841,
            0x8155,
            0x80F0,
            0x808B,
            0x8047,
            0x9EB4,
            0x8DD0,
            0x80EC,
        },
        {
            0x88AA,
            0x823F,
            0x81DE,
            0x817C,
            0x813B,
            0x80D7,
            0x8093,
            0x804F,
            0x800C,
            0x813F,
            0x80DA,
            0x8074,
            0x840F,
            0x81DF,
            0x819C,
            0x8158,
        },
    },
    {0x0000},
};

SaturnSpriteFrameHeader g_Stage15SpriteBank29Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame1 = {
    {0x0400, 0x0000},
    {
        {0x0000, 9, -8, 0},
        {0x0100, -1, -8, 1},
        {0x0100, -15, -38, 2},
        {0x0100, 19, -37, 3},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame2 = {
    {0x0400, 0x0000},
    {
        {0x0000, 9, -8, 0},
        {0x0100, -1, -8, 1},
        {0x0100, -15, -37, 2},
        {0x0100, 18, -36, 3},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame3 = {
    {0x0400, 0x0000},
    {
        {0x0000, 9, -8, 0},
        {0x0100, -1, -8, 1},
        {0x0100, -16, -36, 2},
        {0x0100, 18, -35, 3},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame4 = {
    {0x0400, 0x0000},
    {
        {0x0000, 9, -8, 0},
        {0x0100, -15, -37, 2},
        {0x0100, -1, -8, 1},
        {0x0100, -2, -37, 4},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame5 = {
    {0x0400, 0x0000},
    {
        {0x0000, 9, -8, 0},
        {0x0100, -15, -37, 2},
        {0x0100, -1, -8, 1},
        {0x0100, -4, -37, 4},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame6 = {
    {0x0400, 0x0000},
    {
        {0x0000, 9, -8, 0},
        {0x0200, -11, -37, 5},
        {0x0100, -1, -8, 1},
        {0x0100, -4, -34, 6},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame7 = {
    {0x0400, 0x0000},
    {
        {0x0000, 9, -8, 0},
        {0x0000, -8, -37, 5},
        {0x0100, -1, -8, 1},
        {0x0100, -5, -34, 6},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame8 = {
    {0x0400, 0x0000},
    {
        {0x0000, 9, -8, 0},
        {0x0200, -11, -38, 2},
        {0x0100, -1, -8, 1},
        {0x0100, -10, -38, 7},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame9 = {
    {0x0400, 0x0000},
    {
        {0x0000, 9, -8, 0},
        {0x0200, -11, -38, 2},
        {0x0100, -1, -8, 1},
        {0x0100, -10, -38, 7},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame10 = {
    {0x0400, 0x0000},
    {
        {0x0000, 15, -8, 8},
        {0x0200, -11, -38, 2},
        {0x0100, -8, -8, 9},
        {0x0100, -10, -38, 7},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame11 = {
    {0x0400, 0x0000},
    {
        {0x0000, 9, -8, 0},
        {0x0200, -9, -37, 5},
        {0x0100, -16, -8, 10},
        {0x0100, -6, -34, 6},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame12 = {
    {0x0400, 0x0000},
    {
        {0x0000, -4, -8, 1},
        {0x0200, -9, -37, 5},
        {0x0100, -8, -8, 9},
        {0x0100, -6, -34, 6},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame13 = {
    {0x0400, 0x0000},
    {
        {0x0000, -9, -8, 9},
        {0x0200, -11, -38, 2},
        {0x0100, -1, -8, 1},
        {0x0100, -10, -38, 7},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank29Frame14 = {
    {0x0500, 0x0000},
    {
        {0x0000, -17, -8, 10},
        {0x0200, -11, -38, 2},
        {0x0100, 9, -8, 0},
        {0x0100, -10, -38, 7},
        {0x0100, -16, -7, 11},
    },
};

SaturnSpriteFrame6 g_Stage15SpriteBank29Frame15 = {
    {0x0600, 0x0000},
    {
        {0x0000, -8, -8, 9},
        {0x0200, -9, -37, 5},
        {0x0100, 16, -8, 12},
        {0x0100, 16, -8, 8},
        {0x0100, -6, -34, 6},
        {0x0100, -10, -8, 13},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank29Frame16 = {
    {0x0500, 0x0000},
    {
        {0x0000, -1, -8, 1},
        {0x0200, -9, -37, 5},
        {0x0100, 9, -8, 0},
        {0x0100, -6, -34, 6},
        {0x0100, -16, -7, 11},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame17 = {
    {0x0400, 0x0000},
    {
        {0x0000, 10, -8, 0},
        {0x0000, -7, -37, 5},
        {0x0100, -16, -8, 10},
        {0x0100, -4, -34, 6},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame18 = {
    {0x0400, 0x0000},
    {
        {0x0000, 10, -8, 0},
        {0x0100, -16, -8, 10},
        {0x0100, -8, -37, 2},
        {0x0100, 3, -37, 4},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame19 = {
    {0x0400, 0x0000},
    {
        {0x0000, 0, -8, 1},
        {0x0100, -7, -36, 2},
        {0x0100, -16, -8, 10},
        {0x0100, 5, -36, 4},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame20 = {
    {0x0400, 0x0000},
    {
        {0x0000, -6, -8, 9},
        {0x0100, -16, -8, 10},
        {0x0100, -9, -36, 2},
        {0x0100, 23, -35, 3},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame21 = {
    {0x0400, 0x0000},
    {
        {0x0000, -7, -8, 1},
        {0x0100, -15, -8, 9},
        {0x0200, -15, -37, 2},
        {0x0100, -4, -37, 4},
    },
};

SaturnSpriteFrame5 g_Stage15SpriteBank29Frame22 = {
    {0x0500, 0x0000},
    {
        {0x0000, -5, -8, 0},
        {0x0000, -40, -37, 14},
        {0x0100, -15, -8, 1},
        {0x0100, -37, -36, 15},
        {0x0100, -17, -17, 16},
    },
};

SaturnSpriteFrame6 g_Stage15SpriteBank29Frame23 = {
    {0x0600, 0x0000},
    {
        {0x0000, -32, -8, 9},
        {0x0100, -15, -8, 0},
        {0x0200, -52, -36, 17},
        {0x0100, -27, -16, 16},
        {0x0100, -52, -32, 18},
        {0x0100, -40, -7, 11},
    },
};

SaturnSpriteFrame6 g_Stage15SpriteBank29Frame24 = {
    {0x0600, 0x0000},
    {
        {0x0000, -48, -7, 10},
        {0x0100, -15, -7, 8},
        {0x0100, -34, -15, 16},
        {0x0200, -55, -37, 19},
        {0x0100, -55, -33, 20},
        {0x0100, -41, -7, 13},
    },
};

SaturnSpriteFrame6 g_Stage15SpriteBank29Frame25 = {
    {0x0600, 0x0000},
    {
        {0x0000, -26, -8, 1},
        {0x0200, -48, -39, 19},
        {0x0100, -15, -8, 0},
        {0x0100, -27, -16, 16},
        {0x0100, -48, -35, 20},
        {0x0100, -40, -7, 11},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame26 = {
    {0x0400, 0x0000},
    {
        {0x0000, -4, -8, 0},
        {0x0100, -22, -37, 21},
        {0x0100, -15, -8, 1},
        {0x0100, -21, -37, 22},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame27 = {
    {0x0400, 0x0000},
    {
        {0x0000, -4, -8, 0},
        {0x0100, -27, -38, 23},
        {0x0100, -15, -8, 1},
        {0x0100, -21, -33, 24},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame28 = {
    {0x0400, 0x0000},
    {
        {0x0000, -4, -8, 0},
        {0x0100, -15, -8, 1},
        {0x0100, -26, -37, 25},
        {0x0100, -21, -33, 26},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame29 = {
    {0x0400, 0x0000},
    {
        {0x0000, -4, -8, 0},
        {0x0100, -28, -39, 27},
        {0x0100, -15, -8, 1},
        {0x0100, -20, -36, 28},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame30 = {
    {0x0400, 0x0000},
    {
        {0x0000, -4, -8, 0},
        {0x0100, -27, -39, 27},
        {0x0100, -15, -8, 1},
        {0x0100, -22, -36, 29},
    },
};

SaturnSpriteFrame6 g_Stage15SpriteBank29Frame31 = {
    {0x0600, 0x0000},
    {
        {0x0000, -17, -8, 1},
        {0x0100, -5, -8, 0},
        {0x0200, -35, -39, 19},
        {0x0100, -17, -17, 16},
        {0x0100, -35, -35, 20},
        {0x0100, -30, -7, 11},
    },
};

SaturnSpriteFrame6 g_Stage15SpriteBank29Frame32 = {
    {0x0600, 0x0000},
    {
        {0x0000, -13, -8, 0},
        {0x0200, -47, -36, 17},
        {0x0100, -5, -8, 8},
        {0x0100, -23, -16, 16},
        {0x0100, -47, -32, 18},
        {0x0100, -31, -8, 13},
    },
};

SaturnSpriteFrame6 g_Stage15SpriteBank29Frame33 = {
    {0x0600, 0x0000},
    {
        {0x0000, 3, -8, 8},
        {0x0000, -40, -37, 14},
        {0x0100, -5, -8, 0},
        {0x0100, -17, -17, 16},
        {0x0100, -37, -36, 15},
        {0x0100, -30, -7, 11},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame34 = {
    {0x0400, 0x0000},
    {
        {0x0000, 9, -8, 0},
        {0x0000, -10, -37, 5},
        {0x0100, -2, -8, 1},
        {0x0100, -7, -34, 6},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame35 = {
    {0x0400, 0x0000},
    {
        {0x0000, 13, -8, 8},
        {0x0200, -11, -38, 2},
        {0x0100, -1, -8, 1},
        {0x0100, -10, -38, 7},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank29Frame36 = {
    {0x0400, 0x0000},
    {
        {0x0000, -6, -8, 1},
        {0x0100, -14, -37, 21},
        {0x0100, -14, -8, 9},
        {0x0100, -13, -37, 22},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame37 = {
    {0x0100, 0x0000},
    {
        {0x0300, 2, -5, 30},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame38 = {
    {0x0100, 0x0000},
    {
        {0x0300, 0, 1, 31},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame39 = {
    {0x0100, 0x0000},
    {
        {0x0300, -3, -2, 32},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame40 = {
    {0x0100, 0x0000},
    {
        {0x0300, 1, -2, 33},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame41 = {
    {0x0100, 0x0000},
    {
        {0x0300, -1, -3, 34},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame42 = {
    {0x0100, 0x0000},
    {
        {0x0300, 1, 2, 35},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame43 = {
    {0x0100, 0x0000},
    {
        {0x0310, 2, 0, 36},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame44 = {
    {0x0100, 0x0000},
    {
        {0x0300, -2, -1, 37},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame45 = {
    {0x0100, 0x0000},
    {
        {0x0300, -1, -1, 38},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame46 = {
    {0x0100, 0x0000},
    {
        {0x0300, 2, -1, 39},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame47 = {
    {0x0100, 0x0000},
    {
        {0x0300, -1, 0, 40},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame48 = {
    {0x0100, 0x0000},
    {
        {0x0300, -3, 1, 41},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame49 = {
    {0x0100, 0x0000},
    {
        {0x0300, -2, 1, 42},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame50 = {
    {0x0100, 0x0000},
    {
        {0x0300, 1, -2, 43},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame51 = {
    {0x0100, 0x0000},
    {
        {0x0300, -1, -1, 44},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame52 = {
    {0x0100, 0x0000},
    {
        {0x0300, -1, 0, 45},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame53 = {
    {0x0100, 0x0000},
    {
        {0x0300, -2, 1, 46},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame54 = {
    {0x0100, 0x0000},
    {
        {0x0300, -1, -2, 47},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame55 = {
    {0x0100, 0x0000},
    {
        {0x0300, -1, -2, 48},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame56 = {
    {0x0100, 0x0000},
    {
        {0x0300, -3, -6, 49},
    },
};

SaturnSpriteFrame15 g_Stage15SpriteBank29Frame57 = {
    {0x0F00, 0x0000},
    {
        {0x0400, -6, -50, 43},
        {0x0420, -17, -30, 48},
        {0x0400, -24, -56, 49},
        {0x0400, -29, -37, 32},
        {0x0400, -18, -25, 47},
        {0x0400, 17, -6, 38},
        {0x0400, 12, -6, 33},
        {0x0400, -18, -2, 35},
        {0x0400, -16, -3, 36},
        {0x0400, -4, -10, 34},
        {0x0400, -10, -57, 40},
        {0x0400, 3, -46, 45},
        {0x0400, -6, -22, 46},
        {0x0400, -22, -37, 42},
        {0x0400, -21, -21, 41},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank29Frame58 = {
    {0x0100, 0x0000},
    {
        {0x0500, -3, -6, 49},
    },
};

SaturnSpriteFrameHeader* g_Stage15SpriteBank29Frames[59] = {
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame0,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame1,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame2,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame3,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame4,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame5,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame6,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame7,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame8,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame9,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame10,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame11,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame12,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame13,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame14,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame15,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame16,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame17,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame18,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame19,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame20,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame21,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame22,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame23,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame24,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame25,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame26,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame27,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame28,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame29,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame30,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame31,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame32,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame33,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame34,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame35,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame36,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame37,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame38,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame39,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame40,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame41,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame42,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame43,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame44,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame45,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame46,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame47,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame48,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame49,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame50,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame51,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame52,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame53,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame54,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame55,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame56,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame57,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank29Frame58,
};

SaturnSpriteImage g_Stage15SpriteBank29Images[51] = {
    {36, 12, 0x0000}, {36, 12, 0x006C}, {28, 32, 0x00D8}, {24, 32, 0x01B8},
    {20, 32, 0x0278}, {28, 32, 0x0318}, {24, 32, 0x03F8}, {28, 32, 0x04B8},
    {36, 12, 0x0598}, {36, 12, 0x0604}, {36, 12, 0x0670}, {12, 8, 0x06DC},
    {36, 12, 0x06F4}, {8, 8, 0x0760},   {24, 32, 0x0770}, {20, 32, 0x0830},
    {8, 8, 0x08D0},   {24, 36, 0x08E0}, {24, 32, 0x09B8}, {20, 32, 0x0A78},
    {20, 28, 0x0B18}, {24, 28, 0x0BA4}, {24, 28, 0x0C4C}, {20, 24, 0x0CF4},
    {24, 28, 0x0D6C}, {20, 20, 0x0E14}, {24, 24, 0x0E78}, {16, 24, 0x0F08},
    {24, 28, 0x0F68}, {24, 28, 0x1010}, {12, 16, 0x10B8}, {16, 16, 0x10E8},
    {16, 16, 0x1128}, {12, 8, 0x1168},  {12, 12, 0x1180}, {16, 8, 0x11A4},
    {12, 8, 0x11C4},  {8, 12, 0x11DC},  {16, 8, 0x11F4},  {16, 16, 0x1214},
    {16, 16, 0x1254}, {16, 12, 0x1294}, {12, 16, 0x12C4}, {8, 16, 0x12F4},
    {8, 12, 0x1314},  {16, 16, 0x132C}, {16, 16, 0x136C}, {12, 16, 0x13AC},
    {16, 16, 0x13DC}, {16, 16, 0x141C}, {0, 0, 0x145C},
};
