// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[1][16];
    u16 padding[1];
} g_Stage15SpriteBank31Palette = {
    0x0001,
    {
        {
            0x848D,
            0x9084,
            0x9909,
            0xA9AE,
            0xBE54,
            0xCAB7,
            0xDB3C,
            0xB94B,
            0x8D22,
            0x95AA,
            0xA66D,
            0x8114,
            0x91FC,
            0x9EDC,
            0x801B,
            0x8421,
        },
    },
    {0x0000},
};

SaturnSpriteFrameHeader g_Stage15SpriteBank31Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame13 g_Stage15SpriteBank31Frame1 = {
    {0x0D00, 0x0000},
    {
        {0x0000, -6, -15, 0},
        {0x0000, -10, -19, 1},
        {0x0000, -11, -17, 2},
        {0x0000, -8, -4, 3},
        {0x0000, -5, -10, 4},
        {0x0000, 11, -13, 5},
        {0x0000, 16, -4, 6},
        {0x0000, -2, -11, 5},
        {0x0000, 6, -15, 7},
        {0x0000, -4, -4, 3},
        {0x0000, 8, -11, 5},
        {0x0000, 13, -4, 6},
        {0x0000, 17, -15, 8},
    },
};

SaturnSpriteFrame13 g_Stage15SpriteBank31Frame2 = {
    {0x0D00, 0x0000},
    {
        {0x0000, -9, -8, 3},
        {0x0000, -5, -13, 4},
        {0x0000, 11, -13, 5},
        {0x0000, 16, -7, 6},
        {0x0000, -5, -15, 0},
        {0x0000, 6, -16, 7},
        {0x0000, -10, -20, 1},
        {0x0000, -12, -18, 2},
        {0x0000, 16, -18, 9},
        {0x0000, 15, -11, 10},
        {0x0000, 23, -4, 6},
        {0x0000, -3, -11, 4},
        {0x0000, -7, -6, 3},
    },
};

SaturnSpriteFrame13 g_Stage15SpriteBank31Frame3 = {
    {0x0D00, 0x0000},
    {
        {0x0000, 19, -12, 11},
        {0x0000, 9, -13, 0},
        {0x0000, -11, -8, 3},
        {0x0000, -2, -13, 12},
        {0x0000, -6, -15, 0},
        {0x0000, 5, -15, 7},
        {0x0000, -11, -19, 1},
        {0x0000, -12, -16, 2},
        {0x0000, -6, -11, 4},
        {0x0000, -11, -6, 13},
        {0x0000, 14, -18, 14},
        {0x0020, 14, -15, 12},
        {0x0000, 24, -9, 6},
    },
};

SaturnSpriteFrame13 g_Stage15SpriteBank31Frame4 = {
    {0x0D00, 0x0000},
    {
        {0x0000, 12, -14, 10},
        {0x0000, 18, -7, 6},
        {0x0000, -6, -8, 5},
        {0x0000, -10, -3, 13},
        {0x0000, 5, -13, 7},
        {0x0000, -10, -17, 1},
        {0x0000, -11, -14, 2},
        {0x0010, -6, -9, 4},
        {0x0000, -3, -3, 13},
        {0x0000, -6, -11, 0},
        {0x0010, 6, -10, 10},
        {0x0000, 15, -4, 6},
        {0x0000, 15, -14, 9},
    },
};

SaturnSpriteFrame11 g_Stage15SpriteBank31Frame5 = {
    {0x0B00, 0x0000},
    {
        {0x0010, -9, -11, 4},
        {0x0000, -2, -4, 15},
        {0x0000, 5, -14, 7},
        {0x0000, -11, -18, 1},
        {0x0000, -12, -15, 2},
        {0x0000, -6, -13, 0},
        {0x0010, -7, -10, 12},
        {0x0000, 2, -4, 15},
        {0x0020, 9, -12, 16},
        {0x0000, -2, -5, 17},
        {0x0000, 15, -17, 14},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank31Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, -12, 18},
    },
};

SaturnSpriteFrame11 g_Stage15SpriteBank31Frame7 = {
    {0x0B00, 0x0000},
    {
        {0x0000, 11, -10, 11},
        {0x0000, -1, -4, 19},
        {0x0000, 5, -15, 7},
        {0x0000, -12, -19, 1},
        {0x0000, -13, -16, 2},
        {0x0000, -6, -14, 0},
        {0x0010, -5, -12, 4},
        {0x0000, -1, -8, 3},
        {0x0000, 12, -6, 6},
        {0x0000, 9, -13, 4},
        {0x0000, 15, -16, 9},
    },
};

SaturnSpriteFrame13 g_Stage15SpriteBank31Frame8 = {
    {0x0D00, 0x0000},
    {
        {0x0000, -6, -15, 0},
        {0x0000, -10, -19, 1},
        {0x0000, -11, -17, 2},
        {0x0000, -8, -4, 3},
        {0x0000, -5, -10, 4},
        {0x0000, 11, -13, 5},
        {0x0000, 16, -4, 6},
        {0x0000, -2, -11, 5},
        {0x0000, 6, -15, 7},
        {0x0000, -4, -4, 3},
        {0x0000, 8, -11, 5},
        {0x0000, 13, -4, 6},
        {0x0000, 17, -16, 9},
    },
};

SaturnSpriteFrame13 g_Stage15SpriteBank31Frame9 = {
    {0x0D00, 0x0000},
    {
        {0x0000, -6, -15, 0},
        {0x0000, -10, -19, 1},
        {0x0000, -11, -17, 2},
        {0x0000, -8, -4, 3},
        {0x0000, -5, -10, 4},
        {0x0000, 11, -13, 5},
        {0x0000, 16, -4, 6},
        {0x0000, -2, -11, 5},
        {0x0000, 6, -15, 7},
        {0x0000, -4, -4, 3},
        {0x0000, 8, -11, 5},
        {0x0000, 13, -4, 6},
        {0x0000, 16, -18, 14},
    },
};

SaturnSpriteFrame13 g_Stage15SpriteBank31Frame10 = {
    {0x0D00, 0x0000},
    {
        {0x0000, -6, -12, 0},
        {0x0000, -10, -16, 1},
        {0x0000, -11, -14, 2},
        {0x0000, -11, -2, 13},
        {0x0000, -5, -8, 4},
        {0x0000, 11, -10, 5},
        {0x0000, 18, -4, 6},
        {0x0000, -2, -8, 5},
        {0x0000, -7, -2, 13},
        {0x0000, 6, -12, 7},
        {0x0000, 8, -10, 5},
        {0x0000, 14, -4, 6},
        {0x0020, 17, -19, 8},
    },
};

SaturnSpriteFrame13 g_Stage15SpriteBank31Frame11 = {
    {0x0D00, 0x0000},
    {
        {0x0000, -6, -11, 0},
        {0x0000, -10, -15, 1},
        {0x0000, -12, -13, 2},
        {0x0000, -11, -2, 13},
        {0x0000, -5, -8, 4},
        {0x0000, 11, -10, 5},
        {0x0000, 18, -4, 6},
        {0x0000, -2, -8, 5},
        {0x0000, -7, -2, 13},
        {0x0000, 5, -12, 7},
        {0x0000, 8, -10, 5},
        {0x0000, 14, -4, 6},
        {0x0020, 16, -19, 8},
    },
};

SaturnSpriteFrame10 g_Stage15SpriteBank31Frame12 = {
    {0x0A00, 0x0000},
    {
        {0x0000, -1, -15, 3},
        {0x0010, -3, -25, 2},
        {0x0000, 5, -15, 20},
        {0x0000, -4, -4, 13},
        {0x0000, -7, -23, 2},
        {0x0000, -6, -26, 1},
        {0x0000, -7, -15, 3},
        {0x0030, -7, -19, 12},
        {0x0000, 4, -8, 12},
        {0x0000, -1, -3, 3},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank31Frame13 = {
    {0x0400, 0x0000},
    {
        {0x0000, 2, -24, 21},
        {0x0000, 9, -20, 22},
        {0x0000, 9, -12, 23},
        {0x0000, 6, -23, 24},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank31Frame14 = {
    {0x0400, 0x0000},
    {
        {0x0000, -4, -20, 25},
        {0x0000, -8, -10, 23},
        {0x0000, -8, -18, 22},
        {0x0000, -11, -21, 24},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank31Frame15 = {
    {0x0400, 0x0000},
    {
        {0x0000, -5, -20, 26},
        {0x0000, -7, -11, 23},
        {0x0000, -7, -19, 22},
        {0x0000, -10, -22, 24},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank31Frame16 = {
    {0x0400, 0x0000},
    {
        {0x0000, -6, -21, 27},
        {0x0000, -7, -12, 23},
        {0x0000, -7, -20, 22},
        {0x0000, -10, -23, 24},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank31Frame17 = {
    {0x0400, 0x0000},
    {
        {0x0000, -7, -20, 28},
        {0x0000, -6, -11, 23},
        {0x0000, -6, -19, 22},
        {0x0000, -9, -22, 24},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank31Frame18 = {
    {0x0400, 0x0000},
    {
        {0x0000, -6, -21, 29},
        {0x0000, -7, -12, 23},
        {0x0000, -7, -20, 22},
        {0x0000, -10, -23, 24},
    },
};

SaturnSpriteFrame4 g_Stage15SpriteBank31Frame19 = {
    {0x0400, 0x0000},
    {
        {0x0000, -9, -21, 30},
        {0x0000, -7, -13, 23},
        {0x0000, -7, -21, 22},
        {0x0000, -10, -24, 24},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank31Frame20 = {
    {0x0300, 0x0000},
    {
        {0x0000, 0, -35, 31},
        {0x0000, -12, -20, 32},
        {0x0000, 4, -47, 33},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank31Frame21 = {
    {0x0300, 0x0000},
    {
        {0x0000, 1, -35, 31},
        {0x0000, -12, -20, 32},
        {0x0030, 10, -41, 34},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank31Frame22 = {
    {0x0300, 0x0000},
    {
        {0x0000, 2, -35, 31},
        {0x0000, -12, -20, 32},
        {0x0000, 14, -38, 35},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank31Frame23 = {
    {0x0300, 0x0000},
    {
        {0x0000, 1, -35, 31},
        {0x0000, -12, -20, 32},
        {0x0030, -8, -33, 33},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank31Frame24 = {
    {0x0300, 0x0000},
    {
        {0x0000, 0, -35, 31},
        {0x0000, -12, -20, 32},
        {0x0000, -13, -37, 34},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank31Frame25 = {
    {0x0300, 0x0000},
    {
        {0x0000, -1, -35, 31},
        {0x0000, -12, -20, 32},
        {0x0030, -20, -42, 35},
    },
};

SaturnSpriteFrame2 g_Stage15SpriteBank31Frame26 = {
    {0x0200, 0x0000},
    {
        {0x0000, 23, -41, 36},
        {0x0000, -12, -22, 37},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank31Frame27 = {
    {0x0300, 0x0000},
    {
        {0x0000, -11, -22, 38},
        {0x0000, 7, -39, 39},
        {0x0000, 25, -32, 40},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank31Frame28 = {
    {0x0300, 0x0000},
    {
        {0x0000, -15, -19, 41},
        {0x0000, -46, -26, 42},
        {0x0000, -37, -47, 43},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank31Frame29 = {
    {0x0300, 0x0000},
    {
        {0x0000, -15, -19, 41},
        {0x0000, -42, -8, 44},
        {0x0000, -62, -8, 45},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank31Frame30 = {
    {0x0300, 0x0000},
    {
        {0x0000, -15, -19, 41},
        {0x0000, -42, -8, 44},
        {0x0000, -66, -2, 46},
    },
};

SaturnSpriteFrame3 g_Stage15SpriteBank31Frame31 = {
    {0x0300, 0x0000},
    {
        {0x0000, -15, -19, 41},
        {0x0000, -42, -8, 44},
        {0x0000, -66, -2, 46},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank31Frame32 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 0, 47},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank31Frame33 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 1, 48},
    },
};

SaturnSpriteFrame2 g_Stage15SpriteBank31Frame34 = {
    {0x0200, 0x0000},
    {
        {0x0000, -3, 4, 49},
        {0x0000, 1, -2, 50},
    },
};

SaturnSpriteFrame2 g_Stage15SpriteBank31Frame35 = {
    {0x0200, 0x0000},
    {
        {0x0010, -3, 4, 49},
        {0x0010, -7, -2, 50},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank31Frame36 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 1, 51},
    },
};

SaturnSpriteFrame1 g_Stage15SpriteBank31Frame37 = {
    {0x0100, 0x0000},
    {
        {0x0010, -1, 1, 51},
    },
};

SaturnSpriteFrameHeader* g_Stage15SpriteBank31Frames[38] = {
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame0,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame1,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame2,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame3,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame4,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame5,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame6,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame7,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame8,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame9,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame10,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame11,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame12,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame13,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame14,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame15,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame16,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame17,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame18,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame19,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame20,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame21,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame22,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame23,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame24,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame25,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame26,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame27,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame28,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame29,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame30,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame31,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame32,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame33,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame34,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame35,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame36,
    (SaturnSpriteFrameHeader*)&g_Stage15SpriteBank31Frame37,
};

SaturnSpriteImage g_Stage15SpriteBank31Images[53] = {
    {4, 4, 0x0000},   {8, 4, 0x0004},   {4, 3, 0x000C},   {8, 4, 0x0010},
    {4, 5, 0x0018},   {4, 5, 0x0020},   {8, 5, 0x0028},   {12, 6, 0x0034},
    {4, 4, 0x0048},   {4, 3, 0x004C},   {4, 5, 0x0050},   {8, 3, 0x0058},
    {8, 3, 0x0060},   {8, 3, 0x0068},   {4, 2, 0x0070},   {4, 5, 0x0074},
    {4, 4, 0x007C},   {8, 4, 0x0080},   {8, 12, 0x0088},  {4, 5, 0x00A0},
    {8, 12, 0x00A8},  {16, 25, 0x00C0}, {8, 4, 0x0124},   {8, 4, 0x012C},
    {4, 2, 0x0134},   {16, 20, 0x0138}, {16, 21, 0x0188}, {16, 21, 0x01DC},
    {16, 21, 0x0230}, {16, 21, 0x0284}, {12, 22, 0x02D8}, {4, 5, 0x031C},
    {16, 21, 0x0324}, {20, 7, 0x0378},  {16, 8, 0x039C},  {16, 11, 0x03BC},
    {20, 13, 0x03E8}, {20, 22, 0x042C}, {20, 22, 0x049C}, {16, 10, 0x050C},
    {8, 9, 0x0534},   {20, 20, 0x0548}, {16, 14, 0x05AC}, {16, 8, 0x05E4},
    {8, 7, 0x0604},   {12, 8, 0x0614},  {16, 2, 0x062C},  {8, 5, 0x0634},
    {8, 6, 0x0640},   {8, 4, 0x064C},   {4, 2, 0x0654},   {4, 11, 0x0658},
    {0, 0, 0x0664},
};
