// SPDX-License-Identifier: AGPL-3.0-or-later
#include "no1.h"

u16 OVL_EXPORT(PrizeDrops)[] = {
    ITEMDROP_JEWEL_KNUCKLES, ITEMDROP_MIRROR_CUIRASS, ITEMDROP_HEART_VESSEL,
    ITEMDROP_GARNET,         ITEMDROP_GLADIUS,        ITEMDROP_LIFE_VESSEL,
    ITEMDROP_ZIRCON,
};
