[package]
name = "sotn-lint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
rayon = "1.7.0"
regex = "1.9.1"
num = "0.4.3"
once_cell = "1.19.0"
