// SPDX-License-Identifier: AGPL-3.0-or-later
#include "../rcat/rcat.h"

#include "../pfn_entity_update.h"

extern LayoutEntity* D_8D2E96C;
extern LayoutEntity* D_8D2EA40;

extern Overlay OVL_EXPORT(Overlay);

s32 E_ID(BACKGROUND_BLOCK);
s32 E_ID(LOCK_CAMERA);
s32 E_ID(UNK_ID13);
s32 E_ID(EXPLOSION_VARIANTS);
s32 E_ID(GREY_PUFF);
s32 E_ID(LAVA);
s32 E_ID(CAVERN_BACKGROUND_LOSSOTH);
s32 E_ID(CAVERN_BACKGROUND_DISCUS_LORD);
s32 E_ID(LAVA_EMBERS);
s32 E_ID(SPIKES);
s32 E_ID(SPIKES_PARTS);
s32 E_ID(SPIKES_DUST);
s32 E_ID(SPIKE_ROOM_DARKNESS);
s32 E_ID(SPIKES_DAMAGE);
s32 E_ID(UNK_1F);
s32 E_ID(UNK_20);
s32 E_ID(UNK_21);
s32 E_ID(UNK_22);
s32 E_ID(UNK_23);
s32 E_ID(UNK_24);
s32 E_ID(UNK_25);
s32 E_ID(UNK_26);
s32 E_ID(UNK_27);
s32 E_ID(UNK_28);
s32 E_ID(UNK_29);
s32 E_ID(UNK_2A);
s32 E_ID(UNK_2B);
s32 E_ID(UNK_2C);
s32 E_ID(UNK_2D);
s32 E_ID(SECRET_WALL);
s32 E_ID(BREAKABLE_WALL_SEGMENT);
s32 E_ID(BREAKABLE_WALL_PARTICLES);
s32 E_ID(BREAKABLE_WALL_DEBRIS);
s32 E_ID(SKELETON);
s32 E_ID(SKELETON_THROWN_BONE);
s32 E_ID(SKELETON_PIECES);
s32 E_ID(BLOOD_SKELETON);
s32 E_ID(BAT);

void InitEntityIds(void) {
    E_ID(BACKGROUND_BLOCK) = E_BACKGROUND_BLOCK;
    E_ID(LOCK_CAMERA) = E_LOCK_CAMERA;
    E_ID(UNK_ID13) = E_UNK_ID13;
    E_ID(EXPLOSION_VARIANTS) = E_EXPLOSION_VARIANTS;
    E_ID(GREY_PUFF) = E_GREY_PUFF;
    E_ID(LAVA) = E_LAVA;
    E_ID(CAVERN_BACKGROUND_LOSSOTH) = E_CAVERN_BACKGROUND_LOSSOTH;
    E_ID(CAVERN_BACKGROUND_DISCUS_LORD) = E_CAVERN_BACKGROUND_DISCUS_LORD;
    E_ID(LAVA_EMBERS) = E_LAVA_EMBERS;
    E_ID(SPIKES) = E_SPIKES;
    E_ID(SPIKES_PARTS) = E_SPIKES_PARTS;
    E_ID(SPIKES_DUST) = E_SPIKES_DUST;
    E_ID(SPIKE_ROOM_DARKNESS) = E_SPIKE_ROOM_DARKNESS;
    E_ID(SPIKES_DAMAGE) = E_SPIKES_DAMAGE;
    E_ID(UNK_1F) = E_UNK_1F;
    E_ID(UNK_20) = E_UNK_20;
    E_ID(UNK_21) = E_UNK_21;
    E_ID(UNK_22) = E_UNK_22;
    E_ID(UNK_23) = E_UNK_23;
    E_ID(UNK_24) = E_UNK_24;
    E_ID(UNK_25) = E_UNK_25;
    E_ID(UNK_26) = E_UNK_26;
    E_ID(UNK_27) = E_UNK_27;
    E_ID(UNK_28) = E_UNK_28;
    E_ID(UNK_29) = E_UNK_29;
    E_ID(UNK_2A) = E_UNK_2A;
    E_ID(UNK_2B) = E_UNK_2B;
    E_ID(UNK_2C) = E_UNK_2C;
    E_ID(UNK_2D) = E_UNK_2D;
    E_ID(SECRET_WALL) = E_SECRET_WALL;
    E_ID(BREAKABLE_WALL_SEGMENT) = E_BREAKABLE_WALL_SEGMENT;
    E_ID(BREAKABLE_WALL_PARTICLES) = E_BREAKABLE_WALL_PARTICLES;
    E_ID(BREAKABLE_WALL_DEBRIS) = E_BREAKABLE_WALL_DEBRIS;
    E_ID(SKELETON) = E_SKELETON;
    E_ID(SKELETON_THROWN_BONE) = E_SKELETON_THROWN_BONE;
    E_ID(SKELETON_PIECES) = E_SKELETON_PIECES;
    E_ID(BLOOD_SKELETON) = E_BLOOD_SKELETON;
    E_ID(BAT) = E_BAT;
}

void OVL_EXPORT(Load)(void) {
    InitEntityIds();
    PfnEntityUpdates = OVL_EXPORT(EntityUpdates);
    g_pStObjLayoutHorizontal = &D_8D2E96C;
    g_pStObjLayoutVertical = &D_8D2EA40;
    func_892A018();
    memcpy(&g_api.o, &OVL_EXPORT(Overlay), sizeof(Overlay));
}
