// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_SaturnSharedSpriteBank11Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank11Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 5, 1, 0},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank11Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 1, 1},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank11Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 0, 2},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank11Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 2, 3},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank11Frame5 = {
    {0x0300, 0x0000},
    {
        {0x0000, -1, 3, 4},
        {0x0000, 33, -22, 5},
        {0x0000, 4, 29, 6},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank11Frame6 = {
    {0x0300, 0x0000},
    {
        {0x0000, 4, -1, 7},
        {0x0000, -21, -5, 8},
        {0x0000, 2, 21, 9},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank11Frame7 = {
    {0x0200, 0x0000},
    {
        {0x0000, -3, -10, 10},
        {0x0000, -2, 12, 11},
    },
};

SaturnSpriteFrameHeader* g_SaturnSharedSpriteBank11Frames[8] = {
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank11Frame0,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank11Frame1,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank11Frame2,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank11Frame3,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank11Frame4,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank11Frame5,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank11Frame6,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank11Frame7,
};

SaturnSpriteImage g_SaturnSharedSpriteBank11Images[13] = {
    {20, 15, 0x0000}, {20, 23, 0x004C}, {28, 30, 0x00C0}, {40, 31, 0x0194},
    {32, 19, 0x02CC}, {8, 7, 0x0364},   {4, 3, 0x0374},   {20, 15, 0x0378},
    {8, 5, 0x03C4},   {8, 7, 0x03D0},   {24, 7, 0x03E0},  {8, 5, 0x040C},
    {0, 0, 0x0418},
};

struct {
    u16 countAndFlags;
    u16 colors[1][16];
    u16 padding[1];
} g_SaturnSharedSpriteBank11Palette = {
    0x0001,
    {
        {
            0x8200,
            0x8CEF,
            0x8D30,
            0x9171,
            0x95B3,
            0x99F4,
            0x9E35,
            0xA277,
            0xA6B8,
            0xAAFA,
            0xB71B,
            0xC35C,
            0xD37C,
            0xDF9D,
            0xF3DE,
            0xFFFF,
        },
    },
    {0x0000},
};

SaturnSpriteResource g_SaturnSharedSpriteBank11Resource = {
    g_SaturnSharedSpriteBank11Images,
    (u16*)&g_SaturnSharedSpriteBank11Palette,
    -1,
    0xFFFF,
};
