// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_SaturnSharedSpriteBank3Frame0 = {
    0x0000, 0x0000,
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank3Frame1 = {
    {0x0200, 0x0000},
    {
        {0x0100, 3, -14, 1},
        {0x0130, -3, 13, 1},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank3Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 0, 0},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank3Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 0, 2},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank3Frame4 = {
    {0x0400, 0x0000},
    {
        {0x0100, 3, -14, 1},
        {0x0130, -3, 13, 1},
        {0x0200, -23, -20, 3},
        {0x0200, -8, -14, 4},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank3Frame5 = {
    {0x0400, 0x0000},
    {
        {0x0100, 3, -14, 1},
        {0x0130, -3, 13, 1},
        {0x0200, 25, -20, 3},
        {0x0210, 9, -14, 4},
    },
};

SaturnSpriteFrame5 g_SaturnSharedSpriteBank3Frame6 = {
    {0x0500, 0x0000},
    {
        {0x0100, 3, -14, 1},
        {0x0130, -3, 13, 1},
        {0x0200, -23, -20, 3},
        {0x0200, -8, -14, 4},
        {0x0200, -33, -20, 5},
    },
};

SaturnSpriteFrame5 g_SaturnSharedSpriteBank3Frame7 = {
    {0x0500, 0x0000},
    {
        {0x0100, 3, -14, 1},
        {0x0130, -3, 13, 1},
        {0x0200, 25, -20, 3},
        {0x0210, 9, -14, 4},
        {0x0200, 15, -20, 5},
    },
};

SaturnSpriteFrame5 g_SaturnSharedSpriteBank3Frame8 = {
    {0x0500, 0x0000},
    {
        {0x0100, 3, -14, 1},
        {0x0130, -3, 13, 1},
        {0x0200, -23, -20, 3},
        {0x0200, -8, -14, 4},
        {0x0200, -33, -20, 6},
    },
};

SaturnSpriteFrame5 g_SaturnSharedSpriteBank3Frame9 = {
    {0x0500, 0x0000},
    {
        {0x0100, 3, -14, 1},
        {0x0130, -3, 13, 1},
        {0x0200, 25, -20, 3},
        {0x0210, 9, -14, 4},
        {0x0200, 15, -20, 6},
    },
};

SaturnSpriteFrameHeader* g_SaturnSharedSpriteBank3Frames[10] = {
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank3Frame0,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank3Frame1,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank3Frame2,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank3Frame3,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank3Frame4,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank3Frame5,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank3Frame6,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank3Frame7,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank3Frame8,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank3Frame9,
};

SaturnSpriteImage g_SaturnSharedSpriteBank3Images[8] = {
    {4, 32, 0x0000},
    {8, 19, 0x0020},
    {20, 32, 0x0048},
    {28, 7, 0x00E8},
    {4, 3, 0x011C},
    {12, 3, 0x0120},
    {12, 3, 0x012C},
    {0, 0, 0x0138},
};

struct {
    u16 countAndFlags;
    u16 colors[3][16];
    u16 padding[1];
} g_SaturnSharedSpriteBank3Palette = {
    0x0003,
    {
        {
            0x8522, 0x9462, 0x9CC4, 0xA96A, 0xC22F, 0xDB18, 0x801F, 0x812C,
            0x8217, 0xBB3F, 0x8424, 0x8468, 0x88AA, 0x8CEF, 0xA865, 0xF7BD,
        },
        {
            0x90A5, 0x801A, 0x8013, 0x8017, 0x801B, 0x801F, 0x801A, 0x8013,
            0x8017, 0x801B, 0x801F, 0x801A, 0x8013, 0x8017, 0x801B, 0x801F,
        },
        {
            0x8200, 0x8842, 0x9084, 0x98C6, 0xA108, 0xA94A, 0xB18C, 0xB9CE,
            0xC210, 0xCA52, 0xD294, 0xDAD6, 0xE318, 0xEB5A, 0xF39C, 0xFBDE,
        },
    },
    {0x0000},
};

SaturnSpriteResource g_SaturnSharedSpriteBank3Resource = {
    g_SaturnSharedSpriteBank3Images,
    (u16*)&g_SaturnSharedSpriteBank3Palette,
    -1,
    0xFFFF,
};

