// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[2][16];
    u16 padding[1];
} g_SaturnSharedSpriteBank12Palette = {
    0x4002,
    {
        {
            0x9084, 0x8421, 0xA108, 0xB2BE, 0xA18D, 0xC631, 0xE738, 0x9F5F,
            0x8CD3, 0x8601, 0xFCC1, 0xFEF0, 0xABEA, 0xA11F, 0xCE7F, 0xFBDE,
        },
        {
            0x0000, 0xC210, 0xD294, 0xE738, 0xF7BC, 0x0000, 0x0000, 0x0000,
            0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        },
    },
    {0x0000},
};

SaturnSpriteImage g_SaturnSharedSpriteBank12Images[2] = {
    {64, 64, 0x0000},
    {0, 0, 0x0400},
};

SaturnSpriteResource g_SaturnSharedSpriteBank12Resource = {
    g_SaturnSharedSpriteBank12Images,
    (u16*)&g_SaturnSharedSpriteBank12Palette,
    -1,
    0xFFFF,
};

