// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_SaturnSharedSpriteBank1Frame0 = {
    0x0000, 0x0000,
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, -2, 0},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0010, 1, -2, 0},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, -2, 1},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0010, 0, -2, 1},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, -2, 2},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0010, 0, -2, 2},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, -2, 3},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0010, -1, -2, 3},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 1, 4},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank1Frame10 = {
    {0x0200, 0x0000},
    {
        {0x0000, 1, 1, 5},
        {0x0000, 2, 1, 6},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame11 = {
    {0x0100, 0x0000},
    {
        {0x0010, -1, 1, 6},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame12 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 1, 7},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame13 = {
    {0x0100, 0x0000},
    {
        {0x0010, -1, 1, 7},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame14 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 1, 8},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame15 = {
    {0x0100, 0x0000},
    {
        {0x0010, -1, 1, 8},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame16 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 0, 9},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame17 = {
    {0x0100, 0x0000},
    {
        {0x0010, -3, 0, 9},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame18 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, -3, 10},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame19 = {
    {0x0100, 0x0000},
    {
        {0x0010, -4, -3, 10},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame20 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, -4, 11},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame21 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 0, 0},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame22 = {
    {0x0100, 0x0000},
    {
        {0x0010, -1, 0, 0},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank1Frame23 = {
    {0x0200, 0x0000},
    {
        {0x0000, 2, -1, 1},
        {0x0000, 8, 8, 0},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank1Frame24 = {
    {0x0200, 0x0000},
    {
        {0x0010, -2, -1, 1},
        {0x0010, 8, 8, 0},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank1Frame25 = {
    {0x0300, 0x0000},
    {
        {0x0000, 3, 0, 2},
        {0x0000, 10, 9, 1},
        {0x0000, -2, 16, 0},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank1Frame26 = {
    {0x0300, 0x0000},
    {
        {0x0010, -1, 0, 2},
        {0x0010, 6, 9, 1},
        {0x0010, -2, 16, 0},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank1Frame27 = {
    {0x0400, 0x0000},
    {
        {0x0000, 2, 0, 3},
        {0x0000, 11, 9, 2},
        {0x0000, 2, 16, 1},
        {0x0000, 9, 31, 0},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank1Frame28 = {
    {0x0400, 0x0000},
    {
        {0x0010, 0, 0, 3},
        {0x0010, 7, 9, 2},
        {0x0010, -2, 16, 1},
        {0x0010, 9, 31, 0},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank1Frame29 = {
    {0x0400, 0x0000},
    {
        {0x0000, 8, 9, 3},
        {0x0000, 0, 16, 2},
        {0x0000, 12, 30, 1},
        {0x0000, 0, 31, 0},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank1Frame30 = {
    {0x0400, 0x0000},
    {
        {0x0010, 6, 9, 3},
        {0x0010, -4, 16, 2},
        {0x0010, 8, 30, 1},
        {0x0010, 0, 31, 0},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank1Frame31 = {
    {0x0400, 0x0000},
    {
        {0x0000, 0, 16, 3},
        {0x0000, 13, 31, 2},
        {0x0000, 4, 32, 1},
        {0x0000, -7, 40, 0},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank1Frame32 = {
    {0x0400, 0x0000},
    {
        {0x0010, -3, 16, 3},
        {0x0010, 8, 31, 2},
        {0x0010, -1, 32, 1},
        {0x0010, -8, 40, 0},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank1Frame33 = {
    {0x0400, 0x0000},
    {
        {0x0000, 11, 31, 3},
        {0x0000, 2, 31, 2},
        {0x0000, -8, 40, 1},
        {0x0000, 7, 45, 0},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank1Frame34 = {
    {0x0400, 0x0000},
    {
        {0x0010, 8, 31, 3},
        {0x0010, -3, 31, 2},
        {0x0010, -13, 40, 1},
        {0x0010, 6, 45, 0},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank1Frame35 = {
    {0x0400, 0x0000},
    {
        {0x0000, 3, 31, 3},
        {0x0000, -5, 38, 2},
        {0x0000, 11, 45, 1},
        {0x0000, -3, 51, 0},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank1Frame36 = {
    {0x0400, 0x0000},
    {
        {0x0010, 1, 31, 3},
        {0x0010, -9, 38, 2},
        {0x0010, 7, 45, 1},
        {0x0010, -3, 51, 0},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank1Frame37 = {
    {0x0300, 0x0000},
    {
        {0x0000, -7, 39, 3},
        {0x0000, 8, 44, 2},
        {0x0000, -2, 50, 1},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank1Frame38 = {
    {0x0300, 0x0000},
    {
        {0x0010, -6, 50, 1},
        {0x0010, -9, 39, 3},
        {0x0010, 4, 44, 2},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank1Frame39 = {
    {0x0200, 0x0000},
    {
        {0x0000, 6, 45, 3},
        {0x0000, -2, 50, 2},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank1Frame40 = {
    {0x0200, 0x0000},
    {
        {0x0010, 3, 45, 3},
        {0x0010, -7, 50, 2},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame41 = {
    {0x0100, 0x0000},
    {
        {0x0000, -2, 51, 3},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame42 = {
    {0x0100, 0x0000},
    {
        {0x0010, -2, 51, 3},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame43 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, -1, 4},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank1Frame44 = {
    {0x0200, 0x0000},
    {
        {0x0000, 1, 0, 5},
        {0x0000, 4, -1, 6},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank1Frame45 = {
    {0x0200, 0x0000},
    {
        {0x0010, 1, -1, 6},
        {0x0000, -12, 11, 0},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank1Frame46 = {
    {0x0200, 0x0000},
    {
        {0x0000, 5, -1, 7},
        {0x0010, -13, 11, 0},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank1Frame47 = {
    {0x0300, 0x0000},
    {
        {0x0010, -1, -1, 7},
        {0x0000, -13, 11, 1},
        {0x0000, 13, 15, 4},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank1Frame48 = {
    {0x0400, 0x0000},
    {
        {0x0000, 5, -1, 8},
        {0x0010, -15, 11, 1},
        {0x0000, 9, 15, 5},
        {0x0000, 15, 15, 6},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank1Frame49 = {
    {0x0400, 0x0000},
    {
        {0x0010, 3, -1, 8},
        {0x0000, -9, 9, 2},
        {0x0010, 12, 15, 6},
        {0x0000, 26, -1, 0},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank1Frame50 = {
    {0x0400, 0x0000},
    {
        {0x0000, 6, -2, 9},
        {0x0010, -16, 11, 2},
        {0x0000, 16, 15, 7},
        {0x0010, 22, 0, 0},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank1Frame51 = {
    {0x0400, 0x0000},
    {
        {0x0010, -2, -4, 9},
        {0x0010, 9, 14, 7},
        {0x0000, 24, -1, 1},
        {0x0000, -3, 23, 4},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank1Frame52 = {
    {0x0400, 0x0000},
    {
        {0x0000, 6, -8, 10},
        {0x0000, 11, 14, 8},
        {0x0010, 20, 0, 1},
        {0x0000, -3, 24, 6},
    },
};

SaturnSpriteFrame5 g_SaturnSharedSpriteBank1Frame53 = {
    {0x0500, 0x0000},
    {
        {0x0010, -2, -9, 10},
        {0x0010, 8, 15, 8},
        {0x0000, 24, 1, 2},
        {0x0010, -7, 23, 6},
        {0x0000, 9, 34, 0},
    },
};

SaturnSpriteFrame5 g_SaturnSharedSpriteBank1Frame54 = {
    {0x0500, 0x0000},
    {
        {0x0000, 5, -11, 11},
        {0x0000, 13, 15, 9},
        {0x0010, 19, 1, 2},
        {0x0000, -4, 23, 7},
        {0x0010, 6, 34, 0},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank1Frame55 = {
    {0x0400, 0x0000},
    {
        {0x0000, 22, 0, 3},
        {0x0010, 5, 15, 9},
        {0x0010, -10, 22, 7},
        {0x0000, 4, 31, 4},
    },
};

SaturnSpriteFrame5 g_SaturnSharedSpriteBank1Frame56 = {
    {0x0500, 0x0000},
    {
        {0x0000, 12, 9, 10},
        {0x0010, 20, 0, 3},
        {0x0000, -5, 23, 8},
        {0x0000, 1, 31, 5},
        {0x0000, 4, 31, 6},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank1Frame57 = {
    {0x0400, 0x0000},
    {
        {0x0010, 4, 9, 10},
        {0x0010, -7, 23, 8},
        {0x0010, 1, 31, 6},
        {0x0000, -7, 44, 0},
    },
};

SaturnSpriteFrame4 g_SaturnSharedSpriteBank1Frame58 = {
    {0x0400, 0x0000},
    {
        {0x0000, 10, 8, 11},
        {0x0000, -2, 21, 9},
        {0x0000, 7, 32, 7},
        {0x0010, -8, 45, 0},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank1Frame59 = {
    {0x0300, 0x0000},
    {
        {0x0010, -8, 21, 9},
        {0x0010, 0, 32, 7},
        {0x0000, -6, 45, 1},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank1Frame60 = {
    {0x0300, 0x0000},
    {
        {0x0000, -4, 15, 10},
        {0x0000, 4, 30, 8},
        {0x0010, -11, 44, 1},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank1Frame61 = {
    {0x0300, 0x0000},
    {
        {0x0010, -12, 15, 10},
        {0x0010, -1, 31, 8},
        {0x0000, -8, 46, 2},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank1Frame62 = {
    {0x0300, 0x0000},
    {
        {0x0000, -3, 14, 11},
        {0x0000, 5, 30, 9},
        {0x0010, -11, 46, 2},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank1Frame63 = {
    {0x0200, 0x0000},
    {
        {0x0010, -2, 28, 9},
        {0x0000, -8, 44, 3},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank1Frame64 = {
    {0x0200, 0x0000},
    {
        {0x0010, -9, 44, 3},
        {0x0000, 4, 23, 10},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame65 = {
    {0x0100, 0x0000},
    {
        {0x0010, -3, 22, 10},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame66 = {
    {0x0100, 0x0000},
    {
        {0x0000, 5, 22, 11},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank1Frame67 = {
    {0x0100, 0x0000},
    {
        {0x0100, 3, -9, 12},
    },
};

SaturnSpriteFrameHeader* g_SaturnSharedSpriteBank1Frames[68] = {
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame0,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame1,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame2,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame3,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame4,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame5,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame6,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame7,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame8,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame9,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame10,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame11,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame12,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame13,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame14,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame15,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame16,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame17,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame18,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame19,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame20,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame21,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame22,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame23,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame24,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame25,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame26,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame27,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame28,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame29,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame30,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame31,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame32,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame33,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame34,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame35,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame36,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame37,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame38,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame39,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame40,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame41,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame42,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame43,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame44,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame45,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame46,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame47,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame48,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame49,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame50,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame51,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame52,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame53,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame54,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame55,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame56,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame57,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame58,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame59,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame60,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame61,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame62,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame63,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame64,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame65,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame66,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank1Frame67,
};

SaturnSpriteImage g_SaturnSharedSpriteBank1Images[14] = {
    {8, 7, 0x0000},
    {8, 7, 0x0010},
    {8, 7, 0x0020},
    {4, 7, 0x0030},
    {20, 15, 0x0038},
    {8, 6, 0x0084},
    {20, 15, 0x0090},
    {20, 14, 0x00DC},
    {16, 12, 0x0124},
    {16, 12, 0x0154},
    {16, 7, 0x0184},
    {16, 6, 0x01A0},
    {64, 52, 0x01B8},
    {0, 0, 0x04F8},
};

struct {
    u16 countAndFlags;
    u16 colors[2][16];
    u16 padding[1];
} g_SaturnSharedSpriteBank1Palette = {
    0x0002,
    {
        {
            0xB0A5, 0x8000, 0x83E0, 0xBC00, 0xC900, 0xD900, 0xD940, 0xE180,
            0xFC82, 0xE23F, 0x8033, 0x811C, 0xB19F, 0x825F, 0xBB7F, 0xE3FF,
        },
        {
            0x80C0, 0xFD5B, 0x819C, 0x921D, 0x969E, 0xAF5F, 0xD7DF, 0x80D5,
            0x811A, 0x815B, 0x819C, 0x921D, 0x969E, 0xAF5F, 0xD7DF, 0xFFFF,
        },
    },
    {0x0000},
};

SaturnSpriteResource g_SaturnSharedSpriteBank1Resource = {
    g_SaturnSharedSpriteBank1Images,
    (u16*)&g_SaturnSharedSpriteBank1Palette,
    -1,
    0xFFFF,
};

