// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_SaturnSharedSpriteBank5Frame0 = {
    0x0000, 0x0000,
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -4, 0},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -4, 1},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, -1, -4, 2},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0000, -1, -4, 3},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, -1, 4},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, -1, 5},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, -1, 6},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0000, 5, -1, 7},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 1, 8},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame10 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 2, 9},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame11 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 3, 10},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame12 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 2, 11},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame13 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 4, 12},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame14 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 3, 13},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame15 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 6, 14},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame16 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 6, 15},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame17 = {
    {0x0100, 0x0000},
    {
        {0x0000, -2, 7, 16},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame18 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 8, 17},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame19 = {
    {0x0100, 0x0000},
    {
        {0x0000, -1, 8, 18},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame20 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 7, 19},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame21 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 8, 20},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame22 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 10, 21},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame23 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 7, 22},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank5Frame24 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 5, 23},
    },
};

SaturnSpriteFrameHeader* g_SaturnSharedSpriteBank5Frames[25] = {
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame0,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame1,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame2,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame3,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame4,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame5,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame6,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame7,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame8,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame9,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame10,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame11,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame12,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame13,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame14,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame15,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame16,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame17,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame18,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame19,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame20,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame21,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame22,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame23,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank5Frame24,
};

SaturnSpriteImage g_SaturnSharedSpriteBank5Images[25] = {
    {8, 6, 0x0000},
    {8, 6, 0x000C},
    {8, 6, 0x0018},
    {8, 6, 0x0024},
    {12, 9, 0x0030},
    {12, 8, 0x004C},
    {12, 8, 0x0064},
    {12, 8, 0x007C},
    {12, 10, 0x0094},
    {12, 10, 0x00B4},
    {12, 11, 0x00D4},
    {12, 11, 0x00F8},
    {12, 10, 0x011C},
    {12, 10, 0x013C},
    {12, 9, 0x015C},
    {8, 10, 0x0178},
    {8, 8, 0x018C},
    {8, 8, 0x019C},
    {8, 8, 0x01AC},
    {8, 8, 0x01BC},
    {8, 6, 0x01CC},
    {8, 6, 0x01D8},
    {8, 3, 0x01E4},
    {4, 2, 0x01EC},
    {0, 0, 0x01F0},
};

struct {
    u16 countAndFlags;
    u16 colors[1][16];
    u16 padding[1];
} g_SaturnSharedSpriteBank5Palette = {
    0x0001,
    {
        {
            0xB0A5, 0x8C63, 0x94A5, 0x9CE7, 0xA529, 0xA94A, 0xD940, 0xE180,
            0xFC82, 0xCA13, 0xA92A, 0xB18D, 0xA593, 0xB212, 0xD272, 0xD6B5,
        },
    },
    {0x0000},
};

SaturnSpriteResource g_SaturnSharedSpriteBank5Resource = {
    g_SaturnSharedSpriteBank5Images,
    (u16*)&g_SaturnSharedSpriteBank5Palette,
    -1,
    0xFFFF,
};

