// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

void func_06019058(void);

u32 D_06044348 = 0;
void (*g_SaturnSharedSpriteSetup)(void) = func_06019058;
u32 D_06044350[2] = {0};
u32 D_06044358 = 0xFFFFFFFF;

SaturnSpriteFrameHeader g_SaturnSharedSpriteBank0Frame0 = {
    0x0000, 0x0000,
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, -3, 0},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0010, -3, -3, 0},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0100, 5, 1, 1},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0100, 2, 1, 2},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0100, 2, 1, 3},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0100, 3, 1, 4},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0100, 5, 1, 5},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0100, 2, 1, 6},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0110, -2, 1, 5},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame10 = {
    {0x0100, 0x0000},
    {
        {0x0110, 0, 1, 4},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame11 = {
    {0x0100, 0x0000},
    {
        {0x0110, 1, 1, 3},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame12 = {
    {0x0100, 0x0000},
    {
        {0x0110, 1, 1, 2},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame13 = {
    {0x0100, 0x0000},
    {
        {0x0210, -3, 1, 1},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame14 = {
    {0x0100, 0x0000},
    {
        {0x0100, 4, 3, 7},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame15 = {
    {0x0100, 0x0000},
    {
        {0x0100, 4, 0, 8},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame16 = {
    {0x0100, 0x0000},
    {
        {0x0100, 4, 0, 9},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame17 = {
    {0x0100, 0x0000},
    {
        {0x0100, 4, 0, 10},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame18 = {
    {0x0100, 0x0000},
    {
        {0x0100, 4, 0, 11},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame19 = {
    {0x0100, 0x0000},
    {
        {0x0300, 3, -2, 12},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame20 = {
    {0x0100, 0x0000},
    {
        {0x0300, 2, 4, 13},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame21 = {
    {0x0100, 0x0000},
    {
        {0x0300, 2, 4, 14},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame22 = {
    {0x0100, 0x0000},
    {
        {0x0300, 4, 4, 15},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame23 = {
    {0x0100, 0x0000},
    {
        {0x0300, 5, 4, 16},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame24 = {
    {0x0100, 0x0000},
    {
        {0x0320, 4, 4, 16},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame25 = {
    {0x0100, 0x0000},
    {
        {0x0310, -2, 4, 15},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame26 = {
    {0x0100, 0x0000},
    {
        {0x0400, 1, 1, 17},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame27 = {
    {0x0100, 0x0000},
    {
        {0x0500, 1, 1, 17},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame28 = {
    {0x0100, 0x0000},
    {
        {0x0600, 1, 1, 17},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame29 = {
    {0x0100, 0x0000},
    {
        {0x0700, 5, 0, 18},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame30 = {
    {0x0100, 0x0000},
    {
        {0x0800, 5, 0, 18},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame31 = {
    {0x0100, 0x0000},
    {
        {0x0900, 5, 0, 18},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame32 = {
    {0x0100, 0x0000},
    {
        {0x0A00, 0, -1, 19},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame33 = {
    {0x0100, 0x0000},
    {
        {0x0B00, 0, -1, 19},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame34 = {
    {0x0100, 0x0000},
    {
        {0x0400, 5, -2, 20},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame35 = {
    {0x0100, 0x0000},
    {
        {0x0500, 5, -2, 20},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame36 = {
    {0x0100, 0x0000},
    {
        {0x0600, 5, -2, 20},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame37 = {
    {0x0100, 0x0000},
    {
        {0x0A00, 5, -2, 20},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame38 = {
    {0x0100, 0x0000},
    {
        {0x0700, 5, -2, 20},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame39 = {
    {0x0100, 0x0000},
    {
        {0x0C00, 5, -2, 20},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame40 = {
    {0x0100, 0x0000},
    {
        {0x0800, 5, -2, 20},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame41 = {
    {0x0100, 0x0000},
    {
        {0x0900, 5, -2, 20},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank0Frame42 = {
    {0x0300, 0x0000},
    {
        {0x0D00, -1, -8, 21},
        {0x0D00, 9, -2, 22},
        {0x0D00, 5, 0, 23},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank0Frame43 = {
    {0x0300, 0x0000},
    {
        {0x0D00, -1, -8, 24},
        {0x0D00, 9, -3, 25},
        {0x0D00, 5, 0, 23},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank0Frame44 = {
    {0x0300, 0x0000},
    {
        {0x0E00, -1, -8, 26},
        {0x0E00, 9, -3, 27},
        {0x0D00, 5, 0, 23},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank0Frame45 = {
    {0x0300, 0x0000},
    {
        {0x0D00, -1, -9, 28},
        {0x0D00, 8, -4, 29},
        {0x0D00, 5, 0, 23},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank0Frame46 = {
    {0x0300, 0x0000},
    {
        {0x0D00, -1, -10, 22},
        {0x0D00, 8, 0, 21},
        {0x0D00, 5, 0, 23},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank0Frame47 = {
    {0x0300, 0x0000},
    {
        {0x0D00, -1, -10, 25},
        {0x0D00, 9, 0, 24},
        {0x0D00, 5, 0, 23},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank0Frame48 = {
    {0x0300, 0x0000},
    {
        {0x0D00, -1, -11, 27},
        {0x0D00, 9, 0, 28},
        {0x0D00, 5, 0, 23},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank0Frame49 = {
    {0x0300, 0x0000},
    {
        {0x0D00, -2, -12, 29},
        {0x0D00, 9, -1, 28},
        {0x0D00, 5, 0, 23},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame50 = {
    {0x0200, 0x0000},
    {
        {0x0D00, 2, -9, 22},
        {0x0D00, 3, -1, 30},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame51 = {
    {0x0200, 0x0000},
    {
        {0x0D00, 2, -10, 25},
        {0x0D00, 3, -1, 30},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame52 = {
    {0x0200, 0x0000},
    {
        {0x0D00, 2, -10, 27},
        {0x0D00, 3, -1, 30},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame53 = {
    {0x0200, 0x0000},
    {
        {0x0D00, 1, -11, 29},
        {0x0D00, 3, -1, 30},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame54 = {
    {0x0200, 0x0000},
    {
        {0x0D00, 1, -7, 21},
        {0x0D00, 3, -1, 30},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame55 = {
    {0x0200, 0x0000},
    {
        {0x0D00, 2, -7, 24},
        {0x0D00, 3, -1, 30},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame56 = {
    {0x0200, 0x0000},
    {
        {0x0D00, 2, -7, 26},
        {0x0D00, 3, -1, 30},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame57 = {
    {0x0200, 0x0000},
    {
        {0x0D00, 3, -8, 28},
        {0x0D00, 3, -1, 30},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame58 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 1, -7, 21},
        {0x0E00, 0, -3, 31},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame59 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 2, -8, 24},
        {0x0E00, 0, -3, 31},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame60 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 2, -8, 26},
        {0x0E00, 0, -3, 31},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame61 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 2, -9, 28},
        {0x0E00, 0, -3, 31},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame62 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 2, -10, 22},
        {0x0E00, 0, -3, 31},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame63 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 2, -10, 25},
        {0x0E00, 0, -3, 31},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame64 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 2, -10, 27},
        {0x0E00, 0, -3, 31},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame65 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 0, -12, 29},
        {0x0E00, 0, -3, 31},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame66 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 2, -4, 21},
        {0x0E00, 2, 1, 32},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame67 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 3, -4, 24},
        {0x0E00, 2, 1, 32},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame68 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 3, -4, 26},
        {0x0E00, 2, 1, 32},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame69 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 3, -5, 28},
        {0x0E00, 2, 1, 32},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame70 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 3, -6, 22},
        {0x0E00, 2, 1, 32},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame71 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 3, -7, 25},
        {0x0E00, 2, 1, 32},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame72 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 3, -7, 27},
        {0x0E00, 2, 1, 32},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame73 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 2, -8, 29},
        {0x0E00, 2, 1, 32},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame74 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 1, -3, 21},
        {0x0E00, 2, -1, 33},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame75 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 1, -3, 24},
        {0x0E00, 2, -1, 33},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame76 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 1, -4, 26},
        {0x0E00, 2, -1, 33},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame77 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 1, -5, 28},
        {0x0E00, 2, -1, 33},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame78 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 2, -6, 22},
        {0x0E00, 2, -1, 33},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame79 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 2, -7, 25},
        {0x0E00, 2, -1, 33},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame80 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 1, -7, 27},
        {0x0E00, 2, -1, 33},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame81 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 0, -8, 29},
        {0x0E00, 2, -1, 33},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame82 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 0, -14, 21},
        {0x0E00, 3, -2, 34},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame83 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 1, -14, 24},
        {0x0E00, 3, -2, 34},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame84 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 1, -14, 26},
        {0x0E00, 3, -2, 34},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame85 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 1, -15, 28},
        {0x0E00, 3, -2, 34},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame86 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 1, -16, 22},
        {0x0E00, 3, -2, 34},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame87 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 3, -2, 34},
        {0x0E00, 1, -17, 25},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame88 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 1, -17, 27},
        {0x0E00, 3, -2, 34},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame89 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 0, -18, 29},
        {0x0E00, 3, -2, 34},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank0Frame90 = {
    {0x0300, 0x0000},
    {
        {0x0E00, 1, -2, 21},
        {0x0E00, 2, 1, 35},
        {0x0F00, 1, 1, 36},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank0Frame91 = {
    {0x0300, 0x0000},
    {
        {0x0E00, 2, -2, 24},
        {0x0E00, 2, 1, 35},
        {0x0F00, 1, 1, 36},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank0Frame92 = {
    {0x0300, 0x0000},
    {
        {0x0E00, 2, -2, 26},
        {0x0E00, 2, 1, 35},
        {0x0F00, 1, 1, 36},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank0Frame93 = {
    {0x0300, 0x0000},
    {
        {0x0E00, 2, -3, 28},
        {0x0E00, 2, 1, 35},
        {0x0F00, 1, 1, 36},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank0Frame94 = {
    {0x0300, 0x0000},
    {
        {0x0E00, 2, -4, 22},
        {0x0E00, 2, 1, 35},
        {0x0F00, 1, 1, 36},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank0Frame95 = {
    {0x0300, 0x0000},
    {
        {0x0E00, 2, -5, 25},
        {0x0E00, 2, 1, 35},
        {0x0F00, 1, 1, 36},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank0Frame96 = {
    {0x0300, 0x0000},
    {
        {0x0E00, 2, -5, 27},
        {0x0E00, 2, 1, 35},
        {0x0F00, 1, 1, 36},
    },
};

SaturnSpriteFrame3 g_SaturnSharedSpriteBank0Frame97 = {
    {0x0300, 0x0000},
    {
        {0x0E00, 1, -7, 29},
        {0x0E00, 2, 1, 35},
        {0x0F00, 1, 1, 36},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame98 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 3, -9, 21},
        {0x0E00, 2, -1, 37},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame99 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 4, -9, 24},
        {0x0E00, 2, -1, 37},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame100 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 4, -9, 26},
        {0x0E00, 2, -1, 37},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame101 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 4, -10, 28},
        {0x0E00, 2, -1, 37},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame102 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 4, -11, 22},
        {0x0E00, 2, -1, 37},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame103 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 4, -12, 25},
        {0x0E00, 2, -1, 37},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame104 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 4, -12, 27},
        {0x0E00, 2, -1, 37},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame105 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 2, -13, 29},
        {0x0E00, 2, -1, 37},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame106 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 0, -10, 21},
        {0x0E00, 3, -1, 38},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame107 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 1, -10, 24},
        {0x0E00, 3, -1, 38},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame108 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 1, -10, 26},
        {0x0E00, 3, -1, 38},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame109 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 1, -11, 28},
        {0x0E00, 3, -1, 38},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame110 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 1, -12, 22},
        {0x0E00, 3, -1, 38},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame111 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 1, -13, 25},
        {0x0E00, 3, -1, 38},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame112 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 1, -13, 27},
        {0x0E00, 3, -1, 38},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame113 = {
    {0x0200, 0x0000},
    {
        {0x0E00, 0, -14, 29},
        {0x0E00, 3, -1, 38},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame114 = {
    {0x0100, 0x0000},
    {
        {0x0A00, 1, 0, 39},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame115 = {
    {0x0100, 0x0000},
    {
        {0x0A00, 1, 0, 40},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame116 = {
    {0x0100, 0x0000},
    {
        {0x0400, 1, 0, 40},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame117 = {
    {0x0100, 0x0000},
    {
        {0x0500, 1, 0, 40},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame118 = {
    {0x0100, 0x0000},
    {
        {0x0600, 1, 0, 40},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame119 = {
    {0x0100, 0x0000},
    {
        {0x0700, 1, 0, 40},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame120 = {
    {0x0100, 0x0000},
    {
        {0x0C00, 1, 0, 40},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame121 = {
    {0x0100, 0x0000},
    {
        {0x0800, 1, 0, 40},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame122 = {
    {0x0100, 0x0000},
    {
        {0x0900, 1, 0, 40},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame123 = {
    {0x0100, 0x0000},
    {
        {0x0B00, 1, 0, 40},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame124 = {
    {0x0200, 0x0000},
    {
        {0x1000, 1, 0, 40},
        {0x0A00, 1, 0, 39},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame125 = {
    {0x0200, 0x0000},
    {
        {0x1100, 1, 0, 40},
        {0x0A00, 1, 0, 39},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame126 = {
    {0x0200, 0x0000},
    {
        {0x1200, 1, 0, 40},
        {0x0A00, 1, 0, 39},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame127 = {
    {0x0200, 0x0000},
    {
        {0x0F00, 1, 0, 40},
        {0x0A00, 1, 0, 39},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame128 = {
    {0x0200, 0x0000},
    {
        {0x1300, 1, 0, 40},
        {0x0A00, 1, 0, 39},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame129 = {
    {0x0200, 0x0000},
    {
        {0x1400, 1, 0, 40},
        {0x0A00, 1, 0, 39},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame130 = {
    {0x0100, 0x0000},
    {
        {0x0A00, 1, 0, 41},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame131 = {
    {0x0100, 0x0000},
    {
        {0x0A00, 1, 0, 42},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame132 = {
    {0x0100, 0x0000},
    {
        {0x0400, 1, 0, 42},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame133 = {
    {0x0100, 0x0000},
    {
        {0x0500, 1, 0, 42},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame134 = {
    {0x0100, 0x0000},
    {
        {0x0600, 1, 0, 42},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame135 = {
    {0x0100, 0x0000},
    {
        {0x0700, 1, 0, 42},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame136 = {
    {0x0100, 0x0000},
    {
        {0x0C00, 1, 0, 42},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame137 = {
    {0x0100, 0x0000},
    {
        {0x0800, 1, 0, 42},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame138 = {
    {0x0100, 0x0000},
    {
        {0x0900, 1, 0, 42},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame139 = {
    {0x0100, 0x0000},
    {
        {0x0B00, 1, 0, 42},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame140 = {
    {0x0200, 0x0000},
    {
        {0x1000, 1, 0, 42},
        {0x0A00, 1, 0, 41},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame141 = {
    {0x0200, 0x0000},
    {
        {0x1100, 1, 0, 42},
        {0x0A00, 1, 0, 41},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame142 = {
    {0x0200, 0x0000},
    {
        {0x1200, 1, 0, 42},
        {0x0A00, 1, 0, 41},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame143 = {
    {0x0200, 0x0000},
    {
        {0x0F00, 1, 0, 42},
        {0x0A00, 1, 0, 41},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame144 = {
    {0x0200, 0x0000},
    {
        {0x1300, 1, 0, 42},
        {0x0A00, 1, 0, 41},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame145 = {
    {0x0200, 0x0000},
    {
        {0x1400, 1, 0, 42},
        {0x0A00, 1, 0, 41},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame146 = {
    {0x0100, 0x0000},
    {
        {0x0A00, 0, 2, 43},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame147 = {
    {0x0100, 0x0000},
    {
        {0x0400, 0, 2, 43},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame148 = {
    {0x0100, 0x0000},
    {
        {0x0500, 0, 2, 43},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame149 = {
    {0x0100, 0x0000},
    {
        {0x0600, 0, 2, 43},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame150 = {
    {0x0100, 0x0000},
    {
        {0x0700, 0, 2, 43},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame151 = {
    {0x0100, 0x0000},
    {
        {0x0C00, 0, 2, 43},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame152 = {
    {0x0100, 0x0000},
    {
        {0x0800, 0, 2, 43},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame153 = {
    {0x0100, 0x0000},
    {
        {0x0900, 0, 2, 43},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame154 = {
    {0x0200, 0x0000},
    {
        {0x0500, 0, 2, 43},
        {0x1000, 2, 0, 44},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame155 = {
    {0x0200, 0x0000},
    {
        {0x0500, 0, 2, 43},
        {0x1100, 2, 0, 44},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame156 = {
    {0x0200, 0x0000},
    {
        {0x0500, 0, 2, 43},
        {0x1200, 2, 0, 44},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame157 = {
    {0x0200, 0x0000},
    {
        {0x0500, 0, 2, 43},
        {0x0F00, 2, 0, 44},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame158 = {
    {0x0200, 0x0000},
    {
        {0x0500, 0, 2, 43},
        {0x1300, 2, 0, 44},
    },
};

SaturnSpriteFrame2 g_SaturnSharedSpriteBank0Frame159 = {
    {0x0200, 0x0000},
    {
        {0x0500, 0, 2, 43},
        {0x1400, 2, 0, 44},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame160 = {
    {0x0100, 0x0000},
    {
        {0x1500, 0, 0, 45},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame161 = {
    {0x0100, 0x0000},
    {
        {0x0000, -1, -6, 46},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame162 = {
    {0x0100, 0x0000},
    {
        {0x0010, 1, -6, 46},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame163 = {
    {0x0100, 0x0000},
    {
        {0x1600, -1, -6, 47},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame164 = {
    {0x0100, 0x0000},
    {
        {0x1610, 1, -6, 47},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame165 = {
    {0x0100, 0x0000},
    {
        {0x1600, -1, -6, 48},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame166 = {
    {0x0100, 0x0000},
    {
        {0x1610, 1, -6, 48},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame167 = {
    {0x0100, 0x0000},
    {
        {0x1700, -1, -6, 49},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame168 = {
    {0x0100, 0x0000},
    {
        {0x1710, 1, -6, 49},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame169 = {
    {0x0100, 0x0000},
    {
        {0x0000, -1, -6, 50},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame170 = {
    {0x0100, 0x0000},
    {
        {0x0010, 1, -6, 50},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame171 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 3, 1, 51},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame172 = {
    {0x0100, 0x0000},
    {
        {0x0D00, 0, -1, 52},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame173 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 0, -1, 53},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame174 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 1, -1, 54},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame175 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 1, -2, 55},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame176 = {
    {0x0100, 0x0000},
    {
        {0x0D00, 3, 0, 56},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame177 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 1, 1, 57},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame178 = {
    {0x0100, 0x0000},
    {
        {0x0F00, 1, 1, 36},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame179 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 6, 1, 58},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame180 = {
    {0x0100, 0x0000},
    {
        {0x1800, 2, 0, 59},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame181 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 3, 0, 60},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame182 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 1, 0, 61},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame183 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 2, 0, 62},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame184 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 2, 1, 63},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame185 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 1, 1, 64},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame186 = {
    {0x0100, 0x0000},
    {
        {0x1900, 4, 1, 65},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame187 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 3, 0, 66},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame188 = {
    {0x0100, 0x0000},
    {
        {0x1900, 1, 1, 67},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame189 = {
    {0x0100, 0x0000},
    {
        {0x1900, 1, 1, 68},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame190 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 2, 3, 69},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame191 = {
    {0x0100, 0x0000},
    {
        {0x1A00, 1, -1, 70},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame192 = {
    {0x0100, 0x0000},
    {
        {0x1A00, 1, -1, 71},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame193 = {
    {0x0100, 0x0000},
    {
        {0x1800, 1, 0, 72},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame194 = {
    {0x0100, 0x0000},
    {
        {0x1800, 1, 0, 73},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame195 = {
    {0x0100, 0x0000},
    {
        {0x1800, 1, 0, 74},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame196 = {
    {0x0100, 0x0000},
    {
        {0x1800, 1, 0, 75},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame197 = {
    {0x0100, 0x0000},
    {
        {0x1800, 1, 0, 76},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame198 = {
    {0x0100, 0x0000},
    {
        {0x1800, 1, 0, 77},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame199 = {
    {0x0100, 0x0000},
    {
        {0x1800, 1, 0, 78},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame200 = {
    {0x0100, 0x0000},
    {
        {0x1800, 1, 0, 79},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank0Frame201 = {
    {0x0100, 0x0000},
    {
        {0x1800, 1, 0, 80},
    },
};

SaturnSpriteFrameHeader* g_SaturnSharedSpriteBank0Frames[202] = {
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame0,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame1,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame2,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame3,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame4,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame5,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame6,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame7,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame8,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame9,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame10,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame11,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame12,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame13,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame14,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame15,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame16,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame17,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame18,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame19,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame20,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame21,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame22,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame23,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame24,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame25,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame26,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame27,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame28,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame29,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame30,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame31,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame32,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame33,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame34,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame35,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame36,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame37,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame38,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame39,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame40,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame41,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame42,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame43,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame44,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame45,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame46,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame47,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame48,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame49,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame50,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame51,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame52,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame53,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame54,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame55,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame56,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame57,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame58,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame59,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame60,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame61,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame62,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame63,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame64,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame65,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame66,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame67,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame68,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame69,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame70,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame71,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame72,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame73,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame74,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame75,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame76,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame77,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame78,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame79,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame80,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame81,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame82,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame83,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame84,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame85,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame86,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame87,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame88,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame89,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame90,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame91,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame92,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame93,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame94,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame95,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame96,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame97,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame98,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame99,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame100,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame101,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame102,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame103,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame104,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame105,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame106,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame107,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame108,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame109,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame110,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame111,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame112,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame113,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame114,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame115,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame116,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame117,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame118,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame119,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame120,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame121,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame122,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame123,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame124,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame125,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame126,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame127,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame128,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame129,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame130,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame131,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame132,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame133,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame134,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame135,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame136,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame137,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame138,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame139,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame140,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame141,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame142,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame143,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame144,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame145,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame146,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame147,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame148,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame149,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame150,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame151,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame152,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame153,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame154,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame155,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame156,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame157,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame158,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame159,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame160,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame161,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame162,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame163,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame164,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame165,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame166,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame167,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame168,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame169,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame170,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame171,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame172,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame173,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame174,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame175,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame176,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame177,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame178,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame179,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame180,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame181,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame182,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame183,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame184,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame185,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame186,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame187,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame188,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame189,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame190,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame191,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame192,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame193,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame194,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame195,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame196,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame197,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame198,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame199,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame200,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank0Frame201,
};

SaturnSpriteImage g_SaturnSharedSpriteBank0Images[82] = {
    {8, 11, 0x0000},
    {12, 6, 0x0018},
    {8, 6, 0x002C},
    {8, 6, 0x0038},
    {8, 6, 0x0044},
    {8, 6, 0x0050},
    {4, 6, 0x005C},
    {8, 4, 0x0064},
    {12, 6, 0x006C},
    {12, 6, 0x0080},
    {12, 6, 0x0094},
    {12, 6, 0x00A8},
    {16, 9, 0x00BC},
    {4, 3, 0x00E0},
    {4, 3, 0x00E4},
    {4, 3, 0x00E8},
    {4, 3, 0x00EC},
    {8, 7, 0x00F0},
    {12, 7, 0x0100},
    {12, 9, 0x0118},
    {16, 9, 0x0134},
    {8, 2, 0x0158},
    {8, 4, 0x015C},
    {16, 7, 0x0164},
    {8, 2, 0x0180},
    {8, 5, 0x0184},
    {8, 3, 0x0190},
    {8, 6, 0x0198},
    {8, 3, 0x01A4},
    {8, 7, 0x01AC},
    {12, 9, 0x01BC},
    {12, 10, 0x01D8},
    {12, 4, 0x01F8},
    {12, 9, 0x0204},
    {12, 10, 0x0220},
    {8, 5, 0x0240},
    {4, 3, 0x024C},
    {12, 6, 0x0250},
    {16, 9, 0x0264},
    {8, 7, 0x0288},
    {8, 7, 0x0298},
    {8, 7, 0x02A8},
    {8, 7, 0x02B8},
    {4, 4, 0x02C8},
    {4, 2, 0x02CC},
    {16, 16, 0x02D0},
    {12, 7, 0x0310},
    {12, 7, 0x0328},
    {12, 7, 0x0340},
    {12, 7, 0x0358},
    {12, 7, 0x0370},
    {12, 3, 0x0388},
    {8, 8, 0x0394},
    {8, 9, 0x03A4},
    {8, 8, 0x03B8},
    {12, 9, 0x03C8},
    {12, 7, 0x03E4},
    {12, 8, 0x03FC},
    {12, 5, 0x0414},
    {8, 6, 0x0424},
    {8, 7, 0x0430},
    {8, 6, 0x0440},
    {8, 6, 0x044C},
    {8, 5, 0x0458},
    {8, 3, 0x0464},
    {8, 6, 0x046C},
    {8, 6, 0x0478},
    {4, 3, 0x0484},
    {4, 3, 0x0488},
    {16, 15, 0x048C},
    {12, 20, 0x04C8},
    {12, 4, 0x0504},
    {8, 8, 0x0510},
    {8, 8, 0x0520},
    {8, 8, 0x0530},
    {8, 8, 0x0540},
    {8, 8, 0x0550},
    {8, 8, 0x0560},
    {8, 8, 0x0570},
    {8, 8, 0x0580},
    {8, 8, 0x0590},
    {0, 0, 0x05A0},
};

struct {
    u16 countAndFlags;
    u16 colors[27][16];
    u16 padding[1];
} g_SaturnSharedSpriteBank0Palette = {
    0x001B,
    {
        {
            0x81E0, 0x8421, 0x80EE, 0x8A1F, 0xBBBF, 0xF3DE, 0xD6B5, 0xFD66,
            0xFEA7, 0xFE36, 0xFFFF, 0x9C61, 0xB4A2, 0xCCE3, 0xE524, 0xFD65,
        },
        {
            0xB0A5, 0x8005, 0x8178, 0x827F, 0xBBBF, 0x9084, 0xC52C, 0xC5AE,
            0xD6B5, 0x800C, 0x8C76, 0x94BF, 0xA95F, 0xB9FF, 0xDEFF, 0xFBDE,
        },
        {
            0xB0A5, 0x8138, 0xFD78, 0xFE7F, 0xFFBF, 0x8380, 0x8340, 0x8760,
            0x83E0, 0x81DA, 0x82DF, 0xBBFF, 0xEBFF, 0xFFFF, 0xDEFF, 0xFBDE,
        },
        {
            0x90A5, 0x8000, 0x8260, 0x82C0, 0x8320, 0x8380, 0x83E0, 0xCC80,
            0xFD68, 0x80B2, 0x815F, 0x827F, 0xBBBF, 0xA529, 0xCA52, 0xF7BD,
        },
        {
            0x80C0, 0x8421, 0x8010, 0x801F, 0xA53F, 0xBDFF, 0x8017, 0x801F,
            0xA946, 0x81B9, 0x829E, 0x9CE7, 0xAD6B, 0xC210, 0xDAD6, 0xF7BD,
        },
        {
            0x80C0, 0x8421, 0x80B2, 0x815F, 0x827F, 0xBBBF, 0x80B2, 0x815F,
            0xA946, 0x8DDB, 0x93BF, 0x9CE7, 0xAD6B, 0xC210, 0xDAD6, 0xF7BD,
        },
        {
            0x80C0, 0x8421, 0x810E, 0x81F8, 0x82BC, 0x839F, 0x810E, 0x81F8,
            0xA946, 0xF540, 0xF2AE, 0x9CE7, 0xAD6B, 0xC210, 0xDAD6, 0xF7BD,
        },
        {
            0x80C0, 0x8421, 0x81A0, 0x8240, 0x82C0, 0x83C0, 0x81A0, 0x8240,
            0xA946, 0x825F, 0x837B, 0x9CE7, 0xAD6B, 0xC210, 0xDAD6, 0xF7BD,
        },
        {
            0x8220, 0x8421, 0xC400, 0xFC00, 0xFD68, 0xFE67, 0xD800, 0xFC00,
            0xA946, 0x8957, 0x82BB, 0x9CE7, 0xAD6B, 0xC210, 0xDAD6, 0xF7BD,
        },
        {
            0x8160, 0x8421, 0xCC2D, 0xF112, 0xFE10, 0xFED6, 0xCC2D, 0xF112,
            0xA946, 0x825F, 0x837B, 0x9CE7, 0xAD6B, 0xC210, 0xDAD6, 0xF7BD,
        },
        {
            0x8140, 0x8421, 0xA529, 0xB5AD, 0xCE73, 0xF39C, 0xB5AD, 0xDAD6,
            0xA946, 0x8014, 0x837B, 0x9CE7, 0xAD6B, 0xC210, 0xDAD6, 0xF7BD,
        },
        {
            0x80C0, 0x8421, 0x8421, 0x9084, 0xA108, 0xB18C, 0x8421, 0x9084,
            0xA946, 0xC012, 0xF41B, 0x9CE7, 0xAD6B, 0xC210, 0xDAD6, 0xF7BD,
        },
        {
            0x80C0, 0x8421, 0xA520, 0xB9C0, 0xD280, 0xEF60, 0xA520, 0xB9C0,
            0xA946, 0x81B9, 0x82FB, 0x9CE7, 0xAD6B, 0xC210, 0xDAD6, 0xF7BD,
        },
        {
            0x90A5, 0x8421, 0xE800, 0xCC00, 0xDC00, 0xEC00, 0xFC00, 0xFD60,
            0xFE6B, 0x80B2, 0x815F, 0x827F, 0xBBBF, 0xBD4A, 0xCA52, 0xF7BD,
        },
        {
            0x90A5, 0x8421, 0xE800, 0xCC00, 0xDC00, 0xEC00, 0xFC00, 0xBCD3,
            0xB979, 0x88AE, 0x815F, 0x827F, 0xBBBF, 0xA529, 0xCA52, 0xF7BD,
        },
        {
            0x90A5, 0xE419, 0x823F, 0x8339, 0xCBE0, 0xE720, 0xE419, 0x823F,
            0x8339, 0xCBE0, 0xE720, 0xE419, 0x823F, 0x8339, 0xCBE0, 0xE720,
        },
        {
            0x90A5, 0x819D, 0x921D, 0x969E, 0xAF5F, 0xD7DF, 0x819D, 0x921D,
            0x969E, 0xAF5F, 0xD7DF, 0x819D, 0x921D, 0x969E, 0xAF5F, 0xD7DF,
        },
        {
            0x90A5, 0xA108, 0xAD6B, 0xBDEF, 0xD294, 0xE739, 0xA108, 0xAD6B,
            0xBDEF, 0xD294, 0xE739, 0xA108, 0xAD6B, 0xBDEF, 0xD294, 0xE739,
        },
        {
            0x90A5, 0xDC80, 0xE540, 0xEE00, 0xF6C0, 0xFF80, 0xDC80, 0xE540,
            0xEE00, 0xF6C0, 0xFF80, 0xDC80, 0xE540, 0xEE00, 0xF6C0, 0xFF80,
        },
        {
            0x90A5, 0x984C, 0x98CC, 0x994C, 0x99CC, 0x9A4C, 0x984C, 0x98CC,
            0x994C, 0x99CC, 0x9A4C, 0x984C, 0x98CC, 0x994C, 0x99CC, 0x9A4C,
        },
        {
            0x90A5, 0x8048, 0x804C, 0x8050, 0x8054, 0x8058, 0x8048, 0x804C,
            0x8050, 0x8054, 0x8058, 0x8048, 0x804C, 0x8050, 0x8054, 0x8058,
        },
        {
            0xC0A8, 0x8421, 0x84AB, 0x8D2F, 0x91D6, 0x929B, 0x994A, 0xA5CE,
            0x8421, 0x9CE7, 0xFFE0, 0x98A5, 0xA94A, 0xBE2E, 0xC2F7, 0xF39C,
        },
        {
            0x81E0, 0x8000, 0x8000, 0x8000, 0x8000, 0x8000, 0x8000, 0x8000,
            0x8000, 0x8000, 0x8000, 0xA0A3, 0xB4E4, 0xC945, 0xDD87, 0xF1E8,
        },
        {
            0x81E0, 0x8421, 0x8000, 0x8000, 0x8000, 0x8000, 0x8000, 0x8000,
            0x8000, 0x8000, 0x8000, 0x9840, 0xB081, 0xC8C2, 0xE103, 0xF923,
        },
        {
            0x8180, 0x8C60, 0x8880, 0x8CC0, 0x800B, 0x80F1, 0x9DD9, 0xB2DF,
            0xA1EC, 0xD100, 0xE9E6, 0xC9B4, 0xAD27, 0xBDAC, 0xD251, 0xEF38,
        },
        {
            0xB0A5, 0x815B, 0x819C, 0x921D, 0x969E, 0xAF5F, 0xD7DF, 0xFFFF,
            0xE900, 0xED40, 0xF180, 0xF604, 0xFA85, 0xFF4B, 0xFFD5, 0xFFFF,
        },
        {
            0xC0AC, 0x8842, 0x88A8, 0x950D, 0xA992, 0x8C29, 0x944E, 0xA0D2,
            0xC591, 0xCA52, 0xEF7B, 0x98C6, 0xAD6B, 0xCA52, 0xE739, 0xFFFF,
        },
    },
    {0x0000},
};

SaturnSpriteResource g_SaturnSharedSpriteBank0Resource = {
    g_SaturnSharedSpriteBank0Images,
    (u16*)&g_SaturnSharedSpriteBank0Palette,
    -1,
    0xFFFF,
};

