// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[4][16];
    u16 padding[1];
} g_SaturnSharedSpriteBank13Palette = {
    0x4004,
    {
        {
            0xD800,
            0x8180,
            0xDF7B,
            0xCEF7,
            0xBE73,
            0xA9EF,
            0x954A,
            0x8CE8,
            0x8484,
            0x9441,
            0xB506,
            0x846A,
            0x84D6,
            0x99DA,
            0xB6BD,
            0xC75D,
        },
        {
            0x801B,
            0x8180,
            0x8160,
            0x8540,
            0x8920,
            0x8D00,
            0x90E0,
            0x94C0,
            0x98C0,
            0x98A0,
            0x9C80,
            0xA060,
            0xA440,
            0xA820,
            0xAC00,
            0xB000,
        },
        {
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
        },
        {
            0x7FFF,
            0x4000,
            0x8011,
            0x8010,
            0x800F,
            0x800E,
            0x800D,
            0x800E,
            0x800F,
            0x8010,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
        },
    },
    {0x0000},
};

SaturnSpriteImage g_SaturnSharedSpriteBank13Images[5] = {
    {16, 12, 0x0000}, {16, 12, 0x0030}, {4, 12, 0x0060},
    {4, 8, 0x006C},   {0, 0, 0x0074},
};

SaturnSpriteResource g_SaturnSharedSpriteBank13Resource = {
    g_SaturnSharedSpriteBank13Images,
    (u16*)&g_SaturnSharedSpriteBank13Palette,
    -1,
    0xFFFF,
};
