// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_SaturnSharedSpriteBank2Frame0 = {
    0x0000, 0x0000,
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank2Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 2, 0},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank2Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 1, 1},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank2Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 1, 2},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank2Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0100, 3, -14, 3},
    },
};

SaturnSpriteFrameHeader* g_SaturnSharedSpriteBank2Frames[5] = {
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank2Frame0,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank2Frame1,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank2Frame2,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank2Frame3,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank2Frame4,
};

SaturnSpriteImage g_SaturnSharedSpriteBank2Images[5] = {
    {16, 14, 0x0000},
    {20, 14, 0x0038},
    {20, 15, 0x0080},
    {20, 15, 0x00CC},
    {0, 0, 0x0118},
};

struct {
    u16 countAndFlags;
    u16 colors[2][16];
    u16 padding[1];
} g_SaturnSharedSpriteBank2Palette = {
    0x0002,
    {
        {
            0x8942, 0xAD54, 0xB5D6, 0xBE58, 0xC6DB, 0xCF5D, 0xD7DF, 0xFFFF,
            0xCD2B, 0xD58C, 0xDE0E, 0xE670, 0xEEF1, 0xF753, 0xFFD5, 0xFFFF,
        },
        {
            0xB0A5, 0x8000, 0x83E0, 0xBC00, 0xC900, 0xD900, 0xD940, 0xE180,
            0xFC82, 0xE23F, 0x8033, 0x811C, 0xB19F, 0x825F, 0xBB7F, 0xE3FF,
        },
    },
    {0x0000},
};

SaturnSpriteResource g_SaturnSharedSpriteBank2Resource = {
    g_SaturnSharedSpriteBank2Images,
    (u16*)&g_SaturnSharedSpriteBank2Palette,
    -1,
    0xFFFF,
};

