// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_SaturnSharedSpriteBank10Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 4, 0},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0100, 3, 4, 1},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 4, 2},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0200, 1, 2, 3},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0100, 2, 6, 4},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0100, 2, 1, 5},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0300, 3, 7, 6},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0400, 1, 1, 7},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0500, 2, 2, 8},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame10 = {
    {0x0100, 0x0000},
    {
        {0x0600, 0, 1, 9},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame11 = {
    {0x0100, 0x0000},
    {
        {0x0600, 0, 1, 10},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame12 = {
    {0x0100, 0x0000},
    {
        {0x0600, 0, 1, 11},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame13 = {
    {0x0100, 0x0000},
    {
        {0x0700, 0, 0, 12},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame14 = {
    {0x0100, 0x0000},
    {
        {0x0700, 1, 0, 13},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame15 = {
    {0x0100, 0x0000},
    {
        {0x0800, 2, 0, 14},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame16 = {
    {0x0100, 0x0000},
    {
        {0x0600, 2, 2, 15},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame17 = {
    {0x0100, 0x0000},
    {
        {0x0900, 5, 1, 16},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame18 = {
    {0x0100, 0x0000},
    {
        {0x0A00, 2, 0, 17},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame19 = {
    {0x0100, 0x0000},
    {
        {0x0600, 3, 1, 18},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame20 = {
    {0x0100, 0x0000},
    {
        {0x0A00, 3, 4, 19},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame21 = {
    {0x0100, 0x0000},
    {
        {0x0A00, 1, 4, 20},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame22 = {
    {0x0100, 0x0000},
    {
        {0x0B00, 1, -2, 21},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame23 = {
    {0x0100, 0x0000},
    {
        {0x0900, 4, 1, 22},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame24 = {
    {0x0100, 0x0000},
    {
        {0x0900, 1, 2, 23},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame25 = {
    {0x0100, 0x0000},
    {
        {0x0300, 4, 2, 24},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame26 = {
    {0x0100, 0x0000},
    {
        {0x0900, 3, 2, 25},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame27 = {
    {0x0100, 0x0000},
    {
        {0x0C00, 3, 0, 26},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame28 = {
    {0x0100, 0x0000},
    {
        {0x0200, 2, -2, 27},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame29 = {
    {0x0100, 0x0000},
    {
        {0x0500, 2, -1, 28},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame30 = {
    {0x0100, 0x0000},
    {
        {0x0500, 1, -2, 29},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame31 = {
    {0x0100, 0x0000},
    {
        {0x0500, 1, 2, 30},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame32 = {
    {0x0100, 0x0000},
    {
        {0x0D00, 2, 2, 31},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame33 = {
    {0x0100, 0x0000},
    {
        {0x0300, 1, 1, 32},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame34 = {
    {0x0100, 0x0000},
    {
        {0x0300, 4, 0, 33},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame35 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 1, 6, 34},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame36 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 2, 6, 35},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame37 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 2, 1, 36},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame38 = {
    {0x0100, 0x0000},
    {
        {0x0E00, 3, 4, 37},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame39 = {
    {0x0100, 0x0000},
    {
        {0x0800, 0, 1, 38},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame40 = {
    {0x0100, 0x0000},
    {
        {0x0F00, 3, 0, 39},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame41 = {
    {0x0100, 0x0000},
    {
        {0x0500, 4, -3, 40},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame42 = {
    {0x0100, 0x0000},
    {
        {0x1000, 3, 0, 41},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank10Frame43 = {
    {0x0100, 0x0000},
    {
        {0x1100, 4, 0, 42},
    },
};

SaturnSpriteFrameHeader* g_SaturnSharedSpriteBank10Frames[44] = {
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame0,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame1,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame2,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame3,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame4,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame5,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame6,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame7,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame8,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame9,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame10,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame11,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame12,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame13,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame14,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame15,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame16,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame17,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame18,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame19,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame20,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame21,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame22,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame23,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame24,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame25,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame26,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame27,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame28,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame29,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame30,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame31,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame32,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame33,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame34,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame35,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame36,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame37,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame38,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame39,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame40,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame41,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame42,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank10Frame43,
};

SaturnSpriteImage g_SaturnSharedSpriteBank10Images[44] = {
    {4, 3, 0x0000},   {8, 5, 0x0004},   {8, 5, 0x0010},  {8, 7, 0x001C},
    {8, 3, 0x002C},   {8, 7, 0x0034},   {4, 1, 0x0044},  {8, 6, 0x0048},
    {8, 6, 0x0054},   {8, 7, 0x0060},   {8, 7, 0x0070},  {8, 7, 0x0080},
    {8, 9, 0x0090},   {12, 8, 0x00A4},  {8, 9, 0x00BC},  {8, 6, 0x00D0},
    {12, 7, 0x00DC},  {16, 11, 0x00F4}, {12, 8, 0x0120}, {12, 4, 0x0138},
    {12, 4, 0x0144},  {16, 12, 0x0150}, {16, 6, 0x0180}, {16, 6, 0x0198},
    {20, 6, 0x01B0},  {16, 10, 0x01D0}, {16, 8, 0x01F8}, {8, 9, 0x0218},
    {8, 9, 0x022C},   {8, 11, 0x0240},  {8, 6, 0x0258},  {12, 7, 0x0264},
    {12, 5, 0x027C},  {16, 8, 0x028C},  {4, 3, 0x02AC},  {4, 3, 0x02B0},
    {8, 7, 0x02B4},   {16, 11, 0x02C4}, {12, 8, 0x02F0}, {20, 9, 0x0308},
    {16, 12, 0x0338}, {8, 7, 0x0368},   {12, 5, 0x0378}, {0, 0, 0x0388},
};

struct {
    u16 countAndFlags;
    u16 colors[18][16];
    u16 padding[1];
} g_SaturnSharedSpriteBank10Palette = {
    0x0012,
    {
        {
            0xA640,
            0x8000,
            0x88A8,
            0xBDFF,
            0x9DBB,
            0x9A9F,
            0xCEDF,
            0x9E3F,
            0x8D34,
            0x8F5F,
            0xB630,
            0x9C9B,
            0x85E2,
            0x82C0,
            0xA95F,
            0xFFFF,
        },
        {
            0xBD43,
            0x800B,
            0x9092,
            0xBDFF,
            0x9DBB,
            0x9A9F,
            0xCEDF,
            0x9E3F,
            0x8D34,
            0x8F5F,
            0x8922,
            0x949B,
            0x85E2,
            0x82C0,
            0xA55F,
            0x8863,
        },
        {
            0xC213,
            0x98C5,
            0x8C8F,
            0x99DF,
            0xA199,
            0xA211,
            0xCF7F,
            0x8521,
            0xC60C,
            0xE2F3,
            0xA4FF,
            0xD7ED,
            0x8200,
            0x82C0,
            0xA749,
            0xF39C,
        },
        {
            0x95E8,
            0x8000,
            0x8033,
            0xBDFF,
            0x819F,
            0x9A7F,
            0xCF7E,
            0xA946,
            0xC62C,
            0xE313,
            0x88CA,
            0x9572,
            0x9E7C,
            0xC71C,
            0x801F,
            0xFFDD,
        },
        {
            0xB2A0,
            0x8000,
            0x8031,
            0x8CBC,
            0x9D7F,
            0x958F,
            0x9A17,
            0xCF7E,
            0x82C0,
            0xD860,
            0xFDE0,
            0xFF00,
            0xA946,
            0xC62C,
            0xE313,
            0xF779,
        },
        {
            0x8260,
            0x8065,
            0x80CD,
            0x8D14,
            0x8979,
            0x8DDE,
            0x9A7F,
            0xB2FE,
            0xCF7E,
            0xB9CD,
            0x81A0,
            0x8320,
            0xA529,
            0xCA52,
            0xE739,
            0xFFFF,
        },
        {
            0xA2A0,
            0x8886,
            0x8033,
            0xBDFF,
            0x819F,
            0x9A7F,
            0xDFBF,
            0x9DB9,
            0xA65F,
            0xC37F,
            0xC104,
            0xDE0D,
            0xEB39,
            0x90EC,
            0x801F,
            0xFFFF,
        },
        {
            0xD5AC,
            0x8000,
            0x8033,
            0x91E4,
            0x819F,
            0x9A7F,
            0xCF7F,
            0xA946,
            0xC60C,
            0xE2F5,
            0xD882,
            0xFDE2,
            0xFEE2,
            0x82C0,
            0x801F,
            0xFFDD,
        },
        {
            0xB2A0,
            0x8000,
            0x8033,
            0xBDFF,
            0x819F,
            0x9A7F,
            0xCF7E,
            0xA946,
            0xC62C,
            0xE313,
            0xD860,
            0xFDE0,
            0xFF00,
            0x82C0,
            0x801F,
            0xFFFF,
        },
        {
            0xB903,
            0x8842,
            0x88D3,
            0xADFF,
            0x9597,
            0x9A7E,
            0xC73E,
            0x9552,
            0xC62C,
            0xE313,
            0x888A,
            0xA108,
            0xFF00,
            0x82C0,
            0x8180,
            0xFFDD,
        },
        {
            0xC184,
            0x8000,
            0x8033,
            0xBDFF,
            0x819F,
            0x9A7F,
            0xC73F,
            0xA946,
            0xC62C,
            0xE313,
            0x801F,
            0x98C6,
            0x8200,
            0x82C0,
            0x9939,
            0xF779,
        },
        {
            0x9A20,
            0x8000,
            0x8473,
            0xBDFF,
            0x919B,
            0x9A7F,
            0xCF7E,
            0xA946,
            0xC62C,
            0xE313,
            0xD860,
            0xFDE0,
            0xFF00,
            0x82C0,
            0x8180,
            0xFFFF,
        },
        {
            0x958A,
            0x8000,
            0x8052,
            0xBDFF,
            0x8222,
            0x9F4F,
            0xCF7E,
            0xB126,
            0xC9EC,
            0xE313,
            0x9916,
            0x957A,
            0xA23D,
            0xBF1F,
            0x845C,
            0xFFDD,
        },
        {
            0x81E0,
            0x8000,
            0x8033,
            0xBDFF,
            0x9D9F,
            0xB63D,
            0xCF7E,
            0xA946,
            0xC62C,
            0xE313,
            0x8CEC,
            0xB65A,
            0xBABF,
            0x82C0,
            0x885F,
            0xFF98,
        },
        {
            0x9A88,
            0x8000,
            0x8033,
            0x9177,
            0xAA9F,
            0xBABC,
            0xD7BF,
            0x9164,
            0x9266,
            0xAB2E,
            0x88CA,
            0x9572,
            0xAA56,
            0xC31C,
            0xB13F,
            0xF3DF,
        },
        {
            0xA250,
            0x8842,
            0x84D2,
            0xADDF,
            0x8537,
            0x9A7F,
            0xD37F,
            0x895F,
            0xB25F,
            0xAD6B,
            0x8120,
            0x8240,
            0x83A8,
            0x90EC,
            0x91B7,
            0xEFBA,
        },
        {
            0x95E8,
            0x8000,
            0x8033,
            0xBDFF,
            0x819F,
            0x9A7F,
            0xCF7E,
            0xA946,
            0xC62C,
            0xE313,
            0x88CA,
            0x9572,
            0x9E7C,
            0xC71C,
            0x801F,
            0xFFDD,
        },
        {
            0xB903,
            0x8842,
            0x88D3,
            0xADFF,
            0x9597,
            0x9A7E,
            0xC73E,
            0x9552,
            0xC62C,
            0xE313,
            0x888A,
            0xA108,
            0xFF00,
            0x82C0,
            0x8180,
            0xFFDD,
        },
    },
    {0x0000},
};

SaturnSpriteResource g_SaturnSharedSpriteBank10Resource = {
    g_SaturnSharedSpriteBank10Images,
    (u16*)&g_SaturnSharedSpriteBank10Palette,
    -1,
    0xFFFF,
};
