// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_SaturnSharedSpriteBank9Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank9Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 1, 0},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank9Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 0, 1},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank9Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 0, 2},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank9Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 0, 3},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank9Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 0, 4},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank9Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 1, 5},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank9Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 0, 6},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank9Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 1, 7},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank9Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 1, 8},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank9Frame10 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 0, 9},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank9Frame11 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 0, 10},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank9Frame12 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 0, 11},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank9Frame13 = {
    {0x0100, 0x0000},
    {
        {0x0000, -1, -1, 12},
    },
};

SaturnSpriteFrame1 g_SaturnSharedSpriteBank9Frame14 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, 1, 13},
    },
};

SaturnSpriteFrameHeader* g_SaturnSharedOpaquePuffFrames1[15] = {
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank9Frame0,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank9Frame1,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank9Frame2,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank9Frame3,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank9Frame4,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank9Frame5,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank9Frame6,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank9Frame7,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank9Frame8,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank9Frame9,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank9Frame10,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank9Frame11,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank9Frame12,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank9Frame13,
    (SaturnSpriteFrameHeader*)&g_SaturnSharedSpriteBank9Frame14,
};

SaturnSpriteImage g_SaturnSharedSpriteBank9Images[15] = {
    {16, 14, 0x0000}, {20, 15, 0x0038}, {20, 15, 0x0084}, {20, 15, 0x00D0},
    {20, 15, 0x011C}, {20, 15, 0x0168}, {20, 15, 0x01B4}, {20, 15, 0x0200},
    {20, 15, 0x024C}, {20, 14, 0x0298}, {20, 14, 0x02E0}, {20, 14, 0x0328},
    {16, 13, 0x0370}, {16, 15, 0x03A4}, {0, 0, 0x03E0},
};

struct {
    u16 countAndFlags;
    u16 colors[1][16];
    u16 padding[1];
} g_SaturnSharedSpriteBank9Palette = {
    0x0001,
    {
        {
            0x8200,
            0x8CEF,
            0x8D30,
            0x9171,
            0x95B3,
            0x99F4,
            0x9E35,
            0xA277,
            0xA6B8,
            0xAAFA,
            0xB71B,
            0xC35C,
            0xD37C,
            0xDF9D,
            0xF3DE,
            0xFFFF,
        },
    },
    {0x0000},
};

SaturnSpriteResource g_SaturnSharedSpriteBank9Resource = {
    g_SaturnSharedSpriteBank9Images,
    (u16*)&g_SaturnSharedSpriteBank9Palette,
    -1,
    0xFFFF,
};
