// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
PLAY_SOUND(0x10),
SET_POS(60,24),
LOAD_PORTRAIT(0x80100006,0),
SET_PORTRAIT(0,128),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x501),
WAIT_FOR_SOUND(),
'W','e','l','c','o','m','e',' ','a','b','o','a','r','d',',',' ','O',' ','P','r','i','n','c','e','.',
LINE_BREAK(),
'S','h','a','l','l',' ','I',' ','g','u','i','d','e',' ','t','h','e','e',
LINE_BREAK(),
'\'','c','r','o','s','s',' ','t','h','e',' ','r','i','v','e','r','?',
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
CLOSE_DIALOG(),
SCRIPT_UNKNOWN_20(0x11),
SET_FLAG(7),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
