// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
PLAY_SOUND(0x10),
SET_POS(60,24),
LOAD_PORTRAIT(0x80100006,0),
SET_PORTRAIT(0,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x502),
WAIT_FOR_SOUND(),
'E','u','e','r',' ','S','c','h','i','c','k','s','a','l',' ','e','r','w','a','r','t','e','t',
LINE_BREAK(),
'E','u','c','h',',',' ','o','h',' ','P','r','i','n','z','.',
SET_WAIT(48),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
CLOSE_DIALOG(),
SCRIPT_UNKNOWN_20(0x11),
SET_FLAG(7),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
