// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
PLAY_SOUND(0x10),
SET_POS(60,24),
LOAD_PORTRAIT(0x80100006,0),
SET_PORTRAIT(0,128),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x501),
WAIT_FOR_SOUND(),
'B','i','e','n','v','e','n','i','d','o',' ','a',' ','b','o','r','d','o',',',' ','m','i',
LINE_BREAK(),
'p','r','\xD5','n','c','i','p','e','.',' ','\xB3','Q','u','e','r','\xD1','i','s',' ','q','u','e',
LINE_BREAK(),
'o','s',' ','a','y','u','d','e',' ','a',' ','c','r','u','z','a','r',' ','e','l',' ','r','\xD5','o','?',
SET_WAIT(48),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
CLOSE_DIALOG(),
SCRIPT_UNKNOWN_20(0x11),
SET_FLAG(7),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
