// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
PLAY_SOUND(0x10),
SET_POS(60,24),
LOAD_PORTRAIT(0x80100006,0),
SET_PORTRAIT(0,128),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x501),
WAIT_FOR_SOUND(),
'B','e','n','v','e','n','u','t','o',' ','a',' ','b','o','r','d','o',',',' ',
LINE_BREAK(),
'b','u','o','n',' ','P','r','i','n','c','i','p','e','.',
LINE_BREAK(),
'V','u','o','i',' ','g','u','a','d','a','r','e',' ','i','l',' ','f','i','u','m','e','?',
SET_WAIT(96),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
CLOSE_DIALOG(),
SCRIPT_UNKNOWN_20(0x11),
SET_FLAG(7),
END_CUTSCENE(),
