// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
PLAY_SOUND(0x10),
SET_POS(60,24),
LOAD_PORTRAIT(0x80100006,0),
SET_PORTRAIT(0,128),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x501),
WAIT_FOR_SOUND(),
'B','i','e','n','v','e','n','u','e',' ','\xCB',' ','b','o','r','d',',',
LINE_BREAK(),
'O',' ','P','r','i','n','c','e','.',' ','D','o','i','s','-','j','e',
LINE_BREAK(),
'v','o','u','s',' ','f','a','i','r','e',' ','t','r','a','v','e','r','s','e','r',
LINE_BREAK(),
'l','a',' ','r','i','v','i','\xD0','r','e',' ','?',
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
CLOSE_DIALOG(),
SCRIPT_UNKNOWN_20(0x11),
SET_FLAG(7),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
