// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
PLAY_SOUND(0x10),
SET_POS(60,24),
LOAD_PORTRAIT(0x80100006,0),
SET_PORTRAIT(0,128),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x501),
WAIT_FOR_SOUND(),
'W','i','l','l','k','o','m','m','e','n',' ','a','n',' ','B','o','r','d',',',
LINE_BREAK(),
'o','h',' ','P','r','i','n','z','.',' ','S','o','l','l',' ','i','c','h',' ','E','u','c','h',
LINE_BREAK(),
'\xA8','b','e','r',' ','d','e','n',' ','F','l','u','s','s',' ','g','e','l','e','i','t','e','n','?',
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
CLOSE_DIALOG(),
SCRIPT_UNKNOWN_20(0x11),
SET_FLAG(7),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
