// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
PLAY_SOUND(0x10),
SET_POS(60,24),
LOAD_PORTRAIT(0x80100006,0),
SET_PORTRAIT(0,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x502),
WAIT_FOR_SOUND(),
'E','l',' ','d','e','s','t','i','n','o',' ','e','s','p','e','r','a',',',
LINE_BREAK(),
'm','i',' ','p','r','\xD5','n','c','i','p','e','.',
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
CLOSE_DIALOG(),
SCRIPT_UNKNOWN_20(0x11),
SET_FLAG(7),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
