options:
  target_path:  disks/saturn/ALUCARD.PRG
  asm_path:     asm/saturn/alucard
  src_path:     src/saturn
  obj_path:     build/saturn
  ld_scripts_path: config/saturn
  syms_path: config/saturn
  decomp_empty_funcs: false
segments:
  - name: alucard
    type: code
    start: 0x00000000
    vram:  0x060A5000
    subalign: 2
    subsegments:
      - [0x0, .data, alucard/header]
      - start: 0x44
        type: .text
        file: alucard/hdrstub

      - start: 0x60
        type: c
        file: alucard
        end: 0x1be47
        function_ranges:
          - [0x1384, 0x141E]
          - [0x1A94, 0x2D3A]

      - start: 0x1be48
        type: c
        file: alucard
        end: 0x22F9F
        function_ranges:
          - [0x1BE48, 0x1C373]

      - start: 0x22FA0
        type: c
        file: alucard
        end: 0x234b7

      - start: 0x234b8
        type: data
        file: alucard
        end: 0x2947f
