options:
  target_path:  disks/saturn/GAME.PRG
  asm_path:     asm/saturn/game
  src_path:     src/saturn
  ld_scripts_path: config/saturn
  syms_path: config/saturn
  # some sort of alignment issues
  decomp_empty_funcs: false
segments:
  - name: game
    type: code
    start: 0x00000000
    vram:  0x06066000
    subalign: 2
    subsegments:
      - start: 0x0
        type: data
        file: game_0
        end: 0x3F
      - start: 0x40
        type: c
        file: game_0
        end: 0x8D3
      - start: 0x8D4
        type: c
        file: game_0
        end: 0x92B
      - start: 0x92C
        type: data
        file: game_0
        end: 0xB2F
      - start: 0xB30
        type: c
        file: game_0
        end: 0x197B
        # misdetected function TODO
      - start: 0x197C
        type: data
        file: game_0
        end: 0x1A03
      - start: 0x1A04
        type: c
        file: game_0
        end: 0x80C7
      - start: 0x80C8
        type: data
        file: game_0
        end: 0x80CF
      - start: 0x80D0
        type: c
        file: game_0
        end: 0x92BF

        # file split here

      - start: 0x92C0
        type: c
        file: game_0
        end: 0xA937

        # file split here

      - start: 0xA938
        type: c
        file: game
        end: 0xAA5F
        # function that doesn't have an rts TODO
      - start: 0xAA60
        type: data
        file: game
        end: 0xBC3B
      - start: 0xBC3C
        type: c
        file: game
        end: 0xC8B3
      # todo problematic jump table
      - start: 0xC8B4
        type: data
        file: game
        end: 0xCBCB
      - start: 0xCBCC
        type: c
        file: game
        end: 0x2008B
