options:
  target_path:  disks/saturn/GAME.PRG
  asm_path:     asm/saturn/game
  src_path:     src/saturn/game
segments:
  - name: game
    type: code
    start: 0x00000000
    vram:  0x06066000
    subalign: 2
    subsegments:
      - start: 0x0
        type: data
        file: 40
        end: 0x3F
      - start: 0x40
        type: c
        file: 40
        end: 0x2008B
