options:
  target_path:  disks/saturn/GAME.PRG
  asm_path:     asm/saturn/game
  src_path:     src/saturn
  obj_path:     build/saturn
  ld_scripts_path: config/saturn
  syms_path: config/saturn
  check_layout: true
  # some sort of alignment issues
  decomp_empty_funcs: false
segments:
  - name: game
    type: code
    start: 0x00000000
    vram:  0x06066000
    subalign: 2
    subsegments:
      - [0x0, .data, game/header]
      - start: 0x30
        type: .text
        file: game/hdrstub
      - start: 0x40
        type: c
        file: game_0
        end: 0x8D3
      - start: 0x8D4
        type: c
        file: game_0
        end: 0x92B
      - start: 0x92C
        type: .data
        file: game/savemsg
      - start: 0xB30
        type: c
        file: game_1
        end: 0x197B
        # misdetected function TODO
      - start: 0x197C
        type: data
        file: game_1
        end: 0x1A03
      - start: 0x1A04
        type: c
        file: game_1
        end: 0x1A3B
      - start: 0x1A3C
        type: .text
        file: game/cfgjp
      - start: 0x56D4
        type: .text
        file: game/cfgstr
      - start: 0x56F8
        type: c
        file: game_3
        end: 0x80C7
      - start: 0x80C8
        type: data
        file: game_3
        end: 0x80CF
      - start: 0x80D0
        type: c
        file: game_3
        end: 0x92BF

        # file split here

      - start: 0x92C0
        type: c
        file: game_3
        end: 0xA937

        # file split here

      - start: 0xA938
        type: c
        file: game
        end: 0xBC3B
      - start: 0xBC3C
        type: c
        file: game
        end: 0xC8B3
      # todo problematic jump table
      - start: 0xC8B4
        type: data
        file: game
        end: 0xCBCB
      - start: 0xCBCC
        type: c
        file: game
        end: 0xEC9B
      - start: 0xEC9C
        type: .text
        file: game/miscend
      - start: 0xECC0
        type: c
        file: game_2
        end: 0x1614B
      - [0x1614C, .data, game/cfgjp]
      - start: 0x1E6A8
        type: .text
        file: game/cfgrw1
      - [0x1F0EC, .data, game/jewel]
      - start: 0x1F0F4
        type: .text
        file: game/cfgrw4
      - [0x1F4C8, .data, game/btnmask]
      - start: 0x1F4D8
        type: .text
        file: game/cfgrw2
      - [0x1F4E0, .data, game/lvlhp]
      - start: 0x1F508
        type: .text
        file: game/cfgrw3
      - [0x1F524, .data, game/mnstate]
      - start: 0x1F528
        type: .text
        file: game/cfgrw5
      - [0x1F54C, .data, game/eqhelp]
      - [0x1F5AC, .data, game/mnscroll]
      - start: 0x1F5B0
        type: .text
        file: game/cfgrest
      - [0x1FC30, .data, game/capetbl]
      - [0x1FC70, .data, game/joseph]
      - [0x1FC78, .data, game/capecon]
      - [0x1FC88, .data, game/capepal]
      - [0x1FC90, .data, game/miscend]
      - [0x1FE86, .data, game/sinetbl]
