options:
  target_path:  disks/saturn/0.BIN
  asm_path:     asm/saturn/zero
  src_path:     src/saturn
  obj_path:     build/saturn
  ld_scripts_path: config/saturn
  syms_path: config/saturn
  decomp_empty_funcs: false
segments:
  - name: zero
    type: code
    start: 0x00000000
    vram:  0x06004080
    subalign: 4
    subsegments:
      - start: 0x0
        type: data
        file: zero
        end: 0x57

      - start: 0x58
        type: c
        file: zero
        end: 0xA5C3
        function_ranges:
          - [0x0768, 0x07C2]
          - [0x0806, 0x0874]
          - [0x08B2, 0x0956]
          - [0x09C6, 0x09E2]
          - [0x0AA0, 0x0B56]
          - [0x40DC, 0x4110]
          - [0x411C, 0x419C]
          - [0x4BAC, 0x4C5E]
          - [0x4DBA, 0x4E3C]
          - [0x4F3E, 0x4F4C]
          - [0x4F90, 0x4FCC]

      - start: 0xA5C4
        type: data
        file: zero
        end: 0xADE4

      - start: 0xADE5
        type: c
        file: zero
        end: 0xae07
  
      # ratan2
      - start: 0xae08
        type: c
        file: zero
        end: 0xaf3b

      - start: 0xaf3c
        type: data
        file: zero
        end: 0xb893

      # squareroot12
      - start: 0xB894
        type: c
        file: zero
        end: 0xb8eb

      - start: 0xb8ec
        type: c
        file: zero
        end: 0xbf37

      # DestroyEntity
      - start: 0xBf38
        type: c
        file: zero
        end: 0xbf87

      # before DGFS
      - start: 0xbf88
        type: c
        file: zero
        end: 0xD1F7
        
      # bug
      - start: 0xD1F8
        type: c
        file: zero
        end: 0xD9EB
        function_ranges:
          - [0xD1F8, 0xD9EA]
        
      - start: 0xD9EC
        type: c
        file: zero
        end: 0x14647
        function_ranges:
          - [0x1154C, 0x11BEE]
          - [0x11BF0, 0x1243A]
          - [0x1243C, 0x12592]
          - [0x12594, 0x12626]
          - [0x12628, 0x12AC2]

      - start: 0x14648
        type: c
        file: lib/snd
        end: 0x14FF3

      - start: 0x14FF4
        type: c
        file: zero_2
        end: 0x17213

      # DGFS
      - start: 0x17214
        type: c
        file: lib/gfs
        end: 0x1D76B
        function_ranges:
          - [0x178B2, 0x178E2]
          - [0x17918, 0x17956]
          - [0x17B06, 0x17B7A]
          - [0x17BF4, 0x17C7A]
          - [0x17DEA, 0x17E26]
          - [0x17FBA, 0x17FF4]
          - [0x1801E, 0x1805C]
          - [0x1808A, 0x180C4]
          - [0x180EE, 0x1812C]
          - [0x18AC6, 0x18B38]
          - [0x18C00, 0x18C16]
          - [0x18C88, 0x18CC4]
          - [0x1AEC8, 0x1AEDC]
          - [0x1AF1C, 0x1AF30]
          - [0x1B0A8, 0x1B0BE]
          - [0x1B3CA, 0x1B40C]
          - [0x1B4A8, 0x1B4E8]
          - [0x1B54C, 0x1B55E]
          - [0x1B5BA, 0x1B5E0]
          - [0x1B748, 0x1B7A0]

      # SPR_1C
      - start: 0x1D76C
        type: c
        file: lib/spr/spr_1c
        end: 0x1E0E3
      # SPR_2C
      - start: 0x1E0E4
        type: c
        file: lib/spr/spr_2c
        end: 0x1F087
      # SPR_SLV
      - start: 0x1F088
        type: c
        file: lib/spr/spr_slv
        end: 0x1F0CF
      # SPR_2A.SRC
      - start: 0x1F0D0
        type: data
        file: lib/spr/spr_slv
        end: 0x1F313

      # DMA_CPUM
      - start: 0x1F314
        type: c
        file: lib/dma/dma_cpum
        end: 0x1F473
      # DMA_SCU1
      - start: 0x1F474
        type: c
        file: lib/dma/dma_scu1
        end: 0x1F813
      # DMA_SCU0
      - start: 0x1F814
        type: c
        file: lib/dma/dma_scu0
        end: 0x1FCDB
      # DMA_CPU0
      - start: 0x1FCDC
        type: c
        file: lib/dma/dma_cpu0
        end: 0x20007

      # SEGA_SCL.A
      - start: 0x20008
        type: c
        file: lib/scl
        end: 0x26B1B

      # after SCL
      - start: 0x26B1C
        type: c
        file: lib/scl
        end: 0x274AB

      - start: 0x274AC
        type: c
        file: lib/scl
        end: 0x27933

      # SEGA_CSH.A
      - start: 0x27934
        type: c
        file: lib/csh
        end: 0x27B17

      # SEGA_PER.A
      - start: 0x27B18
        type: c
        file: lib/per
        end: 0x29373

      # after PER
      - start: 0x29374
        type: data
        file: lib/per
        end: 0x29423

      # CDC
      - start: 0x29424
        type: c
        file: lib/cdc
        end: 0x2B4CF

      # MTH_FIXD.SRC
      - start: 0x2B4D0
        type: data
        file: lib/mth
        end: 0x2B573
      # MTH_MTRX.SRC
      - start: 0x2B574
        type: data
        file: lib/mth
        end: 0x2BA6B
      # MTH_PS2D.SRC
      - start: 0x2BA6C
        type: data
        file: lib/mth
        end: 0x2BB03
      # MTH_TRI.SRC
      - start: 0x2BB04
        type: data
        file: lib/mth
        end: 0x2C103
      # MTH_CURV.C
      - start: 0x2C104
        type: c
        file: lib/mth
        end: 0x2C307

      # INT_MAIN
      - start: 0x2C308
        type: c
        file: lib/int
        end: 0x2C363

      # _bup_version
      - start: 0x2C364
        type: data
        file: lib/bup
        end: 0x2C383

      # _BUP_Init to _get_sr
      - start: 0x2C384
        type: c
        file: lib/bup
        end: 0x2C9C9

      # after bup
      - start: 0x2C9CA
        type: data
        file: lib/bup
        end: 0x2CA5B

      # version string
      - start: 0x2CA5C
        type: data
        file: lib/sys
        end: 0x2CA7B

      - start: 0x2CA5C
        type: c
        file: lib/sys
        end: 0x2CB73

      # post-SYS
      - start: 0x2CB74
        type: data
        file: lib/sys
        end: 0x369FB

      # 68k sound driver
      - start: 0x369FC
        type: data
        file: lib/sys
        end: 0x3D1EF

      # post-SYS
      - start: 0x3D1F0
        type: data
        file: lib/sys
        end: 0x4C560
