// SPDX-License-Identifier: AGPL-3.0-or-later
#include "no0.h"

u16 OVL_EXPORT(PrizeDrops)[] = {
    ITEMDROP_LIFE_VESSEL,  ITEMDROP_ALUCART_SHIELD, ITEMDROP_HEART_VESSEL,
    ITEMDROP_LIFE_APPLE,   ITEMDROP_HAMMER,         ITEMDROP_POTION,
    ITEMDROP_ALUCART_MAIL, ITEMDROP_ALUCART_SWORD,  ITEMDROP_LIFE_VESSEL,
    ITEMDROP_HEART_VESSEL, ITEMDROP_LIBRARY_CARD,   ITEMDROP_ATTACK_POTION,
    ITEMDROP_HAMMER,       ITEMDROP_STR_POTION,
};
