// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
SET_END(0x80184e5d),
WAIT_FOR_FLAG(8),
PLAY_SOUND(0x92),
WAIT_FOR_FLAG(0),
SET_POS(60,148),
LOAD_PORTRAIT(0x80192908,0),
SET_PORTRAIT(1,128),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x35f),
WAIT_FOR_SOUND(),
SET_WAIT(8),
SET_FLAG(1),
SET_SPEED(8),
'A','h',',',' ',
SET_WAIT(16),
SET_SPEED(4),
'A','l','u','c','a','r','d','.',
LINE_BREAK(),
SET_WAIT(48),
SET_SPEED(2),
'W','h','a','t',' ','i','s',' ','y','o','u','r',
LINE_BREAK(),
SET_WAIT(4),
'b','u','s','i','n','e','s','s',' ','h','e','r','e','?',
SET_WAIT(48),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x80191b88,1),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x360),
WAIT_FOR_SOUND(),
SET_SPEED(2),
'I','\'','v','e',' ','c','o','m','e',' ','t','o',' ','p','u','t',
LINE_BREAK(),
SET_WAIT(4),
'a','n',' ','e','n','d',' ','t','o',' ','t','h','i','s','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(1,128),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x361),
WAIT_FOR_SOUND(),
SET_FLAG(2),
SET_SPEED(4),
'S','t','i','l','l',' ',
SET_SPEED(3),
'b','e','f','r','i','e','n','d','i','n','g',
LINE_BREAK(),
SET_WAIT(4),
'm','o','r','t','a','l','s','.','.','.',
LINE_BREAK(),
SET_WAIT(32),
SET_SPEED(2),
'I','\'','l','l',' ','n','o','t',' ','a','s','k',' ','y','o','u',' ','t','o',
LINE_BREAK(),
SET_WAIT(4),
SET_SPEED(3),
'r','e','t','u','r','n',' ','t','o',' ','o','u','r',' ','s','i','d','e','.',
LINE_BREAK(),
SET_WAIT(40),
SET_SPEED(2),
'B','u','t',' ','I',' ','d','e','m','a','n','d',' ','y','o','u',
LINE_BREAK(),
SET_WAIT(4),
'c','e','a','s','e',' ','y','o','u','r',' ','a','t','t','a','c','k','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,1),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x362),
WAIT_FOR_SOUND(),
SET_SPEED(5),
'I',' ','w','i','l','l',' ','n','o','t','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(1,128),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x363),
WAIT_FOR_SOUND(),
SET_FLAG(3),
SET_SPEED(4),
'Y','o','u',' ','s','h','a','l','l',' ','r','e','g','r','e','t',
LINE_BREAK(),
SET_WAIT(4),
't','h','o','s','e',' ','w','o','r','d','s','.','.',
LINE_BREAK(),
SET_WAIT(24),
SET_SPEED(3),
'W','e',' ','w','i','l','l',' ',
SET_SPEED(4),
'm','e','e','t',' ','a','g','a','i','n','.',
SET_WAIT(48),
SCRIPT_UNKNOWN_23(),
SET_FLAG(4),
NEXT_DIALOG(),
CLOSE_DIALOG(),
SCRIPT_UNKNOWN_11(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
