// SPDX-License-Identifier: AGPL-3.0-or-later
#include "rnz1.h"

u16 PrizeDrops[] = {
    ITEMDROP_MAGIC_MISSILE, ITEMDROP_KARMA_COIN,   ITEMDROP_STR_POTION,
    ITEMDROP_LUMINUS,       ITEMDROP_SMART_POTION, ITEMDROP_DRAGON_HELM,
    ITEMDROP_DIAMOND,       ITEMDROP_LIFE_APPLE,   ITEMDROP_SUNSTONE,
    ITEMDROP_LIFE_VESSEL,   ITEMDROP_HEART_VESSEL, ITEMDROP_MOON_ROD,

};
