// SPDX-License-Identifier: AGPL-3.0-or-later
#include "stage_data.h"

#define STAGE_02_LOOKUP_ROW {7, 4, 2, 3, 4, 1, 2, 3, 4, 6, 7, 0}

SaturnRoomPriorities g_Stage02RoomPriorities[32] = {
    STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW,
    STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW,
    STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW,
    STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW,
    STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW,
    STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW,
    STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW,
    STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW,
    STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW,
    STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW,
    STAGE_02_LOOKUP_ROW, STAGE_02_LOOKUP_ROW,
};

#undef STAGE_02_LOOKUP_ROW
