// SPDX-License-Identifier: AGPL-3.0-or-later
#include "../rnz0.h"

#include "../../pfn_entity_update.h"

extern LayoutEntity* D_8D2E330;
extern LayoutEntity* D_8D2E404;

extern Overlay OVL_EXPORT(Overlay);

s32 E_ID(BACKGROUND_BLOCK);
s32 E_ID(LOCK_CAMERA);
s32 E_ID(UNK_ID13);
s32 E_ID(EXPLOSION_VARIANTS);
s32 E_ID(GREY_PUFF);
s32 E_ID(PURPLE_BRICK_BG);
s32 E_ID(LEFT_SECRET_WALL);
s32 E_ID(BOTT_SECRET_FLOOR);
s32 E_ID(WALL_DEBRIS);
s32 E_ID(UNK_1A);
s32 E_ID(UNK_1B);
s32 E_ID(UNK_1C);
s32 E_ID(UNK_1D);
s32 E_ID(UNK_1E);
s32 E_ID(UNK_1F);
s32 E_ID(UNK_20);
s32 E_ID(UNK_21);
s32 E_ID(UNK_22);
s32 E_ID(UNK_23);
s32 E_ID(UNK_24);
s32 E_ID(UNK_25);
s32 E_ID(UNK_26);
s32 E_ID(GLOBE_TABLE);
s32 E_ID(LIFE_MAX_TANK);
s32 E_ID(BLUE_FLAME_TABLE);
s32 E_ID(RELIC_CONTAINER);
s32 E_ID(SEALED_DOOR);
s32 E_ID(RED_EYE_BUST);
s32 E_ID(CANNON_LEVER);
s32 E_ID(UNK_2E);
s32 E_ID(CANNON_SHOT);
s32 E_ID(UNK_30);
s32 E_ID(UNK_31);
s32 E_ID(UNK_32);
s32 E_ID(UNK_33);
s32 E_ID(UNK_34);
s32 E_ID(UNK_35);
s32 E_ID(UNK_36);
s32 E_ID(SALEM_WITCH);
s32 E_ID(SALEM_WITCH_GLOW);
s32 E_ID(SALEM_WITCH_CURSE);
s32 E_ID(SALEM_WITCH_TRIBOLT_LAUNCH);
s32 E_ID(SALEM_WITCH_TRIBOLT_PROJECTILE);

void InitEntityIds(void) {
    E_ID(BACKGROUND_BLOCK) = E_BACKGROUND_BLOCK;
    E_ID(LOCK_CAMERA) = E_LOCK_CAMERA;
    E_ID(UNK_ID13) = E_UNK_ID13;
    E_ID(EXPLOSION_VARIANTS) = E_EXPLOSION_VARIANTS;
    E_ID(GREY_PUFF) = E_GREY_PUFF;
    E_ID(PURPLE_BRICK_BG) = E_PURPLE_BRICK_BG;
    E_ID(LEFT_SECRET_WALL) = E_LEFT_SECRET_WALL;
    E_ID(BOTT_SECRET_FLOOR) = E_BOTT_SECRET_FLOOR;
    E_ID(WALL_DEBRIS) = E_WALL_DEBRIS;
    E_ID(UNK_1A) = E_UNK_1A;
    E_ID(UNK_1B) = E_UNK_1B;
    E_ID(UNK_1C) = E_UNK_1C;
    E_ID(UNK_1D) = E_UNK_1D;
    E_ID(UNK_1E) = E_UNK_1E;
    E_ID(UNK_1F) = E_UNK_1F;
    E_ID(UNK_20) = E_UNK_20;
    E_ID(UNK_21) = E_UNK_21;
    E_ID(UNK_22) = E_UNK_22;
    E_ID(UNK_23) = E_UNK_23;
    E_ID(UNK_24) = E_UNK_24;
    E_ID(UNK_25) = E_UNK_25;
    E_ID(UNK_26) = E_UNK_26;
    E_ID(GLOBE_TABLE) = E_GLOBE_TABLE;
    E_ID(LIFE_MAX_TANK) = E_LIFE_MAX_TANK;
    E_ID(BLUE_FLAME_TABLE) = E_BLUE_FLAME_TABLE;
    E_ID(RELIC_CONTAINER) = E_RELIC_CONTAINER;
    E_ID(SEALED_DOOR) = E_SEALED_DOOR;
    E_ID(RED_EYE_BUST) = E_RED_EYE_BUST;
    E_ID(CANNON_LEVER) = E_CANNON_LEVER;
    E_ID(UNK_2E) = E_UNK_2E;
    E_ID(CANNON_SHOT) = E_CANNON_SHOT;
    E_ID(UNK_30) = E_UNK_30;
    E_ID(UNK_31) = E_UNK_31;
    E_ID(UNK_32) = E_UNK_32;
    E_ID(UNK_33) = E_UNK_33;
    E_ID(UNK_34) = E_UNK_34;
    E_ID(UNK_35) = E_UNK_35;
    E_ID(UNK_36) = E_UNK_36;
    E_ID(SALEM_WITCH) = E_SALEM_WITCH;
    E_ID(SALEM_WITCH_GLOW) = E_SALEM_WITCH_GLOW;
    E_ID(SALEM_WITCH_CURSE) = E_SALEM_WITCH_CURSE;
    E_ID(SALEM_WITCH_TRIBOLT_LAUNCH) = E_SALEM_WITCH_TRIBOLT_LAUNCH;
    E_ID(SALEM_WITCH_TRIBOLT_PROJECTILE) = E_SALEM_WITCH_TRIBOLT_PROJECTILE;
}

void OVL_EXPORT(Load)(void) {
    InitEntityIds();
    PfnEntityUpdates = OVL_EXPORT(EntityUpdates);
    g_pStObjLayoutHorizontal = &D_8D2E330;
    g_pStObjLayoutVertical = &D_8D2E404;
    func_892A018();
    memcpy(&g_api.o, &OVL_EXPORT(Overlay), sizeof(Overlay));
}
