// SPDX-License-Identifier: AGPL-3.0-or-later
#include "bo3.h"

u16 PrizeDrops[] = {
    ITEMDROP_HEART_VESSEL, ITEMDROP_LIFE_VESSEL,    ITEMDROP_CRYSTAL_CLOAK,
    ITEMDROP_GLADIUS,      ITEMDROP_ANTIVENOM,      ITEMDROP_LIFE_VESSEL,
    ITEMDROP_LIFE_VESSEL,  ITEMDROP_HERALD_SHIELD,  ITEMDROP_ICE_MAIL,
    ITEMDROP_ZIRCON,       ITEMDROP_GOLD_RING,      ITEMDROP_BANDANNA,
    ITEMDROP_SHIITAKE,     ITEMDROP_CLAYMORE,       ITEMDROP_MEAL_TICKET,
    ITEMDROP_MEAL_TICKET,  ITEMDROP_MEAL_TICKET,    ITEMDROP_MEAL_TICKET,
    ITEMDROP_MOONSTONE,    ITEMDROP_SCIMITAR,       ITEMDROP_RESIST_ICE,
    ITEMDROP_POT_ROAST,    ITEMDROP_ONYX,           ITEMDROP_KNUCKLE_DUSTER,
    ITEMDROP_LIFE_VESSEL,  ITEMDROP_ELIXIR,         ITEMDROP_TOADSTOOL,
    ITEMDROP_SHIITAKE,     ITEMDROP_LIFE_VESSEL,    ITEMDROP_HEART_VESSEL,
    ITEMDROP_PENTAGRAM,    ITEMDROP_SECRET_BOOTS,   ITEMDROP_SHIITAKE,
    ITEMDROP_TOADSTOOL,    ITEMDROP_MONSTER_VIAL_1, ITEMDROP_SHIITAKE,
    ITEMDROP_NUNCHAKU,     ITEMDROP_SMALL_HEART,
};
