// SPDX-License-Identifier: AGPL-3.0-or-later
#include "rcat.h"

u16 OVL_EXPORT(PrizeDrops)[] = {
    ITEMDROP_MAGIC_MISSILE,
    // Buffalo star
    ITEMDROP_BUFFALO_STAR,
    ITEMDROP_RESIST_THUNDER,
    ITEMDROP_RESIST_FIRE,
    ITEMDROP_KARMA_COIN,
    ITEMDROP_KARMA_COIN,
    ITEMDROP_RED_BEAN_BUN,
    ITEMDROP_ELIXIR,
    // Library Card
    ITEMDROP_LIBRARY_CARD,
    ITEMDROP_LIFE_VESSEL,
    ITEMDROP_HEART_VESSEL,
    ITEMDROP_SHIELD_POTION,
    ITEMDROP_ATTACK_POTION,
    ITEMDROP_NECKLACE_OF_J,
    ITEMDROP_DIAMOND,
    ITEMDROP_HEART_VESSEL,
    ITEMDROP_LIFE_VESSEL,
    ITEMDROP_RUBY_CIRCLET,
    ITEMDROP_SPIKE_BREAKER,
    ITEMDROP_SPIKE_BREAKER,
    ITEMDROP_SPIKE_BREAKER,
    ITEMDROP_SPIKE_BREAKER,
    ITEMDROP_SPIKE_BREAKER,
    ITEMDROP_SPIKE_BREAKER,
    ITEMDROP_SPIKE_BREAKER,
    ITEMDROP_SPIKE_BREAKER,
    ITEMDROP_SPIKE_BREAKER,
    ITEMDROP_SPIKE_BREAKER,
    ITEMDROP_SPIKE_BREAKER,
    ITEMDROP_SPIKE_BREAKER,
    ITEMDROP_SPIKE_BREAKER,
    ITEMDROP_SPIKE_BREAKER,
};
