// SPDX-License-Identifier: AGPL-3.0-or-later
#include "rno1.h"

u16 PrizeDrops[] = {
    ITEMDROP_HEART_VESSEL, ITEMDROP_SHOTEL,       ITEMDROP_HAMMER,
    ITEMDROP_LIFE_VESSEL,  ITEMDROP_LUCK_POTION,  ITEMDROP_SHIELD_POTION,
    ITEMDROP_HIGH_POTION,  ITEMDROP_GARNET,       ITEMDROP_HEART_VESSEL,
    ITEMDROP_HEART_VESSEL, ITEMDROP_HEART_VESSEL, ITEMDROP_HEART_VESSEL,
    ITEMDROP_HEART_VESSEL, ITEMDROP_HEART_VESSEL, ITEMDROP_HEART_VESSEL,
    ITEMDROP_HEART_VESSEL,
};
