// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_player_hitbox_decoder.py
#include "sattypes.h"

FrameProperty g_RichterFrameProperties[] = {
    {0, 0, 0, 0},   {1, 3, 8, 20},   {3, 5, 9, 12},   {4, 12, 10, 12},
    {0, -1, 8, 16}, {0, 1, 10, 8},   {0, -5, 9, 5},   {-80, -88, 0, 0},
    {-5, 0, 8, 17}, {0, 0, 11, 16},  {-1, 17, 15, 7}, {-9, 10, 10, 5},
    {-3, 6, 10, 8}, {-8, 6, 9, 17},  {5, 6, 13, 9},   {-4, 3, 11, 20},
    {0, 8, 10, 8},  {-1, 10, 15, 7},
};
