// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_RichterSpritePackage8Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 70, 12, 0},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 70, 12, 1},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 70, 12, 2},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0000, 70, 12, 3},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0000, 70, 12, 4},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0100, 20, 48, 5},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0200, 48, 20, 6},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0000, 8, 4, 7},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 4, 8},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame10 = {
    {0x0100, 0x0000},
    {
        {0x0000, 8, 4, 9},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame11 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 4, 10},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame12 = {
    {0x0100, 0x0000},
    {
        {0x0000, 8, 4, 11},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame13 = {
    {0x0100, 0x0000},
    {
        {0x0000, 8, 4, 12},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame14 = {
    {0x0100, 0x0000},
    {
        {0x0000, 8, 4, 13},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame15 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 4, 14},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame16 = {
    {0x0100, 0x0000},
    {
        {0x0000, 8, 4, 15},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame17 = {
    {0x0100, 0x0000},
    {
        {0x0000, 8, 4, 16},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame18 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 4, 17},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame19 = {
    {0x0100, 0x0000},
    {
        {0x0300, 1, 2, 18},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame20 = {
    {0x0100, 0x0000},
    {
        {0x0310, 1, 2, 18},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame21 = {
    {0x0100, 0x0000},
    {
        {0x0300, 1, -2, 19},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame22 = {
    {0x0100, 0x0000},
    {
        {0x0300, 1, -2, 20},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame23 = {
    {0x0100, 0x0000},
    {
        {0x0300, 1, -2, 21},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame24 = {
    {0x0100, 0x0000},
    {
        {0x0300, 1, 3, 22},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame25 = {
    {0x0100, 0x0000},
    {
        {0x0300, 5, 5, 23},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame26 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 3, 24},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame27 = {
    {0x0100, 0x0000},
    {
        {0x0400, 3, 3, 24},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame28 = {
    {0x0100, 0x0000},
    {
        {0x0500, 3, 3, 24},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame29 = {
    {0x0100, 0x0000},
    {
        {0x0600, 3, 3, 24},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame30 = {
    {0x0100, 0x0000},
    {
        {0x0700, 3, 3, 24},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame31 = {
    {0x0100, 0x0000},
    {
        {0x0800, 3, 3, 24},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame32 = {
    {0x0100, 0x0000},
    {
        {0x0900, 3, 3, 24},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame33 = {
    {0x0100, 0x0000},
    {
        {0x0A00, 3, 3, 24},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame34 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 5, 25},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame35 = {
    {0x0100, 0x0000},
    {
        {0x0400, 4, 5, 25},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame36 = {
    {0x0100, 0x0000},
    {
        {0x0500, 4, 5, 25},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame37 = {
    {0x0100, 0x0000},
    {
        {0x0600, 4, 5, 25},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame38 = {
    {0x0100, 0x0000},
    {
        {0x0700, 4, 5, 25},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame39 = {
    {0x0100, 0x0000},
    {
        {0x0800, 4, 5, 25},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame40 = {
    {0x0100, 0x0000},
    {
        {0x0900, 4, 5, 25},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame41 = {
    {0x0100, 0x0000},
    {
        {0x0A00, 4, 5, 25},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame42 = {
    {0x0100, 0x0000},
    {
        {0x0500, 4, 4, 26},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame43 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 4, 26},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame44 = {
    {0x0100, 0x0000},
    {
        {0x0400, 4, 4, 26},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame45 = {
    {0x0100, 0x0000},
    {
        {0x0600, 4, 4, 26},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame46 = {
    {0x0100, 0x0000},
    {
        {0x0700, 4, 4, 26},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame47 = {
    {0x0100, 0x0000},
    {
        {0x0800, 4, 4, 26},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame48 = {
    {0x0100, 0x0000},
    {
        {0x0900, 4, 4, 26},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame49 = {
    {0x0100, 0x0000},
    {
        {0x0A00, 4, 4, 26},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame50 = {
    {0x0100, 0x0000},
    {
        {0x0B00, 4, 4, 26},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage8Frame51 = {
    {0x0100, 0x0000},
    {
        {0x0C00, 4, 4, 26},
    },
};

SaturnSpriteFrameHeader* g_RichterSpritePackage8Frames[52] = {
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame0,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame1,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame2,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame3,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame4,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame5,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame6,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame7,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame8,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame9,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame10,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame11,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame12,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame13,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame14,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame15,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame16,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame17,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame18,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame19,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame20,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame21,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame22,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame23,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame24,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame25,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame26,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame27,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame28,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame29,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame30,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame31,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame32,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame33,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame34,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame35,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame36,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame37,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame38,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame39,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame40,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame41,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame42,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame43,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame44,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame45,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame46,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame47,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame48,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame49,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame50,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage8Frame51,
};

struct {
    u16 countAndFlags;
    u16 colors[9][16];
    u16 padding[1];
} g_RichterSpritePackage8Palette = {
    0x4009,
    {
        {
            0x8009,
            0xFE9F,
            0xFCDA,
            0xCCF8,
            0x8013,
            0x801F,
            0xA99F,
            0xDEDF,
            0x8000,
            0xBC00,
            0x88CA,
            0x952D,
            0xAA16,
            0xCF7F,
            0xEFFF,
            0xFFFF,
        },
        {
            0x8180,
            0x9D0C,
            0xBC00,
            0xFFFF,
            0x98C6,
            0x8CD4,
            0x8000,
            0xEFFF,
            0xCE73,
            0xBE98,
            0x8CCA,
            0x9D50,
            0xA9F6,
            0xCF7F,
            0x9532,
            0xB18C,
        },
        {
            0x8009,
            0x81E0,
            0x8260,
            0xC270,
            0xFC00,
            0xFC00,
            0xFC00,
            0x801F,
            0xFC00,
            0x8000,
            0x98C6,
            0xB18C,
            0xCE73,
            0xE739,
            0xFFFF,
            0x83E0,
        },
        {
            0xB000,
            0x8000,
            0x8035,
            0xBDFF,
            0x819F,
            0x9A7F,
            0xCF7E,
            0xA946,
            0xC62C,
            0xE313,
            0xD860,
            0xFDE0,
            0xFF00,
            0x801A,
            0x801F,
            0xFFFF,
        },
        {
            0x8009,
            0xDE5F,
            0xD11D,
            0xB0D7,
            0x8013,
            0x801D,
            0xA15D,
            0xD6BF,
            0x8000,
            0xD000,
            0x88CA,
            0x952D,
            0xA9F6,
            0xCF7F,
            0xEFFF,
            0xFFFF,
        },
        {
            0x8009,
            0xBE1F,
            0xA55F,
            0x94B6,
            0x8013,
            0x801B,
            0x9D1B,
            0xCE9F,
            0x8000,
            0xE800,
            0x88CA,
            0x952D,
            0xA9F6,
            0xCF7F,
            0xEFFF,
            0xFFFF,
        },
        {
            0x90A5,
            0x8421,
            0xE800,
            0xCC00,
            0xDC00,
            0xEC00,
            0xFC00,
            0xFD60,
            0xFE6B,
            0x80B2,
            0x815F,
            0x827F,
            0xBBBF,
            0xBD4A,
            0xCA52,
            0xF7BD,
        },
        {
            0x90A5,
            0x8421,
            0xE800,
            0xCC00,
            0xDC00,
            0xEC00,
            0xFC00,
            0xBCD3,
            0xB979,
            0x88AE,
            0x815F,
            0x827F,
            0xBBBF,
            0xA529,
            0xCA52,
            0xF7BD,
        },
        {
            0x90A5,
            0xE419,
            0x823F,
            0x8339,
            0xCBE0,
            0xE720,
            0xE419,
            0x823F,
            0x8339,
            0xCBE0,
            0xE720,
            0xE419,
            0x823F,
            0x8339,
            0xCBE0,
            0xE720,
        },
    },
    {0x0000},
};

SaturnSpriteImage g_RichterSpritePackage8Images[28] = {
    {40, 12, 0x0000}, {40, 8, 0x0078},  {40, 4, 0x00C8},  {40, 8, 0x00F0},
    {40, 12, 0x0140}, {20, 48, 0x01B8}, {48, 20, 0x02A8}, {8, 4, 0x0398},
    {4, 4, 0x03A0},   {8, 4, 0x03A4},   {4, 4, 0x03AC},   {8, 4, 0x03B0},
    {8, 4, 0x03B8},   {8, 4, 0x03C0},   {4, 4, 0x03C8},   {8, 4, 0x03CC},
    {8, 4, 0x03D4},   {4, 4, 0x03DC},   {8, 12, 0x03E0},  {8, 12, 0x03F8},
    {8, 12, 0x0410},  {8, 12, 0x0428},  {8, 12, 0x0440},  {16, 12, 0x0458},
    {8, 4, 0x0488},   {12, 8, 0x0490},  {4, 4, 0x04A8},   {0, 0, 0x04AC},
};
