// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_RichterSpritePackage4Frame0 = {
    0x0000, 0x0000,
};

SaturnSpriteFrame1 g_RichterSpritePackage4Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 0, 0},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage4Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 0, 1},
    },
};

SaturnSpriteFrame6 g_RichterSpritePackage4Frame3 = {
    {0x0600, 0x0000},
    {
        {0x0000, 0, -48, 2},
        {0x0000, 0, -32, 3},
        {0x0000, 0, -16, 4},
        {0x0000, 0, 0, 5},
        {0x0000, 0, 16, 6},
        {0x0000, 0, 32, 7},
    },
};

SaturnSpriteFrame6 g_RichterSpritePackage4Frame4 = {
    {0x0600, 0x0000},
    {
        {0x0000, 0, -48, 8},
        {0x0000, 0, -32, 9},
        {0x0000, 0, -16, 10},
        {0x0000, 0, 0, 11},
        {0x0000, 0, 16, 12},
        {0x0000, 0, 32, 13},
    },
};

SaturnSpriteFrame2 g_RichterSpritePackage4Frame5 = {
    {0x0200, 0x0000},
    {
        {0x0100, -41, -4, 14},
        {0x0100, 43, -4, 15},
    },
};

SaturnSpriteFrame2 g_RichterSpritePackage4Frame6 = {
    {0x0200, 0x0000},
    {
        {0x0100, -40, -2, 16},
        {0x0100, 40, -2, 17},
    },
};

SaturnSpriteFrameHeader* g_RichterSpritePackage4Frames[7] = {
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage4Frame0,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage4Frame1,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage4Frame2,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage4Frame3,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage4Frame4,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage4Frame5,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage4Frame6,
};

struct {
    u16 countAndFlags;
    u16 colors[2][16];
} g_RichterSpritePackage4Palette = {
    0x0002,
    {
        {
            0x8000, 0x8000, 0x8000, 0x8000, 0x8000, 0x8000, 0x8000, 0x8000,
            0xCD2B, 0xD58C, 0xDE0E, 0xE670, 0xEEF1, 0xF753, 0xFFD5, 0xFFF9,
        },
        {
            0x8000, 0x8000, 0x8000, 0x8000, 0x8000, 0x8000, 0x8000, 0x8000,
            0xE900, 0xED40, 0xF180, 0xF604, 0xFA85, 0xFF4B, 0xFFD5, 0xFFFF,
        },
    },
};

SaturnSpriteImage g_RichterSpritePackage4Images[19] = {
    {64, 8, 0x0000},
    {64, 8, 0x0080},
    {8, 8, 0x0100},
    {8, 8, 0x0110},
    {8, 8, 0x0120},
    {8, 8, 0x0130},
    {8, 8, 0x0140},
    {8, 8, 0x0150},
    {8, 8, 0x0160},
    {8, 8, 0x0170},
    {8, 8, 0x0180},
    {8, 8, 0x0190},
    {8, 8, 0x01A0},
    {8, 8, 0x01B0},
    {44, 4, 0x01C0},
    {40, 4, 0x01EC},
    {40, 4, 0x0214},
    {40, 4, 0x023C},
    {0, 0, 0x0264},
};

u16 g_RichterSpritePackage4Padding = 0;
