// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_RichterSpritePackage7Frame0 = {
    0x0000, 0x0000,
};

SaturnSpriteFrame1 g_RichterSpritePackage7Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 1, 0},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage7Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 1, 1},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage7Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 1, 2},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage7Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 1, 3},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage7Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 1, 4},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage7Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0030, -1, 1, 3},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage7Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0030, -1, 1, 2},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage7Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 1, 1},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage7Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 1, 5},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage7Frame10 = {
    {0x0100, 0x0000},
    {
        {0x0100, 3, 1, 5},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage7Frame11 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, 1, 6},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage7Frame12 = {
    {0x0100, 0x0000},
    {
        {0x0100, 3, 1, 6},
    },
};

SaturnSpriteFrameHeader* g_RichterSpritePackage7Frames[13] = {
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage7Frame0,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage7Frame1,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage7Frame2,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage7Frame3,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage7Frame4,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage7Frame5,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage7Frame6,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage7Frame7,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage7Frame8,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage7Frame9,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage7Frame10,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage7Frame11,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage7Frame12,
};

struct {
    u16 countAndFlags;
    u16 colors[2][16];
    u16 padding[1];
} g_RichterSpritePackage7Palette = {
    0x0002,
    {
        {
            0x8220, 0xFC21, 0x8421, 0xFC21, 0xCE73, 0xF39C, 0x87FF, 0x87E1,
            0x8220, 0x8421, 0xD421, 0xFC21, 0xFD42, 0xFE48, 0xF6D1, 0xFFBD,
        },
        {
            0x81E0, 0x87E1, 0x8421, 0x87E1, 0x86BC, 0x879F, 0x87E1, 0x87E1,
            0x8220, 0x8421, 0xA821, 0xC821, 0xD021, 0xD922, 0xE182, 0xE608,
        },
    },
    {0x0000},
};

SaturnSpriteImage g_RichterSpritePackage7Images[8] = {
    {12, 10, 0x0000},
    {12, 10, 0x0020},
    {12, 10, 0x0040},
    {12, 10, 0x0060},
    {12, 10, 0x0080},
    {12, 10, 0x00A0},
    {12, 10, 0x00C0},
    {0, 0, 0x00E0},
};
