// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_RichterSpritePackage9Frame0 = {
    0x0000, 0x0000,
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, -1, -2, 0},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -1, 1},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, -1, 2},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -2, 3},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, -3, 4},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, -1, 5},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, -1, 6},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, -1, 7},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, -1, 8},
    },
};

SaturnSpriteFrame2 g_RichterSpritePackage9Frame10 = {
    {0x0200, 0x0000},
    {
        {0x0000, 13, -22, 9},
        {0x0000, 2, -1, 10},
    },
};

SaturnSpriteFrame2 g_RichterSpritePackage9Frame11 = {
    {0x0200, 0x0000},
    {
        {0x0000, 14, -19, 11},
        {0x0000, 2, -1, 10},
    },
};

SaturnSpriteFrame2 g_RichterSpritePackage9Frame12 = {
    {0x0200, 0x0000},
    {
        {0x0000, 10, -19, 12},
        {0x0000, 2, -1, 10},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame13 = {
    {0x0100, 0x0000},
    {
        {0x0000, 2, -1, 10},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame14 = {
    {0x0100, 0x0000},
    {
        {0x0000, -1, -1, 13},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame15 = {
    {0x0100, 0x0000},
    {
        {0x0000, 3, -1, 14},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame16 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 0, 15},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame17 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, -1, 16},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame18 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 2, 17},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame19 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, 3, 18},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame20 = {
    {0x0100, 0x0000},
    {
        {0x0000, 6, -1, 19},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame21 = {
    {0x0100, 0x0000},
    {
        {0x0000, 8, 4, 20},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame22 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 6, 21},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame23 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 6, 22},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame24 = {
    {0x0100, 0x0000},
    {
        {0x0000, 4, 6, 23},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame25 = {
    {0x0100, 0x0000},
    {
        {0x0100, 2, 2, 24},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame26 = {
    {0x0100, 0x0000},
    {
        {0x0200, 2, 2, 25},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame27 = {
    {0x0100, 0x0000},
    {
        {0x0300, 2, 0, 26},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage9Frame28 = {
    {0x0100, 0x0000},
    {
        {0x0400, 2, 1, 27},
    },
};

SaturnSpriteFrameHeader* g_RichterSpritePackage9Frames[29] = {
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame0,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame1,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame2,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame3,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame4,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame5,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame6,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame7,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame8,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame9,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame10,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame11,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame12,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame13,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame14,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame15,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame16,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame17,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame18,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame19,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame20,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame21,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame22,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame23,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame24,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame25,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame26,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame27,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage9Frame28,
};

struct {
    u16 countAndFlags;
    u16 colors[9][16];
    u16 padding[1];
} g_RichterSpritePackage9Palette = {
    0x0009,
    {
        {
            0xA083, 0x8447, 0xA108, 0xB9AC, 0xDA92, 0xFB78, 0xF8A8, 0x88AF,
            0x99FF, 0xBEDF, 0xCF1F, 0xA0D6, 0xA93C, 0xC1DF, 0x9574, 0x8E5F,
        },
        {
            0xCD40, 0x8060, 0x98A0, 0x9540, 0x8DE8, 0xA24B, 0xA6CD, 0xB753,
            0xA08E, 0xA117, 0x95DA, 0xB2DD, 0xCC2D, 0xF112, 0xFE10, 0xFED6,
        },
        {
            0xA834, 0x8423, 0xA8CA, 0xA170, 0xBEBB, 0xE37E, 0x886A, 0xDDCF,
            0xD655, 0x83E0, 0x83E0, 0x83E0, 0x83E0, 0x83E0, 0x83E0, 0x83E0,
        },
        {
            0xBD00, 0x8000, 0x83E0, 0x83E0, 0x83C0, 0x83C0, 0x8009, 0x800F,
            0x9456, 0xA8DF, 0xBDBF, 0x83E0, 0x81B2, 0x823D, 0x835F, 0x83E0,
        },
        {
            0x8011, 0x8000, 0x80F3, 0x9995, 0x9A1B, 0xC2DE, 0xDF7F, 0xA946,
            0xC62C, 0xE313, 0xB460, 0xD880, 0xED20, 0xFDE0, 0xFF00, 0x88A9,
        },
        {
            0x0000, 0x819D, 0x921D, 0x969E, 0xAF5F, 0xD7DF, 0x819D, 0x921D,
            0x969E, 0xAF5F, 0xD7DF, 0x819D, 0x921D, 0x969E, 0xAF5F, 0x801F,
        },
        {
            0x0000, 0xA108, 0xAD6B, 0xBDEF, 0xD294, 0xE739, 0xA108, 0xAD6B,
            0xBDEF, 0xD294, 0xE739, 0xA108, 0xAD6B, 0xBDEF, 0xD294, 0xE739,
        },
        {
            0x0000, 0xDC80, 0xE540, 0xEE00, 0xF6C0, 0xFF80, 0xDC80, 0xE540,
            0xEE00, 0xF6C0, 0xFF80, 0xDC80, 0xE540, 0xEE00, 0xF6C0, 0xFF80,
        },
        {
            0x0000, 0x8340, 0x8260, 0x82E0, 0x8360, 0x83E0, 0x8340, 0x8260,
            0x82E0, 0x8360, 0x83E0, 0x8340, 0x8260, 0x82E0, 0x8360, 0x83E0,
        },
    },
    {0x0000},
};

SaturnSpriteImage g_RichterSpritePackage9Images[29] = {
    {12, 17, 0x0000},
    {12, 17, 0x0034},
    {16, 18, 0x0068},
    {16, 18, 0x00B0},
    {16, 16, 0x00F8},
    {12, 17, 0x0138},
    {12, 18, 0x016C},
    {12, 18, 0x01A4},
    {12, 18, 0x01DC},
    {12, 9, 0x0214},
    {12, 17, 0x0230},
    {8, 5, 0x0264},
    {4, 3, 0x0270},
    {12, 17, 0x0274},
    {12, 17, 0x02A8},
    {12, 16, 0x02DC},
    {12, 17, 0x030C},
    {12, 15, 0x0340},
    {12, 13, 0x0370},
    {16, 17, 0x0398},
    {16, 13, 0x03DC},
    {12, 11, 0x0410},
    {12, 11, 0x0434},
    {12, 10, 0x0458},
    {20, 18, 0x0478},
    {16, 7, 0x04D4},
    {12, 9, 0x04F0},
    {12, 7, 0x050C},
    {0, 0, 0x0524},
};
