// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

SaturnSpriteFrameHeader g_RichterSpritePackage6Frame0 = {
    0x0000, 0x0000,
};

SaturnSpriteFrame1 g_RichterSpritePackage6Frame1 = {
    {0x0100, 0x0000},
    {
        {0x0000, 8, 8, 0},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage6Frame2 = {
    {0x0100, 0x0000},
    {
        {0x0100, 8, 8, 1},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage6Frame3 = {
    {0x0100, 0x0000},
    {
        {0x0100, 8, 8, 2},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage6Frame4 = {
    {0x0100, 0x0000},
    {
        {0x0100, 8, 8, 3},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage6Frame5 = {
    {0x0100, 0x0000},
    {
        {0x0100, 8, 8, 4},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage6Frame6 = {
    {0x0100, 0x0000},
    {
        {0x0200, 8, 8, 5},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage6Frame7 = {
    {0x0100, 0x0000},
    {
        {0x0200, 8, 36, 6},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage6Frame8 = {
    {0x0100, 0x0000},
    {
        {0x0200, 8, 12, 7},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage6Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0200, 8, 8, 8},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage6Frame10 = {
    {0x0100, 0x0000},
    {
        {0x0200, 4, 4, 9},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage6Frame11 = {
    {0x0100, 0x0000},
    {
        {0x0200, 12, 4, 10},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage6Frame12 = {
    {0x0100, 0x0000},
    {
        {0x0200, 8, 8, 11},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage6Frame13 = {
    {0x0100, 0x0000},
    {
        {0x0200, 12, 8, 12},
    },
};

SaturnSpriteFrame1 g_RichterSpritePackage6Frame14 = {
    {0x0100, 0x0000},
    {
        {0x0300, 8, 8, 13},
    },
};

SaturnSpriteFrameHeader* g_RichterSpritePackage6Frames[15] = {
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage6Frame0,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage6Frame1,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage6Frame2,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage6Frame3,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage6Frame4,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage6Frame5,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage6Frame6,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage6Frame7,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage6Frame8,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage6Frame9,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage6Frame10,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage6Frame11,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage6Frame12,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage6Frame13,
    (SaturnSpriteFrameHeader*)&g_RichterSpritePackage6Frame14,
};

struct {
    u16 countAndFlags;
    u16 colors[4][16];
    u16 padding[1];
} g_RichterSpritePackage6Palette = {
    0x0004,
    {
        {
            0xA420, 0xA0A8, 0x8421, 0xA54E, 0xBA36, 0xD2FB, 0xE39F, 0x992D,
            0x8581, 0x9046, 0x948B, 0x9530, 0xA5B6, 0xBA59, 0xD75F, 0x8661,
        },
        {
            0x98E6, 0x8423, 0xA0A8, 0xAD70, 0xA94F, 0xA52E, 0xA10D, 0x8066,
            0x80AC, 0x80CF, 0x9134, 0x8157, 0x921E, 0xB29F, 0xCF9F, 0xB00B,
        },
        {
            0xA420, 0xA0A8, 0x8421, 0xA54E, 0xBA36, 0xD2FB, 0xE75B, 0x9CEA,
            0x9046, 0x8C8A, 0x94EE, 0x9930, 0xA5D6, 0xB658, 0xB5AD, 0xCE73,
        },
        {
            0x8A63, 0xEFFF, 0xDF7B, 0xCEF7, 0xBE73, 0xA9EF, 0x954A, 0x8CE8,
            0x83E0, 0x83E0, 0x83E0, 0x83E0, 0x83E0, 0x83E0, 0x83E0, 0x83E0,
        },
    },
    {0x0000},
};

SaturnSpriteImage g_RichterSpritePackage6Images[15] = {
    {8, 8, 0x0000},
    {8, 8, 0x0010},
    {8, 8, 0x0020},
    {8, 8, 0x0030},
    {8, 8, 0x0040},
    {8, 8, 0x0050},
    {8, 36, 0x0060},
    {8, 12, 0x00A8},
    {8, 8, 0x00C0},
    {4, 4, 0x00D0},
    {12, 4, 0x00D4},
    {8, 8, 0x00E0},
    {12, 8, 0x00F0},
    {8, 8, 0x0108},
    {0, 0, 0x0118},
};
