// SPDX-License-Identifier: AGPL-3.0-or-later
#include "cat.h"

u16 OVL_EXPORT(PrizeDrops)[] = {
    ITEMDROP_CAT_EYE_CIRCLET, ITEMDROP_ICEBRAND,       ITEMDROP_WALK_ARMOR,
    ITEMDROP_MORMEGIL,        ITEMDROP_LIBRARY_CARD,   ITEMDROP_LIFE_VESSEL,
    ITEMDROP_HEART_VESSEL,    ITEMDROP_BALLROOM_MASK,  ITEMDROP_BLOODSTONE,
    ITEMDROP_LIFE_VESSEL,     ITEMDROP_HEART_VESSEL,   ITEMDROP_CROSS_SHURIKEN,
    ITEMDROP_CROSS_SHURIKEN,  ITEMDROP_KARMA_COIN,     ITEMDROP_KARMA_COIN,
    ITEMDROP_PORK_BUN,        ITEMDROP_SPIKE_BREAKER,  ITEMDROP_MONSTER_VIAL_3,
    ITEMDROP_MONSTER_VIAL_3,  ITEMDROP_MONSTER_VIAL_3, ITEMDROP_MONSTER_VIAL_3,
};
