// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
0x1,0x17,
'C','A','S','T','L','E','V','A','N','I','A',
0x1,0x8,
'S','Y','M','P','H','O','N','Y',' ','O','F',' ','T','H','E',' ','N','I','G','H','T',
SET_WAIT(0),
SET_WAIT(0),
SET_WAIT(30),
'-','C','a','s','t','-',
SET_WAIT(0),
0x1,0xF,
'R','Y','O','U','T','A','R','O','H',' ','O','K','I','A','Y','U',
SET_SPEED(17),
'K','I','Y','O','Y','U','K','I',' ','Y','A','N','A','D','A',
SET_SPEED(18),
'C','H','I','S','A',' ','Y','O','K','O','Y','A','M','A',
SET_SPEED(18),
'N','O','R','I','O',' ','W','A','K','A','M','O','T','O',
SET_SPEED(23),
'R','I','K','A',' ','F','U','K','A','M','I',
SET_SPEED(18),
'M','A','S','A','H','A','R','U',' ','S','A','T','O','H',
SET_SPEED(19),
'H','E','K','I','R','U',' ','S','H','I','I','N','A',
SET_SPEED(19),
'J','Y','O','U','J','I',' ','Y','A','N','A','M','I',
0x1,0x0,
SET_WAIT(28),
'-','S','t','a','f','f','-',
SET_WAIT(0),
0x1,0x9,
'-','P','r','o','d','u','c','e','r',' ','&',' ','D','i','r','e','c','t','o','r','-',
SET_WAIT(19),
'T','O','R','U',' ','H','A','G','I','H','A','R','A',
0x1,0x0,
SET_SPEED(11),
'-','A','s','s','i','s','t','a','n','t',' ','D','i','r','e','c','t','o','r','-',
SET_WAIT(25),
'K','O','U','J','I',' ','I','G','A',
0x1,0x0,
SET_SPEED(25),
'-','P','r','o','g','r','a','m','-',
SET_WAIT(19),
'T','O','R','U',' ','H','A','G','I','H','A','R','A',
SET_SPEED(24),
'G','A','G','E','N','S','A','I','.','F',
SET_SPEED(25),
'K','O','U','J','I',' ','I','G','A',
SET_SPEED(16),
'K','O','U','S','U','K','E',' ','I','W','A','K','U','R','A',
SET_SPEED(15),
'H','I','R','O','S','H','I',' ','Y','O','G','I','A','S','H','I',
SET_SPEED(0),
SET_SPEED(27),
'-','D','e','s','i','g','n','-',
SET_WAIT(22),
'R','E','I','K','A',' ','B','A','N','D','O',
SET_SPEED(12),
'T','O','S','H','I','H','A','R','U',' ','F','U','R','U','K','A','W','A',
SET_SPEED(12),
'K','I','M','I','H','I','R','O',' ','M','O','R','I','S','H','I','T','A',
SET_SPEED(15),
'H','I','R','O','T','O',' ','Y','A','M','A','G','U','C','H','I',
SET_SPEED(16),
'N','O','B','U','Y','A',' ','N','A','K','A','Z','A','T','O',
SET_SPEED(9),
'S','H','I','N','I','C','H','I','R','O',' ','S','H','I','M','A','M','U','R','A',
SET_SPEED(18),
'N','O','R','I','Y','O','S','H','I',' ','S','A','T','O',
SET_SPEED(0),
SET_SPEED(33),
'-','C','G','-',
SET_WAIT(12),
'K','E','N','I','C','H','I','R','O',' ','I','M','A','I','Z','U','M','I',
SET_SPEED(0),
SET_SPEED(24),
'-','S','c','e','n','a','r','i','o','-',
SET_WAIT(25),
'K','O','U','J','I',' ','I','G','A',
SET_SPEED(12),
'T','O','S','H','I','H','A','R','U',' ','F','U','R','U','K','A','W','A',
SET_SPEED(0),
SET_SPEED(19),
'-','S','o','u','n','d',' ','S','t','a','f','f','-',
SET_WAIT(18),
'M','I','C','H','I','R','U',' ','Y','A','M','A','N','E',
0x1,0x9,
'(','M','U','S','I','C','/','S','O','U','N','D',' ','E','F','F','E','C','T',')',
SET_SPEED(28),
'O','.','K','A','S','A','I',
0x1,0x6,
'(','P','R','O','G','R','A','M','/','S','O','U','N','D',' ','E','F','F','E','C','T',')',
SET_SPEED(13),
'I','M','O','H','O','R','E',' ','I','M','A','I','(','M','I','X',')',
0x1,0x0,
SET_SPEED(22),
'-','M','u','s','i','c','i','a','n','s','-',
SET_WAIT(18),
'T','A','K','A','Y','U','K','I',' ','F','U','J','I','I',
0x1,0xD,
'(','E','L','E','C','T','R','I','C',' ','G','U','I','T','A','R',')',
SET_SPEED(11),
'N','I','S','H','I','M','U','R','A',' ','O','H','.','Y','A','.','Z','I','.',
0x1,0xD,
'(','E','L','E','C','T','R','I','C',' ','G','U','I','T','A','R',')',
SET_SPEED(9),
'K','A','H','O','R','I',' ','Y','A','M','A','N','E','(','V','O','C','A','L',')',
SET_SPEED(0),
SET_SPEED(15),
'-','P','r','o','d','u','c','t',' ','D','e','s','i','g','n','-',
SET_WAIT(18),
'S','H','O','G','O',' ','K','U','M','A','S','A','K','A',
SET_SPEED(19),
'Y','U','M','I','K','O',' ','N','O','Z','A','W','A',
0x1,0x0,
SET_WAIT(0),
0x1,0xA,
'-','C','h','a','r','a','c','t','e','r',' ','D','e','s','i','g','n',' ',' ',
0x1,0xA,
' ',' ',' ',' ',' ','&',' ','I','l','l','u','s','t','r','a','t','i','o','n','-',
SET_WAIT(21),
'A','Y','A','M','I',' ','K','O','J','I','M','A',
0x1,0x0,
SET_WAIT(0),
0x1,0xF,
'-','S','p','e','c','i','a','l',' ','T','h','a','n','k','s','-',
SET_WAIT(16),
'S','I','G','E','R','U',' ','F','U','K','U','T','A','K','E',
SET_SPEED(15),
'T','A','K','A','S','H','I',' ','T','A','T','E','I','S','H','I',
SET_SPEED(19),
'Y','U','T','A','K','A',' ','H','A','R','U','K','I',
SET_SPEED(18),
'H','A','R','U','H','I','K','O',' ','I','N','A','B','A',
SET_SPEED(15),
'J','U','N','I','C','H','I',' ','M','U','R','A','K','A','M','I',
SET_SPEED(22),
'T','A','R','O',' ','M','I','Y','A','K','E',
SET_SPEED(27),
'M','A','S','A',' ','H','R','D',
SET_SPEED(19),
'A','K','I','R','A',' ','Y','A','M','A','O','K','A',
SET_SPEED(15),
'S','H','O','I','C','H','I','R','O',' ','H','I','R','A','T','A',
SET_SPEED(24),
'T','A','K','U',' ','U','R','A','B','E',
SET_SPEED(19),
'H','I','R','O','E',' ','N','O','G','U','C','H','I',
SET_SPEED(31),
'Y','.','M','A','T',
SET_SPEED(18),
'H','I','D','E','A','K','I',' ','S','U','G','A','Y','A',
SET_SPEED(21),
'H','I','D','E','K','I',' ','K','A','S','A','I',
SET_SPEED(27),
'K','.','F','U','K','A','M','I',
SET_SPEED(25),
'R','M','C',' ','S','T','A','F','F',
SET_SPEED(0),
SET_SPEED(19),
'-','C','o','o','p','e','r','a','t','i','o','n','-',
SET_WAIT(16),
'A','O','N','I',' ','P','R','O','D','U','C','T','I','O','N',
SET_SPEED(22),
'A','R','T','S',' ','V','I','S','I','O','N',
SET_SPEED(26),
0x82,0x57,0x82,0x50,'P','R','O','D','U','C','E',
SET_SPEED(22),
'S','I','G','M','A',' ','S','E','V','E','N',
SET_SPEED(0),
SET_SPEED(27),
'-','S','t','u','d','i','o','-',
SET_WAIT(18),
'C','E','N','T','R','A','L',' ','S','T','U','D','I','O',
SET_SPEED(27),
'S','T','U','D','I','O',0x82,0x51,0x82,0x53,
SET_SPEED(0),
SET_WAIT(0),
SET_WAIT(9),
'-','E','x','e','c','u','t','i','v','e',' ','P','r','o','d','u','c','e','r','-',
SET_WAIT(19),
'K','A','Z','U','M','I',' ','K','I','T','A','U','E',
0x1,0x0,
SET_WAIT(0),
SET_WAIT(0),
0x1,0x0,
0x1,0x3,
0x9F,0x54,0x82,0x50,0x82,0x58,0x82,0x58,0x82,0x56,' ','K','O','N','A','M','I',
0x1,0x13,
'A','L','L',' ','R','I','G','H','T','S',' ','R','E','S','E','R','V','E','D','.',
SET_SPEED(11),
'D','E','V','E','L','O','P','M','E','N','T',' ','B','Y',' ','K','C','E','T','.',
SET_WAIT(0),
SET_WAIT(0),
SET_WAIT(0),
SET_SPEED(0),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
