REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
#include "sfx.h"
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            g_Tilemap.fg[0x1C4] = 0;
REDACTED
REDACTED
REDACTED
        g_Tilemap.fg[0x1C4] = 0x32F;
REDACTED
REDACTED
REDACTED
REDACTED
            g_Tilemap.fg[0x1C4] = 0;
REDACTED
            g_api.PlaySfx(SFX_WALL_DEBRIS_B);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            g_api.PlaySfx(SFX_ANIME_SWORD_B);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            self->drawFlags = FLAG_DRAW_ROTZ | FLAG_DRAW_UNK8;
REDACTED
            self->velocityX = 0;
            self->velocityY = 0;
REDACTED
REDACTED
REDACTED
REDACTED
            self->rotZ += 0x40;
            if (UnkCollisionFunc3(D_801808F8) & 1) {
REDACTED
REDACTED
REDACTED
            self->velocityY -= FIX(0.125);
REDACTED
REDACTED
REDACTED
            g_api.PlaySfx(SFX_EXPLODE_FAST_A);
REDACTED
REDACTED
                CreateEntityFromEntity(E_EXPLOSION, self, newEntity);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
    case 0:
        InitializeEntity(D_80180628);
        entity->animCurFrame = 3;
        entity->zPriority += 2;
        if (g_isSecretStairsButtonPressed) {
            entity->animCurFrame = 0;
REDACTED
        }
        break;
REDACTED
REDACTED
REDACTED
            g_api.PlaySfx(SFX_WALL_DEBRIS_B);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        entity->posY.val -= FIX(0.25);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
                        g_Tilemap.fg[*tilePos] = 0;
REDACTED
                        g_Tilemap.fg[*tilePos] = *(tilePos + 1);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            self->posX.i.hi = temp_s0 - g_Tilemap.scrollX.i.hi;
            self->posY.i.hi = temp_s1 - g_Tilemap.scrollY.i.hi;
REDACTED
REDACTED
REDACTED
        self->rotZ = -0x200;
        self->drawFlags |= 4;
REDACTED
REDACTED
REDACTED
REDACTED
            g_api.PlaySfx(SFX_DOOR_OPEN);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        self->rotZ += 0x10;
        if (self->rotZ == 0) {
            self->drawFlags = 0;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            g_api.PlaySfx(SFX_DOOR_OPEN);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            posX = g_Tilemap.scrollX.i.hi + self->posX.i.hi;
            posY = g_Tilemap.scrollY.i.hi + self->posY.i.hi;
REDACTED
            self->velocityX = rcos(angle) * 12;
            self->velocityY = rsin(angle) * 12;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            posX = g_Tilemap.scrollX.i.hi + self->posX.i.hi;
REDACTED
                g_api.PlaySfx(SFX_DOOR_CLOSE_A);
                self->posX.i.hi = temp_s0 - g_Tilemap.scrollX.i.hi;
                self->posY.i.hi = temp_s1 - g_Tilemap.scrollY.i.hi;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
                        g_Tilemap.fg[*tilePos] = *(tilePos + 1);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
