// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
SET_END(0x80182c4a),
WAIT_FOR_FLAG(0),
PLAY_SOUND(0x81),
SET_POS(60,36),
LOAD_PORTRAIT(0x8018f130,0),
SET_PORTRAIT(0,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x358),
WAIT_FOR_SOUND(),
SET_SPEED(4),
'D','i','e',' ','m','o','n','s','t','e','r','.',
LINE_BREAK(),
SET_WAIT(28),
SET_SPEED(2),
'Y','o','u',' ','d','o','n','\'','t',' ','b','e','l','o','n','g',
LINE_BREAK(),
SET_WAIT(8),
'i','n',' ','t','h','i','s',' ','w','o','r','l','d','!',
SET_WAIT(48),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x8018feb0,1),
SET_PORTRAIT(1,129),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x359),
WAIT_FOR_SOUND(),
SET_SPEED(3),
'I','t',' ','w','a','s',' ','n','o','t',' ','b','y',' ','m','y',
LINE_BREAK(),
SET_WAIT(4),
'h','a','n','d',' ','t','h','a','t',' ','I',' ','a','m',' ','o','n','c','e',
LINE_BREAK(),
SET_WAIT(4),
'a','g','a','i','n',' ','g','i','v','e','n',' ','f','l','e','s','h','.',
LINE_BREAK(),
SET_WAIT(48),
'I',' ','w','a','s',' ','c','a','l','l','e','d',' ','h','e','r','e',
LINE_BREAK(),
SET_WAIT(4),
'b','y',' ',
SET_WAIT(16),
SET_SPEED(5),
'h','u','m','a','n','s',' ',
SET_WAIT(16),
SET_SPEED(3),
'w','h','o',
LINE_BREAK(),
SET_WAIT(4),
'w','i','s','h',' ','t','o',' ','p','a','y',' ','m','e',
LINE_BREAK(),
SET_WAIT(24),
't','r','i','b','u','t','e','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x35a),
WAIT_FOR_SOUND(),
SET_FLAG(10),
SET_SPEED(4),
'T','r','i','b','u','t','e','!','?','!',
LINE_BREAK(),
SET_WAIT(32),
SET_FLAG(11),
SET_SPEED(4),
'Y','o','u',' ','s','t','e','a','l',' ','m','e','n','\'','s',
LINE_BREAK(),
SET_WAIT(4),
's','o','u','l','s',' ',
SET_WAIT(12),
SET_FLAG(12),
SET_SPEED(2),
'a','n','d',' ','m','a','k','e',' ','t','h','e','m',
LINE_BREAK(),
SET_WAIT(4),
SET_FLAG(13),
'y','o','u','r',' ','s','l','a','v','e','s','!',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(1,129),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x35b),
WAIT_FOR_SOUND(),
SET_SPEED(2),
'P','e','r','h','a','p','s',' ','t','h','e',' ','s','a','m','e',
LINE_BREAK(),
SET_WAIT(4),
'c','o','u','l','d',' ','b','e',' ','s','a','i','d',
LINE_BREAK(),
SET_WAIT(4),
'o','f',
SET_SPEED(3),
' ','a','l','l',' ','r','e','l','i','g','i','o','n','s','.','.','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x35c),
WAIT_FOR_SOUND(),
SET_SPEED(3),
SET_FLAG(14),
'Y','o','u','r',' ','w','o','r','d','s',' ','a','r','e',' ','a','s',
LINE_BREAK(),
SET_WAIT(4),
SET_FLAG(15),
'e','m','p','t','y',' ','a','s',' ','y','o','u','r',' ','s','o','u','l','!',
LINE_BREAK(),
SET_WAIT(40),
SET_FLAG(16),
'M','a','n','k','i','n','d',' ','i','l','l',' ','n','e','e','d','s',' ','a',
LINE_BREAK(),
SET_WAIT(4),
SET_FLAG(4),
SET_FLAG(17),
SET_SPEED(4),
's','a','v','i','o','r',' ','s','u','c','h',' ','a','s',' ','y','o','u','!',
SET_WAIT(48),
SET_FLAG(18),
NEXT_DIALOG(),
SET_PORTRAIT(1,129),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x35d),
WAIT_FOR_SOUND(),
SET_SPEED(3),
'W','h','a','t',' ','i','s',' ','a',' ','m','a','n','?',
LINE_BREAK(),
SET_WAIT(16),
SET_FLAG(5),
SET_WAIT(32),
SET_SPEED(3),
'A',' ','m','i','s','e','r','a','b','l','e',' ','l','i','t','t','l','e',
LINE_BREAK(),
SET_WAIT(4),
'p','i','l','e',' ','o','f',' ','s','e','c','r','e','t','s','.',
LINE_BREAK(),
SET_WAIT(40),
SET_SPEED(2),
WAIT_FOR_FLAG(8),
'B','u','t',' ','e','n','o','u','g','h',' ',
SET_FLAG(6),
't','a','l','k','.','.','.',
LINE_BREAK(),
SET_WAIT(24),
'H','a','v','e',' ','a','t',' ','y','o','u','!',
SET_WAIT(48),
SCRIPT_UNKNOWN_11(),
NEXT_DIALOG(),
SCRIPT_UNKNOWN_20(0x31f),
SET_FLAG(2),
CLOSE_DIALOG(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
