// SPDX-License-Identifier: AGPL-3.0-or-later
#include "rdai.h"

u16 PrizeDrops[] = {
    ITEMDROP_LIFE_VESSEL,   ITEMDROP_LIFE_VESSEL, ITEMDROP_FIRE_BOOMERANG,
    ITEMDROP_DIAMOND,       ITEMDROP_ZIRCON,      ITEMDROP_HEART_VESSEL,
    ITEMDROP_SHURIKEN,      ITEMDROP_TNT,         ITEMDROP_BOOMERANG,
    ITEMDROP_JAVELIN,       ITEMDROP_MANNA_PRISM, ITEMDROP_SMART_POTION,
    ITEMDROP_LIFE_VESSEL,   ITEMDROP_TALWAR,      ITEMDROP_BWAKA_KNIFE,
    ITEMDROP_MAGIC_MISSILE,
};
