files:
  - target: disks/us/BIN/WEAPON0.BIN
    asset_path: assets/weapon
    src_path: src/weapon
    segments:
      - start: 0x04000
        vram: 0x8017A000
        assets:
          - [0x04040, animset, w_000_1]
          - [0x04A44, animset, w_000_2]
          - [0x04A44, skip]
      - start: 0x0B000
        vram: 0x8017A000
        assets:
          - [0x0B040, animset, w_001_1]
          - [0x0BA44, animset, w_001_2]
          - [0x0BA44, skip]
      - start: 0x12000
        vram: 0x8017A000
        assets:
          - [0x12040, animset, w_002_1]
          - [0x12884, animset, w_002_2]
          - [0x12884, skip]
      - start: 0x19000
        vram: 0x8017A000
        assets:
          - [0x19040, animset, w_003_1]
          - [0x19884, animset, w_003_2]
          - [0x19884, skip]
      - start: 0x20000
        vram: 0x8017A000
        assets:
          - [0x20040, animset, w_004_1]
          - [0x20EAC, animset, w_004_2]
          - [0x20EAC, skip]
      - start: 0x27000
        vram: 0x8017A000
        assets:
          - [0x27040, animset, w_005_1]
          - [0x27EAC, animset, w_005_2]
          - [0x27EAC, skip]
      - start: 0x2E000
        vram: 0x8017A000
        assets:
          - [0x2E040, animset, w_006_1]
          - [0x2E884, animset, w_006_2]
          - [0x2E884, skip]
      - start: 0x35000
        vram: 0x8017A000
        assets:
          - [0x35040, animset, w_007_1]
          - [0x35884, animset, w_007_2]
          - [0x35884, skip]
      - start: 0x3C000
        vram: 0x8017A000
        assets:
          - [0x3C040, animset, w_008_1]
          - [0x3C804, animset, w_008_2]
          - [0x3C804, skip]
      - start: 0x43000
        vram: 0x8017A000
        assets:
          - [0x43040, animset, w_009_1]
          - [0x43804, animset, w_009_2]
          - [0x43804, skip]
      - start: 0x4A000
        vram: 0x8017A000
        assets:
          - [0x4A040, animset, w_010_1]
          - [0x4A8EC, animset, w_010_2]
          - [0x4A8EC, skip]
      - start: 0x51000
        vram: 0x8017A000
        assets:
          - [0x51040, animset, w_011_1]
          - [0x51958, animset, w_011_2]
          - [0x51958, skip]
      - start: 0x58000
        vram: 0x8017A000
        assets:
          - [0x58040, animset, w_012_1]
          - [0x582B0, animset, w_012_2]
          - [0x582B0, skip]
      - start: 0x5F000
        vram: 0x8017A000
        assets:
          - [0x5F040, animset, w_013_1]
          - [0x5F2B0, animset, w_013_2]
          - [0x5F2B0, skip]
      - start: 0x66000
        vram: 0x8017A000
        assets:
          - [0x66040, animset, w_014_1]
          - [0x662B0, animset, w_014_2]
          - [0x662B0, skip]
      - start: 0x6D000
        vram: 0x8017A000
        assets:
          - [0x6D040, animset, w_015_1]
          - [0x6D2B0, animset, w_015_2]
          - [0x6D478, skip]
      - start: 0x74000
        vram: 0x8017A000
        assets:
          - [0x74040, animset, w_016_1]
          - [0x742B0, animset, w_016_2]
          - [0x742B0, skip]
      - start: 0x7B000
        vram: 0x8017A000
        assets:
          - [0x7B040, animset, w_017_1]
          - [0x7B040, animset, w_017_2]
          - [0x7B040, skip]
      - start: 0x82000
        vram: 0x8017A000
        assets:
          - [0x82040, animset, w_018_1]
          - [0x82488, animset, w_018_2]
          - [0x82488, skip]
      - start: 0x89000
        vram: 0x8017A000
        assets:
          - [0x89040, animset, w_019_1]
          - [0x8930C, animset, w_019_2]
          - [0x8930C, skip]
      - start: 0x90000
        vram: 0x8017A000
        assets:
          - [0x90040, animset, w_020_1]
          - [0x90630, animset, w_020_2]
          - [0x90630, skip]
      - start: 0x97000
        vram: 0x8017A000
        assets:
          - [0x97040, animset, w_021_1]
          - [0x97564, animset, w_021_2]
          - [0x97564, skip]
      - start: 0x9E000
        vram: 0x8017A000
        assets:
          - [0x9E040, animset, w_022_1]
          - [0x9E540, animset, w_022_2]
          - [0x9E540, skip]
      - start: 0xA5000
        vram: 0x8017A000
        assets:
          - [0xA5040, animset, w_023_1]
          - [0xA58A4, animset, w_023_2]
          - [0xA58A4, skip]
      - start: 0xAC000
        vram: 0x8017A000
        assets:
          - [0xAC040, animset, w_024_1]
          - [0xAC804, animset, w_024_2]
          - [0xAC804, skip]
      - start: 0xB3000
        vram: 0x8017A000
        assets:
          - [0xB3040, animset, w_025_1]
          - [0xB3804, animset, w_025_2]
          - [0xB3804, skip]
      - start: 0xBA000
        vram: 0x8017A000
        assets:
          - [0xBA040, animset, w_026_1]
          - [0xBA804, animset, w_026_2]
          - [0xBA804, skip]
      - start: 0xC1000
        vram: 0x8017A000
        assets:
          - [0xC1040, animset, w_027_1]
          - [0xC1A18, animset, w_027_2]
          - [0xC1A18, skip]
      - start: 0xC8000
        vram: 0x8017A000
        assets:
          - [0xC8040, animset, w_028_1]
          - [0xC8804, animset, w_028_2]
          - [0xC8804, skip]
      - start: 0xCF000
        vram: 0x8017A000
        assets:
          - [0xCF040, animset, w_029_1]
          - [0xCF884, animset, w_029_2]
          - [0xCF884, skip]
      - start: 0xD6000
        vram: 0x8017A000
        assets:
          - [0xD6040, animset, w_030_1]
          - [0xD6040, animset, w_030_2]
          - [0xD6040, skip]
      - start: 0xDD000
        vram: 0x8017A000
        assets:
          - [0xDD040, animset, w_031_1]
          - [0xDD704, animset, w_031_2]
          - [0xDD704, skip]
      - start: 0xE4000
        vram: 0x8017A000
        assets:
          - [0xE4040, animset, w_032_1]
          - [0xE4704, animset, w_032_2]
          - [0xE4704, skip]
      - start: 0xEB000
        vram: 0x8017A000
        assets:
          - [0xEB040, animset, w_033_1]
          - [0xEBA9C, animset, w_033_2]
          - [0xEBA9C, skip]
      - start: 0xF2000
        vram: 0x8017A000
        assets:
          - [0xF2040, animset, w_034_1]
          - [0xF2784, animset, w_034_2]
          - [0xF2784, skip]
      - start: 0xF9000
        vram: 0x8017A000
        assets:
          - [0xF9040, animset, w_035_1]
          - [0xF9404, animset, w_035_2]
          - [0xF9404, skip]
      - start: 0x100000
        vram: 0x8017A000
        assets:
          - [0x100040, animset, w_036_1]
          - [0x100404, animset, w_036_2]
          - [0x100404, skip]
      - start: 0x107000
        vram: 0x8017A000
        assets:
          - [0x107040, animset, w_037_1]
          - [0x107504, animset, w_037_2]
          - [0x107504, skip]
      - start: 0x10E000
        vram: 0x8017A000
        assets:
          - [0x10E040, animset, w_038_1]
          - [0x10EC08, animset, w_038_2]
          - [0x10EC08, skip]
      - start: 0x115000
        vram: 0x8017A000
        assets:
          - [0x115040, animset, w_039_1]
          - [0x115C08, animset, w_039_2]
          - [0x115C08, skip]
      - start: 0x11C000
        vram: 0x8017A000
        assets:
          - [0x11C040, animset, w_040_1]
          - [0x11C504, animset, w_040_2]
          - [0x11C504, skip]
      - start: 0x123000
        vram: 0x8017A000
        assets:
          - [0x123040, animset, w_041_1]
          - [0x123284, animset, w_041_2]
          - [0x123284, skip]
      - start: 0x12A000
        vram: 0x8017A000
        assets:
          - [0x12A040, animset, w_042_1]
          - [0x12A3E4, animset, w_042_2]
          - [0x12A3E4, skip]
      - start: 0x131000
        vram: 0x8017A000
        assets:
          - [0x131040, animset, w_043_1]
          - [0x131A44, animset, w_043_2]
          - [0x131A44, skip]
      - start: 0x138000
        vram: 0x8017A000
        assets:
          - [0x138040, animset, w_044_1]
          - [0x138040, animset, w_044_2]
          - [0x138040, skip]
      - start: 0x13F000
        vram: 0x8017A000
        assets:
          - [0x13F040, animset, w_045_1]
          - [0x13F330, animset, w_045_2]
          - [0x13F330, skip]
      - start: 0x146000
        vram: 0x8017A000
        assets:
          - [0x146040, animset, w_046_1]
          - [0x1462B0, animset, w_046_2]
          - [0x1462B0, skip]
      - start: 0x14D000
        vram: 0x8017A000
        assets:
          - [0x14D040, animset, w_047_1]
          - [0x14D0D4, animset, w_047_2]
          - [0x14D228, skip]
      - start: 0x154000
        vram: 0x8017A000
        assets:
          - [0x154040, animset, w_048_1]
          - [0x154A44, animset, w_048_2]
          - [0x154A44, skip]
      - start: 0x15B000
        vram: 0x8017A000
        assets:
          - [0x15B040, animset, w_049_1]
          - [0x15BA44, animset, w_049_2]
          - [0x15BC00, skip]
      - start: 0x162000
        vram: 0x8017A000
        assets:
          - [0x162040, animset, w_050_1]
          - [0x162A44, animset, w_050_2]
          - [0x162A44, skip]
      - start: 0x169000
        vram: 0x8017A000
        assets:
          - [0x169040, animset, w_051_1]
          - [0x169950, animset, w_051_2]
          - [0x169950, skip]
      - start: 0x170000
        vram: 0x8017A000
        assets:
          - [0x170040, animset, w_052_1]
          - [0x170808, animset, w_052_2]
          - [0x170808, skip]
      - start: 0x177000
        vram: 0x8017A000
        assets:
          - [0x177040, animset, w_053_1]
          - [0x177A44, animset, w_053_2]
          - [0x177A44, skip]
      - start: 0x17E000
        vram: 0x8017A000
        assets:
          - [0x17E040, animset, w_054_1]
          - [0x17EA44, animset, w_054_2]
          - [0x17EA44, skip]
      - start: 0x185000
        vram: 0x8017A000
        assets:
          - [0x185040, animset, w_055_1]
          - [0x185A44, animset, w_055_2]
          - [0x185A44, skip]
      - start: 0x18C000
        vram: 0x8017A000
        assets:
          - [0x18C040, animset, w_056_1]
          - [0x18CA44, animset, w_056_2]
          - [0x18CA44, skip]
      - start: 0x193000
        vram: 0x8017A000
        assets:
          - [0x193040, animset, w_057_1]
          - [0x193A44, animset, w_057_2]
          - [0x193A44, skip]
      - start: 0x19A000
        vram: 0x8017A000
        assets:
          - [0x19A040, animset, w_058_1]
          - [0x19A808, animset, w_058_2]
          - [0x19A808, skip]
