version: pspeu
files:
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/dra.bin
    asset_path: assets/dra
    src_path: src/dra
    splat_config_path: config/splat.pspeu.dra.yaml
    segments:
      - start: 0
        vram: 0x090DC980
        assets:
          - [0x0, skip]
          - [0x6C290, cmpgfx, D_psp_09148C10, 128, 32, 4]
          - [0x6C730, cmpgfx, D_psp_091490B0, 128, 32, 4]
          - [0x6CBD0, cmpgfx, D_psp_09149550, 128, 32, 4]
          - [0x6D070, cmpgfx, D_psp_091499F0, 128, 32, 4]
          - [0x6D510, cmpgfx, D_psp_09149E90, 96, 16, 4]
          - [0x6D630, cmpgfx, D_psp_09149FB0, 96, 16, 4]
          - [0x6D750, cmpgfx, D_psp_0914A0D0, 96, 16, 4]
          - [0x6D8C8, cmpgfx, D_psp_0914A248, 96, 16, 4]
          - [0x6DA08, skip]
          - [0x6FA68, cmpgfx, game_over_left_it, 128, 128, 4]
          - [0x70ED0, cmpgfx, game_over_left_sp, 128, 128, 4]
          - [0x72530, cmpgfx, game_over_left_fr, 128, 128, 4]
          - [0x73900, cmpgfx, game_over_left_ge, 128, 128, 4]
          - [0x74F28, cmpgfx, game_over_right_it, 128, 128, 4]
          - [0x761A0, cmpgfx, game_over_right_sp, 128, 128, 4]
          - [0x778A0, cmpgfx, game_over_right_fr, 128, 128, 4]
          - [0x78FC8, cmpgfx, game_over_right_ge, 128, 128, 4]
          - [0x7A590, skip]
          - [0x7A5C8, rawgfx, D_psp_09156F48, 128, 128, 8, 0x7E5C8]
          - [0x7E5C8, palette, D_psp_0915AF48, 256]
          - [0x7E7C8, cmpgfx, loading_fr, 128, 128, 4]
          - [0x7F548, cmpgfx, loading_it, 128, 128, 4]
          - [0x802F8, cmpgfx, loading_ge, 128, 128, 4]
          - [0x80E88, cmpgfx, loading_sp, 128, 128, 4]
          - [0x81B68, skip]
          - [0x81C20, cmpgfx, intro_left_sp, 128, 128, 4]
          - [0x81F38, cmpgfx, intro_left_it, 128, 128, 4]
          - [0x821F8, cmpgfx, intro_left_ge, 128, 128, 4]
          - [0x82560, cmpgfx, intro_left_fr, 128, 128, 4]
          - [0x82908, cmpgfx, intro_right_sp, 128, 128, 4]
          - [0x82B60, cmpgfx, intro_right_it, 128, 128, 4]
          - [0x82D38, cmpgfx, intro_right_ge, 128, 128, 4]
          - [0x82FC0, cmpgfx, intro_right_fr, 128, 128, 4]
          - [0x83278, skip]
          - [0x84248, palette, D_800DB1F4, 16]
          - [0x84408, palette, D_800D68D4, 16]
          - [0x84428, palette, D_800D68F4, 16]
          - [0x84448, palette, D_800D6914, 16]
          - [0x84468, palette, D_800D6934, 16]
          - [0x84488, palette, D_800D6954, 16]
          - [0x844A8, palette, D_800D6974, 16]
          - [0x844C8, palette, D_800D6994, 16]
          - [0x844E8, palette, D_800D69B4, 16]
          - [0x84508, palette, D_800D69D4, 16]
          - [0x84528, palette, D_800D69F4, 16]
          - [0x84548, palette, D_800D6A14, 16]
          - [0x84568, palette, D_800D6A34, 16]
          - [0x84608, palette, D_800D6AD4, 16]
          - [0x84808, palette, D_800D6CD4, 16]
          - [0x84A08, palette, D_800D6ED4, 16]
          - [0x84C08, palette, D_800D70D4, 16]
          - [0x84E08, palette, D_800D72D4, 16]
          - [0x86408, cmpgfx, psp/text_item_up, 128, 128, 4, 0x86A40]
          - [0x86A40, palette, D_800DB0D4, 16]
          - [0x86A60, palette, D_800DB114, 16]
          - [0x86B40, palette, g_PalEquipIcon, 16]
          - [0x88B40, palette, D_psp_091654C0, 16]
          - [0x89340, cmpgfx, psp/load_room_obj, 128, 128, 4]
          - [0x8A0F0, palette, D_800DB0F4, 16]
          - [0x8A110, cmpgfx, psp/save_room_tile, 80, 16, 4]
          - [0x8A370, cmpgfx, psp/load_room_tile, 80, 16, 4]
          - [0x8A5A0, cmpgfx, psp/save_room_obj, 128, 128, 4]
          - [0x8B8A8, spriteset, D_800D34B8]
          - [0x8BB38, spriteset, D_800D3B88]
          - [0x8D6E0, spriteset, D_800CFF10]
          - [0x8E7F8, spriteset, D_800D372C]
          - [0x8ECB0, spriteset, D_800D5868]
          - [0x8FD10, spriteset, D_800D2BF4]
          - [0x8FE38, spriteset, D_800D684C]
          - [0x8FED0, spriteset, D_800D0F68]
          - [0x922F8, spriteset, D_800D2FFC]
          - [0x92578, spriteset, D_800D5628]
          - [0x92610, spriteset, D_800D327C]
          - [0x927C8, spriteset, D_800D2CF8]
          - [0x92B30, spriteset, D_800D56AC]
          - [0x92D20, spriteset, D_800D3428]
          - [0x92DB8, skip]
          - [0x939A8, headergfx, D_800C4CEC]
          - [0x93A30, headergfx, D_800C4D70]
          - [0x93AB8, headergfx, D_800C4DF4]
          - [0x93B40, headergfx, D_800C4E78]
          - [0x93BC8, headergfx, D_800C4EFC]
          - [0x93C50, headergfx, D_800C4F80]
          - [0x93CD8, headergfx, D_800C5004]
          - [0x93D60, headergfx, D_800C5088]
          - [0x93DE8, headergfx, D_800C510C]
          - [0x93E70, headergfx, D_800C5190]
          - [0x93EF8, headergfx, D_800C5214]
          - [0x93FE0, skip]
          - [0x94010, rawgfx, g_GfxEquipIcon, 16, 5120, 4]
          - [0x9E010, skip]
          - [0xA05C0, cmpgfx, font_eu, 128, 128, 4]
          - [0xA1328, cmpgfx, D_psp_0917DCA8, 128, 128, 4]
          - [0xA23E0, cmpgfx, D_psp_0917ED60, 128, 128, 4]
          - [0xA3590, cmpgfx, D_psp_0917FF10, 128, 128, 4]
          - [0xA4540, cmpgfx, D_psp_09180EC0, 128, 128, 4]
          - [0xA56A8, cmpgfx, D_psp_09182028, 128, 128, 4]
          - [0xA67B8, skip]
          - [0xA6FD8, blueprintsdef, psp/blueprints, AluBlueprints, AluEntities]
          - [0xA72BC, skip]
          - [0xA8948, palette, g_saveIconPal0, 256]
          - [0xA8B48, rawgfx, psp/memcard_0, 16, 48, 4, 0xA8948]
          - [0xA8CC8, rawgfx, psp/memcard_1, 16, 48, 4, 0xA8968]
          - [0xA8E48, rawgfx, psp/memcard_2, 16, 48, 4, 0xA8988]
          - [0xA8FC8, rawgfx, psp/memcard_3, 16, 48, 4, 0xA89A8]
          - [0xA9148, rawgfx, psp/memcard_4, 16, 48, 4, 0xA89C8]
          - [0xA92C8, rawgfx, psp/memcard_5, 16, 48, 4, 0xA89E8]
          - [0xA9448, rawgfx, psp/memcard_6, 16, 48, 4, 0xA8A08]
          - [0xA95C8, rawgfx, psp/memcard_7, 16, 48, 4, 0xA8A28]
          - [0xA9748, rawgfx, psp/memcard_8, 16, 48, 4, 0xA8A48]
          - [0xA98C8, rawgfx, psp/memcard_9, 16, 48, 4, 0xA8A68]
          - [0xA9A48, rawgfx, psp/memcard_10, 16, 48, 4, 0xA8A88]
          - [0xA9BC8, rawgfx, psp/memcard_11, 16, 48, 4, 0xA8AA8]
          - [0xA9D48, rawgfx, psp/memcard_12, 16, 48, 4, 0xA8AC8]
          - [0xA9EC8, rawgfx, psp/memcard_13, 16, 48, 4, 0xA8AE8]
          - [0xAA048, rawgfx, psp/memcard_14, 16, 48, 4, 0xA8B08]
          - [0xAA1C8, rawgfx, psp/memcard_15, 16, 48, 4, 0xA8B28]
          - [0xAA348, skip]
          - [0xAD4E0, cmpgfx, D_psp_09189E60, 128, 128, 4, 0x86A40]
          - [0xADD10, cmpgfx, D_psp_0918A690, 128, 128, 4, 0x86A40]
          - [0xAE228, cmpgfx, D_psp_0918ABA8, 128, 128, 4, 0x86A40]
          - [0xAE820, cmpgfx, D_psp_0918B1A0, 128, 128, 4, 0x86A40]
          - [0xAEEB0, skip]
          - [0xAF3E0, xamusicconfig, psp/xa_music_config]
          - [0xB16F0, sfxconfig, psp/sfx_config]
          - [0xB2C40, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/ric.bin
    asset_path: assets/ric
    src_path: src/ric
    splat_config_path: config/splat.pspeu.ric.yaml
    segments:
      - start: 0x80
        vram: 0x092A6280
        assets:
          - [0x80, skip]
          - [0x28AF0, cmpgfx, font_eu, 128, 128, 4]
          - [0x29858, skip]
          - [0x29870, cmpgfx, hud_sp, 128, 128, 4]
          - [0x2A6B8, cmpgfx, hud_it, 128, 128, 4]
          - [0x2B4F8, cmpgfx, hud_ge, 128, 128, 4]
          - [0x2C348, cmpgfx, hud_fr, 128, 128, 4]
          - [0x2D1B0, skip]
          - [0x2D320, subweaponsdef, subweapons, RicSubweapons, RicBlueprints]
          - [0x2D590, skip]
          - [0x2D718, blueprintsdef, psp/blueprints, RicBlueprints, RicEntities]
          - [0x2D8F0, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/maria.bin
    asset_path: assets/maria
    src_path: src/maria
    splat_config_path: config/splat.pspeu.maria.yaml
    segments:
      - start: 0
        vram: 0x092A6200
        assets:
          - [0x00, skip]
          - [0x1A880, cmpgfx, font_eu, 128, 128, 4]
          - [0x1B5E8, skip]
          - [0x1B600, cmpgfx, hud_sp, 128, 128, 4]
          - [0x1C3F0, cmpgfx, hud_it, 128, 128, 4]
          - [0x1D1D8, cmpgfx, hud_ge, 128, 128, 4]
          - [0x1DFD8, cmpgfx, hud_fr, 128, 128, 4]
          - [0x1EDF0, skip]
          - [0x1EFE0, subweaponsdef, subweapons, MarSubweapons, MarBlueprints]
          - [0x1F260, skip]
          - [0x1F3B0, blueprintsdef, blueprints, MarBlueprints, MarEntities]
          - [0x1F588, skip]
          - [0x20250, palette, maria_pal, 16]
          - [0x20850, spriteset, wpn_owl_spr]
          - [0x20B28, palette, wpn_owl_pal, 16]
          - [0x21128, cmpgfx, wpn_owl_gfx, 128, 128, 4, 0x20B28]
          - [0x218A0, spriteset, wpn_doll_spr]
          - [0x21A98, palette, wpn_doll_pal, 16]
          - [0x22098, cmpgfx, wpn_doll_gfx, 128, 128, 4, 0x21A98]
          - [0x22AE0, spriteset, wpn_turtle_spr]
          - [0x22BD0, palette, wpn_turtle_pal, 16]
          - [0x22BF0, palette, wpn_turtle2_pal, 16]
          - [0x231D0, cmpgfx, wpn_turtle_gfx, 128, 128, 4, 0x22BD0]
          - [0x24390, spriteset, wpn_cardinal_spr]
          - [0x24EA8, palette, wpn_cardinal_pal, 16]
          - [0x254A8, cmpgfx, wpn_cardinal_gfx, 128, 128, 4, 0x24EA8]
          - [0x26358, spriteset, wpn_cat_spr]
          - [0x26770, palette, wpn_cat_pal, 16]
          - [0x26790, palette, wpn_cat2_pal, 16]
          - [0x26D70, cmpgfx, wpn_cat_gfx, 128, 128, 4, 0x26770]
          - [0x27A48, spriteset, wpn_dragon_spr]
          - [0x27C50, palette, wpn_dragon_pal, 16]
          - [0x27C70, palette, wpn_dragon2_pal, 16]
          - [0x28250, cmpgfx, wpn_dragon_gfx, 128, 128, 4, 0x27C50]
          - [0x28E88, spritesheet, maria, disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/maria.bin, 0x20250]
          - [0x38C98, cmpgfx, items_gfx, 128, 128, 4]
          - [0x39C38, cmpgfx, hud_en, 128, 128, 4]
          - [0x3AA28, cmpgfx, crash_turtle_gfx, 128, 128, 4, 0x3ED58]
          - [0x3B980, cmpgfx, crash_dragon_gfx, 128, 128, 4, 0x3ED78]
          - [0x3CC08, cmpgfx, crash_cardinal_gfx, 128, 128, 4, 0x3ED98]
          - [0x3DE70, cmpgfx, crash_cat_gfx, 128, 128, 4, 0x3ED38]
          - [0x3ED38, palette, crash_cat_pal, 16]
          - [0x3ED58, palette, crash_turtle_pal, 16]
          - [0x3ED78, palette, crash_dragon_pal, 16]
          - [0x3ED98, palette, crash_cardinal_pal, 16]
          - [0x3F338, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/chi.bin
    asset_path: assets/st/chi
    src_path: src/st/chi_psp
    splat_config_path: config/splat.pspeu.stchi.yaml
    segments:
      - start: 0x80
        vram: 0x09237700
        assets:
          - [0x80, skip]
          - [0x1D790, cmpgfx, stage_name_en, 128, 64, 4]
          - [0x1DC28, cmpgfx, stage_name_it, 128, 64, 4]
          - [0x1DF88, cmpgfx, stage_name_sp, 128, 64, 4]
          - [0x1E2C8, cmpgfx, stage_name_ge, 128, 64, 4]
          - [0x1E6C8, cmpgfx, stage_name_fr, 128, 64, 4]
          - [0x1EA28, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/dai.bin
    asset_path: assets/st/dai
    src_path: src/st/dai
    splat_config_path: config/splat.pspeu.stdai.yaml
    segments:
      - start: 0x80
        vram: 0x09237700
        assets:
          - [0x80, skip]
          - [0x23A18, cmpgfx, stage_name_en, 128, 64, 4]
          - [0x23C38, cmpgfx, stage_name_it, 128, 64, 4]
          - [0x23E88, cmpgfx, stage_name_sp, 128, 64, 4]
          - [0x24090, cmpgfx, stage_name_ge, 128, 64, 4]
          - [0x24360, cmpgfx, stage_name_fr, 128, 64, 4]
          - [0x2457C, skip]
          - [0x2BCF8, cutscene, cutscene_script_it]
          - [0x2BE5C, skip] # trailing script data
          - [0x2BE70, cutscene, cutscene_script_sp]
          - [0x2BFBC, skip] # trailing script data
          - [0x2BFC8, cutscene, cutscene_script_fr]
          - [0x2C134, skip] # trailing script data
          - [0x2C138, cutscene, cutscene_script_ge]
          - [0x2C2C4, skip] # trailing script data
          - [0x2C2C8, cutscene, cutscene_script_en]
          - [0x2C428, skip] # trailing script data
          - [0x2C4B8, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/lib.bin
    asset_path: assets/st/lib
    src_path: src/st/lib_psp
    splat_config_path: config/splat.pspeu.stlib.yaml
    segments:
      - start: 0x80
        vram: 0x09237700
        assets:
          - [0x80, skip]
          - [0x36AF0, cmpgfx, stage_name_en, 128, 64, 4]
          - [0x36CE8, cmpgfx, stage_name_it, 128, 64, 4]
          - [0x36F70, cmpgfx, stage_name_sp, 128, 64, 4]
          - [0x371F0, cmpgfx, stage_name_ge, 128, 64, 4]
          - [0x37480, cmpgfx, stage_name_fr, 128, 64, 4]
          - [0x37758, skip]
          - [0x3ECB0, cutscene, cutscene_data_it]
          - [0x3EEA0, cutscene, cutscene_data_sp]
          - [0x3F068, cutscene, cutscene_data_fr]
          - [0x3F260, cutscene, cutscene_data_ge]
          - [0x3F448, cutscene, cutscene_data_en]
          - [0x3F608, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/no2.bin
    asset_path: assets/st/no2
    src_path: src/st/no2
    splat_config_path: config/splat.pspeu.stno2.yaml
    segments:
      - start: 0x80
        vram: 0x09237700
        assets:
          - [0x80, skip]
          - [0x24FF0, cmpgfx, stage_name_en, 128, 64, 4]
          - [0x25220, cmpgfx, stage_name_it, 128, 64, 4]
          - [0x25478, cmpgfx, stage_name_sp, 128, 64, 4]
          - [0x25708, cmpgfx, stage_name_ge, 128, 64, 4]
          - [0x25918, cmpgfx, stage_name_fr, 128, 64, 4]
          - [0x25B68, skip]
          - [0x2E9A0, layers, layers]
          - [0x2EC68, skip]
          - [0x2F1C8, rooms, rooms]
          - [0x2F298, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/no3.bin
    asset_path: assets/st/no3
    src_path: src/st/no3_psp
    splat_config_path: config/splat.pspeu.stno3.yaml
    segments:
      - start: 0x80
        vram: 0x09237700
        assets:
          - [0x80, skip]
          #- [0x33300, sprite_banks, sprite_banks]
          #- [0x33360, layers, layers]
          #- [0x33730, paldef, palette_def]
          #- [0x33870, gfx_banks, graphics_banks]
          #- [0x33A58, skip]
          - [0x33FB0, cutscene, cutscene_data_it]
          - [0x34150, cutscene, cutscene_data_sp]
          - [0x342D0, cutscene, cutscene_data_fr]
          - [0x34478, cutscene, cutscene_data_ge]
          - [0x34658, cutscene, cutscene_data_en]
          - [0x347E0, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/no4.bin
    asset_path: assets/st/no4
    src_path: src/st/no4_psp
    splat_config_path: config/splat.pspeu.stno4.yaml
    segments:
      - start: 0x80
        vram: 0x09237700
        assets:
          - [0x80, skip]
          - [0x30728, cutscene, cutscene_data_ferryman_right_it]
          - [0x30770, cutscene, cutscene_data_ferryman_right_sp]
          - [0x307B0, cutscene, cutscene_data_ferryman_right_fr]
          - [0x307F0, cutscene, cutscene_data_ferryman_right_ge]
          - [0x30838, cutscene, cutscene_data_ferryman_right_en]
          - [0x30878, cutscene, cutscene_data_ferryman_left_it]
          - [0x308D0, cutscene, cutscene_data_ferryman_left_sp]
          - [0x30938, cutscene, cutscene_data_ferryman_left_fr]
          - [0x309A0, cutscene, cutscene_data_ferryman_left_ge]
          - [0x30A08, cutscene, cutscene_data_ferryman_left_en]
          - [0x30A68, skip]
          - [0x66460, cmpgfx, stage_name_en, 128, 64, 4]
          - [0x66748, cmpgfx, stage_name_it, 128, 64, 4]
          - [0x669E0, cmpgfx, stage_name_sp, 128, 64, 4]
          - [0x66CB0, cmpgfx, stage_name_ge, 128, 64, 4]
          - [0x66F38, cmpgfx, stage_name_fr, 128, 64, 4]
          - [0x671D0, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/st0.bin
    asset_path: assets/st/st0
    src_path: src/st/st0_psp
    splat_config_path: config/splat.pspeu.stst0.yaml
    segments:
      - start: 0x80
        vram: 0x09237700
        assets:
          - [0x80, skip]
          - [0x1B700, cutscene, cutscene_data_it]
          - [0x1BA10, cutscene, cutscene_data_sp]
          - [0x1BCE8, cutscene, cutscene_data_fr]
          - [0x1BFB0, cutscene, cutscene_data_ge]
          - [0x1C298, cutscene, cutscene_data_en]
          - [0x1C500, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/wrp.bin
    asset_path: assets/st/wrp
    src_path: src/st/wrp
    splat_config_path: config/splat.pspeu.stwrp.yaml
    segments:
      - start: 0x80
        vram: 0x09237700
        assets:
          - [0x80, skip]
          - [0xF5F8, layers, layers]
          - [0xF6E8, skip]
