version: pspeu
files:
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/dra.bin
    asset_path: assets/dra
    src_path: src/dra
    splat_config_path: config/splat.pspeu.dra.yaml
    segments:
      - start: 0
        vram: 0x090DC980
        assets:
          - [0x0, skip]
          - [0x6FA68, cmpgfx, game_over_left_it, 128, 128, 4]
          - [0x70ED0, cmpgfx, game_over_left_sp, 128, 128, 4]
          - [0x72530, cmpgfx, game_over_left_fr, 128, 128, 4]
          - [0x73900, cmpgfx, game_over_left_ge, 128, 128, 4]
          - [0x74F28, cmpgfx, game_over_right_it, 128, 128, 4]
          - [0x761A0, cmpgfx, game_over_right_sp, 128, 128, 4]
          - [0x778A0, cmpgfx, game_over_right_fr, 128, 128, 4]
          - [0x78FC8, cmpgfx, game_over_right_ge, 128, 128, 4]
          - [0x7A590, skip]
          - [0x7A5C8, rawgfx, D_psp_09156F48, 128, 128, 8, 0x7E5C8]
          - [0x7E5C8, palette, D_psp_0915AF48, png, 256]
          - [0x7E7C8, cmpgfx, loading_fr, 128, 128, 4]
          - [0x7F548, cmpgfx, loading_it, 128, 128, 4]
          - [0x802F8, cmpgfx, loading_ge, 128, 128, 4]
          - [0x80E88, cmpgfx, loading_sp, 128, 128, 4]
          - [0x81B68, skip]
          - [0x81C20, cmpgfx, intro_left_sp, 128, 128, 4]
          - [0x81F38, cmpgfx, intro_left_it, 128, 128, 4]
          - [0x821F8, cmpgfx, intro_left_ge, 128, 128, 4]
          - [0x82560, cmpgfx, intro_left_fr, 128, 128, 4]
          - [0x82908, cmpgfx, intro_right_sp, 128, 128, 4]
          - [0x82B60, cmpgfx, intro_right_it, 128, 128, 4]
          - [0x82D38, cmpgfx, intro_right_ge, 128, 128, 4]
          - [0x82FC0, cmpgfx, intro_right_fr, 128, 128, 4]
          - [0x83278, skip]
          - [0xA05C0, cmpgfx, font_eu, 128, 128, 4]
          - [0xA1328, cmpgfx, D_psp_0917DCA8, 128, 128, 4]
          - [0xA23E0, cmpgfx, D_psp_0917ED60, 128, 128, 4]
          - [0xA3590, cmpgfx, D_psp_0917FF10, 128, 128, 4]
          - [0xA4540, cmpgfx, D_psp_09180EC0, 128, 128, 4]
          - [0xA56A8, cmpgfx, D_psp_09182028, 128, 128, 4]
          - [0xA67B8, skip]
          - [0xA6FD8, blueprintsdef, blueprints, AluBlueprints, AluEntities]
          - [0xA72BC, skip]
          - [0xAD4E0, cmpgfx, D_psp_09189E60, 128, 128, 4]
          - [0xADD10, cmpgfx, D_psp_0918A690, 128, 128, 4]
          - [0xAE228, cmpgfx, D_psp_0918ABA8, 128, 128, 4]
          - [0xAE820, cmpgfx, D_psp_0918B1A0, 128, 128, 4]
          - [0xAEEB0, skip]
          - [0xAF3E0, xamusicconfig, xa_music_config]
          - [0xB16F0, sfxconfig, sfx_config]
          - [0xB2C40, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/ric.bin
    asset_path: assets/ric
    src_path: src/ric
    splat_config_path: config/splat.pspeu.ric.yaml
    segments:
      - start: 0x80
        vram: 0x092A6280
        assets:
          - [0x80, skip]
          - [0x28AF0, cmpgfx, font_eu, 128, 128, 4]
          - [0x29858, skip]
          - [0x29870, cmpgfx, hud_sp, 128, 128, 4]
          - [0x2A6B8, cmpgfx, hud_it, 128, 128, 4]
          - [0x2B4F8, cmpgfx, hud_ge, 128, 128, 4]
          - [0x2C348, cmpgfx, hud_fr, 128, 128, 4]
          - [0x2D1B0, skip]
          - [0x2D320, subweaponsdef, subweapons, RicSubweapons, RicBlueprints]
          - [0x2D590, skip]
          - [0x2D718, blueprintsdef, blueprints, RicBlueprints, RicEntities]
          - [0x2D8F0, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/maria.bin
    asset_path: assets/maria
    src_path: src/maria
    splat_config_path: config/splat.pspeu.maria.yaml
    segments:
      - start: 0
        vram: 0x092A6200
        assets:
          - [0x00, skip]
          - [0x1A880, cmpgfx, font_eu, 128, 128, 4]
          - [0x1B5E8, skip]
          - [0x1B600, cmpgfx, hud_sp, 128, 128, 4]
          - [0x1C3F0, cmpgfx, hud_it, 128, 128, 4]
          - [0x1D1D8, cmpgfx, hud_ge, 128, 128, 4]
          - [0x1DFD8, cmpgfx, hud_fr, 128, 128, 4]
          - [0x1EDF0, skip]
          - [0x1EFE0, subweaponsdef, subweapons, MarSubweapons, MarBlueprints]
          - [0x1F260, skip]
          - [0x1F3B0, blueprintsdef, blueprints, MarBlueprints, MarEntities]
          - [0x1F588, skip]
          - [0x20250, palette, maria_pal, png, 16]
          - [0x20850, spriteset, wpn_owl_spr]
          - [0x20B28, palette, wpn_owl_pal, png, 16]
          - [0x21128, cmpgfx, wpn_owl_gfx, 128, 128, 4, 0x20B28] 
          - [0x218A0, spriteset, wpn_doll_spr]
          - [0x21A98, palette, wpn_doll_pal, png, 16]
          - [0x22098, cmpgfx, wpn_doll_gfx, 128, 128, 4, 0x21A98]
          - [0x22AE0, spriteset, wpn_turtle_spr]
          - [0x22BD0, palette, wpn_turtle_pal, png, 16] 
          - [0x22BF0, palette, wpn_turtle2_pal, png, 16]
          - [0x231D0, cmpgfx, wpn_turtle_gfx, 128, 128, 4, 0x22BD0]
          - [0x24390, spriteset, wpn_cardinal_spr]
          - [0x24EA8, palette, wpn_cardinal_pal, png, 16]
          - [0x254A8, cmpgfx, wpn_cardinal_gfx, 128, 128, 4, 0x24EA8]
          - [0x26358, spriteset, wpn_cat_spr]
          - [0x26770, palette, wpn_cat_pal, png, 16]
          - [0x26790, palette, wpn_cat2_pal, png, 16]
          - [0x26D70, cmpgfx, wpn_cat_gfx, 128, 128, 4, 0x26770]
          - [0x27A48, spriteset, wpn_dragon_spr]
          - [0x27C50, palette, wpn_dragon_pal, png, 16]
          - [0x27C70, palette, wpn_dragon2_pal, png, 16]
          - [0x28250, cmpgfx, wpn_dragon_gfx, 128, 128, 4, 0x27C50]
          - [0x28E88, spritesheet, maria, disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/maria.bin, 0x20250]
          - [0x38C98, cmpgfx, items_gfx, 128, 128, 4]
          - [0x39C38, cmpgfx, hud_en, 128, 128, 4]
          - [0x3AA28, cmpgfx, crash_turtle_gfx, 128, 128, 4, 0x3ED58]
          - [0x3B980, cmpgfx, crash_dragon_gfx, 128, 128, 4, 0x3ED78]
          - [0x3CC08, cmpgfx, crash_cardinal_gfx, 128, 128, 4, 0x3ED98]
          - [0x3DE70, cmpgfx, crash_cat_gfx, 128, 128, 4, 0x3ED38]
          - [0x3ED38, palette, crash_cat_pal, png, 16]
          - [0x3ED58, palette, crash_turtle_pal, png, 16]
          - [0x3ED78, palette, crash_dragon_pal, png, 16]
          - [0x3ED98, palette, crash_cardinal_pal, png, 16]
          - [0x3F338, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/lib.bin
    asset_path: assets/st/lib
    src_path: src/st/lib_psp
    splat_config_path: config/splat.pspeu.stlib.yaml
    segments:
      - start: 0x80
        vram: 0x09237700
        assets:
          - [0x80, skip]
          - [0x3ECB0, cutscene, cutscene_data_it]
          - [0x3EEA0, cutscene, cutscene_data_sp]
          - [0x3F068, cutscene, cutscene_data_fr]
          - [0x3F260, cutscene, cutscene_data_ge]
          - [0x3F448, cutscene, cutscene_data_en]
          - [0x3F608, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/no4.bin
    asset_path: assets/st/no4
    src_path: src/st/no4_psp
    splat_config_path: config/splat.pspeu.stno4.yaml
    segments:
      - start: 0x80
        vram: 0x09237700
        assets:
          - [0x80, skip]
          - [0x30728, cutscene, cutscene_data_ferryman_right_it]
          - [0x30770, cutscene, cutscene_data_ferryman_right_sp]
          - [0x307B0, cutscene, cutscene_data_ferryman_right_fr]
          - [0x307F0, cutscene, cutscene_data_ferryman_right_ge]
          - [0x30838, cutscene, cutscene_data_ferryman_right_en]
          - [0x30878, cutscene, cutscene_data_ferryman_left_it]
          - [0x308D0, cutscene, cutscene_data_ferryman_left_sp]
          - [0x30938, cutscene, cutscene_data_ferryman_left_fr]
          - [0x309A0, cutscene, cutscene_data_ferryman_left_ge]
          - [0x30A08, cutscene, cutscene_data_ferryman_left_en]
          - [0x30A68, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/st0.bin
    asset_path: assets/st/st0
    src_path: src/st/st0_psp
    splat_config_path: config/splat.pspeu.stst0.yaml
    segments:
      - start: 0x80
        vram: 0x09237700
        assets:
          - [0x80, skip]
          - [0x1B700, cutscene, cutscene_data_it]
          - [0x1BA10, cutscene, cutscene_data_sp]
          - [0x1BCE8, cutscene, cutscene_data_fr]
          - [0x1BFB0, cutscene, cutscene_data_ge]
          - [0x1C298, cutscene, cutscene_data_en]
          - [0x1C500, skip]
