files:
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/dra.bin
    asset_path: assets/dra
    src_path: src/dra
    splat_config_path: config/splat.pspeu.dra.yaml
    segments:
      - start: 0x80
        vram: 0x090DCA00
        assets:
          - [0x80, skip]
          - [0xA6FD8, blueprintsdef, blueprints_def, AluBlueprints, AluEntities]
          - [0xA72BC, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/ric.bin
    asset_path: assets/ric
    src_path: src/ric
    splat_config_path: config/splat.pspeu.ric.yaml
    segments:
      - start: 0x80
        vram: 0x092A6280
        assets:
          - [0x80, skip]
          - [0x28AF0, cmpgfx, font_eu, 128, 128, 4]
          - [0x29858, skip]
          - [0x29870, cmpgfx, hud_sp, 128, 128, 4]
          - [0x2A6B8, cmpgfx, hud_it, 128, 128, 4]
          - [0x2B4F8, cmpgfx, hud_ge, 128, 128, 4]
          - [0x2C348, cmpgfx, hud_fr, 128, 128, 4]
          - [0x2D1B0, skip]
          - [0x2D320, subweaponsdef, subweapons_def, RicSubweapons, RicBlueprints]
          - [0x2D590, skip]
          - [0x2D718, blueprintsdef, blueprints_def, RicBlueprints, RicEntities]
          - [0x2D8F0, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/maria.bin
    asset_path: assets/maria
    src_path: src/maria
    splat_config_path: config/splat.pspeu.maria.yaml
    segments:
      - start: 0x80
        vram: 0x092A6280
        assets:
          - [0x80, skip]
          - [0x1A880, cmpgfx, font_eu, 128, 128, 4]
          - [0x1B5E8, skip]
          - [0x1B600, cmpgfx, hud_sp, 128, 128, 4]
          - [0x1C3F0, cmpgfx, hud_it, 128, 128, 4]
          - [0x1D1D8, cmpgfx, hud_ge, 128, 128, 4]
          - [0x1DFD8, cmpgfx, hud_fr, 128, 128, 4]
          - [0x1EDF0, skip]
          - [0x1EFE0, subweaponsdef, subweapons_def, MarSubweapons, MarBlueprints]
          - [0x1F260, skip]
          - [0x1F3B0, blueprintsdef, blueprints_def, MarBlueprints, MarEntities]
          - [0x1F588, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/lib.bin
    asset_path: assets/st/lib
    src_path: src/st/lib_psp
    splat_config_path: config/splat.pspeu.stlib.yaml
    segments:
      - start: 0x80
        vram: 0x09237700
        assets:
          - [0x80, skip]
          - [0x3ECB0, cutscene, cutscene_data_it]
          - [0x3EEA0, cutscene, cutscene_data_sp]
          - [0x3F068, cutscene, cutscene_data_fr]
          - [0x3F260, cutscene, cutscene_data_ge]
          - [0x3F448, cutscene, cutscene_data_en]
          - [0x3F608, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/no4.bin
    asset_path: assets/st/no4
    src_path: src/st/no4_psp
    splat_config_path: config/splat.pspeu.stno4.yaml
    segments:
      - start: 0x80
        vram: 0x09237700
        assets:
          - [0x80, skip]
          - [0x30728, cutscene, cutscene_data_ferryman_right_it]
          - [0x30770, cutscene, cutscene_data_ferryman_right_sp]
          - [0x307B0, cutscene, cutscene_data_ferryman_right_fr]
          - [0x307F0, cutscene, cutscene_data_ferryman_right_ge]
          - [0x30838, cutscene, cutscene_data_ferryman_right_en]
          - [0x30878, cutscene, cutscene_data_ferryman_left_it]
          - [0x308D0, cutscene, cutscene_data_ferryman_left_sp]
          - [0x30938, cutscene, cutscene_data_ferryman_left_fr]
          - [0x309A0, cutscene, cutscene_data_ferryman_left_ge]
          - [0x30A08, cutscene, cutscene_data_ferryman_left_en]
          - [0x30A68, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/st0.bin
    asset_path: assets/st/st0
    src_path: src/st/st0_psp
    splat_config_path: config/splat.pspeu.stst0.yaml
    segments:
      - start: 0x80
        vram: 0x09237700
        assets:
          - [0x80, skip]
          - [0x1B700, cutscene, cutscene_data_it]
          - [0x1BA10, cutscene, cutscene_data_sp]
          - [0x1BCE8, cutscene, cutscene_data_fr]
          - [0x1BFB0, cutscene, cutscene_data_ge]
          - [0x1C298, cutscene, cutscene_data_en]
          - [0x1C500, skip]
