version: us
files:
  - target: disks/us/ST/RNZ1/RNZ1.BIN
    asset_path: assets/st/rnz1
    src_path: src/st/rnz1
    splat_config_path: config/splat.us.strnz1.yaml
    segments:
    - start: 0
      vram: 0x80180000
      assets:
        - [0x40, sprite_banks, sprite_banks]
        - [0xA0, skip] #paldef, palette_def]
        - [0x398, layers, layers]
        - [0x590, skip]
        - [0x840, layout, entity_layouts]
        - [0x9E8, skip]