options:
  platform: psx
  basename: bobo0
  base_path: ..
  build_path: build/us
  target_path: disks/us/BOSS/BO0/BO0.BIN
  asm_path: asm/us/boss/bo0
  asset_path: assets/boss/bo0
  src_path: src/boss/bo0
  ld_script_path: build/us/bobo0.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.bobo0.txt
  undefined_funcs_auto_path: build/us/config/undefined_funcs_auto.us.bobo0.txt
  undefined_syms_auto_path: build/us/config/undefined_syms_auto.us.bobo0.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: us_$VRAM
  disassemble_all: true
  section_order:
    - .data
    - .rodata
    - .text
    - .bss
    - .sbss
  ld_bss_is_noload: false
  disasm_unknown: true
  global_vram_start: 0x80010000
  ld_generate_symbol_per_data_segment: true
sha1: c9e00e7555c363d11b6e451403b59d96d3e591af
segments:
  - name: bobo0
    type: code
    start: 0x0
    vram: 0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, data]
      - [0x79C, .data, e_lock_camera]
      - [0x81C, .data, e_breakable]
      - [0x87C, data]
      - [0xA38, .data, e_spikes]
      - [0xA48, data]
      - [0xB44, .data, e_prisoner]
      - [0xBA8, data]
      - [0x1458, .data, st_update]
      - [0x14A4, .data, st_collision]
      - [0x1864, .data, e_red_door]
      - [0x187C, .data, st_common]
      - [0x1A7C, .data, e_collect]
      - [0x1DD0, .data, e_misc]
      - [0x1E88, .data, e_skelerang]
      - [0x1F74, data, e_marionette]
      - [0x2110, .data, e_bloody_zombie]
      - [0x2208, .data, e_owl_knight]
      - [0x24B4, .data, e_life_up]
      - [0x2508, .data, e_particles]
      - [0x2588, .data, e_room_fg]
      - [0x2614, data]
      - [0x292B8, .rodata, 2B9EC]
      - [0x292F0, .rodata, e_prisoner]
      - [0x29344, .rodata, 2D26C]
      - [0x29678, .rodata, 3AB18]
      - [0x2969C, .rodata, e_chair]
      - [0x296E8, .rodata, e_red_door]
      - [0x29700, .rodata, e_collect]
      - [0x297D4, .rodata, e_stage_name]
      - [0x29808, .rodata, e_skelerang]
      - [0x29874, .rodata, e_marionette]
      - [0x298A0, .rodata, e_bloody_zombie]
      - [0x298C8, .rodata, e_owl_knight]
      - [0x299D8, .rodata, e_life_up]
      - [0x299F4, .rodata, prim_helpers]
      - [0x299FC, c, e_room_bg]
      - [0x29AC4, c, e_lock_camera]
      - [0x29C80, c, e_breakable]
      - [0x29DB4, c, 33D8C]
      - [0x2A3B0, c, e_background_house]
      - [0x2ADCC, c, 34DA4]
      - [0x2B2DC, c, e_spikes]
      - [0x2B9EC, c]
      - [0x2CDC8, c, e_prisoner]
      - [0x2D26C, c]
      - [0x3A880, c, 372E8]
      - [0x3AB18, c]
      - [0x3BD24, c, e_chair]
      - [0x3C0DC, c, st_update]
      - [0x3C510, c, st_collision]
      - [0x3DCCC, c, create_entity]
      - [0x3E844, c, e_red_door]
      - [0x3F4F4, c, st_common]
      - [0x409A4, c, e_collect]
      - [0x43308, c, e_misc]
      - [0x456A4, c, e_stage_name]
      - [0x464F8, c, e_skelerang]
      - [0x46F50, c, e_marionette]
      - [0x482E0, c, e_bloody_zombie]
      - [0x49360, c, e_owl_knight]
      - [0x4B9A0, c, e_life_up]
      - [0x4C254, c, e_particles]
      - [0x4CA98, c, e_room_fg]
      - [0x4CB84, c, popup]
      - [0x4CEB4, c, prim_helpers]
      - [0x4D6E4, bss]
      - [0x4D8F4, .bss, create_entity]
      - [0x4D904, bss]
      - [0x4E570, .bss, st_update]
      - [0x4E5B0, bss, 2B9EC]
  - [0x4E5B4]
