options:
  platform: psp
  basename: bobo4
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/bo4.bin
  asm_path: asm/pspeu/boss/bo4_psp
  asset_path: assets/boss/bo4
  src_path: src/boss
  ld_script_path: build/pspeu/bobo4.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.bobo4.txt
  undefined_funcs_auto_path: build/pspeu/config/undefined_funcs_auto.pspeu.bobo4.txt
  undefined_syms_auto_path: build/pspeu/config/undefined_syms_auto.pspeu.bobo4.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  disassemble_all: true
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  global_vram_start: 0x08000000
  ld_generate_symbol_per_data_segment: true
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: 3db4548a368521efaedeb62bb99d6993116b3a28
segments:
  - [0x0, bin, mwo_header]
  - name: bobo4
    type: code
    start: 0x80
    vram: 0x09237700
    bss_start_address: 0x0926BA80
    bss_size: 0x1400
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, bo4/create_entity]
      - [0x1028, c, bo4/e_life_up]
      - [0x1CA8, c, bo4/e_stage_name]
      - [0x2B28, c, bo4/e_red_door]
      - [0x3E30, c, bo4/st_update]
      - [0x4D80, c, bo4/e_particles]
      - [0x58F8, c, bo4/e_collect]
      - [0x59D0, c, bo4/e_collect]
      - [0x9B40, c, bo4/e_misc]
      - [0xA0F0, c, bo4/collision]
      - [0xC2C8, c, bo4/popup]
      - [0xC8C0, c, bo4/e_room_fg]
      - [0xC9D8, c, bo4/st_common]
      - [0xD530, c, bo4/prim_helpers]
      - [0xDC70, c, bo4/doors]
      - [0x101C0, c, bo4/st_init_psp]
      - [0x10308, c, bo4/e_breakable]
      - [0x10488, c, bo4/e_room_bg]
      - [0x10568, c, bo4/e_lock_camera]
      - [0x107C8, c, bo4/unk_365FC]
      - [0x10DA8, c, bo4/unk_49A6C]
      - [0x1B490, c, bo4/doppleganger]
      - [0x1DB38, c, bo4_psp/unk_1DB38]
      - [0x27580, .data, bo4/e_life_up]
      - [0x275D0, .data, bo4/e_red_door]
      - [0x275E8, .data, bo4/st_update]
      - [0x27618, .data, bo4/e_particles]
      - [0x27698, .data, bo4/e_collect]
      - [0x27BE0, .data, bo4/e_misc]
      - [0x27C30, .data, bo4/collision]
      - [0x28008, .data, bo4/e_room_fg]
      - [0x280A8, .data, bo4/doors]
      - [0x281A8, data]
      - [0x2BAC0, .data, bo4/sprite_banks]
      - [0x2BB20, .data, bo4/layers]
      - [0x2BB38, .data, bo4/palette_def]
      - [0x2BBA0, .data, bo4/graphics_banks]
      - [0x2BC10, .data, bo4/e_red_door_tiles]
      - [0x2BC30, .data, bo4/e_init]
      - [0x2BD98, .data, bo4/gen/rooms]
      - [0x2BDB8, .data, bo4/spritesheets]
      - [0x2BDC8, .data, bo4/e_breakable]
      - [0x2BE18, .data, bo4/stage_data]
      - [0x309F0, .data, bo4/header]
      - [0x30A28, .data, bo4/background_block_init]
      - [0x30A68, .data, bo4/e_lock_camera]
      - [0x30AE0, .data, bo4/unk_365FC]
      - [0x30B08, .data, bo4/unk_49A6C]
      - [0x31800, data]
      - [0x33A30, .data, bo4/doppleganger]
      - [0x33AE0, data]
      - [0x33E80, .rodata, bo4/e_life_up]
      - [0x33EA0, .rodata, bo4/e_red_door]
      - [0x33EB8, .rodata, bo4/e_collect]
      - [0x33F18, .rodata, bo4/doors]
      - [0x33F80, .rodata, bo4/unk_365FC]
      - [0x33FA0, .rodata, bo4/unk_49A6C]
      - [0x34240, .rodata, bo4/doppleganger]
      - [0x34400, .bss, bo4/create_entity]
      - [0x34420, .bss, bo4/e_life_up]
      - [0x34428, .bss, bo4/st_update]
      - [0x34468, .bss, bo4/e_collect]
      - [0x34488, .bss, bo4/doors]
      - [0x344B0, bss, '344B0']
      - [0x34608, .bss, bo4/layers]
      - [0x34618, .bss, bo4/st_init_psp]
      - [0x34680, .bss, bo4/e_breakable]
      - [0x34688, .bss, bo4/d_prize_drops]
      - [0x34690, .bss, bo4/e_lock_camera]
      - [0x34698, .bss, bo4/unk_49A6C]
      - [0x352A0, .bss, bo4/doppleganger]
      - [0x35790, bss, '35790']
  - [0x35800]
