options:
  platform: psp
  basename: sttop
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/top.bin
  asm_path: asm/pspeu/st/top_psp
  asset_path: assets/st/top
  src_path: src/st/top
  ld_script_path: build/pspeu/sttop.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.sttop.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.pspeu.sttop.txt
  undefined_syms_auto_path: config/undefined_syms_auto.pspeu.sttop.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  disassemble_all: true
  global_vram_start: 0x8000000
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: c18ec76648fe3c49c97372d8c756f9084fd73ce2
segments:
  - [0x0, bin, mwo_header]
  - name: sttop
    type: code
    start: 0x80
    vram:  0x09237700
    bss_size: 0x800
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, top_psp/80] # create_entity
      # - [0x1028, c, top_psp/80]
      # - [0x33D8, c, top_psp/80] # e_stage_name
      # - [0x42D8, c, top_psp/80] # e_red_door
      # - [0x55E0, c, top_psp/80] # st_update
      # - [0x5B18, c, top_psp/80] # e_particles
      # - [0x70A8, c, top_psp/80] # e_collect
      # - [0xB2F8, c, top_psp/80] # e_misc
      # - [0xB8A8, c, top_psp/80]
      # - [0xBB08, c, top_psp/80] # collision
      # - [0xDCE0, c, top_psp/80] # popup
      # - [0xE2D8, c, top_psp/80]
      # - [0xE9C8, c, top_psp/80] # e_room_fg
      # - [0xEAE0, c, top_psp/80]
      # - [0x17738, c, top_psp/80] # e_room_bg
      # - [0x17818, c, top_psp/80]
      - [0x19500, data]
      - [0x3F280, .rodata, 80]
      - {type: bss, vram: 0x9276A80}
  - [0x3F480]
