options:
  platform: psx
  basename: bobo2
  base_path: ..
  build_path: build/us
  target_path: disks/us/BOSS/BO2/BO2.BIN
  asm_path: asm/us/boss/bo2
  asset_path: assets/boss/bo2
  src_path: src/boss/bo2
  ld_script_path: build/us/bobo2.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.bobo2.txt
  undefined_funcs_auto_path: build/us/config/undefined_funcs_auto.us.bobo2.txt
  undefined_syms_auto_path: build/us/config/undefined_syms_auto.us.bobo2.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: us_$VRAM
  disassemble_all: true
  section_order:
    - .data
    - .rodata
    - .text
    - .bss
    - .sbss
  ld_bss_is_noload: false
  disasm_unknown: true
  global_vram_start: 0x80010000
  ld_generate_symbol_per_data_segment: true
sha1: 91d90c1ea31a9fbfbccc0ab66b59551d823c51f6
segments:
  - name: bobo2
    type: code
    start: 0x0
    vram: 0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .data, header]
      - [0x2C, data]
      - [0x414, .data, e_init]
      - [0x590, data]
      - [0x5C8, .data, e_red_door_tiles]
      - [0x5E8, data]
      - [0x5E8, .data, e_lock_camera]
      - [0x668, data]
      - [0xCA4, .data, d_prize_drops]
      - [0xCA4, .data, st_update]
      - [0xCF0, data]
      - [0xCF0, .data, collision]
      - [0x10B0, .data, e_red_door]
      - [0x10C8, .data, st_common]
      - [0x12C8, .data, e_collect]
      - [0x161C, .data, e_misc]
      - [0x16D4, data]
      - [0x16D4, .data, e_particles]
      - [0x1754, .data, e_room_fg]
      - [0x17E0, data]
      - [0x17FC, .data, e_life_up]
      - [0x1850, data]
      - [0x21E98, .rodata, unk_224DC]
      - [0x21F6C, .rodata, e_cutscene_dialogue]
      - [0x22018, .rodata, unk_26EF8]
      - [0x22058, .rodata, e_red_door]
      - [0x22070, .rodata, e_collect]
      - [0x22144, .rodata, e_stage_name]
      - [0x22178, .rodata, prim_helpers]
      - [0x22180, .rodata, e_life_up]
      - [0x2219C, .rodata, unk_337D0]
      - [0x22258, c, unk_22258]
      - [0x22320, c, e_lock_camera]
      - [0x224DC, c, unk_224DC]
      - [0x25460, c, e_cutscene_dialogue]
      - [0x26EF8, c, unk_26EF8]
      - [0x27670, c, st_update]
      - [0x27AA4, c, collision]
      - [0x29260, c, create_entity]
      - [0x29DD8, c, e_red_door]
      - [0x29E50, c, e_red_door]
      - [0x2AA88, c, st_common]
      - [0x2BF38, c, e_collect]
      - [0x2E89C, c, e_misc]
      - [0x30C38, c, e_stage_name]
      - [0x31A8C, c, e_particles]
      - [0x322D0, c, e_room_fg]
      - [0x323BC, c, popup]
      - [0x326EC, c, prim_helpers]
      - [0x32F1C, c, e_life_up]
      - [0x337D0, c, unk_337D0]
      - [0x35BCC, bss]
      - [0x35C2C, .bss, create_entity]
      - [0x35C3C, bss]
      - [0x368F4, .bss, st_update]
      - [0x36934, bss]
  - [0x36934]
