options:
  platform: psx
  basename: sttop
  base_path: ..
  build_path: build/us
  target_path: disks/us/ST/TOP/TOP.BIN
  asm_path: asm/us/st/top
  asset_path: assets/st/top
  src_path: src/st/top
  ld_script_path: build/us/sttop.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.sttop.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.sttop.txt
  undefined_syms_auto_path: config/undefined_syms_auto.us.sttop.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: us_$VRAM
  section_order:
    - .data
    - .rodata
    - .text
    - .bss
    - .sbss
  ld_bss_is_noload: false
  disasm_unknown: true
  disassemble_all: true
  global_vram_start: 0x80010000
sha1: 47bb15117558c88f516cf4fc72fb8c91445d135e
segments:
  - name: sttop
    type: code
    start: 0
    vram:  0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, data]
      #- [0x, .data, e_init]
      #- [0x, .data, ...]
      #- [0x, .data, e_misc]
      #- [0x, .data, e_collect]
      #- [0x, .data, e_particles]
      #- [0x, .data, e_blue_axe_knight]
      - [0x2891C, .rodata, us]
      # - [0x, .rodata, cutscene]
      # - [0x, .rodata, e_red_door]
      # - [0x, .rodata, e_collect]
      # - [0x, .rodata, e_stage_name]
      # - [0x, .rodata, possibly other stage data]
      # - [0x, .rodata, e_blue_axe_knight]
      - [0x28C30, .rodata, prim_helpers]
      - [0x28C38, c, us] # e_room_bg
      # - [0x28D00, c, us]
      # - [0x2D630, c, us] # st_update
      # - [0x2DA64, c, us] # collision
      # - [0x2F220, c, us] # create_entity
      # - [0x2FD98, c, us] # e_red_door
      # - [0x30A48, c, us] # st_common
      # - [0x31EF8, c, us] # e_collect
      # - [0x34868, c, us] # e_misc
      # - [0x36C04, c, us] # e_stage_name
      # - [0x37A58, c, us] # e_particles
      # - [0x3829C, c, us] # e_room_fg
      # - [0x38388, c, us] # popup
      # - [0x386B8, c, us]
      # - [0x38BB8, c, us] # e_blue_axe_knight
      - [0x3A3C8, c, prim_helpers]
      - [0x3ABF8, c, e_clock_tower]
      - [0x3B7F0, sbss]
  - [0x3C55C]
