options:
  platform: psp
  basename: stdai
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/dai.bin
  asm_path: asm/pspeu/st/dai_psp
  asset_path: assets/st/dai
  src_path: src/st
  ld_script_path: build/pspeu/stdai.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.stdai.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.pspeu.stdai.txt
  undefined_syms_auto_path: config/undefined_syms_auto.pspeu.stdai.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  disassemble_all: true
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  global_vram_start: 0x08000000
  ld_generate_symbol_per_data_segment: true
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: 91f0ea1eaff4cf7a3773ee63cf516ef167bf73e3
segments:
  - [0x0, bin, mwo_header]
  - name: stdai
    type: code
    start: 0x80
    vram: 0x09237700
    bss_start_address: 0x09297000
    bss_size: 0x900
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, dai/create_entity]
      - [0x1028, c, dai/e_bat]
      - [0x1360, c, dai/e_skelerang]
      - [0x2280, c, dai/e_crow]
      - [0x2BA8, c, dai/e_stage_name]
      - [0x3AA8, c, dai/e_red_door]
      - [0x4DB0, c, dai/st_update]
      - [0x52E8, c, dai/e_winged_guard]
      - [0x5A40, c, dai/e_particles]
      - [0x6FD0, c, dai/e_collect]
      - [0xB220, c, dai/e_misc]
      - [0xBBB0, c, dai/st_collision]
      - [0xDD88, c, dai/e_sealed_door]
      - [0xF2E8, c, dai/e_mist_door]
      - [0xF570, c, dai/popup]
      - [0xFB68, c, dai/e_hunting_girl]
      - [0x11750, c, dai/e_bone_pillar]
      - [0x12F98, c, dai/e_corner_guard]
      - [0x142D8, c, dai/e_room_fg]
      - [0x143F0, c, dai/e_spectral_sword]
      - [0x15A88, c, dai/st_common]
      - [0x174B8, c, dai/prim_helpers]
      - [0x17C50, c, dai/e_bone_halberd]
      - [0x18920, c, dai/e_bell]
      - [0x198E0, c, dai/e_end_chime]
      - [0x19A40, c, dai/st_init_psp]
      - [0x19EA0, c, dai/e_breakable]
      - [0x1A770, c, dai/unk_40BA4]
      - [0x1ADC8, c, dai/unk_434FC]
      - [0x1AF48, c, dai/e_chair]
      - [0x1B400, c, dai/e_room_fg_2]
      - [0x1BAB8, c, dai/cutscene_init]
      - [0x1C3F0, c, dai/e_cutscene]
      - [0x1EF30, c, dai/e_room_bg]
      - [0x1F010, c, dai/e_lock_camera]
      - [0x1F270, c, dai/e_gargoyle_statue]
      - [0x1F4A8, c, dai/e_statue_block]
      - [0x1F868, c, dai/e_confessional]
      - [0x20A58, c, dai/e_spikes]
      - [0x214F8, c, dai/e_stained_glass]
      - [0x23008, c, dai/e_clouds]
      - [0x23800, .data, dai/e_bat]
      - [0x23840, .data, dai/e_skelerang]
      - [0x23930, .data, dai/e_crow]
      - [0x23A18, .data, dai/e_stage_name]
      - [0x245B0, .data, dai/e_red_door]
      - [0x245C8, .data, dai/st_update]
      - [0x245F8, .data, dai/e_winged_guard]
      - [0x24668, .data, dai/e_particles]
      - [0x246E8, .data, dai/e_collect]
      - [0x24C30, .data, dai/e_misc]
      - [0x24C90, .data, dai/st_collision]
      - [0x25068, .data, dai/e_sealed_door]
      - [0x25140, .data, dai/e_mist_door]
      - [0x252C8, .data, dai/e_hunting_girl]
      - [0x25440, .data, dai/e_bone_pillar]
      - [0x25520, .data, dai/e_corner_guard]
      - [0x255F8, .data, dai/e_room_fg]
      - [0x25698, .data, dai/e_spectral_sword]
      - [0x256C0, .data, dai/st_common]
      - [0x258C0, .data, dai/e_bone_halberd]
      - [0x25A68, data, dai_psp/e_statue_block]
      - [0x25A70, .data, dai/e_bell]
      - [0x25B18, data] # gen/sprites
      - [0x2B2C8, data] # sprite_banks
      - [0x2B328, data] # layers
      - [0x2B608, data] # palette_def
      - [0x2B6F8, data] # graphics_banks
      - [0x2B8E0, .data, dai/e_red_door_tiles]
      - [0x2B910, .data, dai/e_init]
      - [0x2BC20, data] # gen/rooms
      - [0x2BCF8, .data, dai/cutscene_script]
      - [0x2C430, .data, dai/e_breakable]
      - [0x2C588, data] # e_cutscene_data
      - [0x2C880, data] # stage_data
      - [0x36BF0, data, dai/e_cutscene_data]
      - [0x386F0, data] # stage_data
      - [0x3ADF0, data] # palettes
      - [0x3BAD0, data] # tilemaps
      - [0x5ED00, .data, dai/header]
      - [0x5ED30, .data, dai/e_chair]
      - [0x5ED40, .data, dai/d_prize_drops]
      - [0x5ED60, .data, dai/cutscene_init]
      - [0x5ED90, .data, dai/e_cutscene]
      - [0x5F158, .data, dai/background_block_init]
      - [0x5F178, .data, dai/e_lock_camera]
      - [0x5F1F0, .data, dai/e_statue_block]
      - [0x5F1F8, .data, dai/e_confessional]
      - [0x5F328, .data, dai/e_spikes]
      - [0x5F348, .data, dai/e_stained_glass]
      - [0x5F550, .data, dai/e_clouds]
      - [0x5F680, .rodata, dai/e_skelerang]
      - [0x5F6C8, .rodata, dai/e_crow]
      - [0x5F6E0, .rodata, dai/e_red_door]
      - [0x5F6F8, .rodata, dai/e_collect]
      - [0x5F758, .rodata, dai/e_sealed_door]
      - [0x5F770, .rodata, dai/e_hunting_girl]
      - [0x5F798, .rodata, dai/e_corner_guard]
      - [0x5F7C0, .rodata, dai/e_spectral_sword]
      - [0x5F7D8, .rodata, dai/e_bone_halberd]
      - [0x5F7F8, .rodata, dai/unk_40BA4]
      - [0x5F838, .rodata, dai/cutscene_init]
      - [0x5F858, .rodata, dai/e_cutscene]
      - [0x5F910, .rodata, dai/e_confessional]
      - [0x5F980, .bss, dai/create_entity]
      - [0x5F9A0, .bss, dai/e_collect]
      - [0x5FA00, bss, 5FA00]
      - [0x5FA08, .bss, dai/e_mist_door]
      - [0x5FA20, .bss, dai/e_end_chime]
      - [0x5FA28, bss, 5FA28]
      - [0x5FA38, .bss, dai/st_init_psp]
      - [0x5FC04, .bss, dai/e_cutscene]
      - [0x60210, .bss, dai/e_lock_camera]
      - [0x60218, .bss, dai/e_stained_glass]
      - [0x60230, .bss, dai/e_clouds]
      - [0x60238, bss, 60238]
  - [0x60280]
