options:
  platform: psp
  basename: stdai
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/dai.bin
  asm_path: asm/pspeu/st/dai_psp
  asset_path: assets/st/dai
  src_path: src/st/dai
  ld_script_path: build/pspeu/stdai.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.stdai.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.pspeu.stdai.txt
  undefined_syms_auto_path: config/undefined_syms_auto.pspeu.stdai.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  disassemble_all: true
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  global_vram_start: 0x08000000
  ld_generate_symbol_per_data_segment: true
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: 91f0ea1eaff4cf7a3773ee63cf516ef167bf73e3
segments:
  - [0x0, bin, mwo_header]
  - name: stdai
    type: code
    start: 0x80
    vram: 0x09237700
    bss_start_address: 0x09297000
    bss_size: 0x900
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, create_entity]
      - [0x1028, c, e_bat]
      - [0x1360, c, e_skelerang]
      - [0x2280, c, e_crow]
      - [0x2BA8, c, e_stage_name]
      - [0x3AA8, c, e_red_door]
      - [0x4DB0, c, st_update]
      - [0x52E8, c, e_winged_guard]
      - [0x5A40, c, e_particles]
      - [0x6FD0, c, e_collect]
      - [0xB220, c, e_misc]
      - [0xBBB0, c, st_collision]
      - [0xDD88, c, e_sealed_door]
      - [0xF2E8, c, e_mist_door]
      - [0xF570, c, popup]
      - [0xFB68, c, e_hunting_girl]
      - [0x11750, c, e_bone_pillar]
      - [0x12F98, c, e_corner_guard]
      - [0x142D8, c, e_room_fg]
      - [0x143F0, c, e_spectral_sword]
      - [0x15A88, c, st_common]
      - [0x174B8, c, prim_helpers]
      - [0x17C50, c, e_bone_halberd]
      - [0x18920, c, e_bell]
      - [0x198E0, c, e_end_chime]
      - [0x19A40, c, st_init_psp]
      - [0x19EA0, c, e_breakable]
      - [0x1A770, c, e_tower_exit]
      - [0x1ADC8, c, e_room_bg_2]
      - [0x1AF48, c, e_chair]
      - [0x1B400, c, e_room_fg_2]
      - [0x1BAB8, c, e_cutscene_actors]
      - [0x1C3F0, c, e_cutscene_dialogue]
      - [0x1EF30, c, e_room_bg]
      - [0x1F010, c, e_lock_camera]
      - [0x1F270, c, e_gargoyle]
      - [0x1F4A8, c, e_dai_no2_shortcut]
      - [0x1F868, c, e_confessional]
      - [0x20A58, c, e_spikes]
      - [0x214F8, c, e_stained_glass]
      - [0x23008, c, e_clouds]
      - [0x23800, .data, e_bat]
      - [0x23840, .data, e_skelerang]
      - [0x23930, .data, e_crow]
      - [0x23A18, .data, e_stage_name]
      - [0x245B0, .data, e_red_door]
      - [0x245C8, .data, st_update]
      - [0x245F8, .data, e_winged_guard]
      - [0x24668, .data, e_particles]
      - [0x246E8, .data, e_collect]
      - [0x24C30, .data, e_misc]
      - [0x24C90, .data, st_collision]
      - [0x25068, .data, e_sealed_door]
      - [0x25140, .data, e_mist_door]
      - [0x252C8, .data, e_hunting_girl]
      - [0x25440, .data, e_bone_pillar]
      - [0x25520, .data, e_corner_guard]
      - [0x255F8, .data, e_room_fg]
      - [0x25698, .data, e_spectral_sword]
      - [0x256C0, .data, st_common]
      - [0x258C0, .data, e_bone_halberd]
      - [0x25A70, .data, e_bell]
      - [0x25B18, .data, gen/psp/sprites]
      - [0x2B2C8, .data, sprite_banks]
      - [0x2B328, .data, layers]
      - [0x2B608, .data, pal_stained_glass]
      - [0x2B628, .data, palette_def]
      - [0x2B6F8, .data, graphics_banks]
      - [0x2B8E0, .data, e_red_door_tiles]
      - [0x2B910, .data, e_init]
      - [0x2BC20, .data, gen/rooms]
      - [0x2BCF8, .data, cutscene_data]
      - [0x2C430, .data, e_breakable]
      - [0x2C588, .data, gfx_data]
      - [0x3BAD0, .data, tilemaps]
      - [0x5ED00, .data, header]
      - [0x5ED30, .data, e_chair]
      - [0x5ED40, .data, d_prize_drops]
      - [0x5ED60, .data, e_cutscene_actors]
      - [0x5ED90, .data, e_cutscene_dialogue]
      - [0x5F158, .data, background_block_init]
      - [0x5F178, .data, e_lock_camera]
      - [0x5F1F0, .data, e_dai_no2_shortcut]
      - [0x5F1F8, .data, e_confessional]
      - [0x5F328, .data, e_spikes]
      - [0x5F348, .data, e_stained_glass]
      - [0x5F550, .data, e_clouds]
      - [0x5F680, .rodata, e_skelerang]
      - [0x5F6C8, .rodata, e_crow]
      - [0x5F6E0, .rodata, e_red_door]
      - [0x5F6F8, .rodata, e_collect]
      - [0x5F758, .rodata, e_sealed_door]
      - [0x5F770, .rodata, e_hunting_girl]
      - [0x5F798, .rodata, e_corner_guard]
      - [0x5F7C0, .rodata, e_spectral_sword]
      - [0x5F7D8, .rodata, e_bone_halberd]
      - [0x5F7F8, .rodata, e_tower_exit]
      - [0x5F838, .rodata, e_cutscene_actors]
      - [0x5F858, .rodata, e_cutscene_dialogue]
      - [0x5F910, .rodata, e_confessional]
      - [0x5F980, .bss, create_entity]
      - [0x5F9A0, .bss, e_collect]
      - [0x5FA00, .bss, e_sealed_door]
      - [0x5FA08, .bss, e_mist_door]
      - [0x5FA20, .bss, e_end_chime]
      - [0x5FA28, .bss, layers]
      - [0x5FA38, .bss, st_init_psp]
      - [0x5FC04, .bss, e_cutscene_dialogue]
      - [0x60210, .bss, e_lock_camera]
      - [0x60218, .bss, e_stained_glass]
      - [0x60230, .bss, e_clouds]
      - [0x60238, bss, bss]
  - [0x60280]
