options:
  platform: psp
  basename: stdai
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/dai.bin
  asm_path: asm/pspeu/st/dai_psp
  asset_path: assets/st/dai
  src_path: src/st
  ld_script_path: build/pspeu/stdai.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.stdai.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.pspeu.stdai.txt
  undefined_syms_auto_path: config/undefined_syms_auto.pspeu.stdai.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  nonmatchings_path: nonmatchings
  disassemble_all: true
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  global_vram_start: 0x08000000
  ld_generate_symbol_per_data_segment: true
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: 91f0ea1eaff4cf7a3773ee63cf516ef167bf73e3
segments:
  - [0x0, bin, mwo_header]
  - name: stdai
    type: code
    start: 0x80
    vram: 0x09237700
    bss_start_address: 0x09297000
    bss_size: 0x900
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, dai/create_entity]
      - [0x1028, c, dai_psp/e_bat]
      - [0x1360, c, dai_psp/unk_1360]
      - [0x2BA8, c, dai_psp/e_stage_name]
      - [0x3AA8, c, dai_psp/e_red_door]
      - [0x4DB0, c, dai_psp/st_update]
      - [0x52E8, c, dai_psp/unk_52E8]
      - [0x5A40, c, dai_psp/e_particles]
      - [0x6FD0, c, dai_psp/e_collect]
      - [0xB220, c, dai_psp/e_misc]
      - [0xBBB0, c, dai_psp/st_collision]
      - [0xDD88, c, dai_psp/e_sealed_door]
      - [0xF2E8, c, dai_psp/e_mist_door]
      - [0xF570, c, dai/popup]
      - [0xFB68, c, dai_psp/unk_FB68]
      - [0x142D8, c, dai_psp/e_room_fg]
      - [0x143F0, c, dai_psp/unk_143F0]
      - [0x15A88, c, dai_psp/st_common]
      - [0x174B8, c, dai_psp/prim_helpers]
      - [0x17C50, c, dai_psp/unk_17C50]
      - [0x19A40, c, dai_psp/st_init]
      - [0x19EA0, c, dai_psp/e_breakable]
      - [0x1A390, c, dai_psp/unk_1A390]
      - [0x1C3F0, c, dai_psp/e_cutscene]
      - [0x1EF30, c, dai/e_room_bg]
      - [0x1F010, c, dai/e_lock_camera]
      - [0x1F270, c, dai_psp/unk_1F270]
      - [0x23780, data]
      #- [0x2B910, .data, dai/e_init]
      - [0x5ED00, .data, dai_psp/header]
      - [0x5ED30, data]
      - [0x5F158, .data, dai/e_room_bg]
      - [0x5F1F0, data]
      - [0x5F680, .rodata, dai_psp/unk_1360]
      - [0x5F6E0, .rodata, dai_psp/e_red_door]
      - [0x5F6F8, .rodata, dai_psp/e_collect]
      - [0x5F758, .rodata, dai_psp/e_sealed_door]
      - [0x5F770, .rodata, dai_psp/unk_FB68]
      - [0x5F7C0, .rodata, dai_psp/unk_143F0]
      - [0x5F7D8, .rodata, dai_psp/unk_17C50]
      - [0x5F7F8, .rodata, dai_psp/unk_1A390]
      - [0x5F858, .rodata, dai_psp/e_cutscene]
      - [0x5F910, .rodata, dai_psp/unk_1F270]
      - [0x5F980, .bss, dai/create_entity]
      - [0x5F9A0, bss, 5F9A0]
      - [0x60210, .bss, dai/e_room_bg]
      - [0x60218, bss, 60218]
  - [0x60280]
