options:
  platform: psp
  basename: strno2
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/rno2.bin
  asm_path: asm/pspeu/st/rno2_psp
  asset_path: assets/st/rno2
  src_path: src/st
  ld_script_path: build/pspeu/strno2.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.strno2.txt
  undefined_funcs_auto_path: build/pspeu/config/undefined_funcs_auto.pspeu.strno2.txt
  undefined_syms_auto_path: build/pspeu/config/undefined_syms_auto.pspeu.strno2.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  disassemble_all: true
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  global_vram_start: 0x08000000
  ld_generate_symbol_per_data_segment: true
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: 9e7644ecee7b1df4f2f5c8fb7e24e4072258a7d4
segments:
  - [0x0, bin, mwo_header]
  - name: strno2
    type: code
    start: 0x80
    vram: 0x09237700
    bss_start_address: 0x09287600
    bss_size: 0x280
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, rno2/e_ctulhu]
      - [0x2730, c, rno2/create_entity]
      - [0x36D8, c, rno2_psp/e_bloody_zombie]
      - [0x3EF8, c, rno2/e_azaghal]
      - [0x6E40, c, rno2_psp/unk_3EF8]
      - [0x92B0, c, rno2_psp/e_stage_name]
      - [0xA130, c, rno2_psp/unk_A130]
      - [0xBBB8, c, rno2/st_update]
      - [0xC0F0, c, rno2_psp/unk_C0F0]
      - [0xFCF0, c, rno2_psp/e_particles]
      - [0x10868, c, rno2_psp/unk_10868]
      - [0x10940, c, rno2/e_collect]
      - [0x14AB8, c, rno2_psp/e_misc]
      - [0x15308, c, rno2/collision]
      - [0x174E0, c, rno2/e_medusa_head]
      - [0x179D8, c, rno2/popup]
      - [0x17FD0, c, rno2/e_room_fg]
      - [0x180E8, c, rno2/st_common]
      - [0x194D8, c, rno2/prim_helpers]
      - [0x19FF8, c, rno2_psp/unk_19FF8]
      - [0x1BCC8, c, rno2_psp/st_init]
      - [0x1BF80, c, rno2_psp/unk_1BF80]
      - [0x1DDC8, c, rno2_psp/e_background_house]
      - [0x1ED70, c, rno2_psp/unk_1ED70]
      - [0x20358, c, rno2/e_lock_camera]
      - [0x205B8, c, rno2_psp/e_spikes]
      - [0x20F00, .data, rno2/e_ctulhu]
      - [0x21050, data]
      - [0x21090, .data, rno2/e_azaghal]
      - [0x21390, data, '21390']
      - [0x215D8, .data, rno2/st_update]
      - [0x21608, data, '21608']
      - [0x21880, .data, rno2/e_collect]
      - [0x21DC8, .data, rno2_psp/e_misc]
      - [0x21E18, data, 21E18]
      - [0x21E18, .data, rno2/collision]
      - [0x221F0, .data, rno2/e_medusa_head]
      - [0x22270, .data, rno2/e_room_fg]
      - [0x22310, .data, rno2/st_common]
      - [0x22510, data, '22510']
      - [0x294C8, .data, rno2/e_init]
      - [0x29788, data]
      - [0x4F980, .data, rno2/header]
      - [0x4F9B0, data]
      - [0x4FBB0, .data, rno2/d_prize_drops]
      - [0x4FBC8, data, 4FBC8]
      - [0x4FCB0, .data, rno2/e_lock_camera]
      - [0x4FD28, data, 4FD28]
      - [0x4FD80, .rodata, rno2/e_ctulhu]
      - [0x4FDA0, .rodata, rno2/e_azaghal]
      - [0x4FDD8, .rodata, rno2_psp/unk_3EF8]
      - [0x4FE10, .rodata, rno2_psp/unk_A130]
      - [0x4FE48, .rodata, rno2_psp/unk_C0F0]
      - [0x4FE90, .rodata, rno2/e_collect]
      - [0x4FEF0, .rodata, rno2_psp/unk_19FF8]
      - [0x4FF10, .rodata, rno2_psp/unk_1BF80]
      - [0x4FF80, .bss, rno2/create_entity]
      - [0x4FFA0, .bss, rno2/st_update]
      - [0x4FFE0, bss, 4FFE0]
      - [0x4FFE8, .bss, rno2_psp/unk_10868]
      - [0x50000, bss, '50000']
      - [0x50188, .bss, rno2/e_lock_camera]
      - [0x50190, bss, '50190']
  - [0x50200]
