options:
  platform:     psx
  basename:     stlib
  base_path:    ..
  target_path:  iso/ST/LIB/LIB.BIN
  asm_path:     asm/st/lib
  asset_path:   assets/st/lib
  src_path:     src/st/lib
  compiler:     GCC
  symbol_addrs_path:    config/generated.symbols.stlib.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.stlib.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.stlib.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
segments:
  - name: stlib
    type: code
    start: 0x00000000
    vram:  0x80180000
    subalign: 2
    subsegments:
      - [0x0, rodata]
      - [0x2DED0, c]
      - [0x52CE0, data]
  - [0x552CC]
