options:
  platform: psx
  basename: strnz0
  base_path: ..
  build_path: build/us
  target_path: disks/us/ST/RNZ0/RNZ0.BIN
  asm_path: asm/us/st/rnz0
  asset_path: assets/st/rnz0
  src_path: src/st/rnz0
  ld_script_path: build/us/strnz0.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.strnz0.txt
  undefined_funcs_auto_path: build/us/config/undefined_funcs_auto.us.strnz0.txt
  undefined_syms_auto_path: build/us/config/undefined_syms_auto.us.strnz0.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: us_$VRAM
  section_order:
    - .data
    - .rodata
    - .text
    - .bss
    - .sbss
  ld_bss_is_noload: false
  disasm_unknown: true
  disassemble_all: true
  global_vram_start: 0x80010000
sha1: d2e6eaef70625b8832a2c5af151fe987748c8d73
segments:
  - name: strnz0
    type: code
    start: 0
    vram:  0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .data, header]
      - [0x40, .data, header] # sprite_banks
      - [0xA4, .data, header] # palette_def
      - [0x14C, .data, header] # layers
      - [0x464, .data, header] # graphics banks
      - [0x6F0, .data, gen/e_laydef]
      - [0x898, .data, e_init]
      - [0xB10, .data, e_room_bg]
      - [0xB48, data]
      - [0xB78, .data, e_lock_camera]
      - [0xBF8, .data, e_breakable]
      - [0xC68, .data, e_left_secret_room_wall]
      - [0xCC8, data]
      - [0xCE8, .data, e_globe_table]
      - [0xD08, .data, e_life_max_tank]
      - [0xD38, .data, e_blue_flame_table]
      - [0xD84, .data, e_cannon]
      - [0xDA0, .data, st_update]
      - [0xDEC, .data, collision]
      - [0x11AC, .data, e_red_door]
      - [0x11C4, .data, st_common]
      - [0x13C4, .data, e_collect]
      - [0x1718, .data, e_misc]
      - [0x17D0, .data, e_particles]
      - [0x1850, .data, e_room_fg]
      - [0x18DC, .data, e_floor_trap]
      - [0x18F4, .data, e_ctulhu]
      - [0x1A20, .data, e_fire_demon]
      - [0x1B18, .data, e_lesser_demon]
      - [0x1C8C, .data, e_sealed_door]
      - [0x1CFC, .data, e_bitterfly]
      - [0x1D70, .data, e_unk32-33]
      - [0x1DA4, data]
      - [0x1FA8, .data, gen/rooms]
      - [0x20AC, .data, gen/e_layout]
      - [0x326C, data]
      - [0x3B54, .data, stage_data]
      - [0x2493C, .data, gen/sprites]
      - [0x2ABEC, .rodata, e_red_eye_bust]
      - [0x2ABF8, .rodata, e_blue_flame_table]
      - [0x2AC04, .rodata, e_room_bg]
      - [0x2AC04, .rodata, e_red_door]
      - [0x2AC1C, .rodata, e_collect]
      - [0x2ACF0, .rodata, e_stage_name]
      - [0x2AD24, .rodata, e_floor_trap]
      - [0x2AD30, .rodata, e_ctulhu]
      - [0x2AD5C, .rodata, e_fire_demon]
      - [0x2AE6C, .rodata, e_lesser_demon]
      - [0x2AEBC, .rodata, e_sealed_door]
      - [0x2AED4, .rodata, e_unk32-33]
      - [0x2AF04, .rodata, e_unk34-36]
      - [0x2AF10, .rodata, e_salem_witch]
      - [0x2AF4C, .rodata, prim_helpers]
      - [0x2AF54, c, e_room_bg]
      - [0x2B034, c, e_lock_camera]
      - [0x2B1F0, c, e_breakable]
      - [0x2B4E8, c, e_red_eye_bust]
      - [0x2B610, c, e_purple_brick]
      - [0x2B7EC, c, e_left_secret_room_wall]
      - [0x2BF64, c, e_globe_table]
      - [0x2C064, c, e_life_max_tank]
      - [0x2C1CC, c, e_blue_flame_table]
      - [0x2C548, c, e_cannon]
      - [0x2CC04, c, st_update]
      - [0x2D038, c, collision]
      - [0x2E7F4, c, create_entity]
      - [0x2F36C, c, e_red_door]
      - [0x3001C, c, st_common]
      - [0x314CC, c, e_collect]
      - [0x33E3C, c, e_misc]
      - [0x361D8, c, e_stage_name]
      - [0x3702C, c, e_particles]
      - [0x37870, c, e_room_fg]
      - [0x3795C, c, popup]
      - [0x37C8C, c, e_floor_trap]
      - [0x38238, c, e_ctulhu]
      - [0x39E64, c, e_fire_demon]
      - [0x3C51C, c, e_lesser_demon]
      - [0x3F820, c, e_sealed_door]
      - [0x4060C, c, e_bitterfly]
      - [0x409E8, c, e_unk32-33]
      - [0x41758, c, e_unk34-36]
      - [0x41FA0, c, e_salem_witch]
      - [0x436C0, c, prim_helpers]
      - [0x43EF0, .bss, create_entity]
      - [0x43F00, bss]
      - [0x44B68, .bss, st_update]
      
  - [0x44BA8]