options:
  platform: psp
  basename: strnz1
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/rnz1.bin
  asm_path: asm/pspeu/st/rnz1_psp
  asset_path: assets/st/rnz1
  src_path: src/st/rnz1
  ld_script_path: build/pspeu/strnz1.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.strnz1.txt
  undefined_funcs_auto_path: build/pspeu/config/undefined_funcs_auto.pspeu.strnz1.txt
  undefined_syms_auto_path: build/pspeu/config/undefined_syms_auto.pspeu.strnz1.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  disassemble_all: true
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  global_vram_start: 0x08000000
  ld_generate_symbol_per_data_segment: true
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: 0b3a09b30938a3208f395db8389141d3b3c44642
segments:
  - [0x0, bin, mwo_header]
  - name: strnz1
    type: code
    start: 0x80
    vram: 0x09237700
    bss_start_address: 0x0927BE80
    bss_size: 0x380
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, create_entity]
      - [0x1028, c, e_bomb_knight]
      - [0x28B8, c, e_life_up]
      - [0x3538, c, e_stage_name]
      - [0x43B8, c, e_red_door]
      - [0x44A0, c, e_red_door]
      - [0x56C0, c, st_update]
      - [0x5BF8, c, e_valhalla_knight]
      - [0x6B58, c, e_particles]
      - [0x80E8, c, e_collect]
      - [0xC338, c, e_misc]
      - [0xCB70, c, collision]
      - [0xED48, c, e_cloaked_knight]
      - [0x10188, c, e_medusa_head]
      - [0x106A8, c, water_effects]
      - [0x13630, c, popup]
      - [0x13C28, c, e_room_fg]
      - [0x13D40, c, st_common]
      - [0x15608, c, prim_helpers]
      - [0x15D98, c, e_crusher]
      - [0x16E70, c, e_bg_gears]
      - [0x17168, c, e_dw_batwings]
      - [0x19150, c, e_darkwing_bat]
      - [0x1B398, c, st_init_psp]
      - [0x1B6D0, c, bossfight]
      - [0x1C058, c, e_breakable]
      - [0x1CB18, c, e_water_fg]
      - [0x1CCB0, c, e_clouds]
      - [0x1D200, c, e_room_bg]
      - [0x1D310, c, e_lock_camera]
      - [0x1D570, c, e_explosion_puff_opaque]
      - [0x1DC68, c, e_spikes]
      - [0x1E6E8, c, e_secrets]
      - [0x1F400, c, e_gear_horizontal]
      - [0x1F530, c, e_gear_puzzle]
      - [0x1FB60, c, e_gear_large]
      - [0x1FE68, c, e_gear_small]
      - [0x202B8, c, e_gear_vertical]
      - [0x20580, .data, e_bomb_knight]
      - [0x20958, .data, e_life_up]
      - [0x209A8, .data, e_red_door]
      - [0x209C0, .data, st_update]
      - [0x209F0, .data, e_valhalla_knight]
      - [0x20B88, .data, e_particles]
      - [0x20C08, .data, e_collect]
      - [0x21150, .data, e_misc]
      - [0x211A0, .data, collision]
      - [0x21578, .data, e_cloaked_knight]
      - [0x21598, .data, e_medusa_head]
      - [0x21618, .data, water_effects]
      - [0x216F8, .data, e_room_fg]
      - [0x21798, .data, st_common]
      - [0x21998, .data, e_crusher]
      - [0x219B8, .data, e_bg_gears]
      - [0x219C0, .data, e_dw_batwings]
      - [0x21A80, .data, e_darkwing_bat]
      - [0x21C30, .data, gen/psp/sprites]
      - [0x27048, .data, sprite_banks]
      - [0x270A8, data]
      - [0x27868, .data, e_red_door_tiles]
      - [0x27888, .data, e_init]
      - [0x27B60, data]
      - [0x27BF0, .data, bossfight]
      - [0x27C10, .data, e_breakable]
      - [0x27D60, data]
      - [0x442E0, .data, header]
      - [0x44320, .data, d_prize_drops]
      - [0x44338, .data, d_water_data]
      - [0x44370, .data, e_water_fg]
      - [0x443A8, .data, e_clouds]
      - [0x443B8, data]
      - [0x44460, .data, e_lock_camera]
      - [0x444D8, .data, e_explosion_puff_opaque]
      - [0x44548, .data, e_spikes]
      - [0x44568, .data, e_secrets]
      - [0x44608, .data, e_gear_horizontal]
      - [0x44610, .data, e_gear_puzzle]
      - [0x44628, .data, e_gear_small]
      - [0x44640, .data, e_gear_vertical]
      - [0x44680, .rodata, e_life_up]
      - [0x446A0, .rodata, e_red_door]
      - [0x446B8, .rodata, e_valhalla_knight]
      - [0x446D0, .rodata, rnz1_psp/e_collect]
      - [0x44730, .rodata, e_cloaked_knight]
      - [0x44758, .rodata, e_dw_batwings]
      - [0x44770, .rodata, e_darkwing_bat]
      - [0x447B0, .rodata, rnz1_psp/unk_1B6D0]
      - [0x44800, .bss, create_entity]
      - [0x44820, .bss, e_life_up]
      - [0x44828, .bss, st_update]
      - [0x44868, bss, '44868']
      - [0x44870, .bss, rnz1_psp/unk_80E8]
      - [0x44888, .bss, e_dw_batwings]
      - [0x44908, .bss, gen/psp/sprites]
      - [0x44938, bss, '44938']
      - [0x44948, .bss, st_init_psp]
      - [0x44B18, .bss, bossfight]
      - [0x44B28, .bss, e_lock_camera]
      - [0x44B30, .bss, e_gear_puzzle]
  - [0x44B80]
