options:
  platform: psp
  basename: stno0
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/no0.bin
  asm_path: asm/pspeu/st/no0_psp
  asset_path: assets/st/no0
  src_path: src/st
  ld_script_path: build/pspeu/stno0.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.stno0.txt
  undefined_funcs_auto_path: build/pspeu/config/undefined_funcs_auto.pspeu.stno0.txt
  undefined_syms_auto_path: build/pspeu/config/undefined_syms_auto.pspeu.stno0.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  disassemble_all: true
  global_vram_start: 0x8000000
  ld_generate_symbol_per_data_segment: true
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: c52c8da8d1f51ae799f5ca047c75cb802a3b8c5c
segments:
  - [0x0, bin, mwo_header]
  - name: stno0
    type: code
    start: 0x80
    vram:  0x09237700
    bss_start_address: 0x092A1D00
    bss_size: 0x400
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, no0/e_axe_knight]
      - [0x16B8, c, no0/e_skelerang]
      - [0x25D8, c, no0/clock_room]
      - [0x4728, c, no0/e_stage_name]
      - [0x5628, c, no0/e_marionette]
      - [0x72F0, c, no0/e_red_door]
      - [0x85F8, c, no0/st_update]
      - [0x8B30, c, no0/e_plate_lord]
      - [0xCE78, c, no0/e_plate_lord_2]
      - [0xE898, c, no0/e_stone_rose]
      - [0x108B0, c, no0/e_collect]
      - [0x14AF8, c, no0/e_misc]
      - [0x159A0, c, no0/collision]
      - [0x17B78, c, no0/e_diplocephalus]
      - [0x19A28, c, no0/e_diplocephalus_tail]
      - [0x1AF18, c, no0/e_sealed_door]
      - [0x1C478, c, no0/popup]
      - [0x1CA70, c, no0/e_flea_man]
      - [0x1D0C8, c, no0/e_room_fg]
      - [0x1D1E0, c, no0/4C750]
      - [0x1D5F0, c, no0/e_ghost]
      - [0x1DAE0, c, no0/e_skeleton]
      - [0x1E4D8, c, no0/st_common]
      - [0x20060, c, no0/e_slinger]
      - [0x20A08, c, no0/prim_helpers]
      - [0x21470, c, no0/e_ctulhu]
      - [0x23B60, c, no0/e_ouija_table]
      - [0x24708, c, no0/create_entity]
      - [0x256B0, c, no0/st_init_psp]
      - [0x25A40, c, no0/e_breakable]
      - [0x25BF0, c, no0/e_elevator]
      - [0x26C10, c, no0/e_room_bg]
      - [0x26DA8, c, no0/e_lock_camera]
      - [0x27538, c, no0/42A34]
      - [0x28120, c, no0/e_explosion_puff_opaque]
      - [0x28770, c, no0/e_particles]
      - [0x29D00, .data, no0/e_axe_knight]
      - [0x29DF0, .data, no0/e_skelerang]
      - [0x29EE0, .data, no0/clock_room]
      - [0x29F58, .data, no0/e_stage_name]
      - [0x2AB78, .data, no0/e_marionette]
      - [0x2AD30, .data, no0/e_red_door]
      - [0x2AD48, .data, no0/st_update]
      - [0x2AD78, .data, no0/e_plate_lord]
      - [0x2AD98, .data, no0/e_stone_rose]
      - [0x2AE80, .data, no0/e_collect]
      - [0x2B3C8, .data, no0/e_misc]
      - [0x2B430, .data, no0/collision]
      - [0x2B808, .data, no0/e_diplocephalus]
      - [0x2B910, .data, no0/e_diplocephalus_tail]
      - [0x2BA28, .data, no0/e_sealed_door]
      - [0x2BB00, .data, no0/e_flea_man]
      - [0x2BB68, .data, no0/e_room_fg]
      - [0x2BC08, .data, no0/4C750]
      - [0x2BC28, .data, no0/e_ghost]
      - [0x2BC48, .data, no0/e_skeleton]
      - [0x2BD50, .data, no0/st_common]
      - [0x2BF50, .data, no0/e_slinger]
      - [0x2C038, .data, no0/e_ctulhu]
      - [0x2C188, .data, no0/e_ouija_table]
      - [0x2C1E8, data]
      - [0x37D48, .data, no0/e_init]
      - [0x380F0, .data, no0/e_red_door_tiles]
      - [0x38120, .data, no0/gen/rooms]
      - [0x38260, .data, no0/e_breakable]
      - [0x38310, data]
      - [0x69F80, .data, no0/header]
      - [0x69FB0, .data, no0/e_elevator]
      - [0x69FE0, .data, no0/d_prize_drops]
      - [0x6A000, .data, no0/e_room_bg]
      - [0x6A180, .data, no0/e_lock_camera]
      - [0x6A1E8, .data, no0/42A34]
      - [0x6A290, .data, no0/e_explosion_puff_opaque]
      - [0x6A300, .data, no0/e_particles]
      - [0x6A380, .rodata, no0/e_axe_knight]
      - [0x6A3A8, .rodata, no0/e_skelerang]
      - [0x6A3F0, .rodata, no0/clock_room]
      - [0x6A430, .rodata, no0/e_marionette]
      - [0x6A460, .rodata, no0/e_red_door]
      - [0x6A478, .rodata, no0/e_plate_lord]
      - [0x6A4D8, .rodata, no0/e_stone_rose]
      - [0x6A500, .rodata, no0/e_collect]
      - [0x6A560, .rodata, no0/e_diplocephalus]
      - [0x6A5B8, .rodata, no0/e_diplocephalus_tail]
      - [0x6A5E8, .rodata, no0/e_sealed_door]
      - [0x6A600, .rodata, no0/e_skeleton]
      - [0x6A620, .rodata, no0/e_slinger]
      - [0x6A640, .rodata, no0/e_ctulhu]
      - {start: 0x6A680, type: .bss, vram: 0x092A1D00, name: no0/clock_room}
      - {start: 0x6A680, type: .bss, vram: 0x092A1D18, name: no0/st_update}
      - {start: 0x6A680, type: .bss, vram: 0x092A1D58, name: no0/e_plate_lord}
      - {start: 0x6A680, type: .bss, vram: 0x092A1D60, name: no0/e_plate_lord_2}
      - {start: 0x6A680, type: .bss, vram: 0x092A1D68, name: no0/e_collect}
      - {start: 0x6A680, type: .bss, vram: 0x092A1D88, name: no0/e_sealed_door}
      - {start: 0x6A680, type: .bss, vram: 0x092A1D90, name: no0/create_entity}
      - {start: 0x6A680, type: bss, vram: 0x092A1DB0, name: bss0}
      - {start: 0x6A680, type: .bss, vram: 0x092A1DC0, name: no0/st_init_psp}
      - {start: 0x6A680, type: .bss, vram: 0x092A1FC8, name: no0/e_breakable}
      - {start: 0x6A680, type: .bss, vram: 0x092A1FD8, name: no0/e_room_bg}
      - {start: 0x6A680, type: .bss, vram: 0x092A20A0, name: no0/e_lock_camera}
  - [0x6AA00]
