options:
  platform: psx
  basename: stcat
  base_path: ..
  build_path: build/us
  target_path: disks/us/ST/CAT/CAT.BIN
  asm_path: asm/us/st/cat
  asset_path: assets/st/cat
  src_path: src/st/cat
  ld_script_path: build/us/stcat.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.stcat.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.stcat.txt
  undefined_syms_auto_path: config/undefined_syms_auto.us.stcat.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: us_$VRAM
  nonmatchings_path: nonmatchings
  disassemble_all: true
  section_order:
    - .data
    - .rodata
    - .text
    - .bss
    - .sbss
  ld_bss_is_noload: false
  disasm_unknown: true
  global_vram_start: 0x80010000
  ld_generate_symbol_per_data_segment: true
sha1: 02ac6d5a2cd2db5a402aa9ceaab98574539c095d
segments:
  - name: stcat
    type: code
    start: 0x0
    vram: 0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, data]
      - [0xFCC, .data, e_init]
      - [0x1320, data]
      - [0x1358, .data, e_lock_camera]
      - [0x13D8, .data, e_breakable]
      - [0x14F8, data] # unk_3732C/func_us_801B7B64
      - [0x14FC, .data, e_spikes]
      - [0x1518, data]
      - [0x1798, .data, st_update]
      - [0x17C4, .data, st_collision]
      - [0x1B84, .data, e_red_door]
      - [0x1B9C, .data, st_common]
      - [0x1D9C, .data, e_misc]
      - [0x1E50, .data, e_collect]
      - [0x21A4, data]
      - [0x22D4, .data, e_discus_lord]
      - [0x23F0, .data, e_hellfire_beast]
      - [0x24C8, .data, e_particles]
      - [0x2548, .data, e_room_fg]
      - [0x25D4, .data, e_lossoth]
      - [0x26BC, .data, e_grave_keeper]
      - [0x2770, .data, e_tombstone]
      - [0x278C, .data, en_gremlin]
      - [0x27DC, .data, e_slime]
      - [0x2814, .data, e_wereskeleton]
      - [0x2990, .data, en_thornweed_corpseweed]
      - [0x2A48, .data, e_blood_skeleton]
      - [0x2AF0, data]
      - [0x366D8, .rodata, unk_3732C]
      - [0x36708, .rodata, unk_3872C]
      - [0x36868, .rodata, e_red_door]
      - [0x36880, .rodata, e_collect]
      - [0x36954, .rodata, unk_44C7C]
      - [0x36A5C, .rodata, e_stage_name]
      - [0x36A90, .rodata, e_discus_lord]
      - [0x36B14, .rodata, e_hellfire_beast]
      - [0x36BB8, .rodata, giantbro_helpers]
      - [0x36C18, .rodata, e_lossoth]
      - [0x36C70, .rodata, e_grave_keeper]
      - [0x36CA8, .rodata, en_gremlin]
      - [0x36CB4, .rodata, e_slime]
      - [0x36D20, .rodata, e_wereskeleton]
      - [0x36DA4, .rodata, en_thornweed_corpseweed]
      - [0x36DE0, .rodata, e_blood_skeleton]
      - [0x36DF4, .rodata, prim_helpers]
      - [0x36DFC, c, e_room_bg]
      - [0x36EC4, c, e_lock_camera]
      - [0x37080, c, e_breakable]
      - [0x3732C, c, unk_3732C]
      - [0x37F2C, c, e_spikes]
      - [0x3872C, c, unk_3872C]
      - [0x3B6A4, c, st_update]
      - [0x3BAD8, c, st_collision]
      - [0x3D294, c, create_entity]
      - [0x3DE0C, c, e_red_door]
      - [0x3EABC, c, st_common]
      - [0x3FF6C, c, e_misc]
      - [0x42308, c, e_collect]
      - [0x44C7C, c, unk_44C7C]
      - [0x492E8, c, e_stage_name]
      - [0x4A13C, c, unk_4A13C]
      - [0x4A2A4, c, e_discus_lord]
      - [0x4BE14, c, e_hellfire_beast]
      - [0x4E228, c, e_particles]
      - [0x4EA6C, c, e_room_fg]
      - [0x4EB58, c, popup]
      - [0x4EE88, c, giantbro_helpers]
      - [0x4F87C, c, e_lossoth]
      - [0x5121C, c, e_grave_keeper]
      - [0x52060, c, e_tombstone]
      - [0x522E4, c, en_gremlin]
      - [0x52B3C, c, e_slime]
      - [0x549F8, c, e_wereskeleton]
      - [0x55748, c, en_thornweed_corpseweed]
      - [0x56C70, c, e_blood_skeleton]
      - [0x57054, c, prim_helpers]
      - [0x57884, .bss, create_entity]
      - [0x57894, bss]
      - [0x58504, .bss, giantbro_helpers]
      - [0x58580, .bss, e_collect]
  - [0x585C0]
