options:
  platform: psp
  basename: stno1
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/no1.bin
  asm_path: asm/pspeu/st/no1_psp
  asset_path: assets/st/no1
  src_path: src/st/no1
  ld_script_path: build/pspeu/stno1.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.stno1.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.pspeu.stno1.txt
  undefined_syms_auto_path: config/undefined_syms_auto.pspeu.stno1.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  include_macro_inc: false
  disassemble_all: true
  global_vram_start: 0x8000000
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: 7f647498c74c5fc8adbb25a6fa70a3449587df16
segments:
  - [0x0, bin, mwo_header]
  - name: stno1
    type: code
    start: 0x80
    vram:  0x09237700
    bss_size: 0x400
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, 80]
      - [0x2CA80, data]
      - [0x62B00, .rodata, 80]
      - {type: bss, vram: 0x929A480}
  - [0x62E00]
