options:
  platform: psp
  basename: bobo4
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/bo4.bin
  asm_path: asm/pspeu/boss/bo4_psp
  asset_path: assets/boss/bo4
  src_path: src/boss/bo4
  ld_script_path: build/pspeu/bobo4.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.bobo4.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.pspeu.bobo4.txt
  undefined_syms_auto_path: config/undefined_syms_auto.pspeu.bobo4.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  disassemble_all: true
  global_vram_start: 0x8000000
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: 3db4548a368521efaedeb62bb99d6993116b3a28
segments:
  - [0x0, bin, mwo_header]
  - name: bobo4
    type: code
    start: 0x80
    vram:  0x09237700
    bss_size: 0x1400
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, 80]
      - [0x27580, data]
      - [0x33E80, .rodata, 80]
      - {type: bss, vram: 0x926BA80}
  - [0x34400]
