options:
  platform: psp
  basename: borbo4
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/rbo4.bin
  asm_path: asm/pspeu/boss/rbo4_psp
  asset_path: assets/boss/rbo4
  src_path: src/boss
  ld_script_path: build/pspeu/borbo4.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.borbo4.txt
  undefined_funcs_auto_path: build/pspeu/config/undefined_funcs_auto.pspeu.borbo4.txt
  undefined_syms_auto_path: build/pspeu/config/undefined_syms_auto.pspeu.borbo4.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  disassemble_all: true
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  global_vram_start: 0x08000000
  ld_generate_symbol_per_data_segment: true
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: 3d7fc28620aa0d2334770e5b817f652f7428e798
segments:
  - [0x0, bin, mwo_header]
  - name: borbo4
    type: code
    start: 0x80
    vram: 0x09237700
    bss_start_address: 0x09259A80
    bss_size: 0x180
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, rbo4/create_entity]
      - [0x1028, c, rbo4/e_life_up]
      - [0x1CA8, c, rbo4/e_stage_name]
      - [0x2B28, c, rbo4/e_red_door]
      - [0x2C10, c, rbo4/e_red_door]
      - [0x3E30, c, rbo4/st_update]
      - [0x4D80, c, rbo4/e_particles]
      - [0x58F8, c, rbo4_psp/unk_58F8]
      - [0x59D0, c, rbo4/e_collect]
      - [0x9B40, c, rbo4/e_misc]
      - [0xA248, c, rbo4/collision]
      - [0xC420, c, rbo4/popup]
      - [0xCA18, c, rbo4/e_room_fg]
      - [0xCB30, c, rbo4/st_common]
      - [0xDC60, c, rbo4/prim_helpers]
      - [0xE3A0, c, rbo4_psp/unk_E3A0]
      - [0xE858, c, rbo4_psp/st_init]
      - [0xE968, c, rbo4_psp/unk_E968]
      - [0xFBA8, c, rbo4/e_lock_camera]
      - [0xFE08, c, rbo4_psp/unk_FE08]
      - [0x10800, .data, rbo4/e_life_up]
      - [0x10850, .data, rbo4/e_red_door]
      - [0x10868, .data, rbo4/st_update]
      - [0x10898, data, '10898']
      - [0x10898, .data, rbo4/e_particles]
      - [0x10918, .data, rbo4/e_collect]
      - [0x10E60, data, 10E60]
      - [0x10EB0, .data, rbo4/collision]
      - [0x11288, .data, rbo4/e_room_fg]
      - [0x11328, data, '11328']
      - [0x15FD8, .data, rbo4/e_red_door_tiles]
      - [0x15FE8, data, 15FE8]
      - [0x15FE8, data, rbo4/e_init]
      - [0x16108, data]
      - [0x21F90, .data, rbo4/header]
      - [0x21FC0, data]
      - [0x22130, .data, rbo4/e_lock_camera]
      - [0x221A8, data, 221A8]
      - [0x22280, .rodata, rbo4/e_life_up]
      - [0x222A0, .rodata, rbo4/e_red_door]
      - [0x222B8, .rodata, rbo4/e_collect]
      - [0x22318, .rodata, rbo4_psp/unk_E3A0]
      - [0x22338, .rodata, rbo4_psp/unk_E968]
      - [0x22368, .rodata, rbo4_psp/unk_FE08]
      - [0x22400, .bss, rbo4/create_entity]
      - [0x22420, .bss, rbo4/e_life_up]
      - [0x22428, .bss, rbo4/st_update]
      - [0x22468, bss, '22468']
      - [0x22470, .bss, rbo4_psp/unk_58F8]
      - [0x22488, bss, '22488']
      - [0x22548, .bss, rbo4/d_prize_drops]
      - [0x22550, bss, '22550']
      - [0x22550, .bss, rbo4/e_lock_camera]
      - [0x22558, bss, '22558']
  - [0x22580]
