options:
  platform: psp
  basename: stno1
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/no1.bin
  asm_path: asm/pspeu/st/no1_psp
  asset_path: assets/st/no1
  src_path: src/st
  ld_script_path: build/pspeu/stno1.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.stno1.txt
  undefined_funcs_auto_path: build/pspeu/config/undefined_funcs_auto.pspeu.stno1.txt
  undefined_syms_auto_path: build/pspeu/config/undefined_syms_auto.pspeu.stno1.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  disassemble_all: true
  global_vram_start: 0x8000000
  ld_generate_symbol_per_data_segment: true
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: 7f647498c74c5fc8adbb25a6fa70a3449587df16
segments:
  - [0x0, bin, mwo_header]
  - name: stno1
    type: code
    start: 0x80
    vram:  0x09237700
    bss_start_address: 0x0929A480
    bss_size: 0x400
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, no1_psp/create_entity]
      - [0x1028, c, no1_psp/e_blue_axe_knight]
      - [0x33D8, c, no1_psp/e_bone_archer]
      - [0x4590, c, no1_psp/e_stage_name]
      - [0x5490, c, no1_psp/st_update]
      - [0x59C8, c, no1_psp/59C8]
      - [0x6068, c, no1_psp/e_armor_lord]
      - [0x9300, c, no1_psp/e_particles]
      - [0xA890, c, no1_psp/e_collect]
      - [0xEAE0, c, no1_psp/e_misc]
      - [0xF850, c, no1_psp/collision]
      - [0x11A28, c, no1_psp/e_mist_door]
      - [0x11CB0, c, no1_psp/popup]
      - [0x122A8, c, no1_psp/e_room_fg]
      - [0x123C0, c, no1_psp/e_skeleton_ape]
      - [0x13568, c, no1_psp/e_bone_musket]
      - [0x14468, c, no1_psp/e_skeleton]
      - [0x14E60, c, no1_psp/st_common]
      - [0x169E8, c, no1/prim_helpers]
      - [0x174B8, c, no1_psp/e_sword_lord]
      - [0x18CF0, c, no1_psp/e_wereskeleton]
      - [0x1A048, c, no1_psp/e_spear_guard]
      - [0x1B410, c, no1_psp/1B410]
      - [0x1CB18, c, no1_psp/e_wall_chicken_secret]
      - [0x1E210, c, no1_psp/st_init_psp]
      - [0x1E630, c, no1_psp/1E630]
      - [0x1FF98, c, no1_psp/e_breakable]
      - [0x20858, c, no1_psp/e_red_door]
      - [0x21D20, c, no1_psp/21D20]
      - [0x23408, c, no1_psp/23408]
      - [0x24FA8, c, no1_psp/24FA8]
      - [0x25158, c, no1/e_chair]
      - [0x25668, c, no1_psp/25668]
      - [0x25768, c, no1_psp/e_mouse]
      - [0x25BC0, c, no1_psp/e_room_bg]
      - [0x25DD0, c, no1_psp/e_lock_camera]
      - [0x26030, c, no1_psp/26030]
      - [0x27B60, c, no1_psp/27B60]
      - [0x292B0, c, no1_psp/292B0]
      - [0x2B548, c, no1/unused]
      - [0x2B568, c, no1_psp/2B568]
      - [0x2C580, c, no1/e_medusa_head]
      - [0x2CA80, data, no1_psp/e_blue_axe_knight]
      - [0x2CC60, data, no1_psp/e_bone_archer]
      - [0x2CDF8, data, no1_psp/e_stage_name]
      - [0x2D7B0, data, no1_psp/st_update]
      - [0x2D7E0, data, no1_psp/59C8]
      - [0x2D838, data, no1_psp/e_armor_lord]
      - [0x2D9F8, data, no1_psp/e_particles]
      - [0x2DA78, data, no1_psp/e_collect]
      - [0x2DFC0, data, no1_psp/e_misc]
      - [0x2E030, data, no1_psp/collision]
      - [0x2E408, data, no1_psp/e_mist_door]
      - [0x2E590, data, no1_psp/e_room_fg]
      - [0x2E630, data, no1_psp/e_skeleton_ape]
      - [0x2E7F0, data, no1_psp/e_bone_musket]
      - [0x2E8E8, data, no1_psp/e_skeleton]
      - [0x2E9F0, data, no1_psp/st_common]
      - [0x2EBF0, data, no1_psp/e_sword_lord]
      - [0x2ED60, data, no1_psp/e_wereskeleton]
      - [0x2EEC0, data, no1_psp/e_spear_guard]
      - [0x2F1A0, data, no1_psp/1B410]
      - [0x2F238, data, no1_psp/e_wall_chicken_secret]
      - [0x2F370, data]
      - [0x3DBA0, .data, no1/e_init]
      - [0x3DFA8, data]
      - [0x3E068, data, no1_psp/1E630]
      - [0x3E0E0, data, no1_psp/e_breakable]
      - [0x3E228, data]
      - [0x600B8, data, no1_psp/e_red_door]
      - [0x600D0, .data, no1/e_red_door_tiles]
      - [0x60130, data, no1_psp/21D20]
      - [0x60178, data, no1_psp/23408]
      - [0x601B0, data, no1_psp/24FA8]
      - [0x601F0, .data, no1/e_chair]
      - [0x60208, .data, no1/d_prize_drops]
      - [0x60218, data, no1_psp/25668]
      - [0x602A8, data, no1_psp/e_mouse]
      - [0x602F0, data, no1_psp/e_room_bg]
      - [0x60448, data, no1_psp/e_lock_camera]
      - [0x604C0, data, no1_psp/26030]
      - [0x607A8, data, no1_psp/27B60]
      - [0x62550, data, no1_psp/292B0]
      - [0x62608, data, no1_psp/2B568]
      - [0x62A50, .data, no1/e_medusa_head]
      - [0x62B00, .rodata, no1_psp/e_blue_axe_knight]
      - [0x62B28, .rodata, no1_psp/e_armor_lord]
      - [0x62B78, .rodata, no1_psp/e_collect]
      - [0x62BD8, .rodata, no1_psp/e_skeleton_ape]
      - [0x62BF8, .rodata, no1_psp/e_bone_musket]
      - [0x62C20, .rodata, no1_psp/e_skeleton]
      - [0x62C40, .rodata, no1_psp/e_spear_guard]
      - [0x62C78, .rodata, no1_psp/1B410]
      - [0x62CA8, .rodata, no1_psp/e_wall_chicken_secret]
      - [0x62CC8, .rodata, no1_psp/1E630]
      - [0x62CE8, .rodata, no1_psp/e_red_door]
      - [0x62D00, .rodata, no1_psp/23408]
      - [0x62D20, .rodata, no1_psp/26030]
      - [0x62D40, .rodata, no1_psp/27B60]
      - [0x62D60, .rodata, no1_psp/2B568]
      - [0x62E00, bss]
  - [0x63200]
