options:
  platform: psx
  basename: strno0
  base_path: ..
  build_path: build/us
  target_path: disks/us/ST/RNO0/RNO0.BIN
  asm_path: asm/us/st/rno0
  asset_path: assets/st/rno0
  src_path: src/st/rno0
  ld_script_path: build/us/strno0.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.strno0.txt
  undefined_funcs_auto_path: build/us/config/undefined_funcs_auto.us.strno0.txt
  undefined_syms_auto_path: build/us/config/undefined_syms_auto.us.strno0.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: us_$VRAM
  disassemble_all: true
  section_order:
    - .data
    - .rodata
    - .text
    - .bss
    - .sbss
  ld_bss_is_noload: false
  disasm_unknown: true
  global_vram_start: 0x80010000
  ld_generate_symbol_per_data_segment: true
sha1: 125003c7fe5d3510fddee22d4f5e5390fe507acf
segments:
  - name: strno0
    type: code
    start: 0x0
    vram: 0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .data, header]
      - [0x2C, data]
      - [0x8FC, .data, e_init]
      - [0xC18, data]
      - [0x35B00, .rodata, unk_39A8C]
      - [0x35B18, .rodata, e_collect]
      - [0x35BEC, .rodata, e_clock_room]
      - [0x35C2C, .rodata, e_armor_lord_guardian]
      - [0x35CE8, .rodata, e_stage_name]
      - [0x35D1C, .rodata, e_floor_trap]
      - [0x35D28, .rodata, e_thornweed_corpseweed]
      - [0x35D64, .rodata, e_stone_skull]
      - [0x35D70, .rodata, unk_48100]
      - [0x35DD0, .rodata, giantbro_helpers]
      - [0x35E30, .rodata, e_hammer]
      - [0x35EDC, .rodata, e_gurkha]
      - [0x35FC8, .rodata, e_blade]
      - [0x36048, .rodata, e_subweapon_container]
      - [0x36054, .rodata, unk_4F968]
      - [0x36200, .rodata, e_medusa_head]
      - [0x36208, .rodata, unk_5289C]
      - [0x36220, .rodata, prim_helpers]
      - [0x36228, c, e_room_bg]
      - [0x36328, c, e_lock_camera]
      - [0x364E4, c, e_breakable]
      - [0x36654, c, e_elevator]
      - [0x36E58, c, e_background_clock_pendulum]
      - [0x37104, c, func_us_801b7104]
      - [0x37324, c, st_update]
      - [0x37758, c, collision]
      - [0x38F14, c, create_entity]
      - [0x39A8C, c, unk_39A8C]
      - [0x3A73C, c, st_common]
      - [0x3BBEC, c, e_collect]
      - [0x3E55C, c, e_misc]
      - [0x408F8, c, e_background_pillars]
      - [0x40C54, c, e_clock_room]
      - [0x42340, c, e_armor_lord_guardian]
      - [0x4499C, c, e_stage_name]
      - [0x457F0, c, e_particles]
      - [0x46034, c, e_room_fg]
      - [0x46120, c, popup]
      - [0x46450, c, e_floor_trap]
      - [0x469FC, c, e_thornweed_corpseweed]
      - [0x47F24, c, e_stone_skull]
      - [0x48100, c, unk_48100]
      - [0x4992C, c, giantbro_helpers]
      - [0x4A7A0, c, e_hammer]
      - [0x4BA58, c, e_gurkha]
      - [0x4CCEC, c, e_blade]
      - [0x4E230, c, e_subweapon_container]
      - [0x4EB40, c, e_gorgon]
      - [0x4F968, c, unk_4F968]
      - [0x524C8, c, e_medusa_head]
      - [0x5289C, c, unk_5289C]
      - [0x53688, c, prim_helpers]
      - [0x53EB8, bss]
  - [0x54B8C]
