options:
  platform: psp
  basename: strtop
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/rtop.bin
  asm_path: asm/pspeu/st/rtop_psp
  asset_path: assets/st/rtop
  src_path: src/st/rtop
  ld_script_path: build/pspeu/strtop.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.strtop.txt
  undefined_funcs_auto_path: build/pspeu/config/undefined_funcs_auto.pspeu.strtop.txt
  undefined_syms_auto_path: build/pspeu/config/undefined_syms_auto.pspeu.strtop.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  disassemble_all: true
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  global_vram_start: 0x08000000
  ld_generate_symbol_per_data_segment: true
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: b4b18be96e586cbab0678c0daf1e9dd93f235286
segments:
  - [0x0, bin, mwo_header]
  - name: strtop
    type: code
    start: 0x80
    vram: 0x09237700
    bss_start_address: 0x09267C00
    bss_size: 0x180
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, create_entity]
      - [0x1028, c, e_skull_lord]
      - [0x24A0, c, e_stage_name]
      - [0x3320, c, e_red_door]
      - [0x4628, c, st_update]
      - [0x4B60, c, e_tombstone]
      - [0x58A8, c, e_particles]
      - [0x6420, c, e_collect]
      - [0xA670, c, e_misc]
      - [0xAD78, c, collision]
      - [0xCF50, c, popup]
      - [0xD548, c, e_room_fg]
      - [0xD660, c, e_yorick]
      - [0xE340, c, st_common]
      - [0xF9A0, c, prim_helpers]
      - [0x100E0, c, st_init_psp]
      - [0x10290, c, e_breakable]
      - [0x10BD0, c, e_clouds]
      - [0x11508, c, e_elevator]
      - [0x12820, c, e_secret_stairs]
      - [0x13098, c, e_lion_lamp]
      - [0x134F0, c, e_room_bg]
      - [0x13600, c, e_lock_camera]
      - [0x13D80, c, e_warp_trigger]
      - [0x13E98, c, e_clock_tower]
      - [0x14430, c, e_breakable_wall]
      - [0x14800, .data, e_skull_lord]
      - [0x14820, .data, e_red_door]
      - [0x14838, .data, st_update]
      - [0x14868, data, 14868]
      - [0x14868, .data, e_tombstone]
      - [0x14878, data, 14878]
      - [0x14878, .data, e_particles]
      - [0x148F8, .data, e_collect]
      - [0x14E40, .data, e_misc]
      - [0x14E90, data, 14E90]
      - [0x14E90, .data, collision]
      - [0x15268, .data, e_room_fg]
      - [0x15308, .data, e_yorick]
      - [0x153C8, data]
      - [0x17578, .data, e_red_door_tiles]
      - [0x175A8, .data, e_init]
      - [0x17740, data]
      - [0x177C8, .data, e_breakable]
      - [0x17910, .data, e_clouds]
      - [0x17A08, data]
      - [0x2FE80, .data, header]
      - [0x2FEC0, .data, e_elevator]
      - [0x2FEE8, .data, d_prize_drops]
      - [0x2FF28, .data, e_secret_stairs]
      - [0x2FF98, .data, e_lion_lamp]
      - [0x2FFD0, .data, e_room_bg]
      - [0x30010, .data, e_lock_camera]
      - [0x30060, .data, e_warp_trigger]
      - [0x30068, data, 30068]
      - [0x30068, .data, e_clock_tower]
      - [0x30420, .data, e_breakable_wall]
      - [0x3042C, data]
      - [0x30480, .rodata, e_red_door]
      - [0x30498, .rodata, e_collect]
      - [0x304F8, .rodata, e_yorick]
      - [0x30580, .bss, create_entity]
      - [0x305A0, .bss, st_update]
      - [0x305E0, .bss, e_collect]
      - [0x30600, bss, 30600]
      - [0x30610, .bss, st_init_psp]
      - [0x306D8, .bss, e_clouds]
      - [0x306E0, .bss, e_elevator]
  - [0x30700]
