options:
  platform: psp
  basename: strnz0
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/rnz0.bin
  asm_path: asm/pspeu/st/rnz0_psp
  asset_path: assets/st/rnz0
  src_path: src/st/rnz0
  ld_script_path: build/pspeu/strnz0.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.strnz0.txt
  undefined_funcs_auto_path: build/pspeu/config/undefined_funcs_auto.pspeu.strnz0.txt
  undefined_syms_auto_path: build/pspeu/config/undefined_syms_auto.pspeu.strnz0.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  disassemble_all: true
  global_vram_start: 0x8000000
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: 56bbb04006e93d41b990b4afe11f6a89bd03294c
segments:
  - [0x0, bin, mwo_header]
  - name: strnz0
    type: code
    start: 0x80
    vram:  0x09237700
    bss_size: 0x280
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, rnz0_psp/e_unk1B-1E]
      - [0x2730, c, create_entity] # create_entity
      - [0x3718, c, rnz0_psp/3718] # en_salem_witch
      - [0x5860, c, rnz0_psp/5860]
      - [0x9308, c, e_stage_name] # e_stage_name
      - [0xA188, c, e_red_door] # e_red_door
      - [0xB490, c, st_update] # st_update
      - [0xB9C8, c, e_particles] # e_particles
      - [0xCF58, c, rnz0_psp/CF58]
      - [0xE248, c, e_collect]
      - [0x12498, c, e_misc]
      - [0x12E18, c, collision] # collision
      - [0x14FF0, c, rnz0_psp/14FF0]
      - [0x1AB90, c, popup] # popup
      - [0x1B188, c, e_room_fg] # e_room_fg
      - [0x1B2A0, c, st_common]
      - [0x1C900, c, prim_helpers]
      - [0x1D3F8, c, rnz0_psp/e_unk1A]
      - [0x1DC08, c, rnz0_psp/1DC08]
      - [0x1F2A8, c, rnz0_psp/st_init_psp] # st_init_chi
      - [0x1F530, c, rnz0_psp/1F530]
      # - [0x1FEB8, c, rnz0_psp/80] # e_room_bg
      # - [0x1FFC8, c, rnz0_psp/80] # e_lock_camera
      # - [0x20228, c, rnz0_psp/80]
      - [0x20F00, data]
      - [0x213C8, .data, e_red_door]
      - [0x213E0, .data, st_update]
      - [0x21410, .data, e_particles]
      - [0x21490, data]
      - [0x214C8, .data, e_collect]
      - [0x21A10, data]
      - [0x21A60, .data, collision]
      - [0x21E38, data]
      - [0x220A0, .data, e_room_fg]
      - [0x22140, data]
      - [0x4A158, .data, header]
      - [0x4A198, data]
      - [0x4A400, .rodata, rnz0_psp/e_unk1B-1E]
      - [0x4A420, .rodata, rnz0_psp/5860]
      - [0x4A478, .rodata, e_red_door]
      - [0x4A490, .rodata, rnz0_psp/CF58]
      - [0x4A520, .rodata, rnz0_psp/14FF0]
      - [0x4A580, .bss, create_entity]
      - [0x4A5A0, .bss, st_update]
      - [0x4A5E0, .bss, e_collect]
      - [0x4A600, bss, 4A600]
      - [0x4A620, .bss, rnz0_psp/st_init_psp]
      - [0x4A778, bss, 4A778]

  - [0x4A580]
