options:
  platform: psx
  basename: stdai
  base_path: ..
  build_path: build/us
  target_path: disks/us/ST/DAI/DAI.BIN
  asm_path: asm/us/st/dai
  asset_path: assets/st/dai
  src_path: src/st/dai
  ld_script_path: build/us/stdai.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.stdai.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.stdai.txt
  undefined_syms_auto_path: config/undefined_syms_auto.us.stdai.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: us_$VRAM
  nonmatchings_path: nonmatchings
  disassemble_all: true
  section_order:
    - .data
    - .rodata
    - .text
    - .bss
    - .sbss
  ld_bss_is_noload: false
  disasm_unknown: true
  global_vram_start: 0x80010000
  ld_generate_symbol_per_data_segment: true
sha1: 4189c2f709ce229e48f5cd93a20af40579bda26b
segments:
  - name: stdai
    type: code
    start: 0x0
    vram: 0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .data, header]
      - [0x2C, data] # DAI_spriteBanks
      #- [0x818, .data, e_init]
      #- [0xAC4, data]
      - [0xB0C, .data, st_debug]
      - [0xB8C, data]
      - [0x3FE3C, .rodata, e_breakable]
      - [0x3FE5C, .rodata, unk_408AC]
      #- [0x3FEA8, .rodata, unk_408AC] # Splat suggested
      - [0x3FF24, .rodata, e_cutscene]
      - [0x3FFC0, .rodata, unk_458C4]
      - [0x3FFE0, .rodata, e_red_door]
      - [0x3FFF8, .rodata, e_collect]
      - [0x400CC, .rodata, e_stage_name]
      - [0x40100, .rodata, unk_51010]
      #- [0x4014C, .rodata, unk_51010] # Splat suggested
      #- [0x40160, .rodata, unk_51010] # Splat suggested
      - [0x4018C, .rodata, e_bat]
      - [0x401A0, .rodata, unk_53FD8]
      - [0x401D0, .rodata, e_skelerang]
      - [0x4023C, .rodata, unk_550E4]
      - [0x402D0, .rodata, e_magically_sealed_door]
      - [0x402E8, .rodata, unk_59168]
      - [0x402F0, c, st_debug]
      - [0x40574, c, e_breakable]
      - [0x408AC, c, unk_408AC]
      - [0x43F48, c, e_cutscene]
      - [0x458C4, c, unk_458C4]
      - [0x45F88, c, st_update]
      - [0x463BC, c, st_collision]
      - [0x47B78, c, create_entity]
      - [0x486F0, c, e_red_door]
      - [0x493A0, c, st_common]
      - [0x4A850, c, e_collect]
      - [0x4D1C0, c, e_misc]
      - [0x4F55C, c, e_stage_name]
      - [0x503B0, c, e_particles]
      - [0x50BF4, c, e_room_fg]
      - [0x50CE0, c, popup]
      - [0x51010, c, unk_51010]
      - [0x53D8C, c, e_bat]
      - [0x53FD8, c, unk_53FD8]
      - [0x5468C, c, e_skelerang]
      - [0x550E4, c, unk_550E4]
      - [0x573E4, c, e_magically_sealed_door]
      - [0x581D0, c, e_mist_door]
      - [0x582B8, c, prim_helpers]
      - [0x58AE8, c, e_clouds]
      - [0x59168, c, unk_59168]
      - [0x5A69C, bss]
      - [0x5A6FC, .bss, create_entity]
      - [0x5A70C, sbss]
  - [0x5B404]
