// SPDX-License-Identifier: AGPL-3.0-or-later
#include "mad.h"

u16 OVL_EXPORT(PrizeDrops)[] = {
    ITEMDROP_HEART_VESSEL, ITEMDROP_LIFE_VESSEL, ITEMDROP_CUTLASS, ITEMDROP_SILVER_PLATE, ITEMDROP_HEART_VESSEL, ITEMDROP_LEATHER_SHIELD, ITEMDROP_LIFE_VESSEL, ITEMDROP_FLAMBERGE,
    ITEMDROP_LEATHER_HAT, ITEMDROP_MORMEGIL, ITEMDROP_HEALING_MAIL, ITEMDROP_LIFE_VESSEL, ITEMDROP_HEART_VESSEL, ITEMDROP_PENTAGRAM, ITEMDROP_GODDESS_SHIELD, ITEMDROP_POWER_OF_SIRE,
    ITEMDROP_KARMA_COIN, ITEMDROP_MAGIC_MISSILE, ITEMDROP_AXE_LORD_ARMOR, ITEMDROP_TWILIGHT_CLOAK, ITEMDROP_FIRE_SHIELD, ITEMDROP_RESIST_THUNDER, ITEMDROP_POTION, ITEMDROP_MAGIC_MISSILE,
    ITEMDROP_PENTAGRAM, ITEMDROP_STONE_SWORD, ITEMDROP_FIRE_MAIL, ITEMDROP_STAR_FLAIL, ITEMDROP_RUBY_CIRCLET, ITEMDROP_MOJO_MAIL, ITEMDROP_HEART_VESSEL, ITEMDROP_LIFE_VESSEL,
    ITEMDROP_STAR_FLAIL, ITEMDROP_GLADIUS, ITEMDROP_IRON_FIST, ITEMDROP_LIFE_VESSEL, ITEMDROP_LIFE_VESSEL, ITEMDROP_HERALD_SHIELD, ITEMDROP_DARK_ARMOR, ITEMDROP_NONE,
};
