// SPDX-License-Identifier: AGPL-3.0-or-later
#include "rtop.h"

u16 OVL_EXPORT(PrizeDrops)[] = {
    ITEMDROP_SWORD_OF_DAWN, ITEMDROP_IRON_BALL, ITEMDROP_ZIRCON, ITEMDROP_ZIRCON, ITEMDROP_BASTARD_SWORD, ITEMDROP_LIFE_VESSEL, ITEMDROP_HEART_VESSEL, ITEMDROP_LIFE_VESSEL, ITEMDROP_HEART_VESSEL,
    ITEMDROP_LIFE_VESSEL, ITEMDROP_HEART_VESSEL, ITEMDROP_ROYAL_CLOAK, ITEMDROP_LIFE_VESSEL, ITEMDROP_LIFE_VESSEL, ITEMDROP_LIFE_VESSEL, ITEMDROP_LIFE_VESSEL, ITEMDROP_LIFE_VESSEL, ITEMDROP_RESIST_FIRE,
    ITEMDROP_RESIST_ICE, ITEMDROP_RESIST_THUNDER, ITEMDROP_RESIST_STONE, ITEMDROP_HIGH_POTION, ITEMDROP_GARNET, ITEMDROP_LIGHTNING_MAIL, ITEMDROP_LIBRARY_CARD, ITEMDROP_LIFE_VESSEL, ITEMDROP_LIFE_VESSEL,
    ITEMDROP_LIFE_VESSEL, ITEMDROP_LIFE_VESSEL, ITEMDROP_LIFE_VESSEL, ITEMDROP_LIFE_VESSEL, ITEMDROP_LIFE_VESSEL, 0,      0};
