// SPDX-License-Identifier: AGPL-3.0-or-later
#include "warp/warp.h"

#define WARP_LOOKUP_ROW {7, 4, 2, 3, 4, 1, 2, 3, 4, 6, 7, 0}

SaturnRoomPriorities g_WarpRoomPriorities[32] = {
    WARP_LOOKUP_ROW, WARP_LOOKUP_ROW, WARP_LOOKUP_ROW, WARP_LOOKUP_ROW,
    WARP_LOOKUP_ROW, WARP_LOOKUP_ROW, WARP_LOOKUP_ROW, WARP_LOOKUP_ROW,
    WARP_LOOKUP_ROW, WARP_LOOKUP_ROW, WARP_LOOKUP_ROW, WARP_LOOKUP_ROW,
    WARP_LOOKUP_ROW, WARP_LOOKUP_ROW, WARP_LOOKUP_ROW, WARP_LOOKUP_ROW,
    WARP_LOOKUP_ROW, WARP_LOOKUP_ROW, WARP_LOOKUP_ROW, WARP_LOOKUP_ROW,
    WARP_LOOKUP_ROW, WARP_LOOKUP_ROW, WARP_LOOKUP_ROW, WARP_LOOKUP_ROW,
    WARP_LOOKUP_ROW, WARP_LOOKUP_ROW, WARP_LOOKUP_ROW, WARP_LOOKUP_ROW,
    WARP_LOOKUP_ROW, WARP_LOOKUP_ROW, WARP_LOOKUP_ROW, WARP_LOOKUP_ROW,
};

#undef WARP_LOOKUP_ROW
