// SPDX-License-Identifier: AGPL-3.0-or-later
#include "top.h"

u16 OVL_EXPORT(PrizeDrops)[] = {
    ITEMDROP_TURQUOISE,
    ITEMDROP_TURKEY,
    ITEMDROP_FIRE_MAIL,
    ITEMDROP_TYRFING,
    ITEMDROP_SIRLOIN,
    ITEMDROP_TURKEY,
    ITEMDROP_POT_ROAST,
    ITEMDROP_FRANKFURTER,
    ITEMDROP_RESIST_STONE,
    ITEMDROP_RESIST_DARK,
    ITEMDROP_RESIST_HOLY,
    ITEMDROP_PLATINUM_MAIL,
    ITEMDROP_FALCHION,
    ITEMDROP_LIFE_VESSEL,
    ITEMDROP_LIFE_VESSEL,
    ITEMDROP_HEART_VESSEL,
    ITEMDROP_HEART_VESSEL,
    // Cat-Eye Circlet does not appear in TOP, unused?
    ITEMDROP_CAT_EYE_CIRCLET,
    ITEMDROP_HEART_VESSEL,
};
