// SPDX-License-Identifier: AGPL-3.0-or-later
#include "rlib.h"

u16 PrizeDrops[] = {
    ITEMDROP_TURQUOISE,    ITEMDROP_OPAL,         ITEMDROP_LIBRARY_CARD,
    ITEMDROP_RESIST_FIRE,  ITEMDROP_RESIST_ICE,   ITEMDROP_RESIST_STONE,
    ITEMDROP_NEUTRON_BOMB, ITEMDROP_BADELAIRE,    ITEMDROP_STAUROLITE,
    ITEMDROP_ANKH_OF_LIFE, ITEMDROP_ANKH_OF_LIFE, ITEMDROP_ANKH_OF_LIFE,
    ITEMDROP_ANKH_OF_LIFE, ITEMDROP_ANKH_OF_LIFE, ITEMDROP_ANKH_OF_LIFE,
    ITEMDROP_ANKH_OF_LIFE, ITEMDROP_ANKH_OF_LIFE, ITEMDROP_SMALL_HEART,
};
