// SPDX-License-Identifier: AGPL-3.0-or-later
#include "rno4.h"

u16 PrizeDrops[] = {
    ITEMDROP_ALUCARD_SHIELD, ITEMDROP_SHIITAKE,     ITEMDROP_TOADSTOOL,
    ITEMDROP_SHIITAKE,       ITEMDROP_GARNET,       ITEMDROP_BAT_PENTAGRAM,
    ITEMDROP_LIFE_VESSEL,    ITEMDROP_HEART_VESSEL, ITEMDROP_POTION,
    ITEMDROP_SHIITAKE,       ITEMDROP_SHIITAKE,     ITEMDROP_OPAL,
    ITEMDROP_LIFE_VESSEL,    ITEMDROP_DIAMOND,      ITEMDROP_ZIRCON,
    ITEMDROP_HEART_VESSEL,
};
