// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
SET_END(0x80183cb5),
PLAY_SOUND(0x10),
SCRIPT_UNKNOWN_11(),
SET_FLAG(2),
WAIT_FOR_FLAG(1),
SET_POS(60,28),
WAIT_FOR_FLAG(0),
LOAD_PORTRAIT(0x80193ba4,0),
SET_PORTRAIT(1,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x369),
WAIT_FOR_SOUND(),
SET_FLAG(3),
SET_SPEED(3),
'S','o',' ','w','e',' ','m','e','e','t',' ','a','g','a','i','n',',',
LINE_BREAK(),
SET_WAIT(4),
'A','l','u','c','a','r','d','.',
SET_WAIT(48),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x80194924,1),
SET_PORTRAIT(0,129),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x36a),
WAIT_FOR_SOUND(),
SET_SPEED(4),
'I','t',' ','s','e','e','m','s',' ','s','o','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(1,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x36b),
WAIT_FOR_SOUND(),
SET_SPEED(3),
SET_FLAG(4),
'A','s',' ','f','r','i','e','n','d','l','y',' ','a','s',
LINE_BREAK(),
SET_WAIT(4),
'e','v','e','r',',',' ','I',' ','s','e','e','.',
LINE_BREAK(),
SET_WAIT(16),
SET_FLAG(5),
'I','t','\'','s',' ','s','t','r','a','n','g','e','.',' ',
SET_WAIT(32),
SET_FLAG(6),
SET_SPEED(3),
'T','h','i','s',
LINE_BREAK(),
SET_WAIT(4),
'c','a','s','t','l','e',' ','i','s',' ','d','i','f','f','e','r','e','n','t',
LINE_BREAK(),
SET_WAIT(4),
SET_SPEED(2),
't','h','a','n',' ','I',' ','r','e','m','e','m','b','e','r',' ','i','t','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,129),
SET_SPEED(4),
'.','.','.','.','.','.','.','.','.',
LINE_BREAK(),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x36c),
WAIT_FOR_SOUND(),
SET_SPEED(2),
SET_FLAG(7),
'T','h','i','s',' ','c','a','s','t','l','e',' ','i','s',' ','a',
LINE_BREAK(),
SET_WAIT(4),
'c','r','e','a','t','u','r','e',' ','o','f',' ','C','h','a','o','s','.',
LINE_BREAK(),
SET_WAIT(16),
'I','t',' ','m','a','y',' ','t','a','k','e',' ','m','a','n','y',
LINE_BREAK(),
SET_WAIT(4),
'i','n','c','a','r','n','a','t','i','o','n','s','.',
SET_WAIT(56),
NEXT_DIALOG(),
SET_PORTRAIT(1,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x36d),
WAIT_FOR_SOUND(),
SET_SPEED(3),
SET_FLAG(8),
'S','o',' ','I',' ','c','a','n','\'','t',' ','t','r','u','s','t',' ','m','y',
LINE_BREAK(),
SET_WAIT(4),
'm','e','m','o','r','i','e','s',',',' ',
SET_FLAG(9),
'h','u','h','?',
LINE_BREAK(),
SET_WAIT(16),
'O','h',' ','w','e','l','l',',',' ','I','\'','l','l',' ','d','o',' ','m','y',
LINE_BREAK(),
SET_WAIT(8),
SET_FLAG(10),
'b','e','s','t','.',
SET_WAIT(24),
'G','o','o','d',' ','l','u','c','k','.',
SET_FLAG(11),
SET_WAIT(48),
NEXT_DIALOG(),
CLOSE_DIALOG(),
SCRIPT_UNKNOWN_11(),
WAIT_FOR_FLAG(12),
SCRIPT_UNKNOWN_20(0x11),
SET_FLAG(13),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
END_CUTSCENE(),
