// SPDX-License-Identifier: AGPL-3.0-or-later
#include "nz0.h"

u16 OVL_EXPORT(PrizeDrops)[] = {ITEMDROP_HIDE_CUIRASS, ITEMDROP_HEART_VESSEL, ITEMDROP_CLOTH_CAPE, ITEMDROP_LIFE_VESSEL, ITEMDROP_FLAMBERGE, ITEMDROP_BANDANNA,
                                ITEMDROP_SUNGLASSES, ITEMDROP_RESIST_THUNDER, ITEMDROP_LEATHER_SHIELD, ITEMDROP_BASILARD, ITEMDROP_POTION, ITEMDROP_NONE};
