REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
    if ((self->flags & FLAG_DEAD) && (self->step < 3)) {
        PlaySfxPositional(NA_SE_EN_BLOOD_SKELETON_DISASSEMBLES);
        self->hitboxState = 0;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        self->facingLeft = (u32)Random() % 2;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        if (UnkCollisionFunc3(&D_80182694) & 1) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            if (self->facingLeft != 0) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            (GetDistanceToPlayerY() < 48) && (Random() % 4) == 0) {
            self->facingLeft = GetSideToPlayer() % 2 == 0;
REDACTED
REDACTED
        if ((u8)CheckColliderOffsets(&D_801826AC, self->facingLeft) != 2) {
            self->facingLeft ^= 1;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
                self->rotZ = 0;
                self->drawFlags |= 4;
                PlaySfxPositional(NA_SE_EN_BLOOD_SKELETON_REASSEMBLES);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            if ((g_Timer % 3) == 0) {
REDACTED
REDACTED
                    self->rotZ = 0x10;
REDACTED
                    self->rotZ = -0x10;
REDACTED
REDACTED
REDACTED
REDACTED
                self->drawFlags = 0;
                self->rotZ = 0;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
                self->hitboxState = 3;
                self->flags = g_api.enemyDefs[70].flags & 0x1FFFFFFF;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
