REDACTED
#include "sfx.h"
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
    g_CurrentEntity->velocityY += FIX(0.25);
    slograPosX = g_CurrentEntity->posX.i.hi + g_Tilemap.scrollX.i.hi;
REDACTED
    if (g_CurrentEntity->velocityX > 0 && slograPosX > 896) {
        g_CurrentEntity->posX.i.hi = 896 - g_Tilemap.scrollX.i.hi;
REDACTED
REDACTED
    if (g_CurrentEntity->velocityX < 0 && slograPosX < 64) {
        g_CurrentEntity->posX.i.hi = 64 - g_Tilemap.scrollX.i.hi;
REDACTED
REDACTED
    if (g_CurrentEntity->posY.i.hi + g_Tilemap.scrollY.i.hi > 416) {
REDACTED
        g_CurrentEntity->posY.i.hi = 416 - g_Tilemap.scrollY.i.hi;
        g_CurrentEntity->velocityX = 0;
        g_CurrentEntity->velocityY = 0;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        if ((self->hitFlags & 3) && (self->step != SLOGRA_KNOCKBACK)) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
    if ((self->flags & FLAG_DEAD) && (self->step != SLOGRA_DYING)) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        if (self->hitFlags != 0) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            self->facingLeft = (GetSideToPlayer() & 1) ^ 1;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        self->facingLeft = (GetSideToPlayer() & 1) ^ 1;
REDACTED
        if (self->facingLeft != self->ext.GS_Props.flag) {
            self->velocityX = FIX(0.75);
REDACTED
            self->velocityX = FIX(-0.75);
REDACTED
        UnkCollisionFunc2(&D_8018106C);
REDACTED
            if (GetDistanceToPlayerX() < 72) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            if (GetDistanceToPlayerX() > 112) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            PlaySfxPositional(NA_SE_EN_SLOGRA_HISSING);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        if (self->animFrameIdx == 4 && self->animFrameDuration == 0) {
            PlaySfxPositional(NA_SE_EN_SLOGRA_SPEAR_SLASH);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            self->facingLeft = (GetSideToPlayer() & 1) ^ 1;
REDACTED
REDACTED
REDACTED
REDACTED
                PlaySfxPositional(NA_SE_EN_SLOGRA_SPEAR_PROJECTILE);
                newEntity = AllocEntity(g_Entities + 160, g_Entities + 192);
REDACTED
                    CreateEntityFromEntity(
                        E_SLOGRA_SPEAR_PROJECTILE, self, newEntity);
                    if (self->facingLeft != 0) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
                    newEntity->facingLeft = self->facingLeft;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            self->velocityY = FIX(-4);
            if (!(GetSideToPlayer() & 1)) {
                self->velocityX = FIX(-0.5);
REDACTED
                self->velocityX = FIX(0.5);
REDACTED
            PlaySfxPositional(NA_SE_EN_SLOGRA_HURT);
REDACTED
REDACTED
REDACTED
            if (0x18000 > self->velocityY) {
REDACTED
REDACTED
REDACTED
            self->velocityY -= 0x2400;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            self->facingLeft = (GetSideToPlayer() & 1) ^ 1;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        self->facingLeft = (GetSideToPlayer() & 1) ^ 1;
REDACTED
        if (!(self->facingLeft == self->ext.GS_Props.flag)) {
            self->velocityX = FIX(0.75);
REDACTED
            self->velocityX = FIX(-0.75);
REDACTED
REDACTED
        UnkCollisionFunc2(&D_8018106C);
REDACTED
            if (GetDistanceToPlayerX() < 72) {
REDACTED
REDACTED
REDACTED
                if (GetDistanceToPlayerX() > 112) {
REDACTED
REDACTED
REDACTED
REDACTED
            if (GetDistanceToPlayerX() > 112) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        if (self->animFrameIdx == 7 && self->animFrameDuration == 0) {
            PlaySfxPositional(NA_SE_EN_SLOGRA_BEAK_ATTACK);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
                self->velocityX = 0;
                self->velocityY = 0;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            self->velocityY += FIX(0.25);
            if (self->posY.i.hi + g_Tilemap.scrollY.i.hi > 416) {
                self->posY.i.hi = 416 - g_Tilemap.scrollY.i.hi;
                PlaySfxPositional(SFX_DOOR_CLOSE_A); // Slogra Floor Stomp
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            self->hitboxState = 0;
REDACTED
REDACTED
REDACTED
REDACTED
            PlaySfxPositional(NA_SE_EN_SLOGRA_DEATH_EXPLOSION);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            if (!(g_Timer % 4)) {
                newEntity = AllocEntity(&g_Entities[224], &g_Entities[256]);
REDACTED
                    CreateEntityFromEntity(E_EXPLOSION, self, newEntity);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
                CreateEntityFromEntity(E_EXPLOSION, self, newEntity);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        if (g_pads[1].pressed & PAD_CIRCLE) {
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
    self->hitboxOffX = *hitbox++;
    self->hitboxOffY = *hitbox++;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        self->facingLeft = self[-1].facingLeft;
REDACTED
REDACTED
REDACTED
REDACTED
        self->hitboxOffX = *hitbox++;
        self->hitboxOffY = *hitbox++;
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
            self->drawFlags = FLAG_DRAW_ROTZ;
            self->hitboxState = 0;
            if (self->facingLeft != 0) {
                self->velocityX = FIX(-2.25);
REDACTED
                self->velocityX = FIX(2.25);
REDACTED
            self->velocityY = FIX(-4);
REDACTED
            self->flags |= FLAG_DESTROY_IF_OUT_OF_CAMERA;
REDACTED
REDACTED
REDACTED
REDACTED
            self->velocityY += FIX(0.15625);
            self->rotZ += 0x80;
            if (!(self->rotZ & 0xFFF)) {
                PlaySfxPositional(SFX_ARROW_SHOT_A);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
    if (self->flags & FLAG_DEAD) {
REDACTED
REDACTED
            CreateEntityFromEntity(E_EXPLOSION, self, entity);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
        if (self->facingLeft == 0) {
            self->velocityX = FIX(-4);
REDACTED
            self->velocityX = FIX(4);
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
REDACTED
