extern const char D_800DD18C[];

#ifndef _S
#define _S(x) (x)
#endif

const char* g_MenuStr[] = {
    _S("ALUCARD"),
    _S("STR"),
    _S("CON"),
    _S("INT"),
    _S("LCK"),
    _S("EXP"),
    _S("NEXT"),
    _S("GOLD"),
    _S("LEVEL"),
    _S("TIME"),
    _S("ROOMS"),
    _S("KILLS"),
    _S("HP"),
    _S("MP"),
    _S("HEART"),
    _S("STATUS"),
    _S("Button settings"),
    _S("Cloak lining"),
    _S("Cloak color"),
    "\x65\x65\x65\x65\x65\xFF", // locked menu option?
    _S("Exterior"),
    _S("Lining"),
    _S("Right hand"),
    _S("Left hand"),
    _S("Jump"),
    _S("Special"),
    _S("Wolf"),
    _S("Mist"),
    _S("Bat"),
    "\xB6\xB2\xCA\xC2\xFF", // debug in button config?
    _S("Normal"),
    _S("Reverse"),
    _S("Sound"),
    _S("Stereo"),
    _S("Mono"),
    _S("Window color"),
    _S("Time attack"),
    _S("GOOD"),
    _S("POISON"),
    _S("STONE"),
    _S("CURSE"),
    _S("------------------------------"),
    _S("ALUCART"),
    "\xDA\xCD\xFF\x9E\xD9\xFF",
    "\xB9\xB2\xB9\xDD\xC1\xFF",
    _S("alucart"),
    _S("Bat"),
    _S("Ghost"),
    _S("Faerie"),
    _S("Demon"),
    _S("Sword"),
    "\xD6\xB3\xBE\xB2\xFF",     // JP YOUSEI
    "\xCA\xC5\xB1\xB8\xCF\xFF", // JP NOSE DEMON
    _S("Richter defeats Dracula"),
    _S("Defeat Olrox"),
    _S("Defeat Doppleganger 10"),
    _S("Defeat Granfaloon"),
    _S("Defeat Minotaur and Werewolf"),
    _S("Defeat Scylla"),
    _S("Defeat Slogra and Gaibon"),
    _S("Defeat Hippogryph"),
    _S("Defeat Beelzebub"),
    _S("Defeat Succubus"),
    _S("Defeat Karasuman"),
    _S("Defeat Ralph, Grant & Sypha"),
    _S("Defeat Death"),
    _S("Defeat Cerberus"),
    _S("Save Richter Belmont"),
    _S("Defeat Medusa"),
    _S("Defeat the Creature"),
    _S("Defeat Lesser Demon"),
    _S("Defeat Doppleganger 40"),
    _S("Defeat Akmodan II"),
    _S("Defeat Darkwing Bat"),
    _S("Defeat Galamoth"),
    _S("Final Save point"),
    _S("Meeting with Death"),
    _S("Get Holy Glasses from Maria"),
    _S("Meeting with Master Librarian"),
    _S("First Maria meeting"),
    D_800DD18C,
    D_800DD18C,
    D_800DD18C,
    D_800DD18C,
    D_800DD18C,
    _S("Right hand"),
    _S(" Left hand"),
    _S("   Head"),
    _S("   Body"),
    _S("   Cloak"),
    _S("   Other"),
    _S("   Other"),
    _S("Equip"),
    _S("Spells"),
    _S("Relics"),
    _S("System"),
    _S("Familiars"),
    _S("Familiar List"),
    _S("Special Moves List"),
    _S("S.sword"),
    _S("Sword"),
    _S("Throw 1"),
    _S("Fist"),
    _S("Club"),
    _S("Two-hand"),
    _S("Food"),
    _S("Bomb"),
    _S("Throw 2"),
    _S("Shield"),
    _S("Medicine"),
};
