// SPDX-License-Identifier: AGPL-3.0-or-later
#include "../no3/no3.h"

#include "../pfn_entity_update.h"

extern LayoutEntity* D_8D2E3BC;
extern LayoutEntity* D_8D2E490;

extern Overlay OVL_EXPORT(Overlay);

#include "../get_lang_at.h"

// These entities, and the cutscene data, are BSS
s32 E_ID(BACKGROUND_BLOCK);
s32 E_ID(LOCK_CAMERA);
s32 E_ID(ID_13);
s32 E_ID(EXPLOSION_VARIANTS);
s32 E_ID(GREY_PUFF);
s32 E_ID(ID_16);
s32 E_ID(BG_LIGHTNING);
s32 E_ID(TRANSP_WATER);
s32 E_ID(SHUTTING_WINDOW);
s32 E_ID(CASTLE_DOOR);
s32 E_ID(BACKGROUND_BUSHES);
s32 E_ID(BACKGROUND_TREES);
s32 E_ID(CAVERN_DOOR_LEVER);
s32 E_ID(CAVERN_DOOR_PLATFORM);
s32 E_ID(CAVERN_DOOR);
s32 E_ID(WEIGHTS_SWITCH);
s32 E_ID(WEIGHT_SMALL);
s32 E_ID(WEIGHT_TALL);
s32 E_ID(TRAPDOOR);
s32 E_ID(MERMAN_ROCK_L);
s32 E_ID(MERMAN_ROCK_R);
s32 E_ID(JEWEL_SWORD_DOOR);
s32 E_ID(FALLING_ROCK_2);
s32 E_ID(DEATH_SKY_SWIRL);
s32 E_ID(LIGHTNING_THUNDER);
s32 E_ID(LIGHTNING_CLOUD);
s32 E_ID(HEART_ROOM_SWITCH);
s32 E_ID(HEART_ROOM_DOOR);
s32 E_ID(FIRE_WARG);
s32 E_ID(FIRE_WARG_ATTACK);
s32 E_ID(ID_2F);
s32 E_ID(ID_30);
s32 E_ID(ID_31);
s32 E_ID(EXPLOSION_3);
s32 E_ID(FIRE_WARG_DEATH);
s32 E_ID(ALU_WATER_EFFECT);
s32 E_ID(SPLASH_WATER);
s32 E_ID(SURFACING_WATER);
s32 E_ID(SIDE_WATER_SPLASH);
s32 E_ID(SMALL_WATER_DROP);
s32 E_ID(WATER_DROP);
s32 E_ID(MERMAN2);
s32 E_ID(MERMAN_WATER_SPLASH);
s32 E_ID(MEDIUM_WATER_SPLASH);
s32 E_ID(HIGH_WATER_SPLASH);
s32 E_ID(MERMAN2_SPIT_FIRE);
s32 E_ID(MERMAN2_DYING);
s32 E_ID(MERMAN2_JUMP_AIR);
s32 E_ID(MERMAN);
s32 E_ID(MERMAN_SPIT_FIRE);
s32 E_ID(MERMAN_JUMP_AIR);
s32 E_ID(MERMAN_DYING);
s32 E_ID(MERMAN_SPAWNER);
s32 E_ID(BONE_SCIMITAR);
s32 E_ID(BONE_SCIMITAR_PARTS);
s32 E_ID(BAT);
s32 E_ID(TMAP_SHUFF_UNUSED);
s32 E_ID(WARG);
s32 E_ID(ID_4B);
s32 E_ID(ZOMBIE);
s32 E_ID(ZOMBIE_SPAWNER);
s32 E_ID(PUSH_ALUCARD);
s32 E_ID(FOREGROUND_TREE);
s32 E_ID(FOLIAGE_MAKER);
s32 E_ID(BACKGROUND_PINE_TREES);
s32 E_ID(BACKGROUND_PINE_MAKER);
s32 E_ID(CASTLE_DOOR_TRANSITION);
s32 E_ID(CASTLE_BRIDGE);
s32 E_ID(DIST_BG_TREES);
s32 E_ID(BACKGROUND_WALL);
s32 E_ID(CUTSCENE);
s32 E_ID(DEATH_SCENE_MGR);
s32 E_ID(DEATH_STOLEN_ITEM);
s32 E_ID(DEATH);
s32 E_ID(DEATH_SCYTHE);
s32 E_ID(STAIRWAY_PIECE);
s32 E_ID(FALLING_ROCK);
s32 E_ID(DEATH_SCYTHE_SHADOW);
s32 E_ID(FLYING_OWL_LEAVES);
s32 E_ID(FALLING_LEAF);
s32 E_ID(EXPLODE_PUFF_TRANS);
s32 E_ID(EXPLODE_PUFF_OPAQUE);

u8* OVL_EXPORT(cutscene_data); // bss

extern char cutscene_data_it[];
extern char cutscene_data_sp[];
extern char cutscene_data_fr[];
extern char cutscene_data_ge[];
extern char cutscene_data_en[];

// Weird for this entity to be here. But the static GetLangAt
// above this, and the func_pspeu_09238360 below, must be
// in the same file, so this, sandwiched, must also be.
#include "../e_background_lightning.h"

void InitEntityIds(void) {
    E_ID(BACKGROUND_BLOCK) = E_BACKGROUND_BLOCK;
    E_ID(LOCK_CAMERA) = E_LOCK_CAMERA;
    E_ID(ID_13) = E_ID_13;
    E_ID(EXPLOSION_VARIANTS) = E_EXPLOSION_VARIANTS;
    E_ID(GREY_PUFF) = E_GREY_PUFF;
    E_ID(ID_16) = E_ID_16;
    E_ID(BG_LIGHTNING) = E_BG_LIGHTNING;
    E_ID(TRANSP_WATER) = E_TRANSP_WATER;
    E_ID(SHUTTING_WINDOW) = E_SHUTTING_WINDOW;
    E_ID(CASTLE_DOOR) = E_CASTLE_DOOR;
    E_ID(BACKGROUND_BUSHES) = E_BACKGROUND_BUSHES;
    E_ID(BACKGROUND_TREES) = E_BACKGROUND_TREES;
    E_ID(CAVERN_DOOR_LEVER) = E_CAVERN_DOOR_LEVER;
    E_ID(CAVERN_DOOR_PLATFORM) = E_CAVERN_DOOR_PLATFORM;
    E_ID(CAVERN_DOOR) = E_CAVERN_DOOR;
    E_ID(WEIGHTS_SWITCH) = E_WEIGHTS_SWITCH;
    E_ID(WEIGHT_SMALL) = E_WEIGHT_SMALL;
    E_ID(WEIGHT_TALL) = E_WEIGHT_TALL;
    E_ID(TRAPDOOR) = E_TRAPDOOR;
    E_ID(MERMAN_ROCK_L) = E_MERMAN_ROCK_L;
    E_ID(MERMAN_ROCK_R) = E_MERMAN_ROCK_R;
    E_ID(JEWEL_SWORD_DOOR) = E_JEWEL_SWORD_DOOR;
    E_ID(FALLING_ROCK_2) = E_FALLING_ROCK_2;
    E_ID(DEATH_SKY_SWIRL) = E_DEATH_SKY_SWIRL;
    E_ID(LIGHTNING_THUNDER) = E_LIGHTNING_THUNDER;
    E_ID(LIGHTNING_CLOUD) = E_LIGHTNING_CLOUD;
    E_ID(HEART_ROOM_SWITCH) = E_HEART_ROOM_SWITCH;
    E_ID(HEART_ROOM_DOOR) = E_HEART_ROOM_DOOR;
    E_ID(FIRE_WARG) = E_FIRE_WARG;
    E_ID(FIRE_WARG_ATTACK) = E_FIRE_WARG_ATTACK;
    E_ID(ID_2F) = E_ID_2F;
    E_ID(ID_30) = E_ID_30;
    E_ID(ID_31) = E_ID_31;
    E_ID(EXPLOSION_3) = E_EXPLOSION_3;
    E_ID(FIRE_WARG_DEATH) = E_FIRE_WARG_DEATH;
    E_ID(ALU_WATER_EFFECT) = E_ALU_WATER_EFFECT;
    E_ID(SPLASH_WATER) = E_SPLASH_WATER;
    E_ID(SURFACING_WATER) = E_SURFACING_WATER;
    E_ID(SIDE_WATER_SPLASH) = E_SIDE_WATER_SPLASH;
    E_ID(SMALL_WATER_DROP) = E_SMALL_WATER_DROP;
    E_ID(WATER_DROP) = E_WATER_DROP;
    E_ID(MERMAN2) = E_MERMAN2;
    E_ID(MERMAN_WATER_SPLASH) = E_MERMAN_WATER_SPLASH;
    E_ID(MEDIUM_WATER_SPLASH) = E_MEDIUM_WATER_SPLASH;
    E_ID(HIGH_WATER_SPLASH) = E_HIGH_WATER_SPLASH;
    E_ID(MERMAN2_SPIT_FIRE) = E_MERMAN2_SPIT_FIRE;
    E_ID(MERMAN2_DYING) = E_MERMAN2_DYING;
    E_ID(MERMAN2_JUMP_AIR) = E_MERMAN2_JUMP_AIR;
    E_ID(MERMAN) = E_MERMAN;
    E_ID(MERMAN_SPIT_FIRE) = E_MERMAN_SPIT_FIRE;
    E_ID(MERMAN_JUMP_AIR) = E_MERMAN_JUMP_AIR;
    E_ID(MERMAN_DYING) = E_MERMAN_DYING;
    E_ID(MERMAN_SPAWNER) = E_MERMAN_SPAWNER;
    E_ID(BONE_SCIMITAR) = E_BONE_SCIMITAR;
    E_ID(BONE_SCIMITAR_PARTS) = E_BONE_SCIMITAR_PARTS;
    E_ID(BAT) = E_BAT;
    E_ID(TMAP_SHUFF_UNUSED) = E_TMAP_SHUFF_UNUSED;
    E_ID(WARG) = E_WARG;
    E_ID(ID_4B) = E_ID_4B;
    E_ID(ZOMBIE) = E_ZOMBIE;
    E_ID(ZOMBIE_SPAWNER) = E_ZOMBIE_SPAWNER;
    E_ID(PUSH_ALUCARD) = E_PUSH_ALUCARD;
    E_ID(FOREGROUND_TREE) = E_FOREGROUND_TREE;
    E_ID(FOLIAGE_MAKER) = E_FOLIAGE_MAKER;
    E_ID(BACKGROUND_PINE_TREES) = E_BACKGROUND_PINE_TREES;
    E_ID(BACKGROUND_PINE_MAKER) = E_BACKGROUND_PINE_MAKER;
    E_ID(CASTLE_DOOR_TRANSITION) = E_CASTLE_DOOR_TRANSITION;
    E_ID(CASTLE_BRIDGE) = E_CASTLE_BRIDGE;
    E_ID(DIST_BG_TREES) = E_DIST_BG_TREES;
    E_ID(BACKGROUND_WALL) = E_BACKGROUND_WALL;
    E_ID(CUTSCENE) = E_CUTSCENE;
    E_ID(DEATH_SCENE_MGR) = E_DEATH_SCENE_MGR;
    E_ID(DEATH_STOLEN_ITEM) = E_DEATH_STOLEN_ITEM;
    E_ID(DEATH) = E_DEATH;
    E_ID(DEATH_SCYTHE) = E_DEATH_SCYTHE;
    E_ID(STAIRWAY_PIECE) = E_STAIRWAY_PIECE;
    E_ID(FALLING_ROCK) = E_FALLING_ROCK;
    E_ID(DEATH_SCYTHE_SHADOW) = E_DEATH_SCYTHE_SHADOW;
    E_ID(FLYING_OWL_LEAVES) = E_FLYING_OWL_LEAVES;
    E_ID(FALLING_LEAF) = E_FALLING_LEAF;
    E_ID(EXPLODE_PUFF_TRANS) = E_EXPLODE_PUFF_TRANS;
    E_ID(EXPLODE_PUFF_OPAQUE) = E_EXPLODE_PUFF_OPAQUE;
}

void OVL_EXPORT(Load)(void) {
    OVL_EXPORT(cutscene_data) = GetLangAt(
        0, (u8*)cutscene_data_en, (u8*)cutscene_data_fr, (u8*)cutscene_data_sp,
        (u8*)cutscene_data_ge, (u8*)cutscene_data_it);

    InitEntityIds();
    PfnEntityUpdates = OVL_EXPORT(EntityUpdates);
    g_pStObjLayoutHorizontal = &D_8D2E3BC;
    g_pStObjLayoutVertical = &D_8D2E490;
    func_psp_0892A018();
    memcpy(&g_api.o, &OVL_EXPORT(Overlay), sizeof(Overlay));
}
