/*
 * File: chi.h
 * Overlay: CHI
 * Description: Abandoned Mine
 */

#ifndef CHI_H
#define CHI_H

#include "stage.h"

#define OVL_EXPORT(x) CHI_##x

#define CASTLE_FLAG_BANK 0x52

typedef enum {
    /* 0x00 */ E_NONE,
    /* 0x01 */ E_BREAKABLE,
    /* 0x02 */ E_EXPLOSION,
    /* 0x03 */ E_PRIZE_DROP,
    /* 0x04 */ E_NUMERIC_DAMAGE,
    /* 0x05 */ E_RED_DOOR,
    /* 0x06 */ E_INTENSE_EXPLOSION,
    /* 0x07 */ E_SOUL_STEAL_ORB,
    /* 0x08 */ E_ROOM_FOREGROUND,
    /* 0x09 */ E_STAGE_NAME_POPUP,
    /* 0x0A */ E_EQUIP_ITEM_DROP,
    /* 0x0B */ E_RELIC_ORB,
    /* 0x0C */ E_HEART_DROP,
    /* 0x0D */ E_ENEMY_BLOOD,
    /* 0x0E */ E_SAVE_GAME_POPUP,
    /* 0x0F */ E_DUMMY_0F,
    /* 0x10 */ E_DUMMY_10,
    /* 0x11 */ E_BACKGROUND_BLOCK,
    /* 0x12 */ E_CAMERA_LOCK,
    /* 0x13 */ E_FLAME_TRAIL,
    /* 0x14 */ E_ID_14,
    /* 0x15 */ E_ID_15, // E_GREY_PUFF
    /* 0x16 */ E_DEMON_SWITCH_WALL,
    /* 0x17 */ E_DEMON_SWITCH,
    /* 0x18 */ E_BREAKABLE_WALL,
    /* 0x19 */ E_BREAKABLE_WALL_DEBRIS,
    /* 0x1A */ E_BREAKABLE_DEBRIS,
    /* 0x1B */ E_CERBERUS_GATE_DEBUG,
    /* 0x1C */ E_FALLING_STAIRS,
    /* 0x1D */ E_FALLING_STEP,
    /* 0x1E */ E_GREMLIN,
    /* 0x1F */ E_GREMLIN_EFFECT,
    /* 0x20 */ E_GREMLIN_FIRE,
    /* 0x21 */ E_SALEM_WITCH,
    /* 0x22 */ E_SALEM_WITCH_GLOW,
    /* 0x23 */ E_SALEM_WITCH_CURSE,
    /* 0x24 */ E_SALEM_WITCH_TRIBOLT_LAUNCH,
    /* 0x25 */ E_SALEM_WITCH_TRIBOLT_PROJECTILE,
    /* 0x26 */ E_THORNWEED,
    /* 0x27 */ E_CORPSEWEED,
    /* 0x28 */ E_CORPSEWEED_PROJECTILE,
    /* 0x29 */ E_VENUS_WEED,
    /* 0x2A */ E_VENUS_WEED_FLOWER,
    /* 0x2B */ E_VENUS_WEED_TENDRIL,
    /* 0x2C */ E_VENUS_WEED_DART,
    /* 0x2D */ E_VENUS_WEED_SPIKE,
} EntityIDs;

extern PfnEntityUpdate PfnEntityUpdates[];

#define NA_SE_EN_ELECTRIC_ZAP 0x614
#define NA_SE_EN_SALEM_WITCH_HAND_MOVEMENT 0x624
#define NA_SE_EN_VENUS_WEED_DARTS_LAUNCH 0x626
#define SFX_WEAPON_62C 0x62C
#define NA_SE_EN_SALEM_WITCH_TRIBOLT_LAUNCH 0x634
#define SFX_SWITCH_PRESSED 0x640    // Demon presses switch in CHI
#define NA_SE_SECRET_STAIRS 0x644
#define NA_SE_EN_ROCK_BREAK 0x644
#define NA_SE_DART_WALL_HIT 0x64A
#define NA_SE_SECRET_STAIRS_THUMP 0x655
#define NA_SE_EN_VENUS_WEED_DEATH_EXPLOSION 0x655
#define NA_SE_EN_VENUS_WEED_TENDRIL_DEATH 0x655
#define NA_SE_FIRE_BURST 0x65B
#define NA_SE_EN_DR_FIREBALL 0x660
#define NA_SE_EN_SALEM_WITCH_CURSE_LAUNCH 0x663
#define NA_SE_EN_VENUS_WEED_REVEAL 0x669
#define NA_SE_EN_CORPSEWEED_COLLAPSE 0x672
#define NA_SE_PL_IT_PICKUP 0x67C
#define NA_SE_EN_CORPSEWEED_DEATH 0x683
#define NA_SE_EN_GREMLIN_FLAME 0x691
#define NA_SE_EN_THORNWEED_DEATH 0x691
#define NA_SE_EN_EXPLOSIVE_DEATH 0x693
#define NA_SE_EN_VENUS_WEED_ATTACK_CHARGE 0x6B0
#define NA_SE_EN_VENUS_WEED_ATTACK_TENDRIL_SPIKE 0x6D2
#define NA_SE_EN_CORPSEWEED_ATTACK 0x70D
#define NA_SE_EN_VENUS_WEED_HURT 0x70F
#define NA_SE_EN_VENUS_WEED_DEATH 0x710
#define NA_SE_EN_GREMLIN_HURT 0x728
#define NA_SE_EN_GREMLIN_DEATH 0x729
#define NA_SE_EN_SALEM_WITCH_ATTACK 0x736
#define NA_SE_EN_SALEM_WITCH_HURT 0x737
#define NA_SE_EN_SALEM_WITCH_DEATH 0x738

#endif
