// SPDX-License-Identifier: AGPL-3.0-or-later
#include "../dra/dra.h"
// func_80111928
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", func_80111928);
// func_80111938
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", func_80111938);
// func_8011197C
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", func_8011197C);
// func_801119C4
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", func_801119C4);
// func_80111CC0
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", func_80111CC0);
// func_80111D24
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", func_80111D24);
// func_80111DE8
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", func_80111DE8);
// func_8011203C
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", func_8011203C);
// PlayerStepStand
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepStand);
// PlayerStepWalk
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepWalk);
// PlayerStepJump
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepJump);
// PlayerStepFall
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepFall);
// PlayerStepCrouch
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepCrouch);
// func_801139CC
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", func_801139CC);
// PlayerStepHighJump
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepHighJump);
// func_80113D7C
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", func_80113D7C);
// func_80113E68
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", func_80113E68);
// func_80113EE0
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", func_80113EE0);
// func_80113F7C
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", func_80113F7C);
// AlucardHandleDamage
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", AlucardHandleDamage);
// PlayerStepStoned
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepStoned);
// PlayerStepKill
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepKill);
// PlayerStepUnk17
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepUnk17);
// func_80115C50
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", func_80115C50);
// PlayerStepTeleport
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepTeleport);
// PlayerStepKillWater
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepKillWater);
// PlayerStepBossGrab
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepBossGrab);
// PlayerStepHellfire
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepHellfire);
// PlayerStepUnk48
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepUnk48);
// PlayerStepUnk49
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepUnk49);
// PlayerStepUnk50
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepUnk50);
// BatFormFinished
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", BatFormFinished);
// func_8011690C
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", func_8011690C);
// CheckWingSmashInput
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", CheckWingSmashInput);
// ControlBatForm
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", ControlBatForm);
// PlayerStepUnmorphBat
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepUnmorphBat);
// PlayerStepStuck
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepStuck);
// MistFormFinished
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", MistFormFinished);
// ControlMistForm
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", ControlMistForm);
// PlayerStepUnmorphMist
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepUnmorphMist);
// PlayerStepDarkMetamorphosis
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepDarkMetamorphosis);
// PlayerStepSummonSpells
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepSummonSpells);
// PlayerStepSoulSteal
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepSoulSteal);
// PlayerStepSwordWarp
INCLUDE_ASM("dra_psp/psp/dra_psp/2BF60", PlayerStepSwordWarp);
