import os
import re
import sys

# Define the enum mapping
enum_hand = {
    0x000: "ADD_ITEM_EMPTY_HAND",
    0x001: "ADD_ITEM_MONSTER_VIAL_1",
    0x002: "ADD_ITEM_MONSTER_VIAL_2",
    0x003: "ADD_ITEM_MONSTER_VIAL_3",
    0x004: "ADD_ITEM_SHIELD_ROD",
    0x005: "ADD_ITEM_LEATHER_SHIELD",
    0x006: "ADD_ITEM_KNIGHT_SHIELD",
    0x007: "ADD_ITEM_IRON_SHIELD",
    0x008: "ADD_ITEM_AXELORD_SHIELD",
    0x009: "ADD_ITEM_HERALD_SHIELD",
    0x00A: "ADD_ITEM_DARK_SHIELD",
    0x00B: "ADD_ITEM_GODDESS_SHIELD",
    0x00C: "ADD_ITEM_SHAMAN_SHIELD",
    0x00D: "ADD_ITEM_MEDUSA_SHIELD",
    0x00E: "ADD_ITEM_SKULL_SHIELD",
    0x00F: "ADD_ITEM_FIRE_SHIELD",
    0x010: "ADD_ITEM_ALUCARD_SHIELD",
    0x011: "ADD_ITEM_SWORD_OF_DAWN",
    0x012: "ADD_ITEM_BASILARD",
    0x013: "ADD_ITEM_SHORT_SWORD",
    0x014: "ADD_ITEM_COMBAT_KNIFE",
    0x015: "ADD_ITEM_NUNCHAKU",
    0x016: "ADD_ITEM_WERE_BANE",
    0x017: "ADD_ITEM_RAPIER",
    0x018: "ADD_ITEM_KARMA_COIN",
    0x019: "ADD_ITEM_MAGIC_MISSILE",
    0x01A: "ADD_ITEM_RED_RUST",
    0x01B: "ADD_ITEM_TAKEMITSU",
    0x01C: "ADD_ITEM_SHOTEL",
    0x01D: "ADD_ITEM_ORANGE",
    0x01E: "ADD_ITEM_APPLE",
    0x01F: "ADD_ITEM_BANANA",
    0x020: "ADD_ITEM_GRAPES",
    0x021: "ADD_ITEM_STRAWBERRY",
    0x022: "ADD_ITEM_PINEAPPLE",
    0x023: "ADD_ITEM_PEANUTS",
    0x024: "ADD_ITEM_TOADSTOOL",
    0x025: "ADD_ITEM_SHIITAKE",
    0x026: "ADD_ITEM_CHEESECAKE",
    0x027: "ADD_ITEM_SHORTCAKE",
    0x028: "ADD_ITEM_TART",
    0x029: "ADD_ITEM_PARFAIT",
    0x02A: "ADD_ITEM_PUDDING",
    0x02B: "ADD_ITEM_ICE_CREAM",
    0x02C: "ADD_ITEM_FRANKFURTER",
    0x02D: "ADD_ITEM_HAMBURGER",
    0x02E: "ADD_ITEM_PIZZA",
    0x02F: "ADD_ITEM_CHEESE",
    0x030: "ADD_ITEM_HAM_AND_EGGS",
    0x031: "ADD_ITEM_OMELETTE",
    0x032: "ADD_ITEM_MORNING_SET",
    0x033: "ADD_ITEM_LUNCH_A",
    0x034: "ADD_ITEM_LUNCH_B",
    0x035: "ADD_ITEM_CURRY_RICE",
    0x036: "ADD_ITEM_GYROS_PLATE",
    0x037: "ADD_ITEM_SPAGHETTI",
    0x038: "ADD_ITEM_GRAPE_JUICE",
    0x039: "ADD_ITEM_BARLEY_TEA",
    0x03A: "ADD_ITEM_GREEN_TEA",
    0x03B: "ADD_ITEM_NATOU",
    0x03C: "ADD_ITEM_RAMEN",
    0x03D: "ADD_ITEM_MISO_SOUP",
    0x03E: "ADD_ITEM_SUSHI",
    0x03F: "ADD_ITEM_PORK_BUN",
    0x040: "ADD_ITEM_RED_BEAN_BUN",
    0x041: "ADD_ITEM_CHINESE_BUN",
    0x042: "ADD_ITEM_DIM_SUM_SET",
    0x043: "ADD_ITEM_POT_ROAST",
    0x044: "ADD_ITEM_SIRLION",
    0x045: "ADD_ITEM_TURKEY",
    0x046: "ADD_ITEM_MEAL_TICKET",
    0x047: "ADD_ITEM_NEUTRON_BOMB",
    0x048: "ADD_ITEM_POWER_OF_SIRE",
    0x049: "ADD_ITEM_PENTAGRAM",
    0x04A: "ADD_ITEM_BAT_PENTAGRAM",
    0x04B: "ADD_ITEM_SHURIKEN",
    0x04C: "ADD_ITEM_CROSS_SHURIKEN",
    0x04D: "ADD_ITEM_BUFFALO_STAR",
    0x04E: "ADD_ITEM_FLAME_STAR",
    0x04F: "ADD_ITEM_TNT",
    0x050: "ADD_ITEM_BWAKA_KNIFE",
    0x051: "ADD_ITEM_BOOMERANG",
    0x052: "ADD_ITEM_JAVELIN",
    0x053: "ADD_ITEM_TYRFING",
    0x054: "ADD_ITEM_NAMAKURA",
    0x055: "ADD_ITEM_KNUCKLE_DUSTER",
    0x056: "ADD_ITEM_GLADIUS",
    0x057: "ADD_ITEM_SCIMITAR",
    0x058: "ADD_ITEM_CUTLASS",
    0x059: "ADD_ITEM_SABER",
    0x05A: "ADD_ITEM_FALCHION",
    0x05B: "ADD_ITEM_BROADSWORD",
    0x05C: "ADD_ITEM_BEKATOWA",
    0x05D: "ADD_ITEM_DAMASCUS_SWORD",
    0x05E: "ADD_ITEM_HUNTER_SWORD",
    0x05F: "ADD_ITEM_ESTOC",
    0x060: "ADD_ITEM_BASTARD_SWORD",
    0x061: "ADD_ITEM_JEWEL_KNUCKLES",
    0x062: "ADD_ITEM_CLAYMORE",
    0x063: "ADD_ITEM_TALWAR",
    0x064: "ADD_ITEM_KATANA",
    0x065: "ADD_ITEM_FLAMBERGE",
    0x066: "ADD_ITEM_IRON_FIST",
    0x067: "ADD_ITEM_ZWEIHANDER",
    0x068: "ADD_ITEM_SWORD_OF_HADOR",
    0x069: "ADD_ITEM_LUMINUS",
    0x06A: "ADD_ITEM_HARPER",
    0x06B: "ADD_ITEM_OBSIDIAN_SWORD",
    0x06C: "ADD_ITEM_GRAM",
    0x06D: "ADD_ITEM_JEWEL_SWORD",
    0x06E: "ADD_ITEM_MORMEGIL",
    0x06F: "ADD_ITEM_FIREBRAND",
    0x070: "ADD_ITEM_THUNDERBRAND",
    0x071: "ADD_ITEM_ICEBRAND",
    0x072: "ADD_ITEM_STONE_SWORD",
    0x073: "ADD_ITEM_HOLY_SWORD",
    0x074: "ADD_ITEM_TERMINUS_EST",
    0x075: "ADD_ITEM_MARSIL",
    0x076: "ADD_ITEM_DARK_BLADE",
    0x077: "ADD_ITEM_HEAVEN_SWORD",
    0x078: "ADD_ITEM_FIST_OF_TULKAS",
    0x079: "ADD_ITEM_GURTHANG",
    0x07A: "ADD_ITEM_MOURNEBLADE",
    0x07B: "ADD_ITEM_ALUCARD_SWORD",
    0x07C: "ADD_ITEM_MABLUNG_SWORD",
    0x07D: "ADD_ITEM_BADELAIRE",
    0x07E: "ADD_ITEM_SWORD_FAMILIAR",
    0x07F: "ADD_ITEM_GREAT_SWORD",
    0x080: "ADD_ITEM_MACE",
    0x081: "ADD_ITEM_MORNINGSTAR",
    0x082: "ADD_ITEM_HOLY_ROD",
    0x083: "ADD_ITEM_STAR_FLAIL",
    0x084: "ADD_ITEM_MOON_ROD",
    0x085: "ADD_ITEM_CHAKRAM",
    0x086: "ADD_ITEM_FIRE_BOOMERANG",
    0x087: "ADD_ITEM_IRON_BALL",
    0x088: "ADD_ITEM_HOLBEIN_DAGGER",
    0x089: "ADD_ITEM_BLUE_KNUCKLES",
    0x08A: "ADD_ITEM_DYNAMITE",
    0x08B: "ADD_ITEM_OSAFUNE_KATANA",
    0x08C: "ADD_ITEM_MASAMUNE",
    0x08D: "ADD_ITEM_MURAMASA",
    0x08E: "ADD_ITEM_HEART_REFRESH",
    0x08F: "ADD_ITEM_RUNESWORD",
    0x090: "ADD_ITEM_ANTIVENOM",
    0x091: "ADD_ITEM_UNCURSE",
    0x092: "ADD_ITEM_LIFE_APPLE",
    0x093: "ADD_ITEM_HAMMER",
    0x094: "ADD_ITEM_STR_POTION",
    0x095: "ADD_ITEM_LUCK_POTION",
    0x096: "ADD_ITEM_SMART_POTION",
    0x097: "ADD_ITEM_ATTACK_POTION",
    0x098: "ADD_ITEM_SHIELD_POTION",
    0x099: "ADD_ITEM_RESIST_FIRE",
    0x09A: "ADD_ITEM_RESIST_THUNDER",
    0x09B: "ADD_ITEM_RESIST_ICE",
    0x09C: "ADD_ITEM_RESIST_STONE",
    0x09D: "ADD_ITEM_RESIST_HOLY",
    0x09E: "ADD_ITEM_RESIST_DARK",
    0x09F: "ADD_ITEM_POTION",
    0x0A0: "ADD_ITEM_HIGH_POTION",
    0x0A1: "ADD_ITEM_ELIXIR",
    0x0A2: "ADD_ITEM_MANNA_PRISM",
    0x0A3: "ADD_ITEM_VORPAL_BLADE",
    0x0A4: "ADD_ITEM_CRISSAEGRIM",
    0x0A5: "ADD_ITEM_YASUTSUNA",
    0x0A6: "ADD_ITEM_LIBRARY_CARD",
    0x0A7: "ADD_ITEM_ALUCART_SHIELD",
    0x0A8: "ADD_ITEM_ALUCART_SWORD"
}

other = {
    0x000: "ADD_ITEM_NO_ARMOR",
    0x001: "ADD_ITEM_CLOTH_TUNIC",
    0x002: "ADD_ITEM_HIDE_CUIRASS",
    0x003: "ADD_ITEM_BRONZE_CUIRASS",
    0x004: "ADD_ITEM_IRON_CUIRASS",
    0x005: "ADD_ITEM_STEEL_CUIRASS",
    0x006: "ADD_ITEM_SILVER_PLATE",
    0x007: "ADD_ITEM_GOLD_PLATE",
    0x008: "ADD_ITEM_PLATINUM_MAIL",
    0x009: "ADD_ITEM_DIAMOND_PLATE",
    0x00A: "ADD_ITEM_FIRE_MAIL",
    0x00B: "ADD_ITEM_LIGHTNING_MAIL",
    0x00C: "ADD_ITEM_ICE_MAIL",
    0x00D: "ADD_ITEM_MIRROR_CUIRASS",
    0x00E: "ADD_ITEM_SPIKE_BREAKER",
    0x00F: "ADD_ITEM_ALUCARD_MAIL",
    0x010: "ADD_ITEM_DARK_ARMOR",
    0x011: "ADD_ITEM_HEALING_MAIL",
    0x012: "ADD_ITEM_HOLY_MAIL",
    0x013: "ADD_ITEM_WALK_ARMOR",
    0x014: "ADD_ITEM_BRILLIANT_MAIL",
    0x015: "ADD_ITEM_MOJO_MAIL",
    0x016: "ADD_ITEM_FURY_PLATE",
    0x017: "ADD_ITEM_DRACULA_TUNIC",
    0x018: "ADD_ITEM_GODS_GARB",
    0x019: "ADD_ITEM_AXE_LORD_ARMOR",
    0x01A: "ADD_ITEM_EMPTY_HEAD",
    0x01B: "ADD_ITEM_SUNGLASSES",
    0x01C: "ADD_ITEM_BALLROOM_MASK",
    0x01D: "ADD_ITEM_BANDANNA",
    0x01E: "ADD_ITEM_FELT_HAT",
    0x01F: "ADD_ITEM_VELVET_HAT",
    0x020: "ADD_ITEM_GOGGLES",
    0x021: "ADD_ITEM_LEATHER_HAT",
    0x022: "ADD_ITEM_HOLY_GLASSES",
    0x023: "ADD_ITEM_STEEL_HELM",
    0x024: "ADD_ITEM_STONE_MASK",
    0x025: "ADD_ITEM_CIRCLET",
    0x026: "ADD_ITEM_GOLD_CIRCLET",
    0x027: "ADD_ITEM_RUBY_CIRCLET",
    0x028: "ADD_ITEM_OPAL_CIRCLET",
    0x029: "ADD_ITEM_TOPAZ_CIRCLET",
    0x02A: "ADD_ITEM_BERYL_CIRCLET",
    0x02B: "ADD_ITEM_CAT_EYE_CIRCLET",
    0x02C: "ADD_ITEM_CORAL_CIRCLET",
    0x02D: "ADD_ITEM_DRAGON_HELM",
    0x02E: "ADD_ITEM_SILVER_CROWN",
    0x02F: "ADD_ITEM_WIZARD_HAT",
    0x030: "ADD_ITEM_NO_CAPE",
    0x031: "ADD_ITEM_CLOTH_CAPE",
    0x032: "ADD_ITEM_REVERSE_CLOAK",
    0x033: "ADD_ITEM_ELVEN_CLOAK",
    0x034: "ADD_ITEM_CRYSTAL_CLOAK",
    0x035: "ADD_ITEM_ROYAL_CLOAK",
    0x036: "ADD_ITEM_BLOOD_CLOAK",
    0x037: "ADD_ITEM_JOSEPHS_CLOAK",
    0x038: "ADD_ITEM_TWILIGHT_CLOAK",
    0x039: "ADD_ITEM_NO_ACCESSORY",
    0x03A: "ADD_ITEM_MOONSTONE",
    0x03B: "ADD_ITEM_SUNSTONE",
    0x03C: "ADD_ITEM_BLOODSTONE",
    0x03D: "ADD_ITEM_STAUROLITE",
    0x03E: "ADD_ITEM_RING_OF_PALES",
    0x03F: "ADD_ITEM_ZIRCON",
    0x040: "ADD_ITEM_AQUAMARINE",
    0x041: "ADD_ITEM_TURQUOISE",
    0x042: "ADD_ITEM_ONYX",
    0x043: "ADD_ITEM_GARNET",
    0x044: "ADD_ITEM_OPAL",
    0x045: "ADD_ITEM_DIAMOND",
    0x046: "ADD_ITEM_LAPIS_LAZULI",
    0x047: "ADD_ITEM_RING_OF_ARES",
    0x048: "ADD_ITEM_GOLD_RING",
    0x049: "ADD_ITEM_SILVER_RING",
    0x04A: "ADD_ITEM_RING_OF_VARDA",
    0x04B: "ADD_ITEM_RING_OF_ARCANA",
    0x04C: "ADD_ITEM_MYSTIC_PENDANT",
    0x04D: "ADD_ITEM_HEART_BROACH",
    0x04E: "ADD_ITEM_NECKLACE_OF_J",
    0x04F: "ADD_ITEM_GAUNTLET",
    0x050: "ADD_ITEM_ANKH_OF_LIFE",
    0x051: "ADD_ITEM_RING_OF_FEANOR",
    0x052: "ADD_ITEM_MEDAL",
    0x053: "ADD_ITEM_TALISMAN",
    0x054: "ADD_ITEM_DUPLICATOR",
    0x055: "ADD_ITEM_KINGS_STONE",
    0x056: "ADD_ITEM_COVENANT_STONE",
    0x057: "ADD_ITEM_NAUGLAMIR",
    0x058: "ADD_ITEM_SECRET_BOOTS",
    0x059: "ADD_ITEM_ALUCART_MAIL"
}

def replace_enum(match,category):
    category = int(match.group(2))
    ADD_ITEM_num = int(match.group(1))

    if category == 0:
        enum_name = enum_hand.get(ADD_ITEM_num)
    else:
        enum_name = other.get(ADD_ITEM_num)
    result = f"AddToInventory({enum_name}, {match.group(2)});"
    print(category, ADD_ITEM_num, result)
    return result

def replace_enum_hex(match,category):
    category = int(match.group(2))
    ADD_ITEM_num = int(match.group(1), 16)

    if category == 0:
        enum_name = enum_hand.get(ADD_ITEM_num)
    else:
        enum_name = other.get(ADD_ITEM_num)
    result = f"AddToInventory({enum_name}, {match.group(2)});"
    print(category, ADD_ITEM_num, result)
    return result

# just does category 0 since I'm unclear about the others
def process_add_to_inventory_category(input_file, category):
    with open(input_file, "r") as f:
        content = f.read()

    # do for non-hex
    pattern = r"AddToInventory\((\d+)\s*,\s*(\d+)\);"
    content = re.sub(pattern, lambda match: replace_enum(match, category), content)

    # do for hex
    pattern = r"AddToInventory\((0x[0-9A-Fa-f]+)\s*,\s*(\d+)\);"
    content = re.sub(pattern, lambda match: replace_enum_hex(match, category), content)

    # Write the updated content to the output file
    with open(input_file, "w") as f:
        f.write(content)

def process_directory(dir_path):
    for item in os.listdir(dir_path):
        ADD_ITEM_path = os.path.join(dir_path, item)
        if os.path.isfile(ADD_ITEM_path) and ADD_ITEM_path.endswith('.c'):
            print("processing", ADD_ITEM_path)
            process_add_to_inventory_category(ADD_ITEM_path, 0)
        elif os.path.isdir(ADD_ITEM_path):
            process_directory(ADD_ITEM_path)

process_directory(sys.argv[1])
