#include <game.h>

typedef enum {
    CSOP_END_CUTSCENE,
    CSOP_LINE_BREAK,
    CSOP_SET_SPEED,
    CSOP_SET_WAIT,
    CSOP_SET_PORTRAIT = 5,
    CSOP_NEXT_DIALOG,
    CSOP_SET_POS,
    CSOP_CLOSE_DIALOG,
    CSOP_PLAY_SOUND,
    CSOP_WAIT_FOR_SOUND,
    CSOP_UNK_11,
    CSOP_WAIT_FOR_FLAG = 16,
    CSOP_SET_FLAG,
    CSOP_LOAD_PORTRAIT = 19,
    CSOP_SCRIPT_UNKNOWN_20,
} CutsceneOpcode;

#define END_CUTSCENE() CSOP_END_CUTSCENE
#define LINE_BREAK() CSOP_LINE_BREAK
#define SET_SPEED(x) CSOP_SET_SPEED, x
#define SET_WAIT(x) CSOP_SET_WAIT, x
#define SET_PORTRAIT(clut, side) CSOP_SET_PORTRAIT, clut, !!side
#define NEXT_DIALOG() CSOP_NEXT_DIALOG
#define SET_POS(x, y) CSOP_SET_POS, x, y
#define CLOSE_DIALOG() CSOP_CLOSE_DIALOG
#define PLAY_SOUND(x, y) CSOP_PLAY_SOUND, x, y
#define WAIT_FOR_SOUND() CSOP_WAIT_FOR_SOUND
#define SCRIPT_UNKNOWN_11() CSOP_UNK_11
#define WAIT_FOR_FLAG(x) CSOP_WAIT_FOR_FLAG, x
#define SET_FLAG(x) CSOP_SET_FLAG, x
#define LOAD_PORTRAIT(a, b, c, d, e) CSOP_LOAD_PORTRAIT, a, b, c, d, e
#define SCRIPT_UNKNOWN_20(x, y) CSOP_SCRIPT_UNKNOWN_20, x, y
