// SPDX-License-Identifier: AGPL-3.0-or-later
// clang-format off
SET_END(0x801815db),
WAIT_FOR_FLAG(0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x364),
WAIT_FOR_SOUND(),
SET_FLAG(2),
SET_WAIT(24),
SET_POS(60,28),
LOAD_PORTRAIT(0x80182370,0),
SET_PORTRAIT(1,0),
SET_FLAG(3),
SET_SPEED(3),
'Y','o','u',' ','s','e','e','m',' ','h','u','m','a','n',
LINE_BREAK(),
SET_WAIT(4),
'a','n','d',' ','y','e','t','.','.','.',
LINE_BREAK(),
SET_WAIT(28),
SET_SPEED(3),
'W','h','a','t',' ','d','o',' ','y','o','u',' ','h','e','r','e','?',
SET_WAIT(48),
NEXT_DIALOG(),
LOAD_PORTRAIT(0x801815f0,1),
SET_PORTRAIT(0,129),
SET_SPEED(4),
'.','.','.','.','.','.','.','.','.',
LINE_BREAK(),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x365),
WAIT_FOR_SOUND(),
SET_SPEED(3),
'I','\'','v','e',' ','c','o','m','e',' ','t','o',
LINE_BREAK(),
SET_WAIT(4),
'd','e','s','t','r','o','y',' ','t','h','i','s',' ','c','a','s','t','l','e','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(1,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x366),
WAIT_FOR_SOUND(),
SET_SPEED(3),
SET_FLAG(4),
'T','h','e','n',' ','w','e',' ','h','a','v','e',' ','t','h','e',
LINE_BREAK(),
SET_WAIT(4),
's','a','m','e',' ','p','u','r','p','o','s','e','.',
LINE_BREAK(),
SET_FLAG(5),
SET_WAIT(16),
'I','\'','l','l',' ','t','r','u','s','t',' ','y','o','u',' ','f','o','r',
LINE_BREAK(),
SET_FLAG(6),
SET_WAIT(4),
'n','o','w','.',' ',
SET_WAIT(24),
SET_SPEED(3),
SET_FLAG(7),
'I','\'','m',' ','M','a','r','i','a','.',
LINE_BREAK(),
SET_FLAG(8),
SET_WAIT(32),
SET_SPEED(3),
'W','h','o',' ','a','r','e',' ','y','o','u','?',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(0,129),
SET_SPEED(4),
'.','.','.','.','.','.','.','.','.',
LINE_BREAK(),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x367),
WAIT_FOR_SOUND(),
SET_SPEED(4),
'A','l','u','c','a','r','d','.',
SET_WAIT(48),
NEXT_DIALOG(),
SET_PORTRAIT(1,0),
SCRIPT_UNKNOWN_11(),
PLAY_SOUND(0x368),
WAIT_FOR_SOUND(),
SET_SPEED(3),
SET_FLAG(9),
'N','o','t',' ','t','h','e',' ','t','a','l','k','a','t','i','v','e',
LINE_BREAK(),
SET_WAIT(4),
't','y','p','e',' ','I',' ','c','a','n',' ','s','e','e','.',
LINE_BREAK(),
SET_WAIT(24),
SET_FLAG(10),
'W','e','l','l',',',' ',
SET_WAIT(16),
SET_SPEED(2),
'p','e','r','h','a','p','s',' ','w','e','\'','l','l',
LINE_BREAK(),
SET_WAIT(4),
'm','e','e','t',' ','a','g','a','i','n',' ',
SET_WAIT(24),
'i','f',' ','y','o','u',
LINE_BREAK(),
SET_WAIT(4),
'l','i','v','e',' ','t','h','a','t',' ','l','o','n','g','.',
LINE_BREAK(),
SET_WAIT(32),
SET_FLAG(11),
'F','a','r','e','w','e','l','l','.',
SET_FLAG(12),
SET_WAIT(48),
NEXT_DIALOG(),
CLOSE_DIALOG(),
WAIT_FOR_FLAG(13),
SET_FLAG(1),
SCRIPT_UNKNOWN_11(),
END_CUTSCENE(),
END_CUTSCENE(),
