// SPDX-License-Identifier: AGPL-3.0-or-later
#include "../no2/no2.h"

#include "../pfn_entity_update.h"

extern LayoutEntity* D_8D2E1B4;
extern LayoutEntity* D_8D2E288;

extern Overlay OVL_EXPORT(Overlay);

s32 E_ID(BACKGROUND_BLOCK);
s32 E_ID(LOCK_CAMERA);
s32 E_ID(ID_13);
s32 E_ID(EXPLOSION_VARIANTS);
s32 E_ID(GREY_PUFF);
s32 E_ID(SKELERANG);
s32 E_ID(SKELERANG_BOOMERANG);
s32 E_ID(SKELERANG_UNKNOWN);
s32 E_ID(ID_19);
s32 E_ID(ID_1A);
s32 E_ID(ID_1B);
s32 E_ID(ID_1C);
s32 E_ID(ID_1D);
s32 E_ID(3D_BACKGROUND_HOUSE);
s32 E_ID(3D_HOUSE_SPAWNER);
s32 E_ID(ID_20);
s32 E_ID(SPIKES);
s32 E_ID(SPIKES_PARTS);
s32 E_ID(SPIKES_DUST);
s32 E_ID(ID_24);
s32 E_ID(ID_25);
s32 E_ID(ID_26);
s32 E_ID(BIG_RED_FIREBALL);
s32 E_ID(ID_28);
s32 E_ID(OWL_KNIGHT);
s32 E_ID(OWL);
s32 E_ID(OWL_KNIGHT_SWORD);
s32 E_ID(OWL_TARGET);
s32 E_ID(BLOODY_ZOMBIE);
s32 E_ID(BLOOD_DRIPS);
s32 E_ID(BLOOD_SPLATTER);
s32 E_ID(ID_30);
s32 E_ID(SPIKES_DAMAGE);
s32 E_ID(ID_32);
s32 E_ID(ID_33);
s32 E_ID(VALHALLA_KNIGHT);
s32 E_ID(ID_35);
s32 E_ID(ID_36);
s32 E_ID(HAMMER);
s32 E_ID(GURKHA_BODY_PARTS);
s32 E_ID(HAMMER_WEAPON);
s32 E_ID(GURKHA);
s32 E_ID(GURKHA_WEAPON);
s32 E_ID(BLADE);
s32 E_ID(BLADE_WEAPON);
s32 E_ID(SPECTRAL_SWORD);
s32 E_ID(ID_3F);
s32 E_ID(POLTERGEIST);
s32 E_ID(BREAKABLE_DEBRIS);

void InitEntityIds(void) {
    E_ID(BACKGROUND_BLOCK) = E_BACKGROUND_BLOCK;
    E_ID(LOCK_CAMERA) = E_LOCK_CAMERA;
    E_ID(ID_13) = E_UNK_ID13;
    E_ID(EXPLOSION_VARIANTS) = E_EXPLOSION_VARIANTS;
    E_ID(GREY_PUFF) = E_GREY_PUFF;
    E_ID(SKELERANG) = E_SKELERANG;
    E_ID(SKELERANG_BOOMERANG) = E_SKELERANG_BOOMERANG;
    E_ID(SKELERANG_UNKNOWN) = E_SKELERANG_UNKNOWN;
    E_ID(ID_19) = E_UNK_19;
    E_ID(ID_1A) = E_UNK_1A;
    E_ID(ID_1B) = E_UNK_1B;
    E_ID(ID_1C) = E_UNK_1C;
    E_ID(ID_1D) = E_UNK_1D;
    E_ID(3D_BACKGROUND_HOUSE) = E_3D_BACKGROUND_HOUSE;
    E_ID(3D_HOUSE_SPAWNER) = E_3D_HOUSE_SPAWNER;
    E_ID(ID_20) = E_UNK_20;
    E_ID(SPIKES) = E_SPIKES;
    E_ID(SPIKES_PARTS) = E_SPIKES_PARTS;
    E_ID(SPIKES_DUST) = E_SPIKES_DUST;
    E_ID(ID_24) = E_UNK_24;
    E_ID(ID_25) = E_UNK_25;
    E_ID(ID_26) = E_UNK_26;
    E_ID(BIG_RED_FIREBALL) = E_BIG_RED_FIREBALL;
    E_ID(ID_28) = E_ID_28;
    E_ID(OWL_KNIGHT) = E_OWL_KNIGHT;
    E_ID(OWL) = E_OWL;
    E_ID(OWL_KNIGHT_SWORD) = E_OWL_KNIGHT_SWORD;
    E_ID(OWL_TARGET) = E_OWL_TARGET;
    E_ID(BLOODY_ZOMBIE) = E_BLOODY_ZOMBIE;
    E_ID(BLOOD_DRIPS) = E_BLOOD_DRIPS;
    E_ID(BLOOD_SPLATTER) = E_BLOOD_SPLATTER;
    E_ID(ID_30) = E_UNK_30;
    E_ID(SPIKES_DAMAGE) = E_SPIKES_DAMAGE;
    E_ID(ID_32) = E_ID_32;
    E_ID(ID_33) = E_UNK_33;
    E_ID(VALHALLA_KNIGHT) = E_VALHALLA_KNIGHT;
    E_ID(ID_35) = E_UNK_35;
    E_ID(ID_36) = E_UNK_36;
    E_ID(HAMMER) = E_HAMMER;
    E_ID(GURKHA_BODY_PARTS) = E_GURKHA_BODY_PARTS;
    E_ID(HAMMER_WEAPON) = E_HAMMER_WEAPON;
    E_ID(GURKHA) = E_GURKHA;
    E_ID(GURKHA_WEAPON) = E_GURKHA_WEAPON;
    E_ID(BLADE) = E_BLADE;
    E_ID(BLADE_WEAPON) = E_BLADE_WEAPON;
    E_ID(SPECTRAL_SWORD) = E_SPECTRAL_SWORD;
    E_ID(ID_3F) = E_UNK_3F;
    E_ID(POLTERGEIST) = E_POLTERGEIST;
    E_ID(BREAKABLE_DEBRIS) = E_BREAKABLE_DEBRIS;
}

void OVL_EXPORT(Load)(void) {
    InitEntityIds();
    PfnEntityUpdates = OVL_EXPORT(EntityUpdates);
    g_pStObjLayoutHorizontal = &D_8D2E1B4;
    g_pStObjLayoutVertical = &D_8D2E288;
    func_892A018();
    memcpy(&g_api.o, &OVL_EXPORT(Overlay), sizeof(Overlay));
}
