// SPDX-License-Identifier: AGPL-3.0-or-later
#ifndef SATURN_STAGE_16_H
#define SATURN_STAGE_16_H

// Overlays run on top of the resident zero and game modules.
#include "game.h"
#include "sattypes.h"
#include "shared_sprite_banks.h"
#include <saturn_sprite.h>
#include "stage_data.h"

/* Declarations moved here by tools/saturn/move_declarations.py */
extern char g_Stage16ObtainedText[];
void func_060DE814(Entity* self);
void func_060DE714(Entity* self);
void func_060DDBE0(Entity* self);
void func_060DD6F4(Entity* self);
void func_060DCE98(Entity* self);
void func_060E042C(Entity* self);
void func_060E02C0(Entity* self);
void func_060E01D4(Entity* self);
void func_060E006C(Entity* self);
void func_060DFF04(Entity* self);
void func_060E0A48(Entity* self);
void func_060E075C(Entity* self);
void func_060E102C(Entity* self);
void func_060E0F20(Entity* self);
void func_060DF830(Entity* self);
void func_060DED28(Entity* self);
void func_060E1928(Entity* self);
void func_060E3D00(Entity* self);
void func_060E34CC(Entity* self);
void func_060E4AEC(Entity* self);
void func_060E49F0(Entity* self);
void func_060E4210(Entity* self);
void func_060E7C60(Entity* self);
void func_060E73FC(Entity* self);
void func_060E72FC(Entity* self);
void func_060E6DDC(Entity* self);
extern SaturnSpriteResource g_Stage16SpriteBank16;
void TekiInit(Entity* self, s32 arg);
void func_0600AFA8(SpriteObject* sprite, SaturnSpriteFrameHeader* frame);

extern SaturnSpriteResource g_Stage16SpriteBank25;
void func_060E6C88(Entity* self);
void func_060E6A6C(Entity* self);
void func_060E63A8(Entity* self);
extern SaturnSpriteResource g_Stage16SpriteBank24;
void func_060E53E0(Entity* self);
void func_060E5258(Entity* self);
void func_060E4CF4(Entity* self);
extern SaturnSpriteResource g_Stage16SpriteBank22;
void func_060E55B0(Entity* self);
extern SaturnSpriteResource g_Stage16SpriteBank23;
extern EntityEntry g_Stage16EntityEntry43;
extern EntityEntry g_Stage16EntityEntry42;
extern EntityEntry g_Stage16EntityEntry41;
extern EntityEntry g_Stage16EntityEntry40;
extern EntityEntry g_Stage16EntityWillOWisp;
extern EntityEntry g_Stage16EntityEntry38;
extern EntityEntry g_Stage16EntityEntry37;
extern EntityEntry g_Stage16EntityEntry36;
extern EntityEntry g_Stage16EntitySkeletonBreeder;
extern EntityEntry g_Stage16EntityEntry34;
extern EntityEntry g_Stage16EntityEntry33;
extern EntityEntry g_Stage16EntityGargoyle;
extern EntityEntry g_Stage16EntitySpecter;
extern EntityEntry g_Stage16EntityEntry29;
extern EntityEntry g_Stage16EntityEntry30;
extern EntityEntry g_Stage16EntitySkeletonBeast;
extern EntityEntry g_Stage16EntityEntry27;
extern EntityEntry g_Stage16EntityEntry26;
extern EntityEntry g_Stage16EntityEntry25;
extern EntityEntry g_Stage16EntityEntry24;
extern EntityEntry g_Stage16EntityEntry23;
extern EntityEntry g_Stage16EntityEntry15;
extern EntityEntry g_Stage16EntityEntry08;
extern EntityEntry g_Stage16EntityEntry14;
extern EntityEntry g_Stage16EntityEntry12;
extern EntityEntry g_Stage16EntityEntry06;
extern EntityEntry g_Stage16EntityEntry19;
extern EntityEntry g_Stage16EntityEntry18;
extern EntityEntry g_Stage16EntityEntry05;
extern EntityEntry g_Stage16EntityEntry01;
extern EntityEntry g_Stage16EntityEntry03;
extern EntityEntry g_Stage16EntityEntry04;
extern EntityEntry g_Stage16EntityEntry13;
extern EntityEntry g_Stage16EntityEntry11;
extern EntityEntry g_Stage16EntityEntry10;
extern EntityEntry g_Stage16EntityEntry09;
extern EntityEntry g_Stage16EntityEntry02;
extern EntityEntry g_Stage16EntityEntry22;
extern EntityEntry g_Stage16EntityEntry21;
extern EntityEntry g_Stage16EntityEntry20;
extern EntityEntry g_Stage16EntityEntry16;
extern EntityEntry g_Stage16EntityEntry17;
extern EntityEntry g_Stage16EntityEntry00;
void func_060E887C(Entity* self);
void func_060E8AC0(Entity* self);
void func_060E86BC(Entity* self);
void func_060E7FC4(Entity* self);
void func_060E7ED0(Entity* self);
extern SaturnSpriteResource g_Stage16SpriteBank26;
extern char g_Stage16GoldText5000[];
extern char g_Stage16GoldText2000[];
extern char g_Stage16GoldText1000[];
extern char g_Stage16GoldText700[];
extern char g_Stage16GoldText400[];
extern char g_Stage16GoldText250[];
extern char g_Stage16GoldText100[];
extern char g_Stage16GoldText50[];
extern char g_Stage16GoldText25[];
extern char g_Stage16GoldText1[];
extern SaturnRoomPriorities g_Stage16RoomPriorities[];
extern SaturnRoomGraphics g_Stage16RoomGraphics[];
extern SaturnRoomLayerSetup g_Stage16LayerSetup[];
extern SaturnLayerMapOffsets g_Stage16LayerMapOffsets[];
extern SaturnLayerCompressedSizes g_Stage16LayerCompressedSizes[];
extern SaturnRoomHeader g_Stage16Rooms[];
extern LayoutEntity* g_Stage16LayoutVertical[];
extern LayoutEntity* g_Stage16LayoutHorizontal[];
extern void* g_Stage16SpriteBanks[];
extern EntityEntry* g_Stage16EntityUpdates[];
extern LayoutEntity g_Stage16LayoutHorizontal02[];
extern LayoutEntity g_Stage16LayoutHorizontal01[];
extern LayoutEntity g_Stage16LayoutHorizontal00[];
extern LayoutEntity g_Stage16LayoutHorizontal52[];
extern LayoutEntity g_Stage16LayoutHorizontal51[];
extern LayoutEntity g_Stage16LayoutHorizontal50[];
extern LayoutEntity g_Stage16LayoutHorizontal48[];
extern LayoutEntity g_Stage16LayoutHorizontal49[];
extern u16 g_Stage16SpriteBank20Palette[];
extern SaturnSpriteImage g_Stage16SpriteBank20Images[];
extern u16 g_Stage16SpriteBank21Palette[];
extern SaturnSpriteImage g_Stage16SpriteBank21Images[];
extern u16 g_Stage16SpriteBank22Palette[];
extern SaturnSpriteImage g_Stage16SpriteBank22Images[];
extern u16 g_Stage16SpriteBank23Palette[];
extern SaturnSpriteImage g_Stage16SpriteBank23Images[];
extern u16 g_Stage16SpriteBank24Palette[];
extern SaturnSpriteImage g_Stage16SpriteBank24Images[];
extern u16 g_Stage16SpriteBank25Palette[];
extern SaturnSpriteImage g_Stage16SpriteBank25Images[];
extern u16 g_Stage16SpriteBank26Palette[];
extern SaturnSpriteImage g_Stage16SpriteBank26Images[];
extern u8 g_Stage16SpriteBankWillOWisp[];
extern u8 g_Stage16SpriteBankSkeletonBreeder[];
extern u8 g_Stage16SpriteBankGargoyle[];
extern u8 g_Stage16SpriteBankSpecter[];
extern u8 g_Stage16SpriteBankSkeletonBeast[];
extern u8 g_Stage16SpriteBank18[];
extern u8 g_Stage16SpriteBank17[];
void func_060DC9E0(Entity* self);
void func_060DC894(Entity* self);
void func_060DC60C(Entity* self);
void func_060DC4C0(Entity* self);
void func_060DC418(Entity* self);
void func_060DC040(Entity* self);
extern SaturnSpriteFrameHeader* g_Stage16SpriteBank16Frames[];
extern LayoutEntity g_Stage16LayoutVertical02[];
extern LayoutEntity g_Stage16LayoutVertical01[];
extern LayoutEntity g_Stage16LayoutVertical00[];
extern LayoutEntity g_Stage16LayoutVertical52[];
extern LayoutEntity g_Stage16LayoutVertical51[];
extern LayoutEntity g_Stage16LayoutVertical50[];
extern LayoutEntity g_Stage16LayoutVertical48[];
extern LayoutEntity g_Stage16LayoutVertical49[];
/* End moved declarations */

#endif
