// SPDX-License-Identifier: AGPL-3.0-or-later
#include "rnz0.h"

u16 OVL_EXPORT(PrizeDrops)[] = {
    ITEMDROP_LIFE_VESSEL,    ITEMDROP_HEART_VESSEL, ITEMDROP_LIFE_VESSEL,
    ITEMDROP_GODDESS_SHIELD, ITEMDROP_MANNA_PRISM,  ITEMDROP_KATANA,
    ITEMDROP_HIGH_POTION,    ITEMDROP_TURQUOISE,    ITEMDROP_RING_OF_ARCANA,
    ITEMDROP_RESIST_DARK,    ITEMDROP_HEART_VESSEL, ITEMDROP_HEART_VESSEL,
    ITEMDROP_HEART_VESSEL,   ITEMDROP_HEART_VESSEL, ITEMDROP_HEART_VESSEL,
    ITEMDROP_HEART_VESSEL,
};
