name: Validate decompiled code

on:
  push:
    paths-ignore:
      - '*.md'
      - '**/*.md'
  pull_request_target:
    paths-ignore:
      - '.github/workflows/**'
      - '*.md'
      - '**/*.md'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install requirements
        run: sudo apt-get install gcc-mipsel-linux-gnu
      - name: Downgrade binutils
        run: |
          curl -L -o binutils-mipsel-linux-gnu_2.35.2-2cross2_amd64.deb http://ftp.de.debian.org/debian/pool/main/b/binutils-mipsen/binutils-mipsel-linux-gnu_2.35.2-2cross2_amd64.deb
          sudo dpkg -i binutils-mipsel-linux-gnu_2.35.2-2cross2_amd64.deb
          rm binutils-mipsel-linux-gnu_2.35.2-2cross2_amd64.deb
      - name: Clone main repository
        uses: actions/checkout@v2
        with:
          submodules: false
      - name: Clone game data repository
        uses: actions/checkout@v2
        with:
          repository: xeeynamo/sotn-decomp-private
          token: ${{ secrets.SOTN_DECOM_PRIVATE_REPO_TOKEN }}
          path: 'data'
      - name: Copy game data
        run: |
          mkdir -p iso
          cp -r data/psx_us10/* ./iso
      - name: Split game data
        run: make extract
      - name: Build and test
        run: make all
